### ISSUE TITLE
(Another) heads up: stricter validation coming soon in the create repo for org endpoint

### ISSUE THREAD

**Issue by kytrinyx** [google/go-github#1014]
A few weeks back we discussed an issue where the GitHub API is going to return 422s when incorrect parameters are passed (rather than just ignoring those parameters): https://github.com/google/go-github/issues/992

We found another instance where we get incorrect parameters with the google/go-github header.

Our current plan is to turn on stricter validation on November 1st (we were going to do this earlier, but we've been seeing a lot of mismatches across the board, and are doing some work to let everyone know first!).

The [Create a repository for an organization](https://developer.github.com/v3/repos/#create) endpoint doesn't take an `archived` parameter, but we're seeing `archived` being passed to a number of endpoints.

Would you have a chance to look into whether this is encoded into the library itself, or whether it might be user error?

**Comment by gmlewis** [comment]
This is the same situation as #992: the user can pass in a full `Repository` struct which contains the `archived` field, and our documentation says:

```go
	// Additional mutable fields when creating and editing a repository
...
	Archived          *bool   `json:"archived,omitempty"`
```

which makes it sound like this is a valid field.

Here is the code:
https://github.com/google/go-github/blob/master/github/repos.go#L262-L287

I think this could be handled the same way as #997.

**Comment by kytrinyx** [comment]
> I think this could be handled the same way as #997.

After having read through the discussions and code changes, I think you're right.
