### ISSUE TITLE
(Yet another) heads up: Stricter validation coming soon to the create organization hook endpoint

### ISSUE THREAD

**Issue by kytrinyx** [google/go-github#1015]
We're working on adding stricter validation in the GitHub REST API, and uncovering all sorts of goodies and inconsistencies. ✨ 

In the [Create organization hook](https://developer.github.com/v3/orgs/hooks/#create-a-hook) endpoint we noticed the following errors come through with the `google/go-github` user agent:

```
'"created_at", "updated_at" are not permitted keys.'
```

Would you have a moment to check if this is encoded into the library, or whether this is a user error, as seen in https://github.com/google/go-github/issues/992 ?

**Comment by gmlewis** [comment]
Yes, same situation as #992 and #1014.
We use a full `Hook` struct that has these fields which means the user is able to populate it.
Once again, I think the solution in #997 is the best way to handle this.

**Comment by kytrinyx** [comment]
Yes--I can't act as a tie breaker in the discussion, but I think that the arguments you list in https://github.com/google/go-github/pull/997#issuecomment-420247134 are a propos.
