### ISSUE TITLE
Should "github/examples_test.go" be in "example/" or "test/"?

### ISSUE THREAD

**Issue by gauntface** [google/go-github#1021]
At the moment examples_test.go is in github/ and because it's importing `"github.com/google/go-github/v18/github"` it creates an unusual dependency from github/ on a version of itself.

Is there a reason for this directory to live in github/ instead of example/ and test/ ?

**Comment by gmlewis** [comment]
According to #372, the discussion is in #367.

As far as I can tell, it was an experiment to place `examples_test.go` in the `github` directory.

As far as I'm concerned, it could live elsewhere, and if you would like to create a new experiment to put it where you think it belongs, I'm happy to go along.
