### ISSUE TITLE
Update CreateHook endpoints with new name field restrictions

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#1026]
GitHub Developer API announcement:
https://developer.github.com/changes/2018-10-01-denying-new-github-services/

This issue probably needs some discussion.

If I'm reading the announcement correctly, `web` will be the only allowed value for `name` in the `CreateHook` endpoint for both repos and orgs.
Alternatively, the `name` field can be removed completely.

Please correct me if anyone else has a different understanding of the issue.

**Comment by tadityar** [comment]
From the announcement above I think that we should remove `name` as it is no longer required. Starting 1st Nov including name would result in an error so I am for removing it.
