### ISSUE TITLE
add missing struct fields

### ISSUE THREAD

**Issue by willnorris** [google/go-github#103]
With the new [fields tool](https://github.com/google/go-github/blob/master/tests/fields/fields.go), it's now quite easy to identify which JSON fields are not being mapped into our resource structs.  Most of these are API URLs, but there are also a handful of other fields that got overlooked.

Originally, I had pushed back a bit on adding the API URLs since this library doesn't use them at all.  I've long since given up on that since a few use-cases have been mentioned, so we might as well go ahead and add them all.  I also have a few ideas for how the library could actually use these URLs or ones like them.

Related, the [API Versions](https://developer.github.com/v3/versions/) page documents some changes in API resources that we should make sure are addressed.

**Comment by wesleimp** [comment]
@gmlewis this issue can be closed

**Comment by gmlewis** [comment]
Closing.
