### ISSUE TITLE
Support improvements to the Deployment Statuses API

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#1035]
GitHub Developer API announcement:
https://developer.github.com/changes/2018-10-16-deployments-environments-states-and-auto-inactive-updates/

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by urohit011** [comment]
Can I have it?

**Comment by urohit011** [comment]
Can I have it?

**Comment by unblee** [comment]
Hi! @urohit011, are you still working on this?

I want to use this API now! May I implement it?
