### ISSUE TITLE
List Repositories fails with per_pages=100

### ISSUE THREAD

**Issue by ahmetb** [google/go-github#1037]
```
curl -vH "Accept: application/vnd.github.scarlet-witch-preview+json, application/vnd.github.mercy-preview+json" \
    https://api.github.com/users/kubernetes/repos\?page\=1\&per_page\=100
```

request takes 10 seconds and fails with HTTP 502 Bad Gateway and body:

```
{
  "message": "Server Error"
}
```

I know this is really a GitHub API issue (I just reported to GitHub) but it seems like it's reproducibly happening with these Accept header values injected by go-github by default:

- application/vnd.github.scarlet-witch-preview+json
- application/vnd.github.mercy-preview+json

removing the Accept makes the request succeed just fine. So maybe go-github shouldn't use these headers by default, yet?

**Comment by gmlewis** [comment]
Closing so that discussion can continue in #999.
