### ISSUE TITLE
Support updates to Marketplace-related webhooks and REST APIs

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#1040]
GitHub Developer API announcement:
https://developer.github.com/changes/2018-10-31-improved-experience-for-marketplace-pending-changes/

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by srmocher** [comment]
@gmlewis New contributor here. Interested in working on this, could you assign this issue to me?

**Comment by gmlewis** [comment]
Thank you, @srmocher!
I'm no longer able to send a repo contributor invite to you, but please consider yourself assigned. :smile:

**Comment by dreamer-89** [comment]
@gmlewis : I am also interested to work on this issue. It seems @srmocher working on this one. Can you please assign me other issues/bugs ?

**Comment by gmlewis** [comment]
Thanks for your interest, @dreamer-89!

My recommendation to you is to go through the list of open issues in this repo and choose one that interests you... then add a comment that you want to work on it. (I just browsed through and there are a [bunch of outstanding ones](https://github.com/google/go-github/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22).)

If someone is already listed on it, chances are high that they have forgotten about it and you can ask to take it over from them.

**Comment by dreamer-89** [comment]
Thank you so much @gmlewis :) :)

**Comment by dreamer-89** [comment]
@gmlewis : Please review
https://github.com/google/go-github/pull/1041

**Comment by gmlewis** [comment]
@dreamer-89 - sorry I wasn't clear before... you apparently misunderstood me. This issue is assigned to @srmocher and so you should not be submitting PRs against this issue. I started to review your PR and came across a number of issues (both with the PR and with the GitHub documentation), then came back here and realized that this issue is not yours (currently) to be working on.

As a result, I'm going to close your PR and let's give @srmocher a chance to submit a PR against this issue.

Thank you very much for your enthusiasm, but please go back through the list of other open issues and chose one of those to start contributing to. If it is already assigned (like this one... you have to read the comments to determine that, unfortunately, as I no longer have permissions in this repo to send contributor invites), please first ask if you can take  over the issue, but only if they've had a fair amount of time (a week or two maybe) to work on it.

**Comment by willnorris** [comment]
(invites sent to @srmocher and @dreamer-89.  sorry about the delay)

**Comment by palash25** [comment]
@gmlewis requesting assignment :hand:

**Comment by sinisterstuf** [comment]
If this issue is resolved by #1042 then we could close it. Or is there something that still needs doing here?

**Comment by gmlewis** [comment]
Thank you, @sinisterstuf - I believe you are correct that this can be closed.
Feel free to reopen if anyone disagrees.
