### ISSUE TITLE
Adding body_html

### ISSUE THREAD

**Issue by nico-bock** [google/go-github#1058]
Hello,
are there plans to integrate body_html, to get the body in a HTML format?
https://developer.github.com/v3/media/

**Comment by gmlewis** [comment]
There are no plans than I'm aware of, @nico-bock, and to my knowledge, this is the first request for it.

However, this would be a great PR for any new contributor to this repo or a new Go developer.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by gmlewis** [comment]
OK, thanks, @nico-bock. When you are ready, please create a PR against this repo and we will review it from there.

**Comment by wesleimp** [comment]
@gmlewis is it really relevant or can we close it?

**Comment by gmlewis** [comment]
Thank you, @wesleimp. Closing.
