### ISSUE TITLE
Easy way to patch an issue?

### ISSUE THREAD

**Issue by pwaller** [google/go-github#106]
Given an `Issue`, I want to comment or patch on it. However, to do that I need `owner`, `repo` and `number`, which are buried in the `*issue.URL`. It would be nice if either issues had `CreateComment` and `Edit` methods which received a `*Client`, or if they had a method to obtain those three fields easily.

**Comment by pwaller** [comment]
Since I've not had any response in a long while, I'm closing this.

**Comment by USA24** [comment]
PicsArt_1424503997020.png - https://docs.google.com/file/d/0B9Q-xeAP4U32d2tRR1oydTJudWM/edit?usp=docslist_api

**Comment by USA24** [comment]
https://docs.google.com/file/d/0B9Q-xeAP4U32d2tRR1oydTJudWM/edit?usp=docslist_api.USA24

**Comment by USA24** [comment]
http://witter.com/#supported_languages

**Comment by USA24** [comment]
http://witter.com/#supported_languageUSA24
