### ISSUE TITLE
ProjectCard missing attributes (again)

### ISSUE THREAD

**Issue by lovromazgon** [google/go-github#1071]
The [`ProjectCard`](https://github.com/google/go-github/blob/7c7d51f489bc54d96dfa34c497601b4a05d760c7/github/projects.go#L285) struct is currently still missing 4 attributes, which are returned from the [Events API](https://developer.github.com/v3/issues/events/):

Name | Type | Description
-- | -- | --
`project_card["project_id"]` | `string` | The identification number of the project.
`project_card["project_url"]` | `string` | The API URL of the project.
`project_card["column_name"]` | `string` | The name of the column that the card is listed in.
`project_card["previous_column_name"]` | `string` | The name of the column that the card was listed in prior to `column_name`. Only returned for `moved_columns_in_project` events.

Note: after testing it I see that `project_id` is actually an integer and not a string, as stated in the documentation.

Related issue: https://github.com/google/go-github/issues/667

**Comment by gmlewis** [comment]
Thank you for the issue, @lovromazgon!
Would you mind contacting support@github.com and explaining the discrepancy and ask them to either comment or update their documentation?

**Comment by lovromazgon** [comment]
I've contacted GitHub support and the field should indeed be an integer, they forwarded this to their Documentation team.

**Comment by gmlewis** [comment]
Excellent!  Thank you very much, @lovromazgon !

**Comment by gmlewis** [comment]
I must mention that the support team at GitHub has consistently been a pleasure to work with and always extremely responsive and helpful to requests!
