### ISSUE TITLE
Support Content Attachments API Public Beta

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#1073]
GitHub Developer API announcement:
https://developer.github.com/changes/2018-12-10-content-attachments-api/

As far as I can tell, the affected part of the GitHub V3 API is this:
https://developer.github.com/v3/apps/#create-a-content-attachment
but there may be more. Whoever takes this PR should read the announcement carefully and see what all is involved to resolve this issue.

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by dreamer-89** [comment]
@gmlewis : I want to take this issue. Please assign this issue to me.

**Comment by waseem18** [comment]
Are you working on this @dreamer-89 ? If not I would like to take this up.

**Comment by dreamer-89** [comment]
Hi @waseem18 , yes I am working on this. This is my first issue, thus struggling with doing this Github App using probot for better understanding. Please give me couple of days time, I will update here on this thread, if i couldn't make any progress.

**Comment by waseem18** [comment]
Thanks for the prompt reply.

**Comment by dreamer-89** [comment]
@gmlewis : Please have a look https://github.com/google/go-github/pull/1084

Right now, it is failing unit test with below two errors:

> CreateAttachment returned error: POST http://127.0.0.1:62948/api-v3/content_references/11/attachments: 404  []

**Comment by gmlewis** [comment]
I commented on the PR.

**Comment by dreamer-89** [comment]
> I commented on the PR.

Thanks a lot @gmlewis for the suggestion. I have updated the PR as per guidelines. Unit tests are working fine now.

**Comment by vaibhavsingh97** [comment]
@gmlewis This issue can be closed, as this is fixed in https://github.com/google/go-github/pull/1139
