### ISSUE TITLE
Support the new Interactions API

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#1077]
GitHub Developer API announcement:
https://developer.github.com/changes/2018-12-18-interactions-preview/

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by waseem18** [comment]
@gmlewis I'm really interested in working on this issue.

**Comment by gmlewis** [comment]
Thank you, @waseem18!

This issue is now assigned to you (sorry I can't send you an invite).

Please feel free to work on your PR in your own forked repo and send a pull request when you have tested it out and are ready to have it reviewed.

**Comment by waseem18** [comment]
Sure, Will do that :)

**Comment by waseem18** [comment]
I'm gonna divide this issue into two parts.

1. Interactions API for a repositories
2. Interactions API for organisations

I have put up a [WIP PR](https://github.com/google/go-github/pull/1078) for repo interactions. After finishing repo interactions will hop onto organisation interactions.

**Comment by waseem18** [comment]
Now that #1079 is merged. I'll start on adding Interactions API for Organizations.
