### ISSUE TITLE
When I imported the package, I found that the v21/ directory did not exist. I was surprised

### ISSUE THREAD

**Issue by LoloNoahSauron** [google/go-github#1083]
import "github.com/google/go-github/v21/github"

**Comment by LoloNoahSauron** [comment]
![image](https://user-images.githubusercontent.com/43988363/50436995-1ad23580-0923-11e9-8e6d-bc45d91b23e8.png)

**Comment by LoloNoahSauron** [comment]
There are only three folders

**Comment by LoloNoahSauron** [comment]
Or do you need to change github to v21?

**Comment by gmlewis** [comment]
Please take a look at the "Usage" information in our README.md:
https://github.com/google/go-github

```
import "github.com/google/go-github/v21/github"	// with go modules enabled (GO111MODULE=on or outside GOPATH)
import "github.com/google/go-github/github" // with go modules disabled
```

Are you using Go 1.11 modules? It sounds like you aren't, in which case you would remove the `v21` from the import.

To learn more about Go 1.11 modules, check this out: https://github.com/golang/go/wiki/Modules

**Comment by LoloNoahSauron** [comment]
ok, thanks
