### ISSUE TITLE
Change `acceptHeaders` to `wantAcceptHeaders` in `*_test.go` files

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#1086]
In #1082, @gauntface [noted](https://github.com/google/go-github/pull/1082#discussion_r244305892) that it would make more sense to use ~`wantHeaders`~ `wantAcceptHeaders` in test files than our current use of `acceptHeaders` and I think that's a good idea.

Let's change them in all `*_test.go` files.

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by palash25** [comment]
Requesting assignment @gmlewis

**Comment by gmlewis** [comment]
It just dawned on me that there is nothing technically incorrect about `acceptHeaders`... that's what they really are... but when reading that test code, a person might misinterpret that as "we want to accept these headers"... which would be wrong.

So what if we changed them to the more verbose `wantAcceptHeaders` instead?

Thoughts?

**Comment by palash25** [comment]
That does sound better :+1:

**Comment by gauntface** [comment]
+1 to wantAcceptHeaders

**Comment by palash25** [comment]
@gmlewis this issue can be closed now

**Comment by gmlewis** [comment]
Fixed by #1088. Closing.
