### ISSUE TITLE
Add unit tests for URL escaping for ref parameters

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#1101]
This issue is so that we don't lose track of @gauntface's [comment](https://github.com/google/go-github/pull/1099#pullrequestreview-193804131) about adding unit tests to #1099.

**Comment by vaibhavsingh97** [comment]
@gmlewis I want to take this issue. Please assign to me

**Comment by gmlewis** [comment]
I can't assign the issue to you, @vaibhavsingh97 but consider it yours.
Thank you!

**Comment by vaibhavsingh97** [comment]
Thanks, will send PR for same 🤗

**Comment by Avni-Sharma** [comment]
Hi @vaibhavsingh97 , are you working on this?

**Comment by vaibhavsingh97** [comment]
@Avni-Sharma yes, sorry for the delay was a busy week, will send PR shortly

**Comment by vaibhavsingh97** [comment]
@gmlewis I am stuck here for long time, please help me with this
I wrote the unit test but I don't know how to test it. I read how to contribute file aka `contributing.md`, but when I forked the repository and run `go build ./...` and `go test ./...` and it failed to find packages but when I clone `go-github` and run same commands then I am able to build and compile
![image](https://user-images.githubusercontent.com/8705386/52371896-b6a3a500-2a7c-11e9-8aa3-00ae804bd483.png)

**Comment by gmlewis** [comment]
It looks like you are missing dependencies needed by this package. You should be able to run `go get -u github.com/google/go-github` and it will get all the needed dependencies. Alternatively, you can run `go get -u` on each package that is missing, but that  shouldn't be necessary.
