### ISSUE TITLE
Release UploadOptions missing Label field

### ISSUE THREAD

**Issue by aidenkeating** [google/go-github#1103]
The GitHub v3 documentation for uploading a release asset references `label` as an optional field (see https://developer.github.com/v3/repos/releases/#input-2).

However, there is no label field in UploadOptions (see https://github.com/google/go-github/blob/master/github/github.go#L193)

I'm happy to take this on, just following the guideline here https://github.com/google/go-github/blob/master/CONTRIBUTING.md#submitting-a-patch

**Comment by gmlewis** [comment]
Thank you @aidenkeating! It's yours.
