### ISSUE TITLE
consider installing goodfirstissue app on project go-github

### ISSUE THREAD

**Issue by rajatjindal** [google/go-github#1110]
first of all thank you for this project, makes interactions with github api super simple.

using this library I've developed a github app [goodfirstissue](https://github.com/rajatjindal/goodfirstissue) which tweets 'good first issues' via twitter handle [@goodfirstissue](https://twitter.com/goodfirstissue)

the targeted audience for twitter account are first time contributors, and to encourage open source contributions.

## Some details:

**Permissions this app need:** read permission on issues and metadata.
**Twitter Handle used to tweet:** [@goodfirstissue](https://twitter.com/goodfirstissue)
**Source code of the app/webhook:** https://github.com/rajatjindal/goodfirstissue
**Instructions to install github app**: https://github.com/rajatjindal/goodfirstissue#how-to-install

Thank you for considering this app.

Disclaimer: i am the author of goodfirstissue app but also a first time contributor looking to engage more in open source contributions.

**Comment by gmlewis** [comment]
Very cool, @rajatjindal!

Thanks for the pointer.

@willnorris will need to make the decision for this repo and install the app if he chooses to run it.

**Comment by willnorris** [comment]
sure, we can try that out!  installed.

**Comment by rajatjindal** [comment]
thank you very much. appreciate it.
