### ISSUE TITLE
Unable to Edit Repository Webhooks

### ISSUE THREAD

**Issue by mattburgess** [google/go-github#1114]
Could you consider reverting https://github.com/google/go-github/pull/1111 please? Those API endpoints happen to be used by both the GitHub Services feature, which is being deprecated (as mentioned in https://github.com/google/go-github/issues/1109), but also by repository webhooks which are still very much a supported feature from what I can tell. https://developer.github.com/v3/guides/replacing-github-services/#replacing-services-with-webhooks mentions that the migration path is to use webhooks, and https://developer.github.com/webhooks/#webhooks still mentions both organization and repository webhooks.  Finally, the [announcement](https://developer.github.com/changes/2019-01-29-life-after-github-services/) specifically states that the particular APIs that were removed in https://github.com/google/go-github/pull/1111 

> affect the following endpoints for _service hooks only_ 

i.e. they're still vaild for repository hooks themselves.

FYI, I stumbled across this whilst trying to update the vendored version of go-github in https://github.com/terraform-providers/terraform-provider-github.

**Comment by gmlewis** [comment]
I apologize, @mattburgess - this is my fault. I'll revert.

**Comment by mattburgess** [comment]
That's awesome customer service @gmlewis thanks!  The terraform github provider passes a `make build` and `make test` run against v24.0.0.
