### ISSUE TITLE
Support Draft Pull Requests API Public Beta

### ISSUE THREAD

**Issue by dmitshur** [google/go-github#1120]
GitHub Developer API announcement: https://developer.github.com/changes/2019-02-14-draft-pull-requests/.

It looks like we'll need the following for this issue:

-	a new media type (`application/vnd.github.shadow-cat-preview+json`) must be added to `github.go`,
-	this media type must be added to the header of calls to all affected endpoints (list PRs, get a single PR),
-	a new `Draft` field must be added to the [`PullRequest`](https://godoc.org/github.com/google/go-github/github#PullRequest) struct that is returned from list/get PR endpoints,
-	~~and also to [`NewPullRequest`](https://godoc.org/github.com/google/go-github/github#NewPullRequest) struct used for creating a PR,~~ **Edit:** This doesn't need to be done; this isn't a part of the preview API at this time.
-	~~the [`PullRequestsService.Edit`](https://godoc.org/github.com/google/go-github/github#PullRequestsService.Edit) needs to be updated to allow the new `Draft` field to be passed~~ **Edit:** This doesn't need to be done; this isn't a part of the preview API at this time.

This would be a great PR for any new contributor to this repo or a new Go developer. All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by joshuabezaleel** [comment]
Hi @dmitshur , I am really new to Go and this repo but I tried to take a shot on this. I am sorry if there's anything wrong. Hope this works.

Looking forward to the review.
Thank you very much.

**Comment by dmitshur** [comment]
> I am really new to Go and this repo but I tried to take a shot on this. I am sorry if there's anything wrong.

@joshuabezaleel Thank you for doing that! You don't have to worry, we have code review exactly so that we can improve the PR and get it into a mergeable state.
