### ISSUE TITLE
Question about query with date that includes "+"

### ISSUE THREAD

**Issue by pankona** [google/go-github#1122]
Hello!

I tried to use `Search.Repositories` function.
I see it almost works well, but I tried to use query string `created:` that includes "+" doesn't work well.
Could you please give me some advice to use query in such situation.

Here's snippet I tried:

```go
// c is *github.Client
result, resp, err := c.Search.Repositories(
            context.Background(),                                                                                                       | 18             context.Background(),
            "user:pankona created:2019-01-18T17:35:34+09:00..2019-02-18T17:35:34+09:00 fork:true",                                      | 19             "user:pankona created:2019-01-18T17:35:34+09:00..2019-02-18T17:35:34+09:00 fork:true",
            &github.SearchOptions{                                                                                                      | 20             &github.SearchOptions{
                ListOptions: github.ListOptions{                                                                                        | 21                 ListOptions: github.ListOptions{
                    PerPage: 100,                                                                                                       | 22                     PerPage: 100,
                    Page:    page,                                                                                                      | 23                     Page:    page,
                }})  
```

According to result of `httpuitl.DumpRequestOut`, the escaped query seems as follows:
`GET /search/repositories?q=user:pankona+created:2019-01-18T17:35:34+09:00..2019-02-18T17:35:34+09:00+fork:true&page=1&per_page=100 HTTP/1.1`

I expects 1 results by this search but it returns 0.

(I think "+" included in query's date part is not escaped correctly. I guess it should be `%2B`. Is my assuming correct?)

**Comment by gmlewis** [comment]
Hi @pankona - thank you for the question.

Here https://github.com/google/go-github/blob/master/github/search.go#L230
we have: `query := "q=" + url.PathEscape(q)` and I'm thinking that this instead needs to be
`query := "q=" + url.QueryEscape(q)`

Could you please try that out and report back if it solves the problem you are seeing?

**Comment by pankona** [comment]
Hi @gmlewis , thank you for your reply!

I tried to use `url.QueryEscsape` then I got escaped url as follows:
`GET /search/repositories?q=user%3Apankona%2Bcreated%3A2019-01-18T17%3A35%3A34%2B09%3A00..2019-02-18T17%3A35%3A34%2B09%3A00%2Bfork%3Atrue&page=1&per_page=100 HTTP/1.1`

Unfortunately I got failed from github API. Returned message is:
`{"message":"Validation Failed","errors":[{"message":"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.","resource":"Search","field":"q","code":"invalid"}],"documentation_url":"https://developer.github.com/v3/search/"}`

I think,
- `url.QueryEscape` escapes "+" correctly ("+" are replaced to %2B) 
- But all "+" should not be escaped since some "+" may mean white space
  - search.go#L226 replaces white speces to "+" 

Here's snippet around here:
https://github.com/google/go-github/blob/4e1a504644bfd34564773b2f8c4c2ba91c8e21ec/github/search.go#L226-L230

I'm not sure but is this expected URL and query?
- "+" that means white space are remained
- "+" in date part are escaped to %2B
`
GET /search/repositories?q=user:pankona+created:2019-01-18T17:35:34%2B09:00..2019-02-18T17:35:34%2B09:00+fork:true&page=1&per_page=100 HTTP/1.1`

I tried this URL and query, I got expected result from GitHub API.

**Comment by gmlewis** [comment]
Thank you, @pankona for investigating!

It sounds like we need a more robust escape mechanism.

If anyone would like to tackle this issue, that would be fantastic.
This would need a wide range of (table-driven) tests in the Go style to accompany the PR.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by pankona** [comment]
@gmlewis 

Thank you so much for summarizing. I will try to create patch for this issue!

**Comment by pankona** [comment]
@gmlewis 

I found simple solution. Could you please review #1125 ?

**Comment by gmlewis** [comment]
Thank you, @pankona - please see my comment about #966 and #963.

**Comment by pankona** [comment]
@gauntface @gmlewis 

As mentioned on issue, I supplied comments on `search()` to highlight usage between " " vs "+".
Could you please take a look?
