### ISSUE TITLE
Support Webhooks without a Secret

### ISSUE THREAD

**Issue by jbrockopp** [google/go-github#1126]
I have been unable to find a way of using this library to handle webhooks that do not contain a [secret token](https://developer.github.com/webhooks/securing/#setting-your-secret-token).

Source code:

https://github.com/google/go-github/blob/00add49aab2728f7c246b27be612b002b22e7f94/github/messages.go#L142-L183

Currently, the function expects `secretKey []byte` as a parameter. I believe the simplest way to complete this would be to update the [relevant code](https://github.com/google/go-github/blob/master/github/messages.go#L178-L181) to look like:

```go
	if secretKey != nil {
		sig := r.Header.Get(signatureHeader)
		if err := ValidateSignature(sig, body, secretKey); err != nil {
			return nil, err
		}
	}

	return payload, nil
```

Playing off the provided example usage for the `ValidatePayload` function, it could be consumed like:

```go
func (s *GitHubEventMonitor) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	// Contains a webhook secret token
	payload, err := github.ValidatePayload(r, s.webhookSecretKey)
	if err != nil { ... }
	// Does not contain a webhook secret token
	payload, err := github.ValidatePayload(r, nil)
	if err != nil { ... }
	// Process payload...
}
```

Is there a reason why this functionality isn't offered today?

NOTE: I could see a reasoning that the library doesn't currently support this because of security related reasons. However, I'd like to propose we leave that up to the consumer of the library to determine the security standards for their project.

**Comment by gmlewis** [comment]
Let's step back for one moment... can you please describe what your use case is?

If I'm not mistaken, GitHub requires that you set up a secret key when creating the webhook and your webhook should always be validated, otherwise any system could hit your webhook endpoint with garbage. OK, I see you make the "I want to handle my own security" argument... but I would still like to understand why you would want to remove this validation?

If we head down this potentially dangerous route, we have to make it extremely clear to all users of this package that disabling the validation check is highly discouraged.

**Comment by willnorris** [comment]
I don't *think* this was a conscious decisions to always require a webhook secret.  In our initial use case, we always had one, and so maybe I just assumed folks would always want one present?  I don't remember.

But I'm personally fine with the suggested change, as it is quite minimal.  And to your point @gmlewis, we can add some clear documentation that this is probably a really bad idea unless you know what you're doing.  But there's probably no reason for us to actually prevent it.

**Comment by gmlewis** [comment]
OK, sounds good to me, then, @willnorris ... thanks for the feedback!

Feel free to move ahead with the PR, @jbrockopp.

**Comment by jbrockopp** [comment]
@gmlewis @willnorris I really want it for local development.

I 100% acknowledge that not having a webhook is against best practices. 

However, if I'm just starting out creating an application that is going to parse a webhook, I would probably be developing locally first and I may not have a deployable application to point my webhook at yet. 

When you provide the "secret token", the `X-Hub-Signature` header gets passed along which Github generates and I don't have the experience to "fake out" the header on the fly. The rest of the webhook headers and payload can be "faked out" for local development pretty easily IMO.

Due to that header being hard to manually create, this could cause a barrier to entry if I'm using this library because it would require me to have an actual application deployed that I could point a real webhook at BEFORE I can start to test out my local code.

Let me know if my use case doesn't make sense or if it prompted more questions. I'll begin opening up the PR shortly.

**Comment by jbrockopp** [comment]
@gmlewis @willnorris The pull request I submitted is https://github.com/google/go-github/pull/1127

**Comment by kshitij10496** [comment]
Based on my (limited) experience working with GitHub webhooks, this change would potentially be helpful during the local development phase of bots/applications using this library. 

I agree with the security concern raised by @gmlewis and @willnorris above, and that we need to explicitly document that the use of this feature in production is highly discouraged.

> Due to that header being hard to manually create, this could cause a barrier to entry if I'm using this library because it would require me to have an actual application deployed that I could point a real webhook at BEFORE I can start to test out my local code.

Based on my understanding of the mechanism of validation, GitHub generates the HMAC hexdigest of the response payload using the same secret token provided by us and passes it in the `X-Hub-Signature` header. We can mimic this using some string manipulation and _HMAC foo_ ([geckoboard/cake-bot](https://github.com/geckoboard/cake-bot/pull/19)).

Refer: [Validating payloads from GitHub](https://developer.github.com/webhooks/securing/#validating-payloads-from-github)

**Comment by gmlewis** [comment]
Thank you, @kshitij10496 for the comment!  I now remember doing something like this, although it was a few years ago, but it worked just fine. It's a little bit of effort, but not much.
