### ISSUE TITLE
Mocking go-github

### ISSUE THREAD

**Issue by tbruyelle** [google/go-github#113]
I would like to write tests for an app that uses a lot `go-github`. 

For instance I would like to mock some methods in the `client.*Services` structs. Is this possible with the current usage of structs ? Wouldn't it be preferable that the client struct holds some interfaces rather than some structs ? With interfaces, mocking is very easy with struct embedding.

**Comment by willnorris** [comment]
I'm going to go ahead and close this out, as there's no work to be done.  The above mocking strategy described in my last comment (where the application itself defines the interfaces which go-github implements) is used heavily inside Google, both for go-github and lots of other libraries, and it's worked really well for us.

**Comment by noonien** [comment]
Could you please provide an example of a projects or code that mocks go-github, or a similar library in the manner that you suggest?

I've grepped trough [all the projects that import go-github](http://godoc.org/github.com/google/go-github/github?importers) and not a single one has managed to mock this library. The best effort I've seen just used a httptest and checked that the appropriate paths were called.

**Comment by willnorris** [comment]
Unfortunately, all of the examples I have are internal Google projects which aren't open source.  But they use exactly the method described above together with gomock.

**Comment by Skarlso** [comment]
For anyone potentially looking for an example of how to use the above scheme in a project. Here is an example of this:

In code: https://github.com/gaia-pipeline/gaia/blob/master/pipeline/git.go#L168-L194
In test: https://github.com/gaia-pipeline/gaia/blob/master/pipeline/git_test.go#L252

**Comment by Skarlso** [comment]
@artem-sidorenko Oh excellent. Thanks for fixing that. :)

**Comment by wimglenn** [comment]
There is a more minimal example also given here that I found helpful: https://github.com/google/go-github/issues/1181#issuecomment-497893994

**Comment by shadowshot-x** [comment]
If you are looking to override the external calls, try using this.  :-

For external calls, try to use a variable func and assign the external call. Example :-

```
var getRepoContents func(_ *github.RepositoriesService, ctx context.Context, owner string, repo string, path string, opts *github.RepositoryContentGetOptions) (fileContent *github.RepositoryContent, directoryContent []*github.RepositoryContent, resp *github.Response, err error) = (*github.RepositoriesService).GetContents
```

Call this function in your main methods where you need it. In your tests, simply override it.
```
origGetRepoContents := getRepoContents

//===== Your Code for testing here ======//

getRepoContents = origGetRepoContents
```
