### ISSUE TITLE
Support preview enable/disable Pages API

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#1133]
GitHub Developer API announcement:
https://developer.github.com/changes/2019-03-14-enabling-disabling-pages/

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by vaibhavsingh97** [comment]
@gmlewis I would love to take this issue

**Comment by gmlewis** [comment]
Thank you, @vaibhavsingh97!
Consider it yours. 😁

**Comment by waseem18** [comment]
@vaibhavsingh97 Are you still working on this? If not I would love to take this up :)

**Comment by vaibhavsingh97** [comment]
Hi @waseem18 I am working on it and will send PR soon
