### ISSUE TITLE
Organizations.ListMembers User object not getting certain fields

### ISSUE THREAD

**Issue by FM1337** [google/go-github#1134]
When using Organizations.ListMembers and going through the members/users list that it returns, I've found that it fails to fetch fields like the user's bio and the user's name even if they have it set.

When testing with Users.Get, I found that the user's bio was returned correctly (as well as their name, not to be confused with Login(aka their username))

**Comment by gmlewis** [comment]
Have you checked the GitHub Developer API docs to see what they say about it?
The URLs should be in comments right above the Go method.
Also, you can test to see if the `curl` equivalent behaves differently.
If you could report back on these findings, it would be greatly appreciated.

Thank you, @FM1337!

**Comment by FM1337** [comment]
Okay, so I think I understand a bit more of what's going on now (and I do a apologize for being a bit of a fool)

When the ListMembers is called, it doesn't make a call to the user's URL (in my case it would be https://api.github.com/users/FM1337) it only uses the fields that returned in the JSON response at the members (or public_members) endpoint.

Meaning that this isn't a bug, but rather it is designed like this on purpose.

**Comment by gmlewis** [comment]
No problem, @FM1337!
It definitely can be confusing!
Glad to hear you figured it out.
