### ISSUE TITLE
Support preview endpoints to list branches or pull requests for a commit 

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#1151]
GitHub Developer API announcement:
https://developer.github.com/changes/2019-04-11-pulls-branches-for-commit/

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by vaibhavsingh97** [comment]
@gmlewis Can I take this?

**Comment by gmlewis** [comment]
Thank you, @vaibhavsingh97 !
It's yours.

**Comment by Daanikus** [comment]
@vaibhavsingh97 Any update on this?

**Comment by waseem18** [comment]
@vaibhavsingh97 Any update on the PR?

**Comment by sks444** [comment]
If no one is working on this issue, I would like to take this up.

**Comment by gmlewis** [comment]
I think we can safely say that this issue has been abandoned.

@sks444 - it is yours.
Since #1170 was never reviewed, feel free to start from scratch as you see fit, carefully reviewing the GitHub Developer API announcement listed at the top of this issue and following our CONTRIBUTING.md guide also linked above.

Thank you, @sks444!

**Comment by sks444** [comment]
Thank you @gmlewis,

I will go through all the prerequisite and start working on this.
