### ISSUE TITLE
Remove NodeID from NewTeam struct

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#1152]
In https://github.com/google/go-github/pull/1149#pullrequestreview-226412764, @dmitshur pointed out that `NodeID` should be removed from the `NewTeam` struct.

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by cpanato** [comment]
@gmlewis can i try this one?

**Comment by gmlewis** [comment]
Thank you, @cpanato! 
Yes, it is yours.

**Comment by cpanato** [comment]
PR: https://github.com/google/go-github/pull/1153
