### ISSUE TITLE
Support new webhook events and actions

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#1160]
GitHub Developer API announcement:
https://developer.github.com/changes/2019-04-18-new-webhook-events-and-actions/

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by joshuabezaleel** [comment]
Hi @gmlewis ! Can I take a shot on this? 🙂

**Comment by gmlewis** [comment]
Sure, @joshuabezaleel! Thank you!
It is yours.

**Comment by joshuabezaleel** [comment]
Hi @gmlewis , how do we have to write/generate for the github-accessors.go? Or it will be automatically generated by the gen-accessors.go?

**Comment by gmlewis** [comment]
Check out CONTRIBUTING.md. It has all the details.
