### ISSUE TITLE
Support preview enable or disable vulnerability alerts API for a repository

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#1164]
GitHub Developer API announcement:
https://developer.github.com/changes/2019-04-24-vulnerability-alerts/

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by cpanato** [comment]
Can i try this one?

**Comment by gmlewis** [comment]
Sure, @cpanato - it is yours. Thank you!
