### ISSUE TITLE
Support for Get team by name API for Github Enterprise 

### ISSUE THREAD

**Issue by sourabh3b** [google/go-github#1167]
Currently, we have API to get team details from team_slug. 
link : https://developer.github.com/v3/teams/#get-team-by-name
But this is API is not available in Github enterprise.  link : 
https://developer.github.com/enterprise/2.16/v3/teams/ . Do we have plans to get support for this API in Github enterprise ?

**Comment by gmlewis** [comment]
I believe that this is a question you will want to ask support@github.com.
This repo isn't maintained by GitHub... just by a few enthusiastic Go fans. :smile:

**Comment by sourabh3b** [comment]
sure, thanks
