### ISSUE TITLE
Support preview Update Branch API

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#1183]
GitHub Developer API announcement:
https://developer.github.com/changes/2019-05-29-update-branch-api/

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by waseem18** [comment]
@gmlewis I'd like to work on this issue

**Comment by gmlewis** [comment]
Thank you, @waseem18!
It is yours.
