### ISSUE TITLE
Support preview Automated Security Fixes API

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#1184]
GitHub Developer API announcement:
https://developer.github.com/changes/2019-06-04-automated-security-fixes/

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by cpanato** [comment]
Can i take this one?

**Comment by gmlewis** [comment]
Yes, @cpanato, it is yours.
Thank you!
