### ISSUE TITLE
Support preview Team Sync API for GitHub Enterprise Cloud users

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#1200]
GitHub Developer API announcement:
https://developer.github.com/changes/2019-06-12-team-sync/

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by vaibhavsingh97** [comment]
I would love to fix this issue 😄

**Comment by gmlewis** [comment]
Thank you, @vaibhavsingh97 ! It's all yours.
