### ISSUE TITLE
Support preview repository creation template API

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#1235]
GitHub Developer API announcement:
https://developer.github.com/changes/2019-07-16-repository-templates-api/

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by waseem18** [comment]
I'd like to take this up @gmlewis

**Comment by shanempope** [comment]
@waseem18 I started this as a learning exercise, feel free to use my changes or redo it. I did not want to claim it in case it was over my head. I've linked the PR above. But I appear to need more code coverage. I will look into it tomorrow if you haven't finished your own. Take care!

**Comment by gmlewis** [comment]
Thank you, @waseem18, for your offer, and thanks also for your understanding about @shanempope putting together a PR.

Thanks, @shanempope, for your PR... I reviewed it and made some comments.  In the future, please place a note on the issue that you are working on it so others don't waste their time working on it too.  Thanks!
