### ISSUE TITLE
Add Support For Installation Token Parameters

### ISSUE THREAD

**Issue by emoryruscus** [google/go-github#1237]
Add support for passing additional repository ids and permissions when creating a github installation token.

https://developer.github.com/v3/apps/#create-a-new-installation-token

**Comment by emoryruscus** [comment]
Have worked on this and will be submitting a pull request shortly.

**Comment by gmlewis** [comment]
Are you sure we don't already have this functionality?

https://github.com/gmlewis/go-github/blob/master/github/apps.go#L194-L215

**Comment by ambientsound** [comment]
Thank you @emoryruscus for bringing this up. We're currently implementing a service that will issue scoped installation tokens, would be great to have #1238 merged into go-github.

**Comment by chughpiyush** [comment]
@gmlewis I think this one can be closed.

**Comment by gmlewis** [comment]
Closing as fixed by #1238.
