### ISSUE TITLE
Support deleting head branch of GitHub pull requests

### ISSUE THREAD

**Issue by TomTucka** [google/go-github#1245]
add support for this new feature: https://help.github.com/en/articles/managing-the-automatic-deletion-of-branches

**Comment by stefansedich** [comment]
I might be blind but looking at the V3 Repositories API I cannot see this being part of it...

**Comment by TomTucka** [comment]
@stefansedich Yep! I have asked @GithubHelp on twitter. Will post a response when they reply

**Comment by TomTucka** [comment]
Confirmed by @githubhelp on twitter that this is not in the `v3` or `v4` API. They are going to check if its on the engineering teams roadmap.

**Comment by gmlewis** [comment]
Closing due to lack of support in the v3 API. Please reopen if it becomes supported.

**Comment by cmardonespino** [comment]
@TomTucka Amigo, exists new news about this? I think that it could be pretty usefull if this feature is support for terraform!

**Comment by eriksw** [comment]
@gmlewis Please reopen—GitHub seem to have added this to the api.

Looking at the documentation I see `delete_branch_on_merge` as a parameter for repo [create](https://developer.github.com/v3/repos/#create) and [edit](https://developer.github.com/v3/repos/#edit).

**Comment by gmlewis** [comment]
Cool!  Thank you, all!

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by stefansedich** [comment]
@gmlewis I will pick this up been waiting for the API change long enough may as well see it home :) can you assign it to me?

**Comment by gmlewis** [comment]
Thank you, @stefansedich!  It's yours.

**Comment by TomTucka** [comment]
@stefansedich Can you ping me when this is done? I'd like to add support for this to the terrafrom provider for GitHub

**Comment by stefansedich** [comment]
Sorry @TomTucka was out all weekend, only just sat down and got the PR up!

**Comment by stefansedich** [comment]
@TomTucka I don't mind picking up the Terraform module side once #1388 gets merged.
