### ISSUE TITLE
Question about git push mirror

### ISSUE THREAD

**Issue by crazytaxii** [google/go-github#1246]
Does this library support `git push --mirror` operation?

**Comment by gmlewis** [comment]
No, this repo is a Go package for accessing the GitHub REST Developer API v3:
https://developer.github.com/v3/

The closest approximation to this would be creating a fork:
https://developer.github.com/v3/repos/forks/#create-a-fork

**Comment by crazytaxii** [comment]
Oh I got it, go-github is just a library implementing GitHub API.

**Comment by gmlewis** [comment]
Yes, exactly.
