### ISSUE TITLE
CreateFile or UpdateFile returns 404 Not Found

### ISSUE THREAD

**Issue by hpalba** [google/go-github#1247]
I'm always getting 404 not found when using either CreateFile or UpdateFile. I tried using curl and postman with my correct authentication provided and accessing github api directly works.  But when using the go-github, it won't work.  I already used ListBranches of go-github and this worked fine with my authentication.

My code has:
		commitOption := &github.RepositoryContentFileOptions{
		Branch:  github.String("master"),
		Message: github.String("testing this"),
		Committer: &github.CommitAuthor{
			Name:  github.String("theauthor"),
			Email: github.String("theauthor@email.com"),
		},
		Author: &github.CommitAuthor{
			Name:  github.String("theauthor"),
			Email: github.String("theauthor@email.com"),
		},
		Content: []byte("this is my content"),
	}
	
	c, resp, err := ghClient.Repositories.CreateFile(ctx, owner, repoName, "test1", commitOption)

ERROR i got:
:error: PUT https://api.github.com/repos/testuser/testrepo/contents/test1: 404 Not Found []

&github.ErrorResponse{Response:(*http.Response)(0xc0001e2120), Message:"Not Found", Errors:[]github.Error(nil), Block:(*struct { Reason string "json:\"reason,omitempty\""; CreatedAt *github.Timestamp "json:\"created_at,omitempty\"" })(nil), DocumentationURL:"https://developer.github.com/v3/repos/contents/#create-or-update-a-file"}

**Comment by gmlewis** [comment]
I just ran your test program, and it worked fine for me in order to create a new file in a repo.

For completeness, here is my entire `main.go`:

```go
package main

import (
	"context"
	"log"

	"github.com/davecgh/go-spew/spew"
	"github.com/google/go-github/github"
	"golang.org/x/oauth2"
)

const (
	owner    = "gmlewis"
	repoName = "my-test-repo"
)

func main() {
	ts := oauth2.StaticTokenSource(
		&oauth2.Token{AccessToken: "<token-elided>"}, // repos - gmlewis account
	)
	tc := oauth2.NewClient(oauth2.NoContext, ts)
	client := github.NewClient(tc)

	commitOption := &github.RepositoryContentFileOptions{
		Branch:  github.String("master"),
		Message: github.String("testing this"),
		Committer: &github.CommitAuthor{
			Name:  github.String("theauthor"),
			Email: github.String("theauthor@email.com"),
		},
		Author: &github.CommitAuthor{
			Name:  github.String("theauthor"),
			Email: github.String("theauthor@email.com"),
		},
		Content: []byte("this is my content"),
	}
	ctx := context.Background()
	c, resp, err := client.Repositories.CreateFile(ctx, owner, repoName, "test1", commitOption)
	if err != nil {
		log.Fatalf("CreateFile: %v", err)
	}
	log.Printf("resp.Status=%v", resp.Status)
	log.Printf("resp.StatusCode=%v", resp.StatusCode)
	spew.Dump(c)
}
```

Here is what happened when I ran the program:

```
$ go run main.go
2019/08/08 22:46:50 resp.Status=201 Created
2019/08/08 22:46:50 resp.StatusCode=201
(*github.RepositoryContentResponse)(0xc0000ec300)(github.Commit{SHA:"08dfa6994ffbabea4203dfcf61e532abcf892ca9", Author:github.CommitAuthor{Date:time.Time{wall:, ext:}, Name:"theauthor", Email:"theauthor@email.com"}, Committer:github.CommitAuthor{Date:time.Time{wall:, ext:}, Name:"theauthor", Email:"theauthor@email.com"}, Message:"testing this", Tree:github.Tree{SHA:"b26bc981a0fdd4d4432ab411ecd578aab6e55027"}, Parents:[github.Commit{SHA:"e66cd208f702e26c21d9d5a5e478cd6fd74466ac", HTMLURL:"https://github.com/gmlewis/my-test-repo/commit/e66cd208f702e26c21d9d5a5e478cd6fd74466ac", URL:"https://api.github.com/repos/gmlewis/my-test-repo/git/commits/e66cd208f702e26c21d9d5a5e478cd6fd74466ac"}], HTMLURL:"https://github.com/gmlewis/my-test-repo/commit/08dfa6994ffbabea4203dfcf61e532abcf892ca9", URL:"https://api.github.com/repos/gmlewis/my-test-repo/git/commits/08dfa6994ffbabea4203dfcf61e532abcf892ca9", Verification:github.SignatureVerification{Verified:false, Reason:"unsigned"}, NodeID:"MDY6Q29tbWl0MTAzOTk4OjZjYxZTUzMmFiY2Y4OTJjYTk="})
```

Because of the `404 Not Found`, I'm guessing that your `owner` or `repoName` is not correct.
But `go-github` appears to be working just fine.
(Is your repo's "owner" name really "testuser"? Probably not.. Is "testrepo" really correct? Probably not... but maybe you changed those in your issue report above.  Double-check those and make sure you got everything correct.)

Also check that your access token is correct and that the service account that is associated with that access token has sufficient privileges (in the affected repo) to write to that repo.

Good luck.

**Comment by hpalba** [comment]
Thanks very much. My problem was that one of my If statement is skipping my authentication code.  What bothers me is the error code 404 instead of 401.

**Comment by gmlewis** [comment]
OK, great. Glad you found the problem. We are happy to accept PRs.  :smile:
