### ISSUE TITLE
ListTeams is not providing Team Members Count in RepositoriesService

### ISSUE THREAD

**Issue by donofden** [google/go-github#1252]
I'm using `ListTeams()` to get details on the teams for the specified repository using `RepositoriesService`, but I don't get the 
`GetMembersCount()`. 

https://github.com/google/go-github/blob/24f172eae1a0c53c780f259d8492979900e9af2e/github/repos.go#L623

https://github.com/google/go-github/blob/24f172eae1a0c53c780f259d8492979900e9af2e/github/github-accessors.go#L11264

**It is not returning the Member Count, return zero all the time.**

**Comment by gmlewis** [comment]
Following the URL on the line above the one you gave:
https://github.com/google/go-github/blob/24f172eae1a0c53c780f259d8492979900e9af2e/github/repos.go#L622
leads us to the GitHub Developer API v3 documentation for this endpoint, where you will see that the `members_count` is not being returned in that endpoint:

```
Status: 200 OK
Link: <https://api.github.com/resource?page=2>; rel="next",
      <https://api.github.com/resource?page=5>; rel="last"
[
  {
    "id": 1,
    "node_id": "MDQ6VGVhbTE=",
    "url": "https://api.github.com/teams/1",
    "name": "Justice League",
    "slug": "justice-league",
    "description": "A great team.",
    "privacy": "closed",
    "permission": "admin",
    "members_url": "https://api.github.com/teams/1/members{/member}",
    "repositories_url": "https://api.github.com/teams/1/repos",
    "parent": null
  }
]
```

Therefore, this endpoint will not get you what you want.

I think what you might be looking for instead is:
https://developer.github.com/v3/teams/members/#list-team-members

**Comment by donofden** [comment]
@gmlewis  As per ur comment, `GetCloneURL`, `GetArchiveURL()`, `GetCreatedAt()` too not part of the response but I can able to get in the `ListTeams`  response. 

![Screenshot 2019-08-16 at 6 45 44 PM](https://user-images.githubusercontent.com/5079613/63170074-14313380-c056-11e9-8106-9028895bfe3d.png)

**Comment by gmlewis** [comment]
Then all that means is that the GitHub endpoint is returning that data and their documentation is incomplete.

We can't magically return the `members_count` if the GitHub endpoint is not sending it in the response.

**Comment by wesleimp** [comment]
@gmlewis How to proceed with this issue?

**Comment by gmlewis** [comment]
If anyone wishes to contact support@github.com and ask them to include or populate more fields, they are welcome to.  They can them come back and reopen this issue and include the GitHub response if they agree.  Thanks.

Closing until then.
