### ISSUE TITLE
List Repositories by Org does not support sorting

### ISSUE THREAD

**Issue by Xopherus** [google/go-github#1257]
Sorting repositories is supported by the v3 API, can those options be made available in the `RepositoryListByOrgOptions` struct? 

Sorry for the duplicate, but the older issue is almost 3 years old (#321), figured I would reopen for visibility!

**Comment by gmlewis** [comment]
Related GitHub docs: https://developer.github.com/v3/repos/#list-organization-repositories

#1258 has already been created to address this issue.

**Comment by wesleimp** [comment]
@gmlewis this issue can be closed

**Comment by gmlewis** [comment]
Thank you, @wesleimp.
Closing.
