### ISSUE TITLE
Can't make Issue Template when repository's branch protected

### ISSUE THREAD

**Issue by yunsoul** [google/go-github#1259]
When repository's branch(master) is protected like below, I cannot make Issue Template with go-github API

![image](https://user-images.githubusercontent.com/10693701/63480449-e3755200-c4cc-11e9-82ed-3f09e53e303a.png)

* If I remove the branch's protection configuration, I'm able to make Issue Template.
* And used access token has r/w right to the repository

**Comment by gmlewis** [comment]
Have you checked the GitHub Developer API v3 documentation to see if it is possible to do what you want, or if this is being prevented by the API itself?

If to still feel that the problem lies within this repo, please provide a more detailed example of what methods you are calling, preferably with an example program.

**Comment by yunsoul** [comment]
I can't find the proper API for making issue template in the GitHub Developer API v3.
So, I tried like this...

```go
opt := &github.RepositoryContentFileOptions{
			Message:	github.String("blabla"),
			Content:	contents,
			Branch:		github.String("master"),
			Committer:	&github.CommitAuthor{
						Name: github.String("author"), 
						Email: github.String(some_mail_address),
					},
		}

_, _, err = app.Repositories.CreateFile(context.Background(), org, repo, ".github/ISSUE_TEMPLATE/test-template.md", opt)
```

**Comment by gmlewis** [comment]
If you can't find the API in the GitHub Developer API v3 documentation, then you will not find the API in this repo either, as this repo is a Go client library for the GitHub Developer API v3.
