### ISSUE TITLE
feature request : getting App's installation ID API

### ISSUE THREAD

**Issue by yunsoul** [google/go-github#1261]
Could you add new API which we can get Github App's installation ID more easily?
Sometimes it need to know without github hook event. 

* API spec.
  * input : Github App's App ID, organization name, repository name
  * output : the target Github App's Installation ID

**Comment by gmlewis** [comment]
Hi @yunsoul, as I mentioned [elsewhere](https://github.com/google/go-github/issues/1259#issuecomment-523723713), this repo is a Go client to the GitHub Developer's API v3.

What this means is that you need to find the API you want from the GitHub Developer API documentation first, and then find the corresponding endpoint(s) in this client package.
Alternatively, you can look through the [auto-generated Godocs](https://godoc.org/github.com/google/go-github/github) for this package and proceed from there.

For example, it looks like you might be interested in this endpoint:
https://developer.github.com/v3/apps/installations/#list-installations-for-a-user

So you therefore might want this method:
https://godoc.org/github.com/google/go-github/github#AppsService.ListUserInstallations

Typically, this client package closely corresponds to the GitHub Developer API endpoints and we usually do not make helper functions except on rare occasions.

I hope that helps.

**Comment by yunsoul** [comment]
@gmlewis Thank you for your mention.

In my development scenario, knowing who installed the app doesn't help and even don't know who installed the app.
My goal is to know the installation ID of the app installed in a particular repository.
