### ISSUE TITLE
Support PubSubHubbub API for creating hooks

### ISSUE THREAD

**Issue by tomasaschan** [google/go-github#1265]
Are there any plans to support [the PubSubHubbub API for creating webhooks](https://developer.github.com/v3/repos/hooks/#pubsubhubbub)?

I could try to create a PR for implementing this (I'm hoping to use it for implementing https://github.com/terraform-providers/terraform-provider-github/issues/275) if there is any chance of it being accepted.

**Comment by tomasaschan** [comment]
@gmlewis Great! Is there any design documents or similar that I should submit for review before starting to work on the actual code? (Also, are there any specific build instructions for this repo I should know about?)

**Comment by tomasaschan** [comment]
All the infrastructure for handling authentication etc seems to already be handled, so I figure I can just look at how other API calls are handled, and mimic that. For example, the [create webhook code](https://github.com/google/go-github/blob/master/github/repos_hooks.go#L108) seems simple enough to imitate.

To avoid cluttering up existing code, I figure I'll place it in a new file `github/repos_pubsubhubbub.go` (with unit tests next to it), and add the functions to the `RepositoryService` type.

Does that sound OK?

**Comment by gmlewis** [comment]
That sounds like a great plan to me. Hopefully if others have any feedback they will respond to this thread earlier rather than later. :joy:

**Comment by wesleimp** [comment]
@gmlewis this issue can be closed

**Comment by gmlewis** [comment]
It seems to me like this issue is still open, @wesleimp ... why do you say this one can be closed?

**Comment by wesleimp** [comment]
@gmlewis you are correct, sorry my bad.

**Comment by gmlewis** [comment]
No problem, @wesleimp !  Thank you for all your help!  It is greatly appreciated!

**Comment by joshuabezaleel** [comment]
Hi @gmlewis , I stumbled upon this issue while browsing the repo and I am interested if somehow this issue is still available :slightly_smiling_face:

**Comment by gmlewis** [comment]
Yes, since we have not heard from @tomasaschan since last August, I think we can safely assume that this issue is available.

Thank you, @joshuabezaleel !  I'll assign it to you.

**Comment by joshuabezaleel** [comment]
Hi @gmlewis , is it okay if I ask a particular technical question here? 

For [`DeleteHook` testing](https://github.com/google/go-github/blob/master/github/repos_hooks_test.go#L143-L155), does it mean that we don't have to check whether the statusCode of the response is [204 or not](https://developer.github.com/v3/repos/hooks/#response-6)? 
I tried to issue the PubSubHubBub request using curl and it returns 204 with proper parameters and 422 with invalid parameters but I kept getting 200 while firing it in the testing part of the code.

**Comment by gmlewis** [comment]
If I understand correctly, you are asking about the unit test...  Correct, you don't need to fake (or test) the 204 explicitly... it is sufficient to just fake/test the 200.  You can modify the test if you wish, but the unit tests are mainly concerned with getting the full round-trip exercised, and the 200 is sufficient.

Thank you, @joshuabezaleel !

**Comment by joshuabezaleel** [comment]
Hi @gmlewis , I was actually thinking of this since the `resp.statusCode` would be different if I leave some required parameter empty, that is `hub.mode` and `hub.topic`, or not so I don't know whether I should cover this for the test.

I've put up a PR and I think the code is still not good enough and really subject to change. Sorry for the troublesome in advance. Looking forward to the review! :slightly_smiling_face:

**Comment by gmlewis** [comment]
This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

**Comment by hemachandarv** [comment]
@gmlewis I saw that there was a closed PR (#1540) related to this issue. Can I take this up?

**Comment by gmlewis** [comment]
> @gmlewis I saw that there was a closed PR (#1540) related to this issue. Can I take this up?

Thanks, @hemachandarv , but let's see how #625 goes before you also attempt to tackle this one.
We'll leave this one open so someone else can take it while you work on the other one.
Then, if this is still available when you are done with the other, we can assign it to you.

**Comment by hemachandarv** [comment]
Sounds like a plan. Thanks, @gmlewis

**Comment by hemachandarv** [comment]
@gmlewis As #625 is about to be closed, can I take this up?

**Comment by gmlewis** [comment]
> @gmlewis As #625 is about to be closed, can I take this up?

Sure, @hemachandarv , it is yours. Thank you!
