### ISSUE TITLE
Deleting a file using TreeEntry/CreateTree/CreateCommit?

### ISSUE THREAD

**Issue by bmcstdio** [google/go-github#1268]
I know it is possible to delete a file using `DeleteFile`, but that doesn't seem to support signing the resulting commit. Hence, I'd like to be able to use `TreeEntry`, `CreateTree` and `CreateCommit` to delete a file, but I can't seem to be able to do that. Is there an example of deleting a file using these APIs I can have a look at?

**Comment by gmlewis** [comment]
Looking at our source-of-truth, which is the GitHub Developer API v3 (that this repo is simply a client of):
https://developer.github.com/v3/git/trees/#create-a-tree
It appears that you could create a tree and commit it and the new tree will completely replace the contents of the previous tree.

I have not done this myself and don't have time to create an example, but it looks like this is possible.

If other contributors feel like cooking up an example for @bmcstdio, you are welcome to, and I'll leave this issue open.
