### ISSUE TITLE
Discussion: release cadence

### ISSUE THREAD

**Issue by willnorris** [google/go-github#1280]
gmlewis@: Looking at https://github.com/google/go-github/releases, it seems like you've been tagging a new release nearly every time you merge a pull request, is that right?  That's really not necessary, and we should probably slow it down a bit.  It creates a bunch of extra work (for you!) and noise to tag releases that end up getting newer releases tagged hours or even minutes later.  It also makes it much harder for users to stay up to date with the latest version, if that is their goal.

I totally appreciate you continuing to help us keep the library going!!  But I'd like to see if we can find a release cadence that's more on the order of every week or two, with exception made as needed for critical bug fixes and such.

What do you think?

/cc @gauntface as well if you have thoughts

**Comment by gmlewis** [comment]
OK, that sounds great.  I will stop releasing on every PR and will work on creating one every week or two.  Thanks, @willnorris.

**Comment by willnorris** [comment]
thank *you* :)

**Comment by chapurlatn** [comment]
Hey guys, 
I also would expect much more release. But I fully understand @willnorris arguments.
May be there may be some way to publish two channels for release:
- a stable with monthly release.
- a separated beta one that may include a release for each merged issue (for example, starting for version v58.0.0, it may generate some v58.0.1-beta)?
