### ISSUE TITLE
The APIMeta() method is failing. 

### ISSUE THREAD

**Issue by Shweta-Deshpande** [google/go-github#1286]
https://api.github.com/api/v3/meta does'nt work anymore.
Returns:
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}

**Comment by Shweta-Deshpande** [comment]
Many other endpoints like - GetBranches, GetUser, GetVersion, GetFile, WriteFile etc are also failing with the same error.

**Comment by gmlewis** [comment]
It works for me.

Here's my complete test program:

```go
package main

import (
	"context"
	"log"

	"github.com/google/go-github/github"
)

func main() {
	c := github.NewClient(nil)
	m, _, err := c.APIMeta(context.Background())
	log.Printf("m=%#v, err=%v", m, err)
}
```

and the results of running it:

```sh
$ go run main.go
2019/09/18 22:27:46 m=&github.APIMeta{Hooks:[]string{"192.30.252.0/22", "185.199.108.0/22", "140.82.112.0/20"}, Git:[]string{"192.30.252.0/22", "185.199.108.0/22", "140.82.112.0/20", "13.114.40.48/32", "13.229.188.59/32", "13.234.176.102/32", "13.234.210.38/32", "13.236.229.21/32", "13.237.44.5/32", "13.250.177.223/32", "15.164.81.167/32", "18.194.104.89/32", "18.195.85.27/32", "35.159.8.160/32", "52.192.72.89/32", "52.64.108.95/32", "52.69.186.44/32", "52.74.223.119/32", "52.78.231.108/32"}, VerifiablePasswordAuthentication:(*bool)(0xc000406208), Pages:[]string{"192.30.252.153/32", "192.30.252.154/32", "185.199.108.153/32", "185.199.109.153/32", "185.199.110.153/32", "185.199.111.153/32"}, Importer:[]string{"54.87.5.173", "54.166.52.62", "23.20.92.3"}}, err=<nil>
```

and from the command line:

```sh
$ curl https://api.github.com/meta
{
  "verifiable_password_authentication": true,
  "hooks": [
    "192.30.252.0/22",
    "185.199.108.0/22",
    "140.82.112.0/20"
  ],
...
}
```

So my first question is: Are you on GitHub Enterprise? If so, then you will want `api/v3` in the URL as you have shown above, but then the URL will not have `api.github.com` in it... instead it will probably be more like `api.github.your-organization.com`.

But if you are *not* on GitHub Enterprise, then the code above will show you how to call the API... it sound like you are using the `NewEnterpriseClient`... instead what you really want is `NewClient`.

**Comment by wesleimp** [comment]
@gmlewis Can we close this issue?

**Comment by gmlewis** [comment]
Yes, @wesleimp ... I believe so.
I'm hoping I resolved their issue, but if not, please feel free to reopen.
Closing.
