### ISSUE TITLE
The branch protection dismissal restrictions response doesn't distinguish absent from an empty allowed list

### ISSUE THREAD

**Issue by glenjamin** [google/go-github#1287]
Follows on from #791 

See also https://github.com/terraform-providers/terraform-provider-github/issues/267

With dismissal restrictions disabled the payload looks like this:
```json
  "required_pull_request_reviews": {
    "url": "https://api.github.com/repos/org/project/branches/master/protection/required_pull_request_reviews",
    "dismiss_stale_reviews": true,
    "require_code_owner_reviews": true
  },
```

With dismissal restrictions enabled, but both lists empty, the payload looks like this:
```json
  "required_pull_request_reviews": {
    "url": "https://api.github.com/repos/circleci/audit-test-restricted-repo/branches/master/protection/required_pull_request_reviews",
    "dismiss_stale_reviews": true,
    "require_code_owner_reviews": true,
    "dismissal_restrictions": {
      "url": "https://api.github.com/repos/org/project/branches/master/protection/dismissal_restrictions",
      "users_url": "https://api.github.com/repos/org/project/branches/master/protection/dismissal_restrictions/users",
      "teams_url": "https://api.github.com/repos/org/project/branches/master/protection/dismissal_restrictions/teams",
      "users": [

      ],
      "teams": [

      ]
    }
  }
```

However the Struct for this response doesn't model the optionality
```go
// PullRequestReviewsEnforcement represents the pull request reviews enforcement of a protected branch.
type PullRequestReviewsEnforcement struct {
	// Specifies which users and teams can dismiss pull request reviews.
	DismissalRestrictions DismissalRestrictions `json:"dismissal_restrictions"`
	// Specifies if approved reviews are dismissed automatically, when a new commit is pushed.
	DismissStaleReviews bool `json:"dismiss_stale_reviews"`
	// RequireCodeOwnerReviews specifies if an approved review is required in pull requests including files with a designated code owner.
	RequireCodeOwnerReviews bool `json:"require_code_owner_reviews"`
	// RequiredApprovingReviewCount specifies the number of approvals required before the pull request can be merged.
	// Valid values are 1-6.
	RequiredApprovingReviewCount int `json:"required_approving_review_count"`
}
```

I'm going to look into making a PR for this.

**Comment by glenjamin** [comment]
For completeness, against the `/protection` endpoint:

on GET
- if enabled, you get `dismissal_restrictions`
- if disabled, then `dismissal_restrictions` is omitted

on PUT
- if `dismissal_restrictions` is absent, it is unchanged
- if `dismissal_restrictions` is present, it must be an object
- if the object is empty, `dismissal_restrictions` are removed
- if the object has `teams` or `users`, they must be an array

**Comment by gmlewis** [comment]
From here: https://developer.github.com/v3/repos/branches/#update-pull-request-review-enforcement-of-protected-branch
Since `dismissal_restrictions` has a definite structure:

![Screenshot from 2019-09-21 10-11-42](https://user-images.githubusercontent.com/6598971/65374481-543c9500-dc58-11e9-9843-71333ab06a00.png)

why don't we go ahead and make a struct for it with optional fields for `users` and `teams`?

I'm thinking something like this:

```go
type DismisalRestrictions {
  Users *[]string `json:"users,omitempty"`
  Teams *[]string `json:"teams,omitempty"`
}
```

and then we can get rid of the `[]interface{}` and the `map[string]interface{}` entirely.

Thoughts?

**Comment by glenjamin** [comment]
Good call, that struct already exists for the update payload, so i’ll use that

**Comment by gmlewis** [comment]
Oh, I think I mis-spoke... they are *not* options... they are required.  I'll go edit my other comment... and yes, I think you can reuse that already-existing struct.  Thank you, @glenjamin!
