### ISSUE TITLE
Get 404 Not Found error when getting reviews or reviewers

### ISSUE THREAD

**Issue by git-ktse** [google/go-github#1290]
GET https://github.adaptiveinsights.com/api/v3/repos/<repo owner>/<repo name>/pulls/96/requested_reviewers: 404 Not Found [

From google search, sounds like it's an auth problem.  However, my oath2 token is a site admin account.  I can use the same token to get other PR information.

**Comment by gmlewis** [comment]
Your URL does not make sense to me.  You wrote:

```
GET https://github.adaptiveinsights.com/api/v3/repos///pulls/96/requested_reviewers
```

You are missing the `owner` and `repo` parts of the URL.

For example, if you wanted to look at this particular repo, the `owner` is "google" and the `repo` is "go-github".  Therefore, your call should look like this:

```
GET https://github.adaptiveinsights.com/api/v3/repos/google/go-github/pulls/96/requested_reviewers
```

Obviously, you are using GitHub Enterprise and `github.adaptiveinsights.com` does not have this repo, but I hope you get the idea.

Also, in the future, it is much easier to debug issues you are having if you show a small example of the Go code you are using (without ever divulging your access tokens or passwords, of course).

**Comment by git-ktse** [comment]
I did have repo owner and repo name.  I typed in repos/<repo owner>/<repo name>/... and somehow after I saved the comment, the <repo owner> and <repo name> disappeared.

**Comment by git-ktse** [comment]
It happened again.   I typed in /&ltrepo owner&gt/&ltrepo name&gt/ and the repo owner and name disappeared

**Comment by git-ktse** [comment]
Let me changed it to GET https://github.adaptiveinsights.com/api/v3/repos/:repo owner/:repo name/pulls/96/requested_reviewers

**Comment by gmlewis** [comment]
Oh, OK... so it was just a markup problem above... that's OK.  Sorry for the problems.

It sounds to me like the basic challenge here is authentication.

Did you create a GitHub `Personal Access Token` and use that as your password for accessing GitHub Enterprise?

Here's a simple snippet from some code I recently wrote that accesses GitHub Enterprise:

```go
tp := github.BasicAuthTransport{
  Username: "gmlewis",
  Password: *accessToken,
}
client, err := github.NewEnterpriseClient("https://github.adaptiveinsights.com/api/v3", "", tp.Client())
```

where `*accessToken` is a string flag that is passed in, and is generated by GitHub as a `Personal Access Token` with "Repository" access.

Please try this out and let me know if you still have problems.  If you do, please post the code here so I can try and duplicate the problem.

**Comment by git-ktse** [comment]
Sorry for the false alarm.  We installed the latest version of GitHub, and everything is working fine.
