### ISSUE TITLE
Get 415 error when getting required_status_checks

### ISSUE THREAD

**Issue by git-ktse** [google/go-github#1291]
GET https://github.adaptiveinsights.com/api/v3/repos/<repo owner>/<repo name>/branches/test/protection/required_status_checks: 415 If you would like to help us test the Protected Branches API during its preview period, you must specify a custom media type in the 'Accept' header. Please see the docs for full details. []

**Comment by gmlewis** [comment]
Same problem here as in #1290. You are missing `owner` and `repo`.

**Comment by git-ktse** [comment]
I did have owner and repo name.  I typed in %ltrepo owner%gt and %ltrepo name%gt and after I clicked submit or save, they disappear in my comment.

**Comment by git-ktse** [comment]
%lt = less than sign
%gt = greater than sign.

**Comment by gmlewis** [comment]
OK, gotcha... yeah Markdown can be a bit of a challenge to deal with.  Let's fix #1290 and I bet that this issue will suddenly be resolved as well.  But if you want to paste in your simple example code here, that's fine too.

**Comment by git-ktse** [comment]
Sorry for the false alarm.  We installed the latest version of GitHub, and everything is working fine.
