### ISSUE TITLE
Remove mediaTypePagesPreview custom media header

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#1298]
GitHub Developer API announcement:
https://developer.github.com/changes/2019-09-24-team-sychronization-end-preview/

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

GitHub Enterprise users: Note that you may need to avoid this change in order to continue using this feature until your local version of GitHub has caught up. See announcement link above for more details.

**Comment by dedifferentiator** [comment]
@gmlewis need to just remove support of "mediaTypePagesPreview" header? if so, let me try to resolve this

**Comment by gmlewis** [comment]
Yes, that's correct, @dedifferentiator - thank you!
