### ISSUE TITLE
Does RepositoriesService.ListCommits returns commits in chronological order?

### ISSUE THREAD

**Issue by iamsubratp** [google/go-github#1305]
We have a specific usecase where we need  the last commit for a particular day. I am using since and until options. I can see that the result already has the commits in chronological order( latest commit being the first in the return list).
However, I do not see any documentation that mentions this behavior. Can anyone confirm if the behvior is consistent/guaranteed?

**Comment by gmlewis** [comment]
The only way to get this answer is to send an email to `support@github.com` and ask them your question. This repo is simply a client to the GitHub Developer v3 API and returns the results in the order returned by GitHub. The support people at GitHub are super friendly and helpful and will be happy to answer your question.  (Please make sure to send them enough details and URL links to make their job easier, as they get a lot of questions.)

When you find out, please report back your answer here.  Best wishes to you.

**Comment by wesleimp** [comment]
@iamsubratp Did you get some answer from GitHub or can we close this issue?

**Comment by wesleimp** [comment]
@gmlewis can we close this issue?

**Comment by gmlewis** [comment]
Yes, thank you, @wesleimp. Closing.
