### ISSUE TITLE
webhook: cannot unmarshal string into Go value of type github.Organization

### ISSUE THREAD

**Issue by pwaller** [google/go-github#131]
I've got code that looks like this:

```go
func serveGithubHook(w http.ResponseWriter, req *http.Request) {
	decoder := json.NewDecoder(req.Body)
	defer req.Body.Close()
	event := github.WebHookPayload{}
	err := decoder.Decode(&event)
```

Which when github sends its payload results in an error:

```
json: cannot unmarshal string into Go value of type github.Organization
```

I think this is because the `repository` field on the Body has `organization: "string"`, whereas the `WebHookPayload` has a [`Repository`](http://godoc.org/github.com/google/go-github/github#Repository) whose organization field is a `*Organization`.

Should this work? Have I made a mistake?

**Comment by pwaller** [comment]
How is it a bug in the Github API? If it were, is it something they can fix without breaking all existing clients of the API?

But I also don't understand how anyone is successfully using this code to receive push payloads currently.

**Comment by stevedomin** [comment]
It's not really a bug but an annoying inconsistency, ideally you would want the representation of a resource to be the same across endpoints, especially when you are using a language like Go.

I ran into a similar issue here: https://github.com/google/go-github/pull/158

**Comment by parkr** [comment]
@pengwynn Is this a known issue?

**Comment by pengwynn** [comment]
> @pengwynn Is this a known issue?

@parkr yeah, and something we'd like to change in a future version.

**Comment by bobbytables** [comment]
Yeah I just hit this as well for decoding push webhooks. Is there any idea on how to fix this so I can maybe tackle it?
