### ISSUE TITLE
Plans on supporting the repository-dispatch event?

### ISSUE THREAD

**Issue by geekodour** [google/go-github#1316]
Is there any reason why the [repository_dispatch](https://developer.github.com/v3/repos/#create-a-repository-dispatch-event) is not available as an event type in go-github? I'd be happy to add it if its planned but missing.

https://github.com/google/go-github/blob/master/github/event_types.go

https://github.com/google/go-github/blob/0fad29b185370011778ede8fc39a5462f844da65/github/messages.go#L43

**Comment by gmlewis** [comment]
No reason that I'm aware of. I believe it may have snuck in under the radar without a GitHub Developer API announcement, possibly.

Sure, feel free to send a PR. Please read `CONTRIBUTING.md` first, however, and follow the guidelines.

Thank you, @geekodour!
