### ISSUE TITLE
How to Fork Private Repository 

### ISSUE THREAD

**Issue by safwanolaimat** [google/go-github#1317]
Is there way to fork private repository ?

**Comment by gmlewis** [comment]
This repo is a client library to access the GitHub Developer v3 API. GitHub support would be a better place to ask your question.  However, doing a Google search, it looks like it is a popular question.

Here are some potential answers to your question:
https://www.google.com/search?q=github+fork+private+repo

**Comment by safwanolaimat** [comment]
@gmlewis i mean is this library support fork private repos ?

**Comment by gmlewis** [comment]
Yes (if your authenticated user has access to the private repo, of course):
https://developer.github.com/v3/repos/forks/#create-a-fork
https://godoc.org/github.com/google/go-github/github#RepositoriesService.CreateFork

**Comment by safwanolaimat** [comment]
@gmlewis how to pass userToken with mytoken?

**Comment by gmlewis** [comment]
I think you are asking how to do authentication. Please take a look at our basicauth example:
https://github.com/google/go-github/blob/master/example/basicauth/main.go
