### ISSUE TITLE
Support new preview API endpoint: List GitHub App installations for an organization

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#1319]
GitHub Developer v3 API announcement:
https://developer.github.com/changes/2019-10-23-get-installations-for-org/

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by srivignessh** [comment]
Hi @gmlewis 
I am interested in picking this task.
Thanks,
Srivignessh
