### ISSUE TITLE
Remove deprecated authentication API endpoints and add replacements

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#1331]
GitHub Developer API announcement:
https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by waseem18** [comment]
@gmlewis I'd like to take this up.

**Comment by gmlewis** [comment]
OK, thanks @waseem18 - it is yours.

**Comment by mubeenflora** [comment]
@waseem18  Are you working on it ? i just to know because i would like to do this

**Comment by waseem18** [comment]
@mubeenflora Go ahead, I've started work on it but didn't get a chance to complete it.

**Comment by mubeenflora** [comment]
thanks but it'll take time because i have started my new project

**Comment by pavan541cs** [comment]
@mubeenflora Are you actively working on this ? Else I would love to work on this

**Comment by yashLadha** [comment]
Is this issue still up for grabs? @gmlewis

**Comment by gmlewis** [comment]
With no response from @mubeenflora in two days, I'm opening this issue back up.

**Comment by pavan541cs** [comment]
@gmlewis I am picking this one and start working on this. Thank you for the update

**Comment by gmlewis** [comment]
Thank you, @pavan541cs! It is yours.

**Comment by pavan541cs** [comment]
@gmlewis #1360 Can you check this PR and tell me if this looks good so that I can make all the changes. I have done only for one endpoint

**Comment by gmlewis** [comment]
In another PR, I think it helped (me, at least) to list the things that need to be done to complete an issue. So to complete this issue...

The following endpoints need to be removed:

- [ ] `GET /authorizations`
- [ ] `GET /authorizations/:authorization_id`
- [ ] `POST /authorizations`
- [ ] `PUT /authorizations/clients/:client_id`
- [ ] `PUT /authorizations/clients/:client_id/:fingerprint`
- [ ] `PATCH /authorizations/:authorization_id`
- [ ] `DELETE /authorizations/:authorization_id`
- [ ] `GET /applications/grants`
- [ ] `GET /applications/grants/:grant_id`
- [ ] `DELETE /applications/grants/:grant_id`
- [ ] `GET /applications/:client_id/tokens/:access_token`
- [ ] `POST /applications/:client_id/tokens/:access_token`
- [ ] `DELETE /applications/:client_id/tokens/:access_token`
- [ ] `DELETE /applications/:client_id/grants/:access_token`

The following endpoints need to be implemented:

- [ ] `POST /applications/:client_id/token`
- [ ] `PATCH /applications/:client_id/token`
- [ ] `DELETE /applications/:client_id/token`
- [ ] `DELETE /applications/:client_id/grant`

Thank you, @pavan541cs for continuing to make progress on #1360.

**Comment by sh3nan1gans** [comment]
Any updates on this @pavan541cs @gmlewis ? I'd be happy to help out with the PR

**Comment by gmlewis** [comment]
Hmmm... it looks like #1360 may have stalled. 
Thank you for the ping, @sh3nan1gans.

Let's wait a day or two for @pavan541cs to respond, and then maybe we'll just open this issue up again and someone else can tackle it from scratch (since it seems that there were a lot of issues that needed to be resolved in #1360).

**Comment by sh3nan1gans** [comment]
FYI @gmlewis I'm going to take a stab at this. I'll be referring to your comments and the current state of https://github.com/google/go-github/pull/1360 for guidance but please let me know if there's anything else I should be aware of.

**Comment by sh3nan1gans** [comment]
@gmlewis - please take a look at this PR - https://github.com/google/go-github/pull/1461
Please let me know if there's anything I missed/should change. Willing to make docs updates as well if necessary

**Comment by gmlewis** [comment]
OK, to avoid confusion (hopefully), I'm going to close the stalled PR #1360 and start reviewing #1461 so I can use the checkboxes above to help with the review since this is a non-trivial PR.  Thank you, @sh3nan1gans, and thank you @pavan541cs for the initial work you did on #1360.
