### ISSUE TITLE
Support changes to internal repository visibility

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#1346]
GitHub Developer API announcement:
https://developer.github.com/changes/2019-12-03-internal-visibility-changes/#rest-v3-api

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by rajatjindal** [comment]
I would like to give this a try. I've some experience with golang, but this will be my first PR in this repo.

**Comment by gmlewis** [comment]
Thank you, @rajatjindal and welcome!  This issue is yours.

Please make sure to read through the CONTRIBUTING.md guide... it has lots of useful information in there.

**Comment by rajatjindal** [comment]
opened PR https://github.com/google/go-github/pull/1347
