### ISSUE TITLE
How to create a review comment reply?

### ISSUE THREAD

**Issue by zulhfreelancer** [google/go-github#1352]
From GitHub docs page, looks like we can send replies to PR comment - https://developer.github.com/v3/pulls/comments/#create-a-review-comment-reply

I tried to find the right method inside this package but I didn't find anything. I tried `CreateCommentInReplyTo` but it was unsuccessful — from the [code](https://github.com/google/go-github/blob/master/github/pulls_comments.go#L144), looks like the URL is pointed to [creating PR comment](https://developer.github.com/v3/pulls/comments/#create-a-comment) (`/repos/:owner/:repo/pulls/:pull_number/comments`) and not [PR comment reply](https://developer.github.com/v3/pulls/comments/#create-a-review-comment-reply) (`/repos/:owner/:repo/pulls/:pull_number/comments/:comment_id/replies`).

Do we have that method somewhere inside this package?

**Comment by gmlewis** [comment]
Thank you for the detailed issue post, @zulhfreelancer!
You might be surprised at how much time you just saved me by providing such excellent details.

I think you are absolutely right... the endpoint you listed above is not yet supported by this client library.

Before I open up this issue and offer it for anyone else to work on, would you like to tackle a PR for this one yourself?  Or are you happy to allow other volunteers to tackle it? :smile:

**Comment by zulhfreelancer** [comment]
@gmlewis I just submitted PR for you - https://github.com/google/go-github/pull/1353

**Comment by zulhfreelancer** [comment]
I've closed the PR. Need to do some cleanup when I'm free later and resubmit it. Thanks for your comments.
