### ISSUE TITLE
Remove obsolete custom preview header

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#1373]
GitHub Developer API announcement:
https://developer.github.com/changes/2020-01-08-source-imports-now-official-part-of-API/

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by cpanato** [comment]
I can work on that

**Comment by cpanato** [comment]
PR: https://github.com/google/go-github/pull/1374
