### ISSUE TITLE
Refactor to the Go Standard Layout Project

### ISSUE THREAD

**Issue by wesleimp** [google/go-github#1376]
Refactor to the basic [Go Standard Layout Project](https://github.com/golang-standards/project-layout)

**Comment by gmlewis** [comment]
Thank you, @wesleimp - but I doubt this is going to happen.

This project has a very large number of users (individuals and enterprises) and I'm guessing that this change would be very disruptive for not a lot of benefit.

I'll leave this issue open for awhile in case others have opinions, but will most likely close it if we don't have any compelling arguments to refactor.

**Comment by wesleimp** [comment]
Thank you, @gmlewis - I got your point. So I'm gonna close this issue.
