### ISSUE TITLE
`PushEventRepository` is missing the `archived` and `disabled` fields

### ISSUE THREAD

**Issue by lynncyrin** [google/go-github#1380]
## Context

The [`PushEventRepository`](https://github.com/google/go-github/blob/ac9200d19f35fee922744b768dd393140a9939c8/github/event_types.go#L698-L733) struct is missing the `archived` and `disabled` booleans that you can see present in [Github's documentation](https://developer.github.com/v3/activity/events/types/#pushevent).

## Requested Change

I'm going to submit a PR adding those fields to the struct.

**Comment by lynncyrin** [comment]
Given https://github.com/google/go-github/pull/82, https://github.com/google/go-github/pull/594, and https://github.com/google/go-github/pull/1065 I'm going to assume _"just create the PR"_ is the right thing to do here.

**Comment by gmlewis** [comment]
Yes, you are right, @lynncyrin. Thank you. Please take a look at CONTRIBUTING.md for helpful hints on how to make a PR for this repo, especially the part about `go generate ./...`.
