### ISSUE TITLE
Support preview revoke installation token endpoint

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#1385]
GitHub Developer API announcement:
https://developer.github.com/changes/2020-01-10-revoke-installation-token/

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by vikkyomkar** [comment]
@gmlewis I would like to contribute to this feature
