### ISSUE TITLE
url-encoded query causing unexpected behaviour

### ISSUE THREAD

**Issue by abhimanyusinghgaur** [google/go-github#1392]
Hi,
I was trying to use the [search-issues API](https://developer.github.com/v3/search/#search-issues-and-pull-requests). So, I was running below query directly from chrome: 
https://api.github.com/search/issues?q=is:issue+state:open+repo:dgraph-io/dgraph+created:2019-01-01..2019-01-31
It returns 4 issues.
I tried to do the same thing using the client library, see the below code snippet (or see it on go playground: https://play.golang.org/p/mj1M1S2pAzx):
```
package main

import (
	"context"
	"fmt"

	"github.com/google/go-github/github"
)

func main() {
	client := github.NewClient(nil)
	searchRes, _, _ := client.Search.Issues(context.Background(), "is:issue+state:open+repo:dgraph-io/dgraph+created:2019-01-01..2019-01-31", nil)
	fmt.Println(searchRes.GetTotal())
}
```
But, the above program prints 0 instead of 4.

I debugged and found out that the client library was url-encoding the special characters in query which is causing this issue, specifically the url-encoding of '+' character. This can be confirmed by running the below query directly from chrome (note: first + has been replaced with %2B, its url-encoded form):
https://api.github.com/search/issues?q=is:issue%2Bstate:open+repo:dgraph-io/dgraph+created:2019-01-01..2019-01-31

The URI RFC mandates that all the reserved characters (+ is a reserved character) should be url-encoded while occurring in path or query parameters. So, this is either a problem with the GitHub API server, or the client library should strictly respect the server limitations and not url-encode.

**Comment by gmlewis** [comment]
Please read through #1122 and #1266 as this issue keeps coming up again and again and we think it is solved each time but apparently not satisfactorily.

**Comment by abhimanyusinghgaur** [comment]
Ok, after reading through those issues, it seems using a space instead of + works. I believe this thing should be mentioned properly somewhere in documentation, or in the docs of functions being used directly by any user, and not just in some internal function.
But anyways, official GitHub API supports +, so it should be supported as it is by the client, I guess.

**Comment by gmlewis** [comment]
It was our attempt to clearly document this in those previous issues by adding clear comments to the code (and therefore the auto-generated Godocs in addition) but it sounds like they can still be improved.

Please feel free to submit a PR that you feel improves the documentation and we can include it so that we can hopefully avoid this issue in the future.  Thank you.

**Comment by gitdotvaibhav** [comment]
Can I take this issue

**Comment by gmlewis** [comment]
Closing inactive issue for lack of activity/interest.
