### ISSUE TITLE
Ip issue

### ISSUE THREAD

**Issue by Islam788** [google/go-github#1398]
See man when I tried to display my ip by the command `ifconfig` it's showing something different or I'm unable identified my ip please help 
![Screenshot_20200127_181130_com termux](https://user-images.githubusercontent.com/60348966/73218446-fda01400-417f-11ea-951c-ceeef6f14307.jpg)

**Comment by gmlewis** [comment]
Sorry, I don't see how this relates in any way to this repo. Closing.

**Comment by Islam788** [comment]
If you don't know so why u closed the ticket. Its in termux

**Comment by gmlewis** [comment]
What does that have to do with this repo which is a client library to access the GitHub v3 API from the Go programming language?
