### ISSUE TITLE
Metasploit framework issue

### ISSUE THREAD

**Issue by Islam788** [google/go-github#1401]
Whenever I open the msfconsole always facing the same issue ***
[-] * WARNING: No database support: could not connect to server: Connection refused
        Is the server running on host "127.0.0.1" and accepting
        TCP/IP connections on port 5432?

[-] ***
Place guide me how can fix the problem 
![Screenshot_20200128_132732_com termux](https://user-images.githubusercontent.com/60348966/73245621-a9724f80-41d2-11ea-95bc-ece3bab563ba.jpg)

**Comment by gmlewis** [comment]
This is strike two.
This issue has nothing to do with this repo.
One more strike and you will be blocked from this repo and reported to GitHub as a spammer.

**Comment by Islam788** [comment]
Wtf😡🤬😠

**Comment by gmlewis** [comment]
Apparently I wasn't clear in your strike one issue to this repo (#1398), and you are obviously confused and angry.
This repo is not a general self-help forum for all technology issues you may have.

I found a site that most likely has the answers you are looking for.  Try this out:
https://lmgtfy.com/?q=metasploit+framework

To avoid strike three, please only open issues in this repository that are related to the github.com/google/go-github client API.  All other issues will be rejected. Thank you for your understanding, as this repo is maintained by volunteers who can not possibly attempt to
support every issue that every internet user has about every framework that ever existed.
I know that if you actually think about this for a second, you would understand.
