### ISSUE TITLE
The User field returned as a part of the PullRequests.List response doesn't have the complete User information

### ISSUE THREAD

**Issue by palash25** [google/go-github#1404]
So when I iterated over the Pull Request slice that I receive as a response to the aforementioned method and checked out the User struct returned as a part of it, I noticed that it only has User.Login and other User information like Name and Email are not there.

I tried this with different repos both private and public and came across the same problem.

Why is it so?

**Comment by gmlewis** [comment]
According to the GitHub v3 Developer API docs:
https://developer.github.com/v3/pulls/#list-pull-requests

Here is the information you can expect about a user:

```
    "user": {
      "login": "octocat",
      "id": 1,
      "node_id": "MDQ6VXNlcjE=",
      "avatar_url": "https://github.com/images/error/octocat_happy.gif",
      "gravatar_id": "",
      "url": "https://api.github.com/users/octocat",
      "html_url": "https://github.com/octocat",
      "followers_url": "https://api.github.com/users/octocat/followers",
      "following_url": "https://api.github.com/users/octocat/following{/other_user}",
      "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
      "organizations_url": "https://api.github.com/users/octocat/orgs",
      "repos_url": "https://api.github.com/users/octocat/repos",
      "events_url": "https://api.github.com/users/octocat/events{/privacy}",
      "received_events_url": "https://api.github.com/users/octocat/received_events",
      "type": "User",
      "site_admin": false
    },
```

In my experience, most GitHub users make their email private, so I doubt you will ever find emails... but from the above data, it doesn't look like you will find name either unless you follow one of the provided URLs and get it that way.

I hope that helps.

**Comment by palash25** [comment]
I did contact github about this but they were like "we didn't implement that library so we don't know". Anyway thanks for this will talk to github support again.

**Comment by palash25** [comment]
@gmlewis do you have any idea why the Full Name of the user is not being returned? if I open this in my browser `https://api.github.com/users/palash25` I get the name but if I try to make the same call using the go-github library I get an empty string for the Name field? `Repositories.ListCollaborators`
