### ISSUE TITLE
Add TODOs badge to README

### ISSUE THREAD

**Issue by patrickdevivo** [google/go-github#1406]
Hi there! I wanted to propose adding the following badge to the README to indicate how many `// TODO` comments are in this codebase:

[![TODOs](https://img.shields.io/endpoint?url=https://todos.tickgit.com/badge?repo=github.com/google/go-github)](https://todos.tickgit.com/browse?repo=github.com/google/go-github)

The badge links to `tickgit.com` which is a free service that indexes and displays TODO comments in public github repos. It can help surface latent work and be a way for new contributors to find areas of code to improve.

The markdown is:

```
[![TODOs](https://img.shields.io/endpoint?url=https://todos.tickgit.com/badge?repo=github.com/google/go-github)](https://todos.tickgit.com/browse?repo=github.com/google/go-github)
```

Thanks for considering, feel free to close this issue if it's not appropriate or you prefer not to add the badge!

**Comment by gmlewis** [comment]
Cool! I didn't know about that badge.

Looking through the TODOs, the vast majority are to remove a custom header when the API fully launches.

I'm fine with adding this badge to the top-level README.md.

**Comment by willnorris** [comment]
Given that the **vast** majority of our TODOs are about removing custom headers, I don't think this actually adds any value to the project, and just adds more noise at the top of our (admittedly, already a little noisy) README file.

(I also don't love the fact that it looks like @patrickdevivo made this kind of drive-by contribution to a dozen different projects on Saturday.  Those often end up being spam contributions, or simply promoting one's own project, though I don't think that's necessarily the case here.)

/shrug

**Comment by gmlewis** [comment]
Oh, sorry, @willnorris. We can either revert or we can remove it with another PR... your call.

**Comment by willnorris** [comment]
either way.  And no worries

**Comment by gmlewis** [comment]
OK, I'll just revert then later tonight.

**Comment by patrickdevivo** [comment]
I’m sorry the issue I opened felt like spam - it certainly was a “drive by”
in an effort to get the word out for a project I’m working on, and I
apologize that didn’t “taste right.” I do promise that the intent of my
opening the issue/PR was genuine in that I do believe the TODO index can
provide value to some projects (as TODO comments are often simply
forgotten).

I understand if you don’t feel like there’s a value add to this repo - it
is funny that pretty much all 161 TODOs are essentially the same phrase!
Thank you for considering it in the first place.

As a side note - I'm hoping to soon make it easy to create Github issues
from TODOs in the index, among other features to make it more of an
"actionable" tool rather than just a big list.
