### ISSUE TITLE
Create a Command Line Binary for Simple Github Access

### ISSUE THREAD

**Issue by tyndyll** [google/go-github#141]
Create a simple binary that can be used to interact with Github via the API. This can be a useful tool for command line devs who can (for example) check for open PR's on their projects or view new comments without leaving their terminal (as well as being able to pipe into other Unix tools).

It has the additional benefit of providing additional examples to users wishing to implement the library

**Comment by shurcooL** [comment]
Agree that a CLI program shouldn't be inside this repository.

I know of one that already exists, written by Russ Cox. See [`rsc.io/github/issue`](https://godoc.org/rsc.io/github/issue). There may be more, and I suspect they would vary wildly depending on the exact user needs.
