### ISSUE TITLE
scrape.Authenticate and unsupported browser forms

### ISSUE THREAD

**Issue by kasperlewau** [google/go-github#1419]
I noticed this morning that my calls to Authenticate a `scrape` client are failing, possibly due to an updated list of unsupported browsers on Github.com's end. 

The page at https://github.com/login now includes a banner with a form with an action pointing to  https://github.com/site/dismiss_unsupported_browser. 

![image](https://user-images.githubusercontent.com/2687184/74140093-bc364c80-4bf4-11ea-80e9-f11405a7f07f.png)

Calls to https://github.com/google/go-github/blob/7d28d53999240c3f92dfbc40651e970301b9989a/scrape/scrape.go#L123 are now failing with an unprocessable entitty response. 

I've made changes in my local fork to allow for a custom selector (default: `"form"`) to be passed into https://github.com/google/go-github/blob/7d28d53999240c3f92dfbc40651e970301b9989a/scrape/forms.go#L37

My calls to `client.Authenticate` now look as such; 
```
if err := client.Authenticate(username, password, otpseed, "#login form"); err != nil {
```

I can see in the notes that adding support for selectors in `parseForm` was/is a stretch goal. I can package up what I have and submit the changes for review.

**Comment by gmlewis** [comment]
Closing inactive issue for lack of activity/interest.  Feel free to reopen.
