### ISSUE TITLE
Active setting not respected on webhook creation

### ISSUE THREAD

**Issue by geneshipt** [google/go-github#1434]
Hi, something seems off with CreateHook(ctx context.Context, owner, repo string, hook *gh.Hook) (*gh.Hook, *gh.Response, error)'s respecting of the Active element. 

Meaning that it doesn't. Whether active is set to true or false the webhook created is set to true. I also experimented with putting an active element in the Config block (with content false of type bool, *bool and string).

I'm stumped at this point. I've also included a sanitized version of the code in use in case I've messed up somewhere and the problem is me. 

```
a, b, err := r.repos.CreateHook(ctx, org, name, &gh.Hook{
		Events: []string{"*"},
		Active: gh.Bool(false),
		Config: map[string]interface{}{
			"url":          "removed",
			"content_type": "json",
			"insecure_ssl": "0",
			"secret":       "removed",
	})
```

Thanks!

**Comment by gmlewis** [comment]
Have you tried calling the equivalent GitHub v3 API endpoint using `curl` with `active` both `true` and `false`?  If these behave correctly but our client library in this repo does not, then we have a bug. If you could please experiment and report back, your efforts would be greatly appreciated!

**Comment by geneshipt** [comment]
100% a PEBKAC issue, I was using ./... to build instead of . and testing with the old executable in my smaller test repo. Just realized. Sorry!

**Comment by gmlewis** [comment]
No problem!  Glad you found it and fixed it!  :smile:
