### ISSUE TITLE
Installation deletion

### ISSUE THREAD

**Issue by csandanov** [google/go-github#1436]
I couldn't find a method to delete github app installation. I see it's currently available but under preview https://developer.github.com/v3/apps/#delete-an-installation. Is this why it's missing? Do you accept PRs for preview endpoints?

**Comment by gmlewis** [comment]
Hmm... that's odd.  Usually there is a GitHub blog post about preview endpoints... maybe I missed it.

We certainly try to stay on top of all preview endpoints and attempt to fully support them.

Yes, we gladly accept PRs!

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by nightlark** [comment]
@csandanov were/are you working on adding support for deleting installations? If not, I can add something this weekend.

**Comment by csandanov** [comment]
@nightlark yes, I planned to but don't have time currently, so go ahead, please
