### ISSUE TITLE
GitHub enterprise with internal certificate

### ISSUE THREAD

**Issue by BrendanThompson** [google/go-github#1439]
Currently trying to execute this on GHE where the certificate is signed by an internal CA as such not trusted by Golang or the TLS client. Is there a way to instruct the `go-github` library to ignore certificate errors?

**Comment by gmlewis** [comment]
I'm on my cell phone at the moment, but I'm pretty sure you can override the `baseURL` and use `http://`.

**Comment by BrendanThompson** [comment]
@gmlewis thanks for that. Looks like I found a way to solve this :) 

```go
	ctx := context.Background()
	httpTransport := &http.Transport{
		TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
	}
	httpClient := &http.Client{Transport: httpTransport}
	ts := oauth2.StaticTokenSource(
		&oauth2.Token{AccessToken: "... TOKEN ..."},
	)

	ctx = context.WithValue(ctx, oauth2.HTTPClient, httpClient)

	tc := oauth2.NewClient(ctx, ts)

	client, err := github.NewEnterpriseClient("https://github.enterprise/api/v3", "https://github.enterprise/", tc)
	if err != nil {
		panic(err)
	}
```
