### ISSUE TITLE
help:PullRequestListOptions State

### ISSUE THREAD

**Issue by tanjunchen** [google/go-github#1440]
see
```
// PullRequestListOptions specifies the optional parameters to the
// PullRequestsService.List method.
type PullRequestListOptions struct {
	// State filters pull requests based on their state. Possible values are:
	// open, closed, all. Default is "open".
	State string `url:"state,omitempty"`

	// Head filters pull requests by head user and branch name in the format of:
	// "user:ref-name".
	Head string `url:"head,omitempty"`
```

Is there State merged?

**Comment by gmlewis** [comment]
Hi @tanjunchen - I'm sorry, but I don't understand the question.
What do you mean "Is there State merged"?

Looking at the code, I'm wondering why both `State` and `Head` are not string pointers... maybe that is the issue you are having problems with?  If so, then maybe we have a bug.

**Comment by tanjunchen** [comment]
Sorry, I didn’t describe my problem well. My question is  that we can pass "merged" in flag State.

**Comment by gmlewis** [comment]
Oh!  I understand now... sorry I didn't get it before.

According to the GitHub v3 API documentation:
https://developer.github.com/v3/pulls/#list-pull-requests
it doesn't look like it accepts a `merged` value for `State`. 

But then it also has this endpoint:
https://developer.github.com/v3/pulls/#get-if-a-pull-request-has-been-merged
and our corresponding method is `IsMerged`:
https://pkg.go.dev/github.com/google/go-github/github?tab=doc#PullRequestsService.IsMerged

I hope that helps.

**Comment by tanjunchen** [comment]
@gmlewis thanks
/close
