### ISSUE TITLE
Support new "Delete Reactions" endpoints

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#1442]
GitHub Developer API announcement:
https://developer.github.com/changes/2020-02-26-new-delete-reactions-endpoints/

These new endpoints need to be supported:

- [x] Delete a commit comment reaction- #1445
  * `DELETE /repos/:owner/:repo/comments/:comment_id/reactions/:reaction_id`
  * Docs: https://developer.github.com/v3/reactions/#delete-a-commit-comment-reaction
- [x] Delete an issue reaction
  * `DELETE /repos/:owner/:repo/issues/:issue_number/reactions/:reaction_id`
  * Docs: https://developer.github.com/v3/reactions/#delete-an-issue-reaction
- [x] Delete a reaction to a commit comment
  * `DELETE /repos/:owner/:repo/issues/comments/:comment_id/reactions/:reaction_id`
  * https://developer.github.com/v3/reactions/#delete-an-issue-comment-reaction
- [x] Delete a pull request comment reaction
  * `DELETE /repos/:owner/:repo/pulls/comments/:comment_id/reactions/:reaction_id`
  * https://developer.github.com/v3/reactions/#delete-a-pull-request-comment-reaction
- [x] Delete team discussion reaction
  * `DELETE /orgs/:org/teams/:team_slug/discussions/:discussion_number/reactions/:reaction_id`
  * Docs: https://developer.github.com/v3/reactions/#delete-team-discussion-reaction
- [x] Delete team discussion comment reaction
  * `DELETE /orgs/:org/teams/:team_slug/discussions/:discussion_number/comments/:comment_number/reactions/:reaction_id`
  * Docs: https://developer.github.com/v3/reactions/#delete-team-discussion-comment-reaction

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by wesleimp** [comment]
@gmlewis I could take it over

**Comment by gmlewis** [comment]
Thank you, @wesleimp!  It is yours.

**Comment by gmlewis** [comment]
I neglected to mention that the existing "delete reactions" endpoint also needs to be deleted (assuming we implemented it... I'll have to check later).

**Comment by wesleimp** [comment]
> I neglected to mention that the existing "delete reactions" endpoint also needs to be deleted (assuming we implemented it... I'll have to check later).

@gmlewis I'll delete the endpoint `DeleteReactions` when all these endpoints mentioned above are be supported. What do you think?

**Comment by gmlewis** [comment]
We typically add new endpoints and delete deprecated endpoints in the same PR so that the single issue (pointing to a blog post) can be fully closed and so that it can be more easily found.
But I'm actually fine to split the single issue up into two PRs if you would prefer.

**Comment by wesleimp** [comment]
> We typically add new endpoints and delete deprecated endpoints in the same PR so that the single issue (pointing to a blog post) can be fully closed and so that it can be more easily found.
> But I'm actually fine to split the single issue up into ~two~ multiple PRs if you would prefer.

@gmlewis I prefer to split the issue in multiple PRs to make the review easier, but after the  #1445 meged, I can close this issue in a single one. No problems to me

**Comment by ayzu** [comment]
I would like to take the second bullet point.

**Comment by gmlewis** [comment]
Thank you, @ayzu, but @wesleimp already signed up for the full issue.

**Comment by ayzu** [comment]
Oh, my bad:)

> Thank you, @ayzu, but @wesleimp already signed up for the full issue.

**Comment by gmlewis** [comment]
No problem, @ayzu ! It's always better to have more volunteers than not enough! 😁
