### ISSUE TITLE
Missing `AuthorAssociation` field in issue struct

### ISSUE THREAD

**Issue by you06** [google/go-github#1458]
I found that there is already `author_association` field in issues API, but the [Issue struct](https://github.com/google/go-github/blob/6e0f6ebdef7d6db18d0eb92bb6f7aa9c0c7d4101/github/issues.go#L28-L63) is not updated. 

Also the example in document doesn't has this field yet https://developer.github.com/v3/issues/#get-an-issue. However it's available in API v4 https://developer.github.com/v4/object/issue/ .

**Comment by vikkyomkar** [comment]
Let me look into it

**Comment by gmlewis** [comment]
The way we typically handle this situation is to first contact support@github.com and ask them to please update their documentation for the API.  They have always been super helpful, friendly, and responsive, so please do this, @you06.

This does two things:
* it validates that indeed the field is being returned and we didn't make a mistake on our end
* improves the user experience for all GitHub v3 API users (regardless of programming language) by helping GitHub to improve their documentation.

As for #1460, I will comment on it directly.

Thank you!

**Comment by you06** [comment]
I've sent an email to GitHub team about this. If there are any updates, I'll comment here.
