### ISSUE TITLE
Error using Projects.CreateProjectCard ( 422 Validation Failed )

### ISSUE THREAD

**Issue by mangelajo** [google/go-github#1467]
I was trying to use the CreateProjectCard in the following code:
```go
	newCard, resp, err := gh.client.Projects.CreateProjectCard(context.Background(), columnID, &cardOptions)
	if err != nil {
		return nil, nil, fmt.Errorf("creating new card: err=%s resp=%+v columnID=%d, cardOptions=%+v", err, resp,
			columnID, cardOptions)
	}
```

But I always get:

💥 moving card: creating new card: with cardOptions={Note: ContentID:278 ContentType:Issue Archived:<nil>}

err=POST https://api.github.com/projects/columns/8343273/cards: 422 Validation Failed [{Resource:ProjectCard Field:data Code:unprocessable Message:Could not resolve to a node with the global id of 'MDU6SXNzdWUyNzg='.}] 
resp=&{Response:0xc0003462d0 NextPage:0 PrevPage:0 FirstPage:0 LastPage:0 NextPageToken: Rate:github.Rate{Limit:5000, Remaining:4940, Reset:github.Timestamp{2020-03-20 18:18:26 +0100 CET}}} columnID=8343273, 

This is the full snippet of my code in case is:
```go
func (gh *GitHub) MoveCardToAnotherProjectColumn(card *github.ProjectCard, columnID int64) (*github.ProjectCard, *github.Response, error) {

	cardOptions, err := ProjectCardOption(card)
	if err != nil {
		return nil, nil, err
	}
	fmt.Println(cardOptions)
	newCard, resp, err := gh.client.Projects.CreateProjectCard(context.Background(), columnID, &cardOptions)
	if err != nil {
		return nil, nil, fmt.Errorf("creating new card: err=%s resp=%+v columnID=%d, cardOptions=%+v", err, resp,
			columnID, cardOptions)
	}

	_, err = gh.client.Projects.DeleteProjectCard(context.Background(), *card.ID)
	if err != nil {
		return nil, nil, fmt.Errorf("deleting old card: %s", err)
	}

	return newCard, resp, nil

}

func ProjectCardOption(card *github.ProjectCard) (cardOpts github.ProjectCardOptions, err error) {

	if card.Note != nil {
		cardOpts.Note = *card.Note
		return
	}
	//           0     1 2                3         4          5         6    7
	// example: https://api.github.com/repos/submariner-io/lighthouse/issues/81
	path := strings.Split(*card.ContentURL, "/")

	contentId, err := strconv.ParseInt(path[7], 10, 64)
	if err != nil {
		return cardOpts, fmt.Errorf("Unable to parse content ID from URL: %s", err)
	}

	contentType := path[6]

	if contentType == "issues" {
		cardOpts.ContentType = "Issue"
	} else if contentType == "pull" {
		cardOpts.ContentType = "PullRequest"
	}
	cardOpts.ContentID = contentId
	return
}
```

**Comment by gmlewis** [comment]
Trying to debug this, I'm looking back at the original API documentation:
https://developer.github.com/v3/projects/cards/#create-a-project-card

So `8343273` is the `columnID`, `278` is the issue ID... hmmm... looks good to me.

Can you try calling the "curl" equivalent of the command to see if that works?

If that fails, then I recommend you contact support@github.com and see why your call is failing.

**Comment by mangelajo** [comment]
> Trying to debug this, I'm looking back at the original API documentation:
> https://developer.github.com/v3/projects/cards/#create-a-project-card
> 
> So `8343273` is the `columnID`, `278` is the issue ID... hmmm... looks good to me.
> 
> Can you try calling the "curl" equivalent of the command to see if that works?
> 
> If that fails, then I recommend you contact [support@github.com](mailto:support@github.com) and see why your call is failing.

Thanks gmlewis, I will try that and update this issue with the details.

**Comment by gmlewis** [comment]
Closing issue as obsolete.
