### ISSUE TITLE
How to enable mandatory review

### ISSUE THREAD

**Issue by pradeepkusingh** [google/go-github#1468]
How can I enable CODE REVIEW protection feature in all existing master and selected branches?

**Comment by gmlewis** [comment]
Searching through the GitHub v3 API documentation, it looks to me like you want this:
https://developer.github.com/v3/repos/branches/#update-branch-protection
and specifically, you want `require_code_owner_reviews` to be `true`.

Looking through this client repo, the corresponding call would be:
https://pkg.go.dev/github.com/google/go-github/v30/github?tab=doc#RepositoriesService.UpdateBranchProtection

**Comment by pradeepkusingh** [comment]
Thank you.
