### ISSUE TITLE
Add support for visibility parameter when creating / editing repository

### ISSUE THREAD

**Issue by patrickmarabeas** [google/go-github#1470]
Add support for the visibility parameter when creating or editing a repository.

Currently this has only been implemented at:
a) an organisational permission level
b) filtering when listing repositories

API: https://developer.github.com/v3/repos/#parameters-4

UI: https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-new-repository

**NOTE: This parameter should overwrite the `private` parameter when both are used.**

Happy to pick this issue up if I haven't missed anything obvious.

**Comment by gmlewis** [comment]
Thank you for the report, @patrickmarabeas.

For your highlighted note, the GitHub docs say:

> The visibility parameter overrides the private parameter when you use both parameters with the nebula-preview preview header.

so it won't be necessary to take any extra action when `visibility` is populated.

I'm thinking that the cleanest solution at this point is to add a new `Visibility *string `json:"visibility,omitempty"` field to the `Repository` struct in `repos.go` at the very end near line 124, and add a comment that this field is only used for the `Create` and `Edit` endpoints, and that its use overrides the value of the `private` field.

Then additionally, this same field would need to be added to the `createRepoRequest` struct probably right after the `Private` field on line 298 and it also needs to be copied over after line 336.

Sure, it would be great to have you pick up this issue.  Thanks again!
