### ISSUE TITLE
func (*ActionsService) ListRunners always returns error

### ISSUE THREAD

**Issue by summerwind** [google/go-github#1472]
[func (*ActionsService) ListRunners](https://godoc.org/github.com/google/go-github/github#ActionsService.ListRunners) always returns error due to the GitHub API response format was changed.

**Previous response format**

```
[
  {
    "id": 23,
    "name": "MBP",
    "os": "macos",
    "status": "online"
  },
  {
    "id": 24,
    "name": "iMac",
    "os": "macos",
    "status": "offline"
  }
]
```

**New response format**

```
{
  "total_count": 2,
  "runners": [
    {
      "id": 23,
      "name": "MBP",
      "os": "macos",
      "status": "online"
    },
    {
      "id": 24,
      "name": "iMac",
      "os": "macos",
      "status": "offline"
    }
  ]
}
```

**Comment by gmlewis** [comment]
Ah, yes!  Thank you, @summerwind!
I'll work on a fix.

**Comment by summerwind** [comment]
Thanks for the quick fix!
Actions API support on go-github is really useful for me. Thank you!
