### ISSUE TITLE
Add: RenameOrg for Org Admin API

### ISSUE THREAD

**Issue by JoshRodstein** [google/go-github#1479]
Hi,

I'm currently extending the terraform-github-provider to manage organizations with Terraform for my team's GHE Redux. It would be very helpful to implement RenameOrg for the [Organization Administration API.](https://developer.github.com/enterprise/2.20/v3/enterprise-admin/orgs/#rename-an-organization) I assume there are plans to do this at some point. But I've already got an adhoc implementation working so figured if throw it out there. Cheers!

**Comment by gmlewis** [comment]
@JoshRodstein - do you need a new release of this repo for Terraform?  We currently are only releasing on-demand. I believe this would be a minor release (since the last release), but will have to verify.

**Comment by JoshRodstein** [comment]
@gmlewis -Delayed answer is yes, a release would be great. Looks like it was included in v31.00. Thanks!
