### ISSUE TITLE
Repository.Get should set mediaTypeRepositoryVisibilityPreview

### ISSUE THREAD

**Issue by propertone** [google/go-github#1481]
Per https://developer.github.com/v3/repos/#get-a-repository, the mediaTypeRepositoryVisibilityPreview accept header needs to be set to see the Visibility flag for a repository.

**Comment by gmlewis** [comment]
Great catch!  Thank you, @propertone.  Would you like to submit a PR?

The value needs to be added here:
https://github.com/google/go-github/blob/master/github/repos.go#L417

**Comment by wesleimp** [comment]
@gmlewis could I take this issue?

**Comment by gmlewis** [comment]
Thanks, @wesleimp!  This one is yours. :smile:
