### ISSUE TITLE
Support new triage and maintain permissions API endpoints

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#1482]
GitHub Developer v3 API announcement:
https://developer.github.com/changes/2020-04-07-expanding-rest-api-support-for-the-triage-and-maintain-roles/

These new endpoints need to be supported:

* [Endpoints you can access with the triage permission](https://developer.github.com/changes/2020-04-07-expanding-rest-api-support-for-the-triage-and-maintain-roles/#endpoints-you-can-access-with-the-triage-permission)
  * [ ] `POST /repos/:owner/:repo/issues/:issue_number/labels`
    - Docs: https://developer.github.com/v3/issues/labels/#add-labels-to-an-issue
  * [ ] `DELETE /repos/:owner/:repo/issues/:issue_number/labels/:name`
    - Docs: https://developer.github.com/v3/issues/labels/#remove-a-label-from-an-issue
  * [ ] `POST /repos/:owner/:repo/issues/:issue_number/assignees`
    - Docs: https://developer.github.com/v3/issues/assignees/#add-assignees-to-an-issue
  * [ ] `DELETE /repos/:owner/:repo/issues/:issue_number/assignees`
    - Docs: https://developer.github.com/v3/issues/assignees/#remove-assignees-from-an-issue
  * [ ] `POST /repos/:owner/:repo/pulls/:pull_number/requested_reviewers`
    - Docs: https://developer.github.com/v3/pulls/review_requests/#create-a-review-request

* [Endpoints you can access with the maintain permission](https://developer.github.com/changes/2020-04-07-expanding-rest-api-support-for-the-triage-and-maintain-roles/#endpoints-you-can-access-with-the-maintain-permission)
  * [ ] `PUT /repos/:owner/:repo/topics`
    - Docs: https://developer.github.com/v3/repos/#replace-all-repository-topics
  * [ ] `PUT /repos/:owner/:repo/interaction-limits`
    - Docs: https://developer.github.com/v3/interactions/repos/#add-or-update-interaction-restrictions-for-a-repository
  * All of the endpoints that you can use with the triage permission role:
    * [ ] `POST /repos/:owner/:repo/issues/:issue_number/labels`
      - Docs: https://developer.github.com/v3/issues/labels/#add-labels-to-an-issue
    * [ ] `DELETE /repos/:owner/:repo/issues/:issue_number/labels/:name`
      - Docs: https://developer.github.com/v3/issues/labels/#remove-a-label-from-an-issue
    * [ ] `POST /repos/:owner/:repo/issues/:issue_number/assignees`
      - Docs: https://developer.github.com/v3/issues/assignees/#add-assignees-to-an-issue
    * [ ] `DELETE /repos/:owner/:repo/issues/:issue_number/assignees`
      - Docs: https://developer.github.com/v3/issues/assignees/#remove-assignees-from-an-issue
    * [ ] `POST /repos/:owner/:repo/pulls/:pull_number/requested_reviewers`
      - Docs: https://developer.github.com/v3/pulls/review_requests/#create-a-review-request

* [Endpoints to assign, update, or view permissions](https://developer.github.com/changes/2020-04-07-expanding-rest-api-support-for-the-triage-and-maintain-roles/#endpoints-to-assign-update-or-view-permissions)
  * [ ] `PUT /repos/:owner/:repo/collaborators/:username`
    - Docs: https://developer.github.com/v3/repos/collaborators/#add-user-as-a-collaborator
  * [ ] `GET /repos/:owner/:repo/invitations`
    - Docs: https://developer.github.com/v3/repos/invitations/#list-invitations-for-a-repository
  * [ ] `PATCH /repos/:owner/:repo/invitations/:invitation_id`
    - Docs: https://developer.github.com/v3/repos/invitations/#update-a-repository-invitation
  * [ ] `GET /user/repository_invitations`
    - Docs: https://developer.github.com/v3/repos/invitations/#list-a-users-repository-invitations
  * [ ] `GET /orgs/:org/teams/:team_slug/repos/:owner/:repo`
    - Docs: https://developer.github.com/v3/teams/#check-if-a-team-manages-a-repository
  * [ ] `PUT /orgs/:org/teams/:team_slug/repos/:owner/:repo`
    - Docs: https://developer.github.com/v3/teams/#add-or-update-team-repository
  * [ ] `GET /orgs/:org/teams/:team_slug/repos`
    - Docs: https://developer.github.com/v3/teams/#list-team-repos

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.  Also, feel free to volunteer for any subset of this (rather large) issue.  Let's keep track of all of it here.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by willnorris** [comment]
Just a note for whoever ends up working on this... not all of these are actually new methods.  Some of them are existing methods that can now be accessed using accounts with the triage or maintain role, in which case there is probably nothing to be done for those.  A good first step might be to review the whole list and verify which of these are new.

**Comment by jamesallured** [comment]
I'd quite like to take a look at this! 🙂

**Comment by gmlewis** [comment]
Thank you, @jamesallured!  It is yours.

**Comment by jamesallured** [comment]
Just been through all of the endpoints listed above and I could match all of them to existing methods. Forgive me if I'm missing something, but is there anything to do with the triage and maintain roles that needs implementing here or is this issue already solved without requiring extra work?

**Comment by gmlewis** [comment]
Thank you, @jamesallured !    I post GitHub Developer v3 API announcements as they come out, and don't always have the time to investigate if we are up-to-date, as most often they announcements really do highlight recent changes.

It looks like in this case, we are good to go.

I apologize for the dead-end issue, but I really appreciate you taking the time to investigate and determine that no action is needed.

Closing.
