### ISSUE TITLE
Remove graduated custom media headers

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#1488]
GitHub Developer v3 API announcement:
https://developer.github.com/changes/2020-04-07-graduated-previews/

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by wesleimp** [comment]
@gmlewis could I take this issue?

**Comment by gmlewis** [comment]
Thank you, @wesleimp ! It's yours.
