### ISSUE TITLE
URLs to GitHub Actions API docs changed

### ISSUE THREAD

**Issue by nightlark** [google/go-github#1502]
Various URLs to pages for the GitHub Actions related API docs have changed earlier today. The original links give page not found errors.

Of the sections listed for https://developer.github.com/v3/actions/ the changed URLs are:
* self_hosted_runners to self-hosted-runners
* workflow_jobs to workflow-jobs
* workflow_runs to workflow-runs

I sent an email to GitHub support to confirm that the change (without a redirect) was intentional, and mentioning that the link in a blog post made the same day is now broken.

**Comment by gmlewis** [comment]
Thank you, @nightlark!

**Comment by nightlark** [comment]
The change was intentional -- something about making the URLs more consistent (though the older docs are unchanged and many have underscores in the URL).

**Comment by gmlewis** [comment]
OK, thanks for reporting back, @nightlark!
I have added a new utility to this repo in #1477  that should be able to update all the URLs so don't worry about catching them all.  After we get #1507 in, I can run it.
