### ISSUE TITLE
Add github_teams data source to list teams per organization

### ISSUE THREAD

**Issue by brokorus** [google/go-github#1511]
Being able to list teams per organization for use in other Terraform code is a must have.

Currently there is no mechanism I have found to achieve this with this provider.
A single team can be found by searching for the slug, but there is no way to gather the slug name short of generating it with Terraform. Or importing the existing resource, then referencing it (< Not ideal)

I need this to feed other systems to mirror the accesses granted to users within a gitorg and git team.

I attempted to patch this by copying github/data_source_github_team.go and removing the slug pieces. But I could not get it to compile, or pass tests.

<< (Going to continue trying, but am hoping someone more competent will help or just release it)

None of the current data sources have teams as queryable information or I would just use that.

**Comment by gmlewis** [comment]
We try to keep up-to-date with the official GitHub v3 API, so if it is possible to do what you want there, then you should be able to do the same thing with this repo. At least, that's the goal.

There was a recent change to the API where you can get teams by slug (like you mention), or by ID.
We basically have two verisons of these endpoints, just like the official API.

If you can point to the official API, we should be able to help you find it here.
For example, here is ListTeams: https://developer.github.com/v3/teams/#list-teams
and here is the one for this repo: https://pkg.go.dev/github.com/google/go-github/v31/github?tab=doc#RepositoriesService.ListTeams

Here's how you get a team either by slug or by ID: https://developer.github.com/v3/teams/#get-team-by-name
and here are ours:
https://pkg.go.dev/github.com/google/go-github/v31/github?tab=doc#TeamsService.GetTeamByID
https://pkg.go.dev/github.com/google/go-github/v31/github?tab=doc#TeamsService.GetTeamBySlug

So please let us know if you still can't find something, and it always helps if you give us a URL to the official GitHub v3 API docs.

**Comment by gmlewis** [comment]
Closing inactive issue for lack of activity/interest.  Feel free to reopen.
