### ISSUE TITLE
Update permission levels for repositories owned by an organization

### ISSUE THREAD

**Issue by jaysiyani** [google/go-github#1515]
https://github.com/google/go-github/blob/747f93dd9b489bd56f7442b3c42bfea12800a75b/github/repos_collaborators.go#L101-L110

Can this be updated to include maintain and triage ?
As per https://developer.github.com/v3/repos/collaborators/#add-user-as-a-collaborator

**Comment by gmlewis** [comment]
Since the parameter is a string, you can already do that. But you are correct that the documentation comment should be updated.

Thank you for the report!

**Comment by vaibhavsanap** [comment]
Can I take this

**Comment by gmlewis** [comment]
Yes, @vaibhavsanap - thank you!  It is yours.

**Comment by vaibhavsanap** [comment]
Also as per https://developer.github.com/v3/teams/#add-or-update-team-repository 

type TeamAddTeamRepoOptions struct {
	// Permission specifies the permission to grant the team on this repository.
	// Possible values are:
	//     pull - team members can pull, but not push to or administer this repository
	//     push - team members can pull and push, but not administer this repository
	//     admin - team members can pull, push and administer this repository
	//
	// If not specified, the team's permission attribute will be used.
	Permission string `json:"permission,omitempty"`
}

Do we need to update documentation comment for above struct also with for same changes

**Comment by vaibhavsanap** [comment]
#1518

**Comment by gmlewis** [comment]
Yes, if you see comments that are out-of-date, it would be good to update them. Thank you.
