### ISSUE TITLE
Add support to retrieve pinned projects on user profile pages

### ISSUE THREAD

**Issue by gogolemon** [google/go-github#1523]

**Comment by gmlewis** [comment]
If you can find it in the official GitHub Developer API v3 documentation, we can add it.

Looking here, however: https://developer.github.com/v3/projects/
I'm not seeing anything matching this description.

Closing issue.

If you find it, please comment and I'll re-open.

**Comment by nightlark** [comment]
From looking around the GitHub community forums, there is no v3 REST API endpoint to get pinned projects. However, it is possible using the v4 GraphQL API has a method to get it. https://github.com/shurcooL/githubv4 might be useful for getting that information.
