### ISSUE TITLE
Support new workflow usage and workflow run usage API endpoints

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#1526]
GitHub Developer v3 API announcement:
https://developer.github.com/changes/2020-05-15-actions-api-workflow-usage/

These new endpoints need to be supported:

* [Get workflow usage](https://developer.github.com/v3/actions/workflows/#get-workflow-usage)
  * [ ] `GET /repos/:owner/:repo/actions/workflows/:workflow_id/timing`

* [Get workflow run usage](https://developer.github.com/v3/actions/workflow-runs/#get-workflow-run-usage)
  * [ ] `GET /repos/:owner/:repo/actions/runs/:run_id/timing`

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by joshuabezaleel** [comment]
May I have a shot on this? :slightly_smiling_face:

**Comment by gmlewis** [comment]
Thank you, @joshuabezaleel ... it is yours.
