### ISSUE TITLE
The archiveFormat type is not exported but used in an exported API GetArchiveLink

### ISSUE THREAD

**Issue by posener** [google/go-github#1533]
The archiveFormat type is not exported but used in an exported API GetArchiveLink.
I assume that the intention was to allow only the defined const, but this is a bad practice - for example, if I want to wrap the function to GetArchiveLink and want also to accept the archiveformat argument.

Can this type be exported?

**Comment by gmlewis** [comment]
Whups... looks like a bug.  Thanks for the report, @posener !
Do you want to put together a PR, or would you like someone else to address this issue?
