### ISSUE TITLE
ListMatchingRefs does not work with the pagination options

### ISSUE THREAD

**Issue by nbramblett** [google/go-github#1567]
I noticed this today while querying a repo with 101 refs. When `ListMatchingRefs` was called with no `ReferenceListOptions` provided, it provided a complete list of 101 refs, without any pagination needed. 

It also repeated this behavior when provided a `ReferenceListOptions` that had defined `PerPage: X, Page: 1`. The expected behavior in this case would be that only the first X refs would be returned.

Given that the matching-refs endpoint no longer seems to respect pagination, I believe the best course of action would be to either update the `ReferenceListOptions` struct to reflect this change, or to simply remove the object from the `ListMatchingRefs` method.

**Comment by gmlewis** [comment]
Before we take any action on this endpoint, could you please contact support@github.com and ask what their recommendation is, then report back here?
Thank you!

**Comment by gmlewis** [comment]
Closing inactive issue for lack of activity/interest.  Feel free to reopen.
