### ISSUE TITLE
confusion between roles and permissions

### ISSUE THREAD

**Issue by surajnarwade** [google/go-github#1572]
**Problem statement**

When we try to list teams on a repo, permissions I get don't match with roles which can be seen from GitHub console.
for example, I can see permissions `push`, `pull` & `admin` in API response.

whereas if we look at roles from GitHub console, they are five different `roles`: `read`, `write`, `admin`, `triage`, `maintain`

permission reference from  `go-Github` https://github.com/google/go-github/blob/master/github/teams.go#L449

```
pull - team members can pull, but not push to or administer this repository
push - team members can pull and push, but not administer this repository
admin - team members can pull, push and administer this repository
maintain - team members can manage the repository without access to sensitive or destructive actions.
triage - team members can proactively manage issues and pull requests without write access.
```

also, I have noticed the correlation between the actual roles and permissions I got through API response.

* read ~ pull
* write ~ push
* maintain ~ push
*  triage ~ pull
* admin ~ admin

**Questions ?**

* are roles and permissions are supposed to be same? if yes is it documented somewhere?
* if not, is a correlation I mentioned is correct?
* is there any way to fetch teams and their roles for particular repo using APIs

**Comment by gmlewis** [comment]
Note that this repo tracks the GitHub v3 API Documentation: https://developer.github.com/v3/teams/#add-or-update-team-repository-permissions

So what you have discovered is actually an excellent question for support@github.com.  Once you hear back, please report what you have discovered in this issue.

Thank you.

**Comment by surajnarwade** [comment]
@gmlewis apprently github provides two set of permissions,

```
    "permissions": {
      "admin": false,
      "push": false,
      "pull": true
    },
```
this is one which I was getting  but I expected the following response:

```
  "permissions": {
    "pull": true,
    "triage": true,
    "push": false,
    "maintain": false,
    "admin": false
  }
```

appropriate API call to fetch this response is https://github.com/google/go-github/blob/master/github/teams.go#L122

**Comment by derekjobst** [comment]
@suhaibmujahid did you end up finding a solution for reading maintain/triage permissions on teams?
