### ISSUE TITLE
Notifications API does not return what is expected

### ISSUE THREAD

**Issue by matt-canty-dragon** [google/go-github#1574]
I'm probably missing something, but when I use `client.Activity.ListNotifications(ctx, &github.NotificationListOptions{})` I expect the same view as in the picture, which is accessed by going to https://github.com/notifications. (truncated to retain privacy, but essential it's a list of PR review requests)

![image](https://user-images.githubusercontent.com/56073682/87568708-fc2abf80-c6bd-11ea-9c78-c86865a12d0a.png)

Instead I just get the top one. I see that the top one is the only one which is an _issue_ rather than a _pull request_.

I'm interested in getting the same list via the SDK, is this possible?

**EDIT**

What I am trying to achieve is:
1. Auto "Done" the merged or closed pull requests from the notification list
2. Get any unread notifications from the list

**Comment by gmlewis** [comment]
Hmmm... my best recommendation is see if you can perform the same operations using the GitHub v3 API via `curl` and then report back... if you are successful, then we should surely be able to do the same thing via this client repo.

https://developer.github.com/v3/activity/notifications/

**Comment by matt-canty-dragon** [comment]
OK so clearly the Notifications page on GitHub bears no resemblance to this resource...
```
➜  ~ curl -u my-username:my-token https://api.github.com/notifications
[

]

**Comment by matt-canty-dragon** [comment]
https://github.com/notifications actually renders the notifications server-side. So they're probably doing a lot of joining under the hood. This is disappointing.
