### ISSUE TITLE
How to rename the remote branch

### ISSUE THREAD

**Issue by pradeepkusingh** [google/go-github#1577]
I would like to rename the few existing branches across multiple repos, how can I achieve this?

**Comment by pradeepkusingh** [comment]
another extended question is how to rename the master branch and still set it to the default branch?

**Comment by gmlewis** [comment]
Let's research this together and see if we can come up with a solution.

First, we go to the GitHub Developer v3 API documentation involving Repositories and Branches:
https://developer.github.com/v3/repos/branches/
Oooo... they have new shiny docs too: https://docs.github.com/en/rest/reference/repos#branches

I'm not finding "rename" so let's look at "update"... hmmm... I'm not finding that either.  I looked for "patch" as well.

As far as I can tell, this is currently not possible with the GitHub Developer v3 API.

So your best bet is to contact support@github.com and ask if they can add this feature.
I'm betting it is a huge amount of work on their side if they don't already support it.
I'll close this issue for now, but if you hear back that it is possible, please feel free to reopen the issue.

Good luck.
