### ISSUE TITLE
Updating default branch fails

### ISSUE THREAD

**Issue by mdeggies** [google/go-github#1578]
After creating a new branch called `default` using `client.Git.CreateRef()`, I make a call to update the repo's default branch:

```
	client := github.NewClient(...)

        // Get repo
        repo, _, err := client.Repositories.Get(context.Background(), owner, repoName)
	if err != nil {
		// handle error
	}

       // Update default branch
       ref := "default"
       repo.DefaultBranch = &ref
       repo, _, err = client.Repositories.Edit(context.Background(), owner, repoName, repo)
	if err != nil {
		// handle error
	}

```

This fails with the following:

```
Failed to update default branch: PATCH https://api.github.com/repos/$owner/$repo: 422 Validation Failed [{Resource:Repository Field:default_branch Code:invalid Message:The branch default was not found. Please push that ref first or create it via the Git Data API.}]
```

I verified that the branch exists using `client.Repositories.ListBranches()` and `client.Git.GetRef()`. Some posts on google [suggest](https://github.community/t/cannot-change-default-branch/13728) you need to pass in the repo name to update the default branch, but the PATCH call works fine without it in curl and python.

**Comment by gmlewis** [comment]
Hmmm... I'm honestly wondering here if it is timing-related.

After creating a new branch, how much time transpired between creation and updating it?
I know that some operations on GitHub require that the changes propagate through their system, as I ran into something similar in the past.

First, however, I should ask... are you _ever_ able to get the PATCH work, like after waiting a minute or so?

But if it is _not_ timing-related, can you please share the `curl` example that works and then we can compare that with this client version that is failing... and hopefully fix it.

Thank you, @mdeggies !

**Comment by mdeggies** [comment]
Thanks for your note! Nope, unfortunately the PATCH call never works using `go-github`. It always returns a 422. 

This is the successful curl call:

```
curl -X PATCH \
  https://api.github.com/repos/$owner/$repo \
  -H 'accept: application/json' \
  -H 'authorization: token $github_token' \
  -H 'content-type: application/json' \
  -d '{ "default_branch": "default" }'
```

**Comment by gmlewis** [comment]
Ah!  Thank you for the curl example.  I think I see the difference.

Could you please try the following experiment for me?

Instead of:

```
       // Update default branch
       ref := "default"
       repo.DefaultBranch = &ref
       repo, _, err = client.Repositories.Edit(context.Background(), owner, repoName, repo)
	if err != nil {
		// handle error
	}
```

could you please try:

```
       // Update default branch
       ref := "default"
       editRepo := &github.Repository{DefaultBranch: &ref}
       repo, _, err = client.Repositories.Edit(context.Background(), owner, repoName, editRepo)
	if err != nil {
		// handle error
	}
```

I'm betting here that all that extra information in the original `repo` struct is getting sent to GitHub, and you don't want any of that other information to change.  All you want to change is the `DefaultBranch`, so that is all we are going to send (as demonstrated in the `curl` call). I'm hoping that this will solve the issue.  Please report back.  Thank you, @mdeggies !

**Comment by mdeggies** [comment]
Ahh, sorry about that -- I should have caught it earlier! Sending in just the default branch did work. Thanks for your help! :)

**Comment by gmlewis** [comment]
Glad it worked! No problem. Closing issue.
