### ISSUE TITLE
problem deleting repo

### ISSUE THREAD

**Issue by rubiin** [google/go-github#1587]
```go
_, err := client.Repositories.Delete(ctx, "", "rubiin/testrepo")
	if err != nil {
		fmt.Println(err)
	}

```
I am doing something like this and get an error

```sh
DELETE https://api.github.com/repos//rubiin/testrepo: 404 Not Found []
```

BTW: The repo exists

**Comment by gmlewis** [comment]
According to the docs: https://godoc.org/github.com/google/go-github/github#RepositoriesService.Delete

the second argument is the owner of the repo.

So your code should be:

```
client.Repositories.Delete(ctx, "rubiin", "testrepo")
```

**Comment by rubiin** [comment]
also isnt it supposed to fetch all user repos, I  mean the forked and sources 

```golang
	repos, _, err := client.Repositories.List(ctx, "", nil)
```
I dont get the full repo list as seen in the user repos in github. LIke i hva earound 61 repos but it only gets around 15-20 repos

**Comment by gmlewis** [comment]
This is the only call I see in the GitHub v3 API docs that says it will list forks:
https://developer.github.com/v3/repos/#list-organization-repositories
Note that this call requires the org name (e.g. "rubiin").
