### ISSUE TITLE
Some service calls don't respect URLs specified by API responses

### ISSUE THREAD

**Issue by pentaphobe** [google/go-github#1588]
## Context

Some API endpoints will vary depending upon installed version of Github / Github Enterprise

Whilst this can't be helped for top level endpoints, the Github API design includes URLs in its response for gathering further data.

eg. [Get a team by name](https://developer.github.com/enterprise/2.21/v3/teams/#list-teams) returns:

- `members_url`
- `repositories_url`

These returned values differ between (say) 

- [github.com and GHE v.2.21](https://developer.github.com/v3/teams/members/#list-team-members) `GET /orgs/:org/teams/:team_slug/members` or `GET /organizations/:org_id/team/:team_id/members`
- [github enterprise v2.20](https://developer.github.com/enterprise/2.20/v3/teams/members/#list-team-members) `GET /teams/:team_id/members`

## Problem

The current implementation of (some?) services include the aforementioned URL responses in their structures, but don't use them.

The hardcoded URLs used create a version lockstep which might be (at least partially) avoidable

### Example: `teams`

- [`teams.go` contains the required response URLs](https://github.com/google/go-github/blob/4a2bf0671d35d62e3c8807cf7df4df6c516ff42a/github/teams.go#L45-L46)
- [`teams_members.go` v28](https://github.com/google/go-github/blob/9686ff0746200cf521ce225525b421e13b4eac1a/github/teams_members.go#L28) hardcodes the `teams/{teamId}/members` URL
- [`teams_members.go` v31](https://github.com/google/go-github/blob/0683ca03b4e9f6cfab67a0f95f8c42bcacd57f6c/github/teams_members.go#L28) hardcodes the `organizations/{orgId}/team/{teamId}/members` URL

This is not ideal, partially because it version-locks the library to specific releases - but also future API changes will likely necessitate refactoring which could be avoided by respecting the URLs in prior responses

## Proposed solution

This is debatable, but two possible options:

1. Use the provided URLs from the `Teams` struct to construct the new endpoint
   - This assumes the data has been fetched, whether the library puts the onus on enduser to provide the `Teams` struct (rather than ID), or silently performs the required API call to retrieve it (by ID) is a design consideration outside my scope
2. Vary the URL template depending on remote version
   - This seems a little more painful, and likely gets increasingly messy as API expectations change
   - eg. Even in the simple `Teams` example, different data are required to build the request:
      - `teamId` (for Enterprise v2.20)
      - `teamId` _and_ `orgId` (for Enterprise v2.21 + github.com)

**Comment by gmlewis** [comment]
Thank you for reporting this issue, @pentaphobe.
As you have pointed out, this is a complex problem, and not easily solved, especially as the GitHub v3 API advances ever forward.

The options you suggest will make maintenance and support of this repo even more challenging than it already is, and may not fully solve the problem for all endpoints. We also need to keep in mind that this repo has thousands of users and we can't easily make sweeping changes like this that could potentially break a large number of users.

In the past, our stance has been that people should use the tagged version of this repo that most closely matches the version of Enterprise GitHub that they are communicating with, but that this repo would attempt to always keep up with the cutting-edge latest version of the GitHub v3 API itself, including supporting all the custom headers for new pre-release features.

So I'm going to leave this issue open in case others want to discuss possible solutions, but versioning has been discussed many times in the past... so after a few weeks we can close this issue if there are no other suggestions or expressed interest.

**Comment by pentaphobe** [comment]
Thanks @gmlewis - I'll give it a further ponder too, suspect I made it sound a little more of a hopeless case with my rather prolix description :)

One thought (which I could have been clearer about in the original ticket) is that currently the related functions have parameters which map directly to the expected RESTful variables, which puts it in lockstep with API changes 

eg.

- [In `v28` we have](https://github.com/google/go-github/blob/9686ff0746200cf521ce225525b421e13b4eac1a/github/teams_members.go#L27) just the `team` ID as an `int64`:
   ```go
   func (s *TeamsService) ListTeamMembers(ctx context.Context, team int64, opt *TeamListTeamMembersOptions) ([]*User, *Response, error) {
   ```
- And in [`v32` we have](https://github.com/google/go-github/blob/0683ca03b4e9f6cfab67a0f95f8c42bcacd57f6c/github/teams_members.go#L27) the `teamID` and `orgID` params as `int64`
   ```go
   func (s *TeamsService) ListTeamMembersByID(ctx context.Context, orgID, teamID int64, opts *TeamListTeamMembersOptions) ([]*User, *Response, error) {
  ```

I assume in most use cases the `orgID` or `teamID` value has been looked up in the consumer application via one of the other calls, so:

## Potential non-breaking solution

Without introducing a breaking change to other people using the library, one could incorporate the proposed pattern with something akin to the following:

> NB: (I'm writing this in-browser, so please consider it pseudocode - but I wouldn't be surprised if it JustWorks™)
```go
// ListTeamMembers lists all of the users who are members of a team, 
// given specified Organization and Team structs
//
// GitHub API docs: https://developer.github.com/v3/teams/members/#list-team-members
func (s *TeamsService) ListTeamMembers(ctx context.Context, org *Organization, team *Team, opts *TeamListTeamMembersOptions) ([]*User, *Response, error) {
	// Previously:
        // u := fmt.Sprintf("organizations/%v/team/%v/members", orgID, teamID)
        u := strings.Replace(org.MembersURL, "{/member}", fmt.Sprintf("/%d", team.ID), 1)
	u, err := addOptions(u, opts)
	if err != nil {
		return nil, nil, err
	}

	req, err := s.client.NewRequest("GET", u, nil)
	if err != nil {
		return nil, nil, err
	}

	var members []*User
	resp, err := s.client.Do(ctx, req, &members)
	if err != nil {
		return nil, resp, err
	}

	return members, resp, nil
}
``` 

ie.

- New function (don't break anything which exists)
- Takes the associated org & team structs, rather than the IDs (which are likely derived from said structs in the first place)
- No version detection required, as Github API follows the pattern of including URL templates in responses
- Can be entirely ignored by consumers that (say) have cached IDs to requested records rather than having the struct available

---

If this approach works for the core team I'll gladly do the PR and add the requisite tests

**Comment by gmlewis** [comment]
I think I understand, but the fact that you are relying on `org.MembersURL` means that you were forced to make a call to the API before making the call you are really interested in.

This new method now relies on `org.MembersURL` having a somewhat consistent format since you are performing a string search-and-replace on it.

I'm back to my original statement that this kind of solution introduces a maintenance nightmare because the moment that GitHub decides to change the format of the URL, it can easily break any string manipulation we attempt to perform.

So I'm sorry, but no, I'm not OK with this approach, but I will still leave the issue open to see if there is any other interest.

**Comment by pentaphobe** [comment]
Fair enough, thanks for the feedback @gmlewis

I'll try not to ponder it further :)

**Comment by gmlewis** [comment]
Closing inactive issue for lack of activity/interest.  Feel free to reopen.
