### ISSUE TITLE
Add `busy` field to runners

### ISSUE THREAD

**Issue by davidkarlsen** [google/go-github#1589]
From https://docs.github.com/en/rest/reference/actions#self-hosted-runners there seems to be a boolean `busy`field. This should be added to https://pkg.go.dev/github.com/google/go-github/v31/github?tab=doc#Runner

**Comment by gmlewis** [comment]
Thank you, @davidkarlsen !
It's interesting that the old docs do not appear to be getting updated:
https://developer.github.com/v3/actions/self-hosted-runners/#list-self-hosted-runners-for-an-organization
