### ISSUE TITLE
Github API changed for getting PR files?

### ISSUE THREAD

**Issue by Jonnymcc** [google/go-github#1591]
The API call here seems to be broken
https://github.com/google/go-github/blob/0683ca03b4e9f6cfab67a0f95f8c42bcacd57f6c/github/pulls.go#L398

The sprintf function uses "/pulls/" which results in a 404, but "/pull/" works.

Using version `github.com/google/go-github/v29 v29.0.3`

**Comment by nightlark** [comment]
I'm not seeing this -- https://api.github.com/repos/google/go-github/pulls/1584/files works for me, and https://api.github.com/repos/google/go-github/pull/1584/files gives a JSON response with `"message": "Not Found"`.

**Comment by Jonnymcc** [comment]
I think we resolved this issue.
