### ISSUE TITLE
Copying branch protection from one branch to another

### ISSUE THREAD

**Issue by mdeggies** [google/go-github#1593]
Hello! I'm attempting to copy a `*github.Protection` from one branch to another. This involves turning the existing `*github.Protection` into a `*github.ProtectionRequest` to use in the `UpdateBranchProtection()` method. Is there a recommended way to do this? 

I have a monster of a function that tries to convert an existing `Protection` into a `ProtectionRequest`, but there's lots of nested requests needed, and any nil from `Protection` that's copied over throws an error.

**Comment by gmlewis** [comment]
To debug things like this, I usually try to make a working example with curl and then convert it to the Go equivalent. Is that easy to do in this case?

**Comment by gmlewis** [comment]
Closing inactive issue for lack of activity/interest.  Feel free to reopen.
