### ISSUE TITLE
Support self-hosted runner groups

### ISSUE THREAD

**Issue by davidkarlsen** [google/go-github#1594]
Implement API for https://docs.github.com/en/rest/reference/actions#self-hosted-runner-groups

**Comment by nightlark** [comment]
I've started looking at implementing support for self-hosted runner groups, though this week is pretty busy so I probably won't get a PR open for it until end of next weekend.

**Comment by nightlark** [comment]
Sorry, I started adding support for this API then work got busy -- estimating that I'll have time to finish work on it towards the end of next week.

**Comment by davidkarlsen** [comment]
It's open-source - I fully understand this cannot be main concert at any given time! Thanks and good luck :)
