### ISSUE TITLE
Add support for webhook payload from event "change the base-branch in a pull request" 

### ISSUE THREAD

**Issue by JacobValdemar** [google/go-github#1617]
I'm new in the open source community, but I would be happy to contribute with a PR to solve this issue :-)

Let's say you open a pull request where you want to merge into `originalBranch` from `feature/thing`. But whoops, you actually wanted to merge into `master` so you change the pull request base to `master`. It will look something like [this](https://github.blog/2016-08-15-change-the-base-branch-of-a-pull-request/).

This will trigger a webhook with a payload which looks kinda like this (cropped):

```
{
    "action": "edited",
    "pull_request": {
        "base": {
            "label": "githubUser:master",
            "ref": "master"
        },
    },
    "changes": {
        "base": {
            "ref": {
                "from": "originalBranch"
            },
            "sha": {
                "from": "f8743xxxx"
            }
        }
    },
}
```

Here comes the problem: Using go-github, it will try to map `changes` from the payload into the `EditChange` struct, but `EditChange` does not support this kind of data from the payload.

https://github.com/google/go-github/blob/d57a3a84ba041135efb6b7ad3991f827c93c306a/github/event_types.go#L215-L224

https://github.com/google/go-github/blob/d57a3a84ba041135efb6b7ad3991f827c93c306a/github/event_types.go#L616

I do not know if there are any other types of changes which is not supported, but could something like the following at least be added to the `EditChange` struct?

```go
Base *struct {
	Ref *struct {
		From *string `json:"from,omitempty"`
	} `json:"ref,omitempty"`
	Sha *struct {
		From *string `json:"from,omitempty"`
	} `json:"sha,omitempty"`
} `json:"base,omitempty"`
```

Should I just create a pull request with the just mentioned changes?

Reference to GitHub API documentation:
[pull_request webhook payload](https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#pull_request)

**Comment by gmlewis** [comment]
Thank you @JacobValdemar !

Can you find out if this is documented anywhere so that we can also attempt to catch other unsupported scenarios?

But the answer is: Yes, please create a PR to support this currently-missed scenario.
Hopefully you don't have to embed structs like you showed in your example, but you can use existing Base, Ref, and/or SHA structs.  Please look around to see if you can find something like this already existing with the same or similar meanings.

**Comment by JacobValdemar** [comment]
@gmlewis I think It's probably an edge case GitHub didn't consider when writing their docs. Or they didn't update their docs then this feature was introduced in August 2016.

**Comment by gmlewis** [comment]
I used to suggest sending an email to the tech support team at GitHub, but apparently that's not how feedback is given anymore. If you would like to send the tech team a suggestion via their forum, that would help improve their documentation which benefits everyone.  But I'll leave that up to you.  Thanks again, @JacobValdemar !
