### ISSUE TITLE
GitHub errors do not check for nil fields in Error() functions

### ISSUE THREAD

**Issue by prabenzom** [google/go-github#1620]
Hi,

I noticed that the Error functions do not check to see if http.Response.request  is set when creating the error string. I'd like to make changes to check that the fields are non-nil before including them in the error string. For example:

https://github.com/google/go-github/blob/d57a3a84ba041135efb6b7ad3991f827c93c306a/github/github.go#L678

Does this seem reasonable?

**Comment by gmlewis** [comment]
Have you found cases where `r.Response.Request` is `nil`?
Can you reliably reproduce this scenario?

If yes, then that sounds like a great idea, and we might even want to look into why this is happening in the first place.
If no, then what prompted this?

Thank you, @prabenzom !

**Comment by prabenzom** [comment]
This happened when I was using the library with an HTTPOverGRPC client
written by someone at my company. Their client did not set the request in
the response. I have since fixed that client to include the request in the
response.

I doubt that this is occuring with the use of the default http client, but
changing this could prevent it from happening in the future for other use
cases.

**Comment by gmlewis** [comment]
Thank you for the explanation, @prabenzom !
I'm totally fine with that.

Feel free to put together a PR with a unit test demonstrating that it is working.

Also, please check out our CONTRIBUTING.md guide for helpful information.

**Comment by gmlewis** [comment]
Closing inactive issue for lack of activity/interest.  Feel free to reopen.
