### ISSUE TITLE
func (*SearchService) Issues - Issue data type doesn't return Repositories

### ISSUE THREAD

**Issue by pisces-period** [google/go-github#1627]
Golang version: 1.14.4 darwin/amd64
Library version: github.com/google/go-github/v32/github

I've been using the go-github library to query GitHub API to search code, commits, and issues matching against a particular string. The necessary functions and data types that I'm using in particular are documented [here](https://pkg.go.dev/github.com/google/go-github/v31/github?tab=doc#Search).

While I'm able to query the GitHub API and obtain and parse the results for code and commits, I've noticed that the `Issue` data type doesn't return a `*Repository` in response to a call to `GetRepository()` func (see [here](https://pkg.go.dev/github.com/google/go-github/v31/github?tab=doc#Issue)). It always returns `nil`, and I'm then unable to get the string representation of the `HTMLURL` field (which contains the actual URL of the repo).

Consider the following code snippets (I'm abstracting the GitHub token and authentication portion since it's out of the scope of this issue report. I wrote the funcs in separate files for better readability, but that's irrelevant to the point I want to highlight):

```
//Set search options
opts := &github.SearchOptions{Sort: "indexed", Order: "asc", TextMatch: true}

//Set search terms
regex := "my_search"

//Set context
ctx := context.Background()

//Get CodeSearchResults
csr, res, err := github.Search.Code(ctx, regex, opts)
if err != nil {
    log.Fatal(err)
}

//For CodeResult in CodeSearchResults
for _, cr := range csr {
    fmt.Printf("%v", cr.GetRepository())
}
```
```
//Get Issue Search Results
isr, res, err := github.Search.Issues(ctx, regex, opts)
if err != nil {
    log.Fatal(err)
}

//For Issue in Issues
for _, i := range isr.Issues {
    fmt.Printf("%v", i.GetRepository())
}

```

In the first instance (code) the output is something like this:

```
github.Repository{ID:${ID}, NodeID:${SOME_ID}, Owner:github.User{Login:${LOGIN}, ID:${ID}, NodeID:${SOME_ID}, AvatarURL:"https://avatars1.githubusercontent.com/u/${U_ID}, HTMLURL:"${REPOURL}", GravatarID:"", Type:"User", SiteAdmin:false, URL:"https://api.github.com/users/{$USER}", EventsURL:"https://api.github.com/users/${USER}/events{/privacy}", ... etc etc ...
```

In the second instance (issue) the output is this:
```
<nil>
```

Am I missing something obvious, or is it possible that there is a problem with the implementation of the `Issue` data type?

I'm able to get other properties of `Issue` by invoking other functions such as `GetTitle()` etc. It's just `GetRepository()` func that returns a nil value.

**Comment by gmlewis** [comment]
Hi @pisces-period - whenever I'm faced with questions regarding "what data can I get from GitHub", I scan through the official documentation until I find what I want, and then if the methods from this repo don't give me the results I want, I then revert to using the curl commands directly from the official docs to see if those provide the data I want. This will typically tell me if there is a limitation in the GitHub v3 API endpoints themselves or if there is a gap in the processing of the data within this repo.

Now, having said that, if you could boil your issue down into a simple, reproducible test case where was can see the results that you are expecting, and then work backward from there, it would be greatly beneficial.

But while we are strictly dealing with the hypothetical "my_search", we can do a lot of theorizing, but that won't help you solve the problem.

So please reply with two tiny practical example test programs (excluding AUTH details) with expected results and we can attempt to help you figure out what is going on.  (Feel free to create a fake repo with fake data for testing this on... that often helps and doesn't expose your actual search criteria.)

**Comment by pisces-period** [comment]
Hi @gmlewis, I apologize for the late reply.

I had already tested w/ running cURL commands directly against the GitHub API v3. The data that I need (the repository HTML URL associated with code, commits and issues) is available through a direct API call.

Since you requested a more thorough example than what I had previously provided, here's a simple implementation (excluding authentication) that exemplifies an API request to Search Commit and Search Issues. The search term is read at run-time from the command-line and thus the search criteria is encapsulated.

Searching commits produces the expected output (the repository HTML URL).

Searching issues does not produce the expected output (repository is nil).

According to the go-github documentation, both data types (_CommitResult_ and _Issue_) contain a field of type *Repository, which I'd expect gives you access to the corresponding _*Repository_ values. Somehow it does not seem to be the case.

It could easily be me mishandling or misunderstanding this module, or an actual issue/limitation with the code?

I commented out the snippet which throws an error, feel free to uncomment it. I added another snippet which, without throwing the panic (nil pointer dereference) demonstrates that the repository is always empty when you search through issues.

```
package main

import (
	"context"
	"fmt"

	"github.com/google/go-github/v32/github"
)

//Search options
var opts = &github.SearchOptions{
	Sort: "indexed", 
	Order: "asc", 
	TextMatch: true,
}

//This function returns first 100 Commits search results based on REGEX
func searchCommits(client *github.Client, search string) (*github.CommitsSearchResult, error) {
	commits, _, err := client.Search.Commits(context.Background(), search, opts)

	return commits, err
}

//This function returns first 100 Issues search results based on REGEX
func searchIssues(client *github.Client, search string) (*github.IssuesSearchResult, error) {
	issues, _, err := client.Search.Issues(context.Background(), search, opts)

	return issues, err
	
}

func main() {
	
	var regex string

	fmt.Print("Enter search term: ")
        //"Windows", "Linux", "Ansible", "my_search", "anything"
	fmt.Scanf("%s", &regex)

	//Commit and Issue Search API endpoint don't require authentication
	client := github.NewClient(nil)

	issues, err := searchIssues(client, regex)

	if err != nil {
		fmt.Printf("Error: %v\n", err)
		return
	}

	commits, err := searchCommits(client, regex)

	if err != nil {
		fmt.Printf("Error: %v\n", err)
		return
	}

	/*
	
	Running the snippet below results in the following error:
	panic: runtime error: invalid memory address or nil pointer dereference

	for _, i := range issues.Issues {
		fmt.Printf("Issue: %v\n", *i.GetRepository().HTMLURL)
	}

	*/

	//This line demonstrates that IssueSearchResult does return
	//a slice of Issues, and other attributes of Issues can be accessed
	//however Repository is always empty for some reason.
	//Perhaps that's why de-referencing Repository and attributes fails
	for _, i := range issues.Issues {
		fmt.Printf("Repo: %v\nA non-nil attribute of issue: %v\n", i.GetRepository().GetHTMLURL(), i.GetTitle())
	}

	//This line demonstrates that Commits are able to access
	//Repository's HTML URL correctly
	for _, c := range commits.Commits {
		fmt.Printf("Commit: %v\n", *c.GetRepository().HTMLURL)
	}
}
```

**Comment by gmlewis** [comment]
Hi @pisces-period , you wrote:

> I had already tested w/ running cURL commands directly against the GitHub API v3. The data that I need (the repository HTML URL associated with code, commits and issues) is available through a direct API call.

But you neglected to say where (i.e. in which field) this information was found.

So I went ahead and did what I had recommended myself, and performed a curl call, like so:

```
$ curl 'https://api.github.com/search/issues?order=asc&q=Windows&sort=indexed' > response.json
```

I then looked through the response that it gave, and noticed that the field you are trying to get data from (`repository` in your Go example code) is not being returned at all!

This means that your Go example code is not going to work because the data returned by the V3 API is not returning that data.

So instead, we have to look through the data returned and find a value of interest. I noticed that the "html_url" field looks like it might be the closest to what you want. If you want the repo, you could use that field and strip off everything after "/pull/...".

So I modified your loop to look like this:

```
	for _, i := range issues.Issues {
		repo := i.GetHTMLURL()
		if j := strings.LastIndex(repo, "/pull/"); j >= 0 {
			repo = repo[:j]
		}
		fmt.Printf("Repo: %v\nA non-nil attribute of issue: %v\n", repo, i.GetTitle())
	}
```

and then re-ran your program, and it looks to me like it is working just fine now:

```
Repo: https://github.com/harsimranmaan/qbec
A non-nil attribute of issue: Windows
Repo: https://github.com/crisschan/course
A non-nil attribute of issue: Windows
Repo: https://github.com/Nicolab/php-ftp-client
A non-nil attribute of issue: [Windows Compatibility] Support for Windows FTP listings
Repo: https://github.com/apache/cordova-lib
A non-nil attribute of issue: (windows): set Windows as deprecated
Repo: https://github.com/MicrosoftDocs/azure-dev-docs.ja-jp
A non-nil attribute of issue: [LOC]Back-Translation "Windows ターミナル"→"Windows Terminal"
Repo: https://github.com/envoyproxy/envoy
A non-nil attribute of issue: [Windows] Adds a native windows filesystem implementation
...
```

I hope this answers your questions and shows you how to debug these kinds of things for yourself.

**Comment by pisces-period** [comment]
Hi @gmlewis,

I appreciate the help. I'll close the issue.
