### ISSUE TITLE
I think the condition "resp.ContentLength == -1" isn't needed because "-1" < "2048"

### ISSUE THREAD

**Issue by Sympho** [google/go-github#1628]
https://github.com/google/go-github/blob/master/github/github.go#L576

**Comment by gmlewis** [comment]
Yes, that is true, and we have an open PR addressing that issue: https://github.com/google/go-github/pull/1615/files

**Comment by chughpiyush** [comment]
@gmlewis I think this issue can be closed now, code in question has been removed : https://github.com/google/go-github/commit/c5b0f2133dafff1990647022a89886d173e3d7e6

**Comment by gmlewis** [comment]
Good call, @chughpiyush .
Closing issue as obsolete.
