### ISSUE TITLE
Remove graduated GitHub v3 API preview header: antiope

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#1634]
GitHub Developer v3 API announcement:
https://developer.github.com/changes/2020-10-01-graduate-antiope-preview/

This custom preview header has now graduated and needs to be removed from this repo:

* application/vnd.github.antiope-preview+json

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by n1lesh** [comment]
@gmlewis I can take this up if no one's started yet.

**Comment by gmlewis** [comment]
Thank you, @n1lesh !  It's yours.

**Comment by n1lesh** [comment]
Submitted a PR #1636.
