### ISSUE TITLE
Add Workflow enable and disable states

### ISSUE THREAD

**Issue by n1lesh** [google/go-github#1637]
Github has two APIs to manually enable and disable a workflow by ID or Filename,

- [Enable a workflow](https://docs.github.com/en/free-pro-team@latest/rest/reference/actions#enable-a-workflow)
- [Disable a workflow](https://docs.github.com/en/free-pro-team@latest/rest/reference/actions#disable-a-workflow)

Both are not implemented yet. I would like to take this up if it is supposed to be added.

**Comment by gmlewis** [comment]
> Both are not implemented yet. I would like to take this up if it is supposed to be added.

That would be great!  Thank you, @n1lesh - this is yours.
