### ISSUE TITLE
Can't create workflow dispatch event by filename

### ISSUE THREAD

**Issue by n1lesh** [google/go-github#1639]
Noticed that, [GitHub API docs: Create a workflow dispatch event](https://docs.github.com/en/free-pro-team@latest/rest/reference/actions#create-a-workflow-dispatch-event), let's you create dispatch event by both workflowID and Filename.

However, [PR #1623 ](https://github.com/google/go-github/pull/1623) adds support for just workflowID, with **CreateWorkflowDispatchEvent**.

Can we split it into two _funcs_ for each type, as that's the general implementation in other APIs?

**Comment by gmlewis** [comment]
Excellent catch, @n1lesh  - thank you!  Yes, that would be consistent and generally useful.
Let's do that, please.

**Comment by gmlewis** [comment]
This will be a breaking API change, but I think we should do it, so I've labeled it as such.
