### ISSUE TITLE
Get Label data from call to ListOrganizationRunners

### ISSUE THREAD

**Issue by nkaplatt** [google/go-github#1647]
I'm currently doing some work around our organisational runners, part of that is verifying state and collect some high level metrics. Whilst using the library I noticed that the function ListOrganizationRunners and struct `Runners` doesn't collect the array of labels that also comes back with this call https://docs.github.com/en/free-pro-team@latest/rest/reference/actions#list-self-hosted-runners-for-an-organization.

Would this be able to be added? I currently have a working fork as it's just an addition of 5 or so lines but wanted to check this is either by design or has already been discussed.

**Comment by gmlewis** [comment]
Rarely do we omit fields by design (except for possibly all the redundant URLs).
(Typically, the GitHub team adds fields as they go, and we eventually find out about them through issues like this one.)

So it looks like #1648 addresses this.
Thank you, @nkaplatt !  I'll add comments to the PR.
