### ISSUE TITLE
goauth2 is deprecated

### ISSUE THREAD

**Issue by begizi** [google/go-github#165]
golang.org/x/oauth2 should be supported in it's place.

**Comment by willnorris** [comment]
yep.  @kjk started to update links in #163, but we need to update the sample code as well.  Feel free to send over a PR, or otherwise I'll get to it when I can.

**Comment by begizi** [comment]
PR at #166

**Comment by dmitris** [comment]
very timely considering the upcoming code.google.com sunset! :smile:

**Comment by willnorris** [comment]
fixed in #166
