### ISSUE TITLE
CompareCommits function not working post #1649

### ISSUE THREAD

**Issue by srinidhis05** [google/go-github#1654]
The comparecommits function is returning 404 for comparison of the commits post PR [#1649](https://github.com/google/go-github/pull/1649) root cause being query escape . 

Call to github without the change : repos/org/repo/compare/commit1...commit2
Call to github with the change : repos%2Forg%2Frepo%2Fcompare%2Fcommit1...commit2

**Comment by gmlewis** [comment]
Ah, yes, of course. This was not tested well. I'll revert it.
Thank you, @srinidhis05 !

**Comment by gmlewis** [comment]
Reverted.
