### ISSUE TITLE
Webhook payload fields for Github Apps: action, organization and installation

### ISSUE THREAD

**Issue by afdesk** [google/go-github#1674]
Each webhook event payload contains properties unique to the event. There are a few common keys for these properties: `action`, `sender`, `repository`, `organization`, `installation`.
more details: [Webhook payload object common properties](https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#webhook-payload-object-common-properties).

`WebHookPayload` struct doesn't contain `action`, `organization` and `installation` fields yet, but these objects need for webhooks from Github App.

Can I add these objects to `WebHookPayload`?

**Comment by gmlewis** [comment]
Yes, that would be great.  Thank you, @afdesk .
Please be sure to read CONTRIBUTING.md if you have not contributed to this repo before.

**Comment by afdesk** [comment]
@gmlewis I've created a pull request #1678 `Add action, organization and installation objects to Webhook payload`.
