### ISSUE TITLE
Default commit message?

### ISSUE THREAD

**Issue by parkr** [google/go-github#168]
Hey!

I'm looking to merge pull requests while using the default merge message. Is there a way to call `client.PullRequests.Merge` without supplying a commit message so it defaults? I don't want to include an empty string for fear that it'll cause empty or otherwise undesired commit messages. Is passing `""` the ticket to defaulting?

Thanks :)

**Comment by willnorris** [comment]
Not sure what will happen if you pass an empty string in that case. Try in a test repo and find out? :)

**Comment by parkr** [comment]
Hm! Turns out if you *do* send something, it will just stick it at the bottom of your automatic commit message:

```text
commit 4255f7ec0dcda04efe40d863d55650793468a767
Merge: fc4d671 a8f4633
Author: Parker Moore <parkrmoore@gmail.com>
Date:   Wed Mar 11 01:17:55 2015 -0700

    Merge pull request #20 from parkr/fix-release

    Merge pull request 20
```
