### ISSUE TITLE
OAuth token leakage in error messages

### ISSUE THREAD

**Issue by AustinDizzy** [google/go-github#169]
OAuth tokens are leaked in Go errors. The errors contain the full URL which contains `client_id` and `client_secret` and can be leaked to a user or easily passed on to someone who shouldn't see it.

Shouldn't it be sanitized from the URL - basically just remove the `client_id` and `client_secret` fields and their respective values from the error string - to prevent those from being leaked to an end-user?

**Before:** `Get https://api.github.com/user/:username/repos?sort=created&client_id=test1234&client_secret=1234test: 404 Not Found []`.

**After:** `Get https://api.github.com/user/:username/repos?sort=created: 404 Not Found []`.

I have a basic solution that I'm about to commit and submit as a pull request. It simply removes those fields and their values from the error text. It satisfies the before/after clause detailed above.

**Comment by willnorris** [comment]
The more annoying part here is that GitHub requires that we send these credentials as query parameters.  

@pengwynn @izuzak,

I sent an email about this back in June 2013, which I'll copy below:

> Presently, the GitHub API allows you to make unauthenticated rate limited requests by appending your OAuth client ID and secret to the request (http://developer.github.com/v3/#rate-limiting).  Have you considered supporting OAuth's "Client Credentials Grant" (http://tools.ietf.org/html/rfc6749#section-4.4), which was designed for expressly this purpose?  That's what Twitter does (https://dev.twitter.com/docs/auth/application-only-auth) and it makes things quite a bit simpler for client libraries, since there's now only way kind of authentication worry about, regardless of whether a user is involved.

Any hope of supporting this?  Or maybe some variant of HTTP Basic Auth using the client ID and secret?  Anything that prevents us from having to put credentials in query parameters?

**Comment by pengwynn** [comment]
No update, but better app-level authentication is on the radar. As a workaround, most clients opt for a scope-less token for these type of scenarios.

**Comment by willnorris** [comment]
fixed in #170
