### ISSUE TITLE
Struct field `json:"xxx,omitempty"` return nil when reference

### ISSUE THREAD

**Issue by yisiper** [google/go-github#173]
I am trying to get github user repositories 
https://gist.github.com/yisiper/48ea8ddc9c48d97e7a9f

Not all repositories return it's language , the return json may just {language : null}, thus the pointer in struct point to nil.

it need to do many pointer nil checking before use those field.
Is it possible to let the default type initialized?  
says string should be "", int should be 0.

ref: https://github.com/google/go-github/issues/19#issuecomment-22151321

**Comment by rsc** [comment]
I use helpers like this in my own code using this package:

	func getInt(x *int) int {
		if x == nil {
			return 0
		}
		return *x
	}
	
	func getString(x *string) string {
		if x == nil {
			return ""
		}
		return *x
	}
	
	func getUserLogin(x *github.User) string {
		if x == nil || x.Login == nil {
			return ""
		}
		return *x.Login
	}
	
	func getTime(x *time.Time) time.Time {
		if x == nil {
			return time.Time{}
		}
		return *x
	}
	
	func getMilestoneTitle(x *github.Milestone) string {
		if x == nil || x.Title == nil {
			return ""
		}
		return *x.Title
	}
	
	func getLabelNames(x []github.Label) []string {
		var out []string
		for _, lab := range x {
			out = append(out, getString(lab.Name))
		}
		sort.Strings(out)
		return out
	}

Then if you don't care about present vs not present, you can use, say, getString(issue.Milestone) instead of checking whether issue.Milestone is nil.

**Comment by willnorris** [comment]
Unfortunately, there's not an easy solution to this.  #19 certainly does have all the discussion that led to this design, but I also [wrote about it here](https://willnorris.com/2014/05/go-rest-apis-and-pointers) if you're interested.

The best solution will be to implement #45, which is what the proto library does.  `go generate` didn't exist when I originally filed that issue, so it would actually be much easier to implement now.

Closing this for now, as there isn't actually anything to do here.
