### ISSUE TITLE
Remove mediaTypeRequiredApprovingReviewsPreview header from remaining APIs

### ISSUE THREAD

**Issue by n1lesh** [google/go-github#1779]
As mentioned in,
https://developer.github.com/changes/2018-03-16-protected-branches-required-approving-reviews/

only 4 endpoints require `mediaTypeRequiredApprovingReviewsPreview` header as mentioned in [here as well](https://docs.github.com/en/rest/reference/repos#branches).

Can we remove the header in remaining APIs, namely status checks APIs, as I see it being used in around 14 endpoints, or am I missing something?

**Comment by gmlewis** [comment]
Hmmm... I think we have a disconnect.  If I search for that custom media header in this repo, I see this:

https://github.com/google/go-github/search?q=mediaTypeRequiredApprovingReviewsPreview

which shows it being used in two locations:

* https://github.com/google/go-github/blob/c2c4a6d477016a3e73a63d67b1933fb24f52fd99/github/repos.go#L924
* https://github.com/google/go-github/blob/c2c4a6d477016a3e73a63d67b1933fb24f52fd99/github/repos.go#L946

These appear to have been modified most recently in: https://github.com/google/go-github/pull/880

Can you please clarify where you are seeing this custom media header?

**Comment by n1lesh** [comment]
Well, I took the latest for the last pull request, plus here, https://github.com/google/go-github/blob/c2c4a6d477016a3e73a63d67b1933fb24f52fd99/github/repos.go, where I can see it being used multiple times.

I guess [here](https://github.com/google/go-github/search?q=mediaTypeRequiredApprovingReviewsPreview) they are just showing the top 2 matches, but if you open the file, it's more than 2.

**Comment by gmlewis** [comment]
Ah!  You are right!  Mine was the disconnect.  Sorry about that.

Then yes, please feel free to submit a PR to clean these all up, or we can open it up to another volunteer to do this... your choice.

Thank you, @n1lesh !

**Comment by n1lesh** [comment]
Will work on it, no problem. Thank you, @gmlewis
