### ISSUE TITLE
How to use the master branch with go modules?

### ISSUE THREAD

**Issue by andygrunwald** [google/go-github#1785]
Hey all,

I am using go modules in my app and would like to use the master branch of this library (because I depend on some fixes that don't have released yet).
Due to the line https://github.com/google/go-github/blob/master/go.mod#L1, I get the following message:

```sh
$ go get -u github.com/google/go-github@master
go: github.com/google/go-github@v0.0.0-20210126170847-5cd6a0f4812a: invalid version: go.mod has post-v0 module path "github.com/google/go-github/v33" at revision 5cd6a0f4812a
```

Is there a way to use the master branch without waiting for a new release?
Thanks in advance!

**Comment by gmlewis** [comment]
Please try:

```
go get -u github.com/google/go-github/v33/github@latest
```

as provided by @dmitshur in #1641.

**Comment by andygrunwald** [comment]
@gmlewis This doesn't seem to end up with what I am trying, but you pointed me in the right direction:

```
$ go get -u github.com/google/go-github/v33/github@master
go: downloading github.com/google/go-github/v33 v33.0.1-0.20210126170847-5cd6a0f4812a
go: found github.com/google/go-github/v33/github in github.com/google/go-github/v33 v33.0.1-0.20210126170847-5cd6a0f4812a
go: github.com/google/go-github/v33 master => v33.0.1-0.20210126170847-5cd6a0f4812a
go: golang.org/x/crypto upgrade => v0.0.0-20201221181555-eec23a3978ad
```

Here you see this works by getting the latest / master branch of the current version.

In #1641, @dmitshur is saying that @latest can be omitted.
If I understand this correctly this would lead to the same situation as using `import github.com/google/go-github/v33/github` in an app.

Maybe it is a good idea to add an installation section to the README.
Thanks for your help!

**Comment by dmitshur** [comment]
For posterity, the `@latest` and `@master` are version queries and are fully documented at https://golang.org/ref/mod#version-queries.
