### ISSUE TITLE
Add support for Enterprise interfaces

### ISSUE THREAD

**Issue by moutons** [google/go-github#179]
in the [godocs](https://godoc.org/github.com/google/go-github/github) for go-github there are a few references to using it with GitHub Enterprise instances, but I don't see reference to the management tasks other than [PromoteSiteAdmin](https://github.com/google/go-github/blob/master/github/users_administration.go#L13). It would be nice to be able to use go-github to work with some interfaces like /enterprise/settings/license or /enterprise/stats/

**Comment by gmlewis** [comment]
6 years later, it looks like `/enterprise/settings/...` endpoints are still missing, but closing issue for lack of interest/activity.
Feel free to reopen if anyone is still interested.

**Comment by BlackVegetable** [comment]
I'd like this! Can I re-open.

**Comment by naikrovek** [comment]
I would also like to see the enterprise settings endpoints become supported.  I was very surprised when I discovered that they weren't.

**Comment by marcellodesales** [comment]
Wow, no Github Enterprise support?

**Comment by gmlewis** [comment]
> Wow, no Github Enterprise support?

Have you looked at the repo or the docs?
I don't think "no GitHub Enterprise support" is quite accurate, as I have personally used this repo extensively within GitHub Enterprise environments to great success.
It might be limited in some aspects such as those listed above, but PRs are welcome.

**Comment by marcellodesales** [comment]
@gmlewis my bad... I just found `github.NewEnterpriseClient` ... I think this should be closed!

**Comment by gmlewis** [comment]
OK, good point.
Thank you, @marcellodesales .
Closing issue as obsolete.

**Comment by naikrovek** [comment]
feel free to leave this closed, i just wanted to say that while enterprise API endpoints are supported, support for all of them is not present, and I would like to see that.  I'm not going to demand that, as I have no right to, and I don't expect you to provide me anything that you have not already provided, just so I am being clear. 

*I am thankful for this repo and what it has allowed me to do.*

I would also like to add that there is a response above that is probably almost never intended to be rude or dismissive, but in effect, it _always_ is:

> PRs are welcome

You don't need to say that.  PRs are always welcome, it should be assumed, unless there is some declaration that they are not welcomed.  Saying this equates to "do it yourself if you want it so bad" and that is rude and dismissive.  So saying this is not only unneeded, it can potentially turn a willing contributor into a non-contributor.

I understand that life as an open source code maintainer is much worse than it should be, thanks to people on the Internet who believe they are owed, and/or whatever else goes on in the minds of someone who thinks people that they don't know owe them software features.  I am not one of those people, and I want to say that being dismissive about a user's needs in even that tiny way just makes lives worse for open source maintainers in the long term.

I am not saying that you owe it to us to be nice.  I am saying that being nice and being understanding will necessarily improve any imperfect conversation, and that saying "PRs are welcome" has a non-zero probability of making any negative situation worse.

I myself am not a great communicator, so I don't have any suggestions on how this could have been handled better, I just know bad communication when I see it, and I want to _try_ to make the world better.  Even if it's just a little tiny bit.

**Comment by gmlewis** [comment]
Thank you, @naikrovek, for the thoughtful and well-written comment.

I apologize for saying that and never really took the time to fully appreciate how rude and dismissive that statement can be.
I'm sorry and will try to not use that phrase ever again.

Additionally, I would like to state that new issues are also very welcome, when people see gaps between what the GitHub v3 API _provides_ and what this repo _supports_.

It is only with the help of contributors and users of this repo that we can, as a team, attempt to keep this repo as up-to-date as possible.

So I'm going to leave this issue closed, but everyone, please feel free to open more specific issues targeting specific APIs that are not yet fully supported.

Thank you very much to each and every one of you, and especially to @naikrovek who called me out on my rudeness. 
I really do appreciate the correction.

:heart:

**Comment by BlackVegetable** [comment]
Hey this is the internet. Stop having wholesome conversations. 

(On a serious note, I believe the "PRs Welcome" can be a habit from closed source projects where other employees truly might not be or feel empowered to contribute to someone else's codebase. In that light, I can see it innocently carrying over, only to sound tone-deaf in a community where "PRs Welcome" is always 100% implied.)
