### ISSUE TITLE
DownloadContents does not return RepositoryContent

### ISSUE THREAD

**Issue by daniellanner** [google/go-github#1809]
**Summary**
_DownloadContents_ allows receiving files exceeding the 1MB limit of _GetContents_. Unfortunately, the current implementation does not return the _RepositoryContent_ of the requested file.

**Limitation**
When trying to read, update and commit changes to a file larger than 1MB, the user currently has to additionally call _GetContents_ of the directory to receive the SHA of the file currently being edited.

**Expectation**
_DownloadContents_ should additionally return the _RepositoryContent_ of the requested file.

**Proposed Changes**
I am happy to work on this. For the sake of backwards compatibility, I suggest an additional method with the above mentioned return values and identical test coverage. Naturally, this comes at the cost of (temporary) code duplication.

**Comment by gmlewis** [comment]
Thank you, @daniellanner !  This sounds good and will also require some good method comments explaining the differences and when you should use one method versus the other.

**Comment by daniellanner** [comment]
Hi @gmlewis, I added my changes and opened a PR. To ensure parity with DownloadContents I naively and without critical thought added the new method to the skipMethods map in update-urls/main.go.

Thanks for letting me have a go (chichi) at this and let me know if anything is unsatisfactory.
