### ISSUE TITLE
IssuesService.Edit cannot clear an issue's labels

### ISSUE THREAD

**Issue by rsc** [google/go-github#181]
IssuesService.Edit sends an IssueRequest, which has Labels []string, with omitempty. Unfortunately this means that the JSON serialization never sends an empty Labels, so you cannot send the JSON to clear an issue's labels this way. If you dropped omitempty, you'd have the other problem, that you can't leave an issue's labels alone. The right fix is probably to use a *[]string for this field. In some sense this is the opposite of #173, and it's also a good warning against doing too much (if anything) for #173.

**Comment by tbruyelle** [comment]
HTTP PATCH requests and golang are a terrible mix.
