### ISSUE TITLE
OrganizationsService.ListFailedOrgInvitations 

### ISSUE THREAD

**Issue by micimize** [google/go-github#1812]
[/orgs/{org}/failed_invitations](https://docs.github.com/en/rest/reference/orgs#list-failed-organization-invitations) has the same API as `/orgs/{org}/invitations`, although we should likely expand the `Invitation` model to include failure fields. My userland copypasta "implementation:"

```go
// listFailedOrgInvitations returns a list of pending invitations.
// Copied and edited version of ListPendingOrgInvitations.
//
// GitHub API docs: https://docs.github.com/en/rest/reference/orgs#list-failed-organization-invitations
func listFailedOrgInvitations(ctx context.Context, client *Client, org string, opts *gh.ListOptions) ([]*gh.Invitation, *gh.Response, error) {
	u := fmt.Sprintf("orgs/%v/failed_invitations", org)
	u, err := addOptions(u, opts)
	if err != nil {
		return nil, nil, err
	}

	req, err := client.NewRequest("GET", u, nil)
	if err != nil {
		return nil, nil, err
	}

	var failedInvitations []*gh.Invitation
	resp, err := client.Do(ctx, req, &failedInvitations)
	if err != nil {
		return nil, resp, err
	}
	return failedInvitations, resp, nil
}
```

**Comment by gmlewis** [comment]
Thank you, @micimize !  (There is a bit more involved, so I'll open this up to volunteers for a complete implementation.)

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by micimize** [comment]
@gmlewis I can probably PR this, but why do you say it's more involved? The API is identical (the failure fields are in both responses).

**Comment by gmlewis** [comment]
Thanks, @micimize - it's yours.

What I meant by "a bit more involved" is that you also need to write one or more tests for the new endpoint and need to run `go generate ./...` as described in our CONTRIBUTING.md guide... but yes, you are definitely on the right track for success.

**Comment by IamMaheshDere** [comment]
@micimize Are you still working on it ? 
I am also interested in contributing

**Comment by micimize** [comment]
@IamMaheshDere I'm planning on it but probably won't get to it for a while – if you want to take it go ahead

**Comment by itsmatinx** [comment]
Since it's been almost two months that nobody has sent any PR, I'll take care of the issue in the next few hours.
