### ISSUE TITLE
Proposal: New Users Methods

### ISSUE THREAD

**Issue by irevenko** [google/go-github#1819]
What about adding these new methods?
It could be a new API Section: <b>Users > Statistics </b> or <b>Users > Repos </b>
- Most used languages
- Most starred repositories
- Most forked repositories 
- Stars per language
- Forks per language

**Comment by gmlewis** [comment]
Thank you, @irevenko. Could you please provide links to the GitHub v3 API dev docs for these endpoints?

**Comment by irevenko** [comment]
```https://api.github.com/users/USERNAME/repos```
We just need to fetch all repos and then iterate over them and calc languages, stars, forks, etc...

**Comment by gmlewis** [comment]
Sorry, but this repo is a client library and will not be providing a method to iterate over all repos. You can write tools that use this client library to do that, of course... but that is up to you.

Unless I'm missing something.

I'm on my phone at the moment but I'm pretty confident that we already support this endpoint: https://docs.github.com/en/rest/reference/repos#list-repositories-for-a-user

... and this is the kind of URL I was asking for, by the way.

**Comment by irevenko** [comment]
Thank you for answering, i'm gonna build my own tool on top of this lib

**Comment by irevenko** [comment]
if someone is interested in what i've built: https://github.com/irevenko/octostats
