### ISSUE TITLE
bug: Pagination link header seems not stable

### ISSUE THREAD

**Issue by Yiyiyimu** [google/go-github#1825]
There are two problems I met:
1. when I get the `LastPage`, there are still `NextPage` after the `LastPage`
2. when I get the `LastPage` on page 1, there is nothing on the LastPage. And when I get to page 2, the new `LastPage` is one page before the original one and full of contents.

Although I think it would be more like the github API side problem, but it seems I could not get link header information for `ListCommits` in bare Github API, so I hope maybe the community could help me a bit.

A demo to reproduce the problem 1:
```
package main

import (
	"context"
	"fmt"

	"github.com/google/go-github/v33/github"
	"golang.org/x/oauth2"
)

func main() {
	ctx := context.Background()

	client := github.NewClient(nil)

	owner := "kong"
	repo := "kong"
	author := "thibaultcha"

	//Get first page
	listCommitOpts := &github.CommitsListOptions{Author: author, ListOptions: github.ListOptions{PerPage: 100}}
	commits, resp, err := client.Repositories.ListCommits(ctx, owner, repo, listCommitOpts)
	if err != nil {
		panic(err)
	}
	fmt.Printf("commits num: %d\n", len(commits))
	fmt.Printf("First page: %#v\n", resp)

	//Get last page
	listCommitOpts.Page = resp.LastPage
	commits, resp, err = client.Repositories.ListCommits(ctx, owner, repo, listCommitOpts)
	if err != nil {
		panic(err)
	}
	fmt.Printf("commits num: %d\n", len(commits))
	fmt.Printf("Last page: %#v\n", resp)

	//Test with new next page
	commits, resp, err = client.Repositories.ListCommits(ctx, owner, repo, listCommitOpts)
	if err != nil {
		panic(err)
	}
	fmt.Printf("commits num: %d\n", len(commits))
	fmt.Printf("Last page: %#v\n", resp)
}

```

And the result would be
```
commits num: 100
First page: &github.Response{Response:(*http.Response)(0xc000570000), NextPage:2, PrevPage:0, FirstPage:0, LastPage:19, NextPageToken:"", Rate:github.Rate{Limit:5000, Remaining:4911, Reset:github.Timestamp{Time:time.Time{wall:0x0, ext:63752023103, loc:(*time.Location)(0x95dea0)}}}}
commits num: 100
Last page: &github.Response{Response:(*http.Response)(0xc0000fed80), NextPage:20, PrevPage:18, FirstPage:1, LastPage:19, NextPageToken:"", Rate:github.Rate{Limit:5000, Remaining:4910, Reset:github.Timestamp{Time:time.Time{wall:0x0, ext:63752023103, loc:(*time.Location)(0x95dea0)}}}}
commits num: 100
Last page: &github.Response{Response:(*http.Response)(0xc0000fe120), NextPage:20, PrevPage:18, FirstPage:1, LastPage:19, NextPageToken:"", Rate:github.Rate{Limit:5000, Remaining:4909, Reset:github.Timestamp{Time:time.Time{wall:0x0, ext:63752023103, loc:(*time.Location)(0x95dea0)}}}}
```

As you could see the `NextPage` still increase itself even I reached `LastPage`. And the new page still got information.
BTW, as we could find on github insights, `thibaultcha` got [1626 commits](https://github.com/Kong/kong/graphs/contributors) so maybe 20 pages is already not a good response

**Comment by gmlewis** [comment]
Looking at the code and the corresponding output, everything appears to be working correctly to me (except for GitHub... see my analysis below).

Let's break this down one issue at a time...

> 1. when I get the LastPage, there are still NextPage after the LastPage

Since `NextPage: 20`  exceeds `LastPage: 19`, I believe this is your indication to stop at 19... however, it looks like I would be completely wrong... see below.

> 2. when I get the LastPage on page 1, there is nothing on the LastPage.

I'm not understanding this sentence. According to your output, you got 100 commits when you requested the `LastPage (Page=19)`.

> ... And when I get to page 2, the new LastPage is one page before the original one and full of contents.

In your code, you never updated `listCOmmitOpts.Page = 2` so you never asked for page 2.

For us to better understand what is going on, maybe it would make sense to debug this situation using `curl`:

Here is the equivalent of your first query:

```bash
$ curl -i  -H "Accept: application/vnd.github.v3+json"   'https://api.github.com/repos/kong/kong/commits?author=thibaultcha&per_page=100' > response-page1.json
$ grep link !$
link: <https://api.github.com/repositories/26783295/commits?author=thibaultcha&per_page=100&page=2>; rel="next", <https://api.github.com/repositories/26783295/commits?author=thibaultcha&per_page=100&page=19>; rel="last"
```

Note that you received `Page: 1`.

Here is the equivalent of your second (_and third... they are identical queries..._):

```bash
$ curl -i  -H "Accept: application/vnd.github.v3+json"   'https://api.github.com/repos/kong/kong/commits?author=thibaultcha&per_page=100&page=19' > response-page19.json
$ grep link !$
link: <https://api.github.com/repositories/26783295/commits?author=thibaultcha&per_page=100&page=20>; rel="next", <https://api.github.com/repositories/26783295/commits?author=thibaultcha&per_page=100&page=19>; rel="last", <https://api.github.com/repositories/26783295/commits?author=thibaultcha&per_page=100&page=1>; rel="first", <https://api.github.com/repositories/26783295/commits?author=thibaultcha&per_page=100&page=18>; rel="prev"
```

Note that GitHub still says that page 19 is the last page and page 20 is "next"... so just for kicks, let's ask for page 20:

```bash
$ curl -i  -H "Accept: application/vnd.github.v3+json"   'https://api.github.com/repos/kong/kong/commits?author=thibaultcha&per_page=100&page=20' > response-page20.json
$ grep link !$
link: <https://api.github.com/repositories/26783295/commits?author=thibaultcha&per_page=100&page=21>; rel="next", <https://api.github.com/repositories/26783295/commits?author=thibaultcha&per_page=100&page=19>; rel="last", <https://api.github.com/repositories/26783295/commits?author=thibaultcha&per_page=100&page=1>; rel="first", <https://api.github.com/repositories/26783295/commits?author=thibaultcha&per_page=100&page=19>; rel="prev"
```

Well, I'll be bamboozled... we still get 100 commits!

Obviously, GitHub's notion of "LastPage" appears to be broken.  Please contact GitHub technical support and point them to this issue.  Maybe they can figure out what is going on here.

**Comment by Yiyiyimu** [comment]
@gmlewis thank you for the reply and the method to reproduce it with bare Github API! Since we make sure it's the Github side problem, I'll ask Github for support

Just one thing to point out:
> I'm not understanding this sentence. According to your output, you got 100 commits when you requested the LastPage (Page=19).
In your code, you never updated listCommitOpts.Page = 2 so you never asked for page 2.

Sorry I didn't make it clear. It's actually another problem I met that related to the link header. I'll find a case to reproduce the problem.

**Comment by Yiyiyimu** [comment]
@gmlewis thank you for the reply and the method to reproduce it with bare Github API! Since we make sure it's the Github side problem, I'll ask Github for support

Just one thing to point out:
> I'm not understanding this sentence. According to your output, you got 100 commits when you requested the LastPage (Page=19).
In your code, you never updated listCommitOpts.Page = 2 so you never asked for page 2.

Sorry I didn't make it clear. It's actually another problem I met that related to the link header. I'll find a case to reproduce the problem.

---

Case coming. So on page 1, we get `LastPage` is page 3, but actually we did not get any contents on page 3. However, page 2 is actually the last page ( amount not fulfill the 100 buckets ).
```
package main

import (
	"context"
	"fmt"

	"github.com/google/go-github/v33/github"
	"golang.org/x/oauth2"
)

func main() {
	ctx := context.Background()

	client := github.NewClient(nil)

	owner := "apache"
	repo := "kafka"
	author := "junrao"
	listOpts := github.ListOptions{PerPage: 100}

	//Get first page
	listCommitOpts := &github.CommitsListOptions{Author: author, ListOptions: listOpts}
	commits, resp, err := client.Repositories.ListCommits(ctx, owner, repo, listCommitOpts)
	if err != nil {
		panic(err)
	}
	fmt.Printf("commits num: %d\n", len(commits))
	fmt.Printf("First page: %#v\n", resp)

	//Get page 2
	listCommitOpts.Page = 2
	commits, resp, err = client.Repositories.ListCommits(ctx, owner, repo, listCommitOpts)
	if err != nil {
		panic(err)
	}
	fmt.Printf("commits num: %d\n", len(commits))
	fmt.Printf("Last page: %#v\n", resp)

	//Get page 3
	listCommitOpts.Page = 3
	commits, resp, err = client.Repositories.ListCommits(ctx, owner, repo, listCommitOpts)
	if err != nil {
		panic(err)
	}
	fmt.Printf("commits num: %d\n", len(commits))
	fmt.Printf("Last page: %#v\n", resp)
}
```

And the result
```
commits num: 100
First page: &github.Response{Response:(*http.Response)(0xc000160120), NextPage:2, PrevPage:0, FirstPage:0, LastPage:3, NextPageToken:"", Rate:github.Rate{Limit:5000, Remaining:4993, Reset:github.Timestamp{Time:time.Time{wall:0x0, ext:63752067716, loc:(*time.Location)(0xa71ec0)}}}}
commits num: 92
Last page: &github.Response{Response:(*http.Response)(0xc0004c0000), NextPage:0, PrevPage:1, FirstPage:1, LastPage:0, NextPageToken:"", Rate:github.Rate{Limit:5000, Remaining:4992, Reset:github.Timestamp{Time:time.Time{wall:0x0, ext:63752067716, loc:(*time.Location)(0xa71ec0)}}}}
commits num: 0
Last page: &github.Response{Response:(*http.Response)(0xc0004c0120), NextPage:0, PrevPage:2, FirstPage:1, LastPage:0, NextPageToken:"", Rate:github.Rate{Limit:5000, Remaining:4991, Reset:github.Timestamp{Time:time.Time{wall:0x0, ext:63752067716, loc:(*time.Location)(0xa71ec0)}}}}
```

**Comment by gmlewis** [comment]
OK, thanks, @Yiyiyimu .
As explained in #1826, we don't track GitHub issues here, so I'm closing this one.
Feel free to add a comment when you hear back from GitHub tech support.

**Comment by gmlewis** [comment]
Relates to: #1848.
