### ISSUE TITLE
Release timeline for v34

### ISSUE THREAD

**Issue by billjh** [google/go-github#1829]
Hi thanks for this wonderful library, and I am looking forward to using the new self-hosted runner group API where the support has been merged in #1804. 

Is there a release to include this feature any time soon? Since the latest release v33 dated back in Dec 2020.

**Comment by gmlewis** [comment]
Hi @billjh - as of #1280, all releases (major, minor, and patch) are on-demand.

We had one other request just this morning, so this afternoon I will be working on a new major release (v34). Hopefully it will be read to use tonight or early tomorrow morning.

**Comment by gmlewis** [comment]
Hi @billjh - https://github.com/google/go-github/releases/tag/v34.0.0 has been released.
