### ISSUE TITLE
Add support for pull_request_target webhook event

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#1834]
GitHub API documentation:
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target

As mentioned in #1619, this webhook event needs to be supported.

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by ganboonhong** [comment]
Hi @gmlewis, I would like to work on this. 😄
Could you please assign it to me? Thanks.

**Comment by gmlewis** [comment]
Thank you, @ganboonhong !
It is yours. 😁

**Comment by jhlegarreta** [comment]
@ganboonhong thanks for having addressed this :100:; @gmlewis thanks for the support :+1: !
