### ISSUE TITLE
Audit Log API Returns Non-Standard Link Header

### ISSUE THREAD

**Issue by lindluni** [google/go-github#1848]
For tracking purposes, I've requested information on how they intend to handle this:

While working with the beta release of the `google/go-github` SDK I noted that pagination was not working for this API. After digging into the SDK I discovered the reason for this was that the audit-log API does not return traditional page parameters in the link array of the header. For example this query:

```
curl -v -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" https://api.github.com/orgs/lindluni-enterprise/audit-log > /dev/null
```

Returns this link header:

```
link: <https://api.github.com/organizations/80307827/audit-log?after=MS42MTUzMzYzNzg4MzNlKzEyfFlBdkVhclBZR21reGtQMG5uRng4bVE%3D&before=>; rel="next"
```

Which unlike the traditional link headers such as this:

```
link: <https://api.github.com/organizations/<id trunc>/repos?page=2>; rel="next", <https://api.github.com/organizations/<id trunc>/repos?page=124>; rel="last"
```

The audit log API does not return a page, it returns the traditional graphql `After` and `Before` fields. This is despite the fact the API documentation states that the API accepts a page parameter. If I do in fact include a page parameter, such as this query:

```
 curl -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/orgs/<org trunc>/audit-log?page=1"
```

The resultant link header does include the page property:

```
https://api.github.com/organizations/<org trunc>/audit-log?page=1&after=MS42MTcxNjQ3MzUxZSsxMnxNR1h4NFpmTUh6aEFyZGFQVWlWUzhn&before=
```
However no matter what page I pass in it returns the same dataset, and the page property returned is whatever I pass in.

**Comment by gmlewis** [comment]
Relates to: #1825.

**Comment by gmlewis** [comment]
As I mentioned in #1825, this appears to be a GitHub bug and GitHub tech support needs to be contacted and asked why this is happening.  Please report back here once you find out the answer, but in general, this repo does not track GitHub API bugs.

**Comment by lindluni** [comment]
I'll track the information in #1825

**Comment by Yiyiyimu** [comment]
@lindluni FYI, I've submitted a ticket to Github Support on this problem, and I was told the bug is confirmed but there would be no ETA to fix it.
