### ISSUE TITLE
switch tests to use github.com/google/go-cmp package

### ISSUE THREAD

**Issue by willnorris** [google/go-github#1851]
#1846 calls out not using `reflect.DeepEqual` for comparing error values, but in reality we shouldn't be using it all. https://pkg.go.dev/github.com/google/go-cmp/cmp is designed to be a much safer alternative, so we should use that for tests.

**Comment by willnorris** [comment]
and just to be clear, we should use go-cmp for all of our non-error values (of which there appear to be 600+ comparisons?!).  Switching to go1.13's `errors.Is` is the right change for errors.

**Comment by photongupta** [comment]
@willnorris Can I start working on this?

**Comment by willnorris** [comment]
have at it!  (With so many instances, you might want to do a global find and replace, or use `gofmt -r`)

**Comment by sagar23sj** [comment]
Hi @photongupta. Are You Still working on this issue.
