### ISSUE TITLE
fix pkg.go.dev link

### ISSUE THREAD

**Issue by sanposhiho** [google/go-github#1855]
Hello 👋
Thank you for developing such a great tool!

The link on GitHub is for v34, please fix it.(to v35) 🙏 

![S__103194626](https://user-images.githubusercontent.com/44139130/115103129-80caa700-9f8a-11eb-9f42-add9f4e289bb.jpg)

https://pkg.go.dev/github.com/google/go-github/v34/github

**Comment by gmlewis** [comment]
Fixed. Thank you, @sanposhiho !
