### ISSUE TITLE
go generate broken when adding map[string]bool

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#1866]
In #1864, I asked that a new parameter be changed from `*map[string]bool` to `map[string]bool` since `map` is already a reference-type and shouldn't need a pointer to it.

However, this change broke the `go generate ./...` tools and needs to be fixed.

Eventually, we should change all `*map...` to `map...` but that can be a separate issue: #1865.

**Comment by derekjobst** [comment]
👍🏻
