### ISSUE TITLE
Star event is missing events

### ISSUE THREAD

**Issue by jloh** [google/go-github#1868]
Hi all. The Star event is missing the `sender`, `repository` and `organization` fields that come in the [webhook payload](https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#star) from GitHub:

https://github.com/google/go-github/blob/b3962edc2585434a67e90f9cecf31b5673ae1c6b/github/event_types.go#L909-L919

I'm happy to make the changes to this type myself if a PR would be accepted.

Thanks for the excellent library! It does absolutely everything!

**Comment by gmlewis** [comment]
Thank you, @jloh !
It is yours. 😁

**Comment by gmlewis** [comment]
If this is your first PR, please read through our `CONTRIBUTING.md` document.
