### ISSUE TITLE
Support organization permission changes

### ISSUE THREAD

**Issue by willnorris** [google/go-github#187]
Announcement: https://developer.github.com/changes/2014-12-08-organization-permissions-api-preview/

Tasks:
- [x] allow fetching org repos from List Repositories endpoint (patch: #200)
- [x] update Org Membership methods to take a username argument (they currently only work with the authenticated user)
- [x] add `role` field to `ListMembersOptions`
- [x] add docs to `Membership.Role` field

----

### API changes for working with new org permissions 
Announcement: https://developer.github.com/changes/2015-06-24-api-enhancements-for-working-with-organization-permissions/

(This probably overlaps somewhat with the list above)

#### Team permissions
- [x] Add "permission" parameter to "Add team repository" method
- [x] Ensure "List team repositories" method has "permission" field
- [x] Ensure "Check if team manages repo" method has "permission" field
- [x] Update docs for "permission" parameter on "create team" and "edit team" methods

#### Team privacy
- [x] Add "privacy" parameter to "create team" and "edit team" methods
- [x] Add "privacy" field to Team type

#### Team maintainers
- [x] Add "role" parameter to "add team membership" method
- [x] Add "role" parameter to "list team members" method
- [x] Add "role" field to Membership type for "get team membership" and "add team membership" methods

#### Filter org members by role
- [x] Add "role" parameter to "list org members" method

#### Repository collaborators
- [x] Ensure "add user as collaborator" method works for org repos.  Also add "permission" parameter and document as being valid only for org-owned repos.
- [x] Add "permissions" field to "list collaborators" method

**Comment by captncraig** [comment]
#200 provides a way to support organization repos in the List Repositories endpoint.

**Comment by willnorris** [comment]
thanks for starting on the ListRepositories changes.  I've update the issue to list some of the other things that I think need to happen for this as well if you (or anyone else) want to tackle those.

**Comment by willnorris** [comment]
missed adding ref on commits 2b11c0d910bd9e1a4d9276371ae0606006d3eb44 and 4476aa45b5f735de27fd5e87fb3d9eaf831c9248

**Comment by willnorris** [comment]
Pretty sure this is now all covered so marking as closed.
