### ISSUE TITLE
Parse `reviewed` event object `state` property returned by Timeline Events API

### ISSUE THREAD

**Issue by campesel** [google/go-github#1885]
The Timeline Events API can return a `reviewed` event object when listing events for a pull request. One of the properties of [this object](https://docs.github.com/en/developers/webhooks-and-events/events/issue-event-types#reviewed) is `state`, which tells you the state of a submitted review.

The values `state` can have are:

- `commented`
- `changes_requested`
- `approved`

I'd like to add this field to the `Timeline` struct defined in `issues_timeline.go` to make it possible to tell the state of a review when listing pull request events.

**Comment by gmlewis** [comment]
Fixed by #1886. Closing.
