### ISSUE TITLE
How do I check whether a ref has a status at all with CombinedStatus?

### ISSUE THREAD

**Issue by cbrgm** [google/go-github#1887]
Hello all,

I would like to check with the go-github client if any kind of CI pipeline has been set up in my repository or not.

For this I use a [CombinedStatus](https://github.com/google/go-github/blob/master/github/repos_statuses.go#L89) struct and check the [*State](https://github.com/google/go-github/blob/master/github/repos_statuses.go#L92) string attribute.

According to the [docs](
https://docs.github.com/en/rest/reference/repos#get-the-combined-status-for-a-specific-reference), the`*State` can be either `pending`,`failure` or `success`. Apparently, for repositories where no state has been set, it seems like `pending` is returned as the default.

Shouldn't there be another state `notFound` or similar?

**Comment by gmlewis** [comment]
Hi @cbrgm ,

That's a great question for GitHub tech support.
This repo is a client library used to access the GitHub v3 API using Go but is maintained by volunteers and is not officially associated with the GitHub organization.

I'll leave this ticket open for a while in case someone wishes to comment, but your best bet is to contact GitHub tech support directly.

**Comment by cbrgm** [comment]
Thanks for your response @gmlewis !

**Comment by gmlewis** [comment]
Closing inactive issue.  Feel free to comment if you hear back from GitHub Tech Support.
