### ISSUE TITLE
Support Go 1.17 compiler toolchain

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#1890]
In #1889, a simple typo fix in the `README.md` file demonstrated that the Go 1.17 compiler toolchain is now modifying the formatting of `// +build` lines.

We will need to fix this before we are able to continue merging PRs.

**Comment by gmlewis** [comment]
https://tip.golang.org/doc/go1.17
https://go.googlesource.com/proposal/+/master/design/draft-gobuild.md

**Comment by willnorris** [comment]
Should be as simple as adding the new syntax.  From https://tip.golang.org/doc/go1.17:

> As of this release, the new syntax is fully supported, and all Go files should be updated to have both forms with the same meaning.

**Comment by willnorris** [comment]
Though I'm very surprised that actions/setup-go is included a beta release for the "1.x" go version.  I would expect that to be the latest stable release.  I seem to recall running into this before, so will look into that separately.

**Comment by willnorris** [comment]
fixed the "1.x" stable release issue in 77dd0eb64ad232f78c67fd86fe4b84be887bab5b
