### ISSUE TITLE
checkRateLimitBeforeDo prevents roundtripper from waiting

### ISSUE THREAD

**Issue by gauntface** [google/go-github#1920]
I've been trying to find a way to write a generic RoundTripper that would examine GitHub headers and/or the go-github errors to detect when quota has run out and wait for the quota reset.

Because `checkRateLimitBeforeDo` get's called and returns early, there isn't a way for the RoundTripper to handle waiting / retries.

The benefit of doing this in the RoundTripper is that it'll apply to all API calls, but without it, each call needs to be wrapped with retry and quota logic.

Is there another approach I can take for this?

**Comment by gmlewis** [comment]
What if we were to add a new `WithContext` that would cause the call to wait for the next `Reset` time?

**Comment by gmlewis** [comment]
Friendly ping, @gauntface - will close in a couple weeks if there is no further interest/activity.

**Comment by gauntface** [comment]
Sorry I'm going to close this. Still relevant but work is hogging up time and we've got around the issue by watching for the error in our roundtripper.
