### ISSUE TITLE
Pull request comment is not shown until page is reloaded

### ISSUE THREAD

**Issue by leodamasceno** [google/go-github#1932]
Hello,
I am trying to add a comment to a pull-request using the following code:
```
    _, _, err = client.Issues.CreateComment(
        context.Background(),
        "myorg",
        "myrepo,
        pr_number,
        &github.IssueComment{Body: &body},
    )
```
The comment is added to the pull-request, but I can only see it if I reload/refresh the page.

Is there something I can do to avoid the page refresh?

Thanks

**Comment by gmlewis** [comment]
This repo is a client library for the [GitHub v3 REST API](https://docs.github.com/en/rest) and has nothing to do with the GitHub web-based user interface.

So no, there is nothing this repo can provide that will help you prevent a browser page refresh.
