### ISSUE TITLE
Export parts of `github/messages.go`

### ISSUE THREAD

**Issue by m19c** [google/go-github#1944]
In order to use `github.com/google/go-github` in projects using a different http library (such as `fasthttp`), it would be great to export several parts of the `messages.go` file.

currently only `ValidatePayload`, `WebHookType`, `DeliveryID` and `ParseWebHook` are exposed.

Suggestion:

- Export `signatureHeader`, `eventTypeHeader` and `deliveryIDHeader` constant.
- Introduce a new function called `ValidatePayloadFrom(body io.Reader, sig string, secretKey []byte)`.

This change enables the possibility to use `google/go-github` even with http servers like `fiber`.

I would love to prepare a pull-request, if needed.

**Comment by gmlewis** [comment]
That sounds like a useful and valuable addition, @m19c.
Bonus points if you can implement it without breaking the API.  :joy:

**Comment by m19c** [comment]
That's the goal. I'll create a pull-request in the next few days.
