### ISSUE TITLE
Problem creating a deployment

### ISSUE THREAD

**Issue by victorcoder** [google/go-github#197]
The problem is in the definition of the `RequiredContexts` field in `DeploymentRequest` struct.

As per create deployment docs:

> Optional array of status contexts verified against commit status checks. If this parameter is omitted from the parameters then all unique contexts will be verified before a deployment is created. To bypass checking entirely pass an empty array. Defaults to all unique contexts.

The `omitempty` in [this struct field](https://github.com/google/go-github/blob/master/github/repos_deployments.go#L33) makes impossible to bypass the checkings.

**Comment by willnorris** [comment]
sounds like we need to use a `*[]string`, similar to what was needed in #181.  Want to send a pull request?

**Comment by victorcoder** [comment]
@willnorris yeah it looks the same. Sure, I'll craft the PR and tests

**Comment by parkr** [comment]
Fixed?

**Comment by willnorris** [comment]
oops, yeah.  Fixed in b2f8d2ec4070d3535b493308749e1c1f5c6c8e55
