### ISSUE TITLE
Repository organization is nil

### ISSUE THREAD

**Issue by serain** [google/go-github#1999]
I'm trying to list a user's repos and get the organizations they belong to using [go-github](https://github.com/google/go-github).

These repositories belong to an organization, but the organization values seem to be `nil`.

Code:

```
import "github.com/google/go-github/v37/github"

func GetClient(token) *GitHub {
	ctx := context.Background()
	ts := oauth2.StaticTokenSource(
		&oauth2.Token{AccessToken: token},
	)
	tc := oauth2.NewClient(ctx, ts)
	client := github.NewClient(tc)

	return client
}

func main() {
	client := GetClient("TOKEN")

	repos, _, err := client.Repositories.List(context.TODO(), "", nil)
	if err != nil {
		log.Fatal(err)
	}

	for _, repo := range repos {
		println(*repo.Name)
		org := repo.GetOrganization()
		println(org)
		println(repo.Organization)
    }
}
```

Output:

```
api
0x0
0x0
api-inserter
0x0
0x0
bbprograms
0x0
0x0
console-api
0x0
0x0
console-spa
...
```

I know for a fact that these repos are part of an organization the user belongs to and I expected `repo.Organization` to be non-nil.

**Comment by gmlewis** [comment]
The best way to debug issues like this is to call the GitHub v3 API directly using `curl` and check the responses that you are getting. If there is then a discrepancy between what it returns and what this client library returns, we can see exactly where the problem lies.

**Comment by gmlewis** [comment]
Closing issue. Feel free to comment or re-open if you find a discrepancy.
