### ISSUE TITLE
Authorizations Service does not get permission scopes for Personal access token.

### ISSUE THREAD

**Issue by mitalipaygude** [google/go-github#2022]
I was trying to use the `go-github` to determine the permissions a Github personal access token has, but the only functionality provided by Authorizations service is to check if an Oauth token is valid.

Code: https://github.com/google/go-github/blob/master/github/authorizations.go#L147

Is there any functionality to check the validity and permissions for the personal access token in this library? If not, are there plans to add those anytime soon?

**Comment by gmlewis** [comment]
No. The GitHub v3 API does not provide and endpoints that identify the permissions for a personal access token.
Therefore, this client library that makes it easy to call GitHub v3 API endpoint has no way of doing this either.

If you want this functionality, you might consider contacting GitHub technical support and asking for a feature request.
