### ISSUE TITLE
Missing organization repositories

### ISSUE THREAD

**Issue by housingdreams** [google/go-github#2026]
I am trying to look at an organization with dozens of private and public repositories. However, using this API I only see 8 returned (mixed: a few public and private). [go docs link](https://pkg.go.dev/github.com/google/go-github/v37/github#RepositoriesService.ListByOrg) says pagination should return 30 by default and I'm using the [exact demo code](https://pkg.go.dev/github.com/google/go-github/github#hdr-Pagination)

```
func loadAllRepos(ctx context.Context, client *github.Client, organizationName string) ([]*github.Repository, error) {
	opt := &github.RepositoryListByOrgOptions{
		ListOptions: github.ListOptions{PerPage: 30},
	}
	// get all pages of results
	var allRepos []*github.Repository
	for {
		repos, resp, err := client.Repositories.ListByOrg(ctx, organizationName, opt)
		if err != nil {
			return nil, err
		}
		allRepos = append(allRepos, repos...)
		if resp.NextPage == 0 {
			break
		}
		opt.Page = resp.NextPage
	}

	fmt.Printf("total repos found: %d\n", len(allRepos))
	return allRepos, nil
}
```

I tried calling the endpoint directly and only see 8 as well. There are missing repos from the API.

```
https://api.github.com/orgs/NAME/repos?access_token=ghp_3...
```

This doesn't seem to be an issue with this codebase, but I'm hoping for direction here. Any ideas what I might be doing wrong?

**Comment by gmlewis** [comment]
Please make sure that the account you used to make the personal access token has access to the private repos and then it should work just fine.

**Comment by housingdreams** [comment]
Yes, I can see all of them listed in the interface (https://github.com/NAME/) when using this account which the personal access token has been created for. I can only see a few of them when using the api token though.

**Comment by housingdreams** [comment]
My mistake, the repos returned were all public. Playing with the personal access token permissions settings I was able to finally show all the private repositories.
