### ISSUE TITLE
Issue with creating PR review comments

### ISSUE THREAD

**Issue by Giles-Billenness** [google/go-github#2027]
Hi, I am trying to make a prototype that adds a code review comment to a pr.

```
githubAPIKey := os.Getenv("GITHUB_API_KEY")
ctx := context.Background()
ts := oauth2.StaticTokenSource(
&oauth2.Token{AccessToken: githubAPIKey},
)
tc := oauth2.NewClient(ctx, ts)
client := github.NewClient(tc)
OWNER := os.Getenv("OWNER")
REPO := os.Getenv("REPO")
PULLREQNUM, stringToIntError := strconv.Atoi(os.Getenv("PULL_REQ_NUMBER"))
errorReport(stringToIntError)

path := "README.md"
body := "this is a comment body"
pos1 := 1
Review := &github.PullRequestReviewRequest{
Comments: []*github.DraftReviewComment{{
Path:     &path,
Body:     &body,
Position: &pos1,
}}}

pullRequestReview, githubresponce, err := client.PullRequests.CreateReview(ctx, OWNER, REPO, PULLREQNUM, Review)
if err != nil {
log.Fatal("\nPullRequests.CreateReview returned error: : ", err, "\n")
}
log.Fatal("\ngithub response is: ", githubresponce, "\n")
log.Println("\ngithub-commenter: Created GitHub PR Review comment", *pullRequestReview.ID, "\n")
```

When I try running this more than once I get this back (I have to manually remove the previous comment added to run it successfully again):
`PullRequests.CreateReview returned error: : POST https://api.github.com/repos/Giles-Billenness/testpr1/pulls/1/reviews: 422 Unprocessable Entity [{Resource: Field: Code: Message:}]`
Even though you can comment on the same code line multiple times in the web client

**Comment by Giles-Billenness** [comment]
Is there a more simple way to comment on code on a PR? In the case, you want to run it multiple times or have it remove/update the previous one?

**Comment by gmlewis** [comment]
Did you try `UpdateReview` and `DeleteReview`?

https://pkg.go.dev/github.com/google/go-github/v37/github#PullRequestsService.UpdateReview

**Comment by Giles-Billenness** [comment]
I will now thank you. It just seemed strange that you cant create multiple reviews, and the response isn't particularly informative (it took me a while to find this was the issue).

**Comment by Giles-Billenness** [comment]
by DeleteReview did you mean DeletePendingReview?
also im trying to use updateReview now, 
`client.PullRequests.UpdateReview undefined (type *github.PullRequestsService has no field or method UpdateReview)`

**Comment by gmlewis** [comment]
As written in our [README.md](https://github.com/google/go-github/blob/master/README.md#installation), you will want to type this:

```bash
go get github.com/google/go-github/v37
```

for the latest release, or

```bash
go get github.com/google/go-github/v37@master
```

if you want the top-of-trunk latest.

**Comment by Giles-Billenness** [comment]
AH! Now I'm getting some better error responses

**Comment by Giles-Billenness** [comment]
It's probably a limitation but GitHub enterprise-server@2.21 doesn't seem to support deleting pending review comments
