### ISSUE TITLE
Feature: implement SCIM

### ISSUE THREAD

**Issue by hazcod** [google/go-github#2030]
https://docs.github.com/en/rest/reference/scim

Would be nice to be able to query for member usernames based on their email address.

**Comment by gmlewis** [comment]
Thank you, @hazcod !

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

**Comment by gmlewis** [comment]
Since this is a new service in its own area of documentation on the GitHub dev website, I think this should have is own new `SCIMService` and its own new `scim_*.go` set of files.

**Comment by krishnaindani** [comment]
Is this issue up for grab/unassigned, I would like to check if I can contribute to it?

**Comment by gmlewis** [comment]
Thank you, @krishnaindani !
It is yours.

**Comment by krishnaindani** [comment]
Thank you, I will post the questions here as I get them while working.

**Comment by krishnaindani** [comment]
I would like to check for https://docs.github.com/en/rest/reference/scim#update-an-attribute-for-a-scim-user call, what would we use for the Parameters Operations Value, it looks to be `object or array or string(value (object or array or string))`.

I am confused here, could you be able to guide me?

**Comment by gmlewis** [comment]
The link you gave points to the SCIM specification here: https://datatracker.ietf.org/doc/html/rfc7644#section-3.5.2
which says:

> The body of an HTTP PATCH request MUST contain the attribute
   "Operations", whose value is an array of one or more PATCH
   operations.  Each PATCH operation object MUST have exactly one "op"
   member, whose value indicates the operation to perform and MAY be one
   of "add", "remove", or "replace".  The semantics of each operation
   are defined in the following subsections.

I don't have time now to read all the subsections... however, from a quick scan, it looks like you might want to make the `value` be of type `json.RawMessage`.  We have _many_ examples of using `json.RawMessage` in this repo which should help.

**Comment by krishnaindani** [comment]
Thank you, I will go though this.

**Comment by davidkarlsen** [comment]
@krishnaindani hey - how is this going, we'd like to use this feature for https://github.com/redhat-cop/group-sync-operator/issues/111

**Comment by krishnaindani** [comment]
> @krishnaindani hey - how is this going, we'd like to use this feature for [redhat-cop/group-sync-operator#111](https://github.com/redhat-cop/group-sync-operator/issues/111)

I have been working on this last week, couldn't get on this week. I will push it in few days.
