### ISSUE TITLE
[BUG] Can't update the default branch on a repo

### ISSUE THREAD

**Issue by PaulSonOfLars** [google/go-github#2040]
The github API has a weird edge case where changing the default branch also requires passing the repository name.
This is undocumented, but has been noticed as behaviour [here](https://github.community/t/cannot-change-default-branch/13728/13). 

Given that this bug has now existed for a while, its safe to assume github have no intention of fixing it. Is this something that could be feasible from the library instead?

**Comment by gmlewis** [comment]
> Is this something that could be feasible from the library instead?

So I'm not completely clear how you would want this library to address the issue.

Currently, a user can fill in the `Name` field in the [`Repository`](https://github.com/google/go-github/blob/master/github/repos.go#L27) struct and call the [`RepositoriesService.Edit`](https://github.com/google/go-github/blob/master/github/repos.go#L486-L489) endpoint.

I can see two paths forward to address this:

1. Add a comment to the `Edit` endpoint to explain the situation (less drastic), or
2. Fill in the `Name` field if it is not populated in the `Edit` call itself (more drastic and may cause problems in other situations, possibly?)

Obviously, I'm leaning toward option 1, but am willing to discuss alternatives.

**Comment by gmlewis** [comment]
And by the way, I would not consider this issue a bug of this repo.

**Comment by PaulSonOfLars** [comment]
Very well, just wanted to make a suggestion to improve usability regarding undocumented github "features".
