### ISSUE TITLE
"go run ./update-urls/main.go" fails with "unhandled X receiver type: *ast.CallExpr"

### ISSUE THREAD

**Issue by anthonyfok** [google/go-github#2057]
While trying to follow the instructions in the header comments of update-urls/main.go:

```
// Usage (from go-github directory):
//   go run ./update-urls/main.go
//   go generate ./...
//   go test ./...
//   go vet ./...
```

I encountered the following error at the very first step:

```
$ go run ./update-urls/main.go
2021/08/20 23:06:44 processCallExpr: unhandled X receiver type: *ast.CallExpr
exit status 1
```

Tested with go1.15.15, go1.16.7 and go1.17.

Might be related to #2056?

Thanks in advance!

**Comment by gmlewis** [comment]
`update-urls` is a maintainer tool only.  Users of the repository are not expected to run it.
Thank you for the alert, though.
I will investigate.
Closing issue.
