### ISSUE TITLE
Adding support for enabling auto merge on repositories

### ISSUE THREAD

**Issue by Richard-de-Vries** [google/go-github#2073]
Hey! 

I'm using the github terraform plugin which makes use of this api. I would like to  add support for the enabling of automatic merges on a repository level. integrations/terraform-provider-github#649
I'm new to open source but i'm willing to make a PR.

**Comment by gmlewis** [comment]
> I'm new to open source but i'm willing to make a PR.

Sounds great, @Richard-de-Vries ! Thank you.

Please be sure to check out our CONTRIBUTING.md guide.
