### ISSUE TITLE
Does not to be any support for the Packages API

### ISSUE THREAD

**Issue by Cyb3r-Jak3** [google/go-github#2075]
I do not see any support for the [Packages API](https://docs.github.com/en/rest/reference/packages). I don't know if I miss it somewhere though.

If it does not exist then I would be happy to work on it.

**Comment by gmlewis** [comment]
> If it does not exist then I would be happy to work on it.

You are right... thank you, @Cyb3r-Jak3 !  It is yours.
Please take a look at our CONTRIBUTING.md file for tips on how to contribute to this repo.

**Comment by Cyb3r-Jak3** [comment]
@gmlewis looking into it and I see a potential issue. `Package` is already defined in [packages.go](https://github.com/google/go-github/blob/88b13f9ab1027c88609e6740acdc1710106f908e/github/packages.go#L9) this appears to be for the package webhook and contains different JSON than the package API. I'd like to rename `Package` to something like `PackageWebhook` and create a new `Package` struct but I don't want to break backward compatibility. 

What do you think is the best path forward?
