### ISSUE TITLE
Feature: Check if automated security fixes are enabled for a repository

### ISSUE THREAD

**Issue by rvdh** [google/go-github#2080]
In https://github.com/google/go-github/pull/1188 the endpoint was added to enable or disable automated security fixes.

However, there seems to be no way to check the current status of this setting. This is required to implement https://github.com/integrations/terraform-provider-github/issues/272.

I also noticed on the [REST api documentation page](https://docs.github.com/en/rest/reference/repos) there doesn't seem to be an API endpoint to check this (there is one for [checking vulnerability alerts](https://docs.github.com/en/rest/reference/repos#check-if-vulnerability-alerts-are-enabled-for-a-repository)).

Is it possible to implement this feature? If not, where do I create an issue for making such an endpoint available?

**Comment by gmlewis** [comment]
> I also noticed on the [REST api documentation page](https://docs.github.com/en/rest/reference/repos) there doesn't seem to be an API endpoint to check this (there is one for [checking vulnerability alerts](https://docs.github.com/en/rest/reference/repos#check-if-vulnerability-alerts-are-enabled-for-a-repository)).
> 
> Is it possible to implement this feature? If not, where do I create an issue for making such an endpoint available?

Thank you for the issue, @rvdh .

Since this repo is "simply" a Go client library to the GitHub v3 REST API, if the API itself doesn't provide a feature, then this repo can not help with its implementation, unfortunately.

Your best bet is to contact GitHub tech support and request that the feature be added.

On this page: https://docs.github.com/en/rest they have a "Contact support" button you can use.

Feel free to report back here once you find out the status of your request.

**Comment by rvdh** [comment]
> 
> Your best bet is to contact GitHub tech support and request that the feature be added.
> 

Thanks, I've done this just now. Will update this issue when I hear back from them.

**Comment by rvdh** [comment]
GitHub response:

> We have an open feature request for this and have added your feedback.
> We cannot say if or when this will be implemented. Keep an eye on the GitHub blog and GitHub Public Roadmap for information on when and if this makes it into the product.

So I guess.. time will tell? I'm not sure wether this issue should be closed now or not.

**Comment by gmlewis** [comment]
Thank you for reporting back, @rvdh .

I'm fine to leave this issue open. I'll tag it that we are waiting. 😁
