### ISSUE TITLE
Support for Apps Webhook configuration endpoints

### ISSUE THREAD

**Issue by rpelliard** [google/go-github#2095]
Hello,

I saw that there is support for configuring [Repository webhooks](https://docs.github.com/en/rest/reference/repos#webhooks) and [Organization webhooks](https://docs.github.com/en/rest/reference/orgs#webhooks), but it looks like [AppsService](https://pkg.go.dev/github.com/google/go-github/v34/github#AppsService) has no support for the endpoints allowing to get / update the webhook configuration of an app: https://docs.github.com/en/rest/reference/apps#webhooks.

Can you confirm that this is not supported ? Is that something that you would consider adding support for ? If yes, I'd be happy to work on a PR for this !

**Comment by gmlewis** [comment]
> Can you confirm that this is not supported ? Is that something that you would consider adding support for ? If yes, I'd be happy to work on a PR for this !

I confirm your assertion. :smile:
Yes, I think that would be perfectly reasonable to add to this repo since it it part of the GitHub v3 API.
One interesting challenge for your PR will be that we currently do not support sending a JWT, so you will need to add a nice and convenient way of doing so.

Thank you, @rpelliard !

**Comment by rpelliard** [comment]
@gmlewis Thanks for confirming :)

About the JWT, would it be reasonable to leave the responsibility of authentication to the underlying transport, like what is used for requests as installations / as users ? e.g. using https://github.com/bradleyfalzon/ghinstallation/blob/master/appsTransport.go#L46
I might be wrong, but it looks like for example, [this existing method](https://pkg.go.dev/github.com/google/go-github/v34/github#AppsService.GetInstallation) queries an endpoint that requires authentication as an app using a JWT

**Comment by gmlewis** [comment]
> About the JWT, would it be reasonable to leave the responsibility of authentication to the underlying transport, like what is used for requests as installations / as users ? e.g. using https://github.com/bradleyfalzon/ghinstallation/blob/master/appsTransport.go#L46
> I might be wrong, but it looks like for example, [this existing method](https://pkg.go.dev/github.com/google/go-github/v34/github#AppsService.GetInstallation) queries an endpoint that requires authentication as an app using a JWT

Ah, yes! Perfect. Thank you... Let's do that.
Please make sure to add a comment in your new methods showing how to authenticate.
