### ISSUE TITLE
branch_protection_rule event type not available

### ISSUE THREAD

**Issue by bhogatemadhura** [google/go-github#2098]
I was looking into the event - https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#branch_protection_rule

and couldn't find an associated event type under - 
https://github.com/google/go-github/blob/master/github/event_types.go

Is it missing ?

**Comment by gmlewis** [comment]
Yes, I believe you are correct. We have `GetBranchProtection` but we don't appear to support the event type.
Would you like to add it, or would you like me to open up this issue to other contributors to this repo so that they will add it?

**Comment by bhogatemadhura** [comment]
Thank you @gmlewis. I'll submit a change for it!
