### ISSUE TITLE
CI uses an older version of Go

### ISSUE THREAD

**Issue by kallydev** [google/go-github#2106]
Hi, why does `go.mod` already use Go **1.16**, but `tests.yml` still uses **1.15.x**? Should we update the CI config?

**Comment by gmlewis** [comment]
We attempt to CI test the most recent version of Go along with the prior version. We have not yet bumped it to v1.17.x and v1.16.x.

I'm not actually sure that the version declared in go.mod has much significance... but I should probably read up on that. I thought it was simply the version of Go used to create it.

**Comment by kallydev** [comment]
If go.mod is newer than the CI's version of Go, then the CI may fail to build because it is using a new function from a newer version of Go.

Ref https://golang.org/ref/mod#go-mod-file-go.

**Comment by gmlewis** [comment]
> If go.mod is newer than the CI's version of Go, then the CI may fail to build because the code is using a new function from a newer version of Go.
> 
> Ref https://golang.org/ref/mod#go-mod-file-go.

Interesting, as we've had no problems to date.

I'll bump the CI Go version today to use v1.17.x and v1.16.x and we should be good by just leaving go.mod alone.
