### ISSUE TITLE
http2 failure in `UploadAsset`

### ISSUE THREAD

**Issue by vchuravy** [google/go-github#2113]
We are using `ghr` to upload binary assets from Github to CI.

Currently I am seeing an increased failure rate:

```
Failed to upload one of assets: one of the goroutines failed: failed to upload asset: /tmp/jl_A641Uc/Clang_assert.v12.0.1.x86_64-linux-gnu-cxx11.tar.gz: failed to upload release asset: /tmp/jl_A641Uc/Clang_assert.v12.0.1.x86_64-linux-gnu-cxx11.tar.gz: Post https://uploads.github.com/repos/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/49230189/assets?name=Clang_assert.v12.0.1.x86_64-linux-gnu-cxx11.tar.gz: http2: Transport: cannot retry err [stream error: stream ID 117; REFUSED_STREAM] after Request.Body was written; define Request.GetBody to avoid this error
```

AFAIK `ghr` uses `UploadAsset`: https://github.com/tcnksm/ghr/blob/93494744e6930d13e5c052eac9ca64a6027779a4/github.go#L184 from https://github.com/tcnksm/ghr/blob/93494744e6930d13e5c052eac9ca64a6027779a4/github.go#L209

and the error looks like https://github.com/golang/go/issues/25009

**Comment by vchuravy** [comment]
Turned out that is was hiding the actual errors:

```
Failed to upload one of assets: one of the goroutines failed: failed to upload asset: /tmp/jl_kxYk28/Clang_assert.v12.0.1.aarch64-apple-darwin.tar.gz: failed to upload release asset: /tmp/jl_kxYk28/Clang_assert.v12.0.1.aarch64-apple-darwin.tar.gz: Post https://uploads.github.com/repos/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/49230189/assets?name=Clang_assert.v12.0.1.aarch64-apple-darwin.tar.gz: write tcp 128.30.92.237:33810->140.82.113.13:443: use of closed network connection
Failed to upload one of assets: one of the goroutines failed: failed to upload asset: /tmp/jl_kxYk28/Clang_assert.v12.0.1.x86_64-unknown-freebsd.tar.gz: failed to upload release asset: /tmp/jl_kxYk28/Clang_assert.v12.0.1.x86_64-unknown-freebsd.tar.gz: Post https://uploads.github.com/repos/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/49230189/assets?name=Clang_assert.v12.0.1.x86_64-unknown-freebsd.tar.gz: write tcp 128.30.92.237:33988->140.82.113.13:443: use of closed network connection
Failed to upload one of assets: one of the goroutines failed: failed to upload asset: /tmp/jl_kxYk28/Clang_assert.v12.0.1.aarch64-linux-gnu-cxx11.tar.gz: failed to upload release asset: /tmp/jl_kxYk28/Clang_assert.v12.0.1.aarch64-linux-gnu-cxx11.tar.gz: Post https://uploads.github.com/repos/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/49230189/assets?name=Clang_assert.v12.0.1.aarch64-linux-gnu-cxx11.tar.gz: write tcp 128.30.92.237:36032->140.82.114.14:443: write: broken pipe
```

**Comment by gmlewis** [comment]
Glad you found it. Closing issue.

**Comment by vchuravy** [comment]
I still think there is an issue here to be fixed. Upgrading to HTTP/2 shouldn't have swallowed these error messages.

**Comment by gmlewis** [comment]
Is anyone able to write a unit test that demonstrates the problem?

**Comment by wangyoucao577** [comment]
any update on this?

**Comment by caarlos0** [comment]
FWIW this happens occasionally for some goreleaser users as well (using v39).

 https://github.com/goreleaser/goreleaser/issues/2746

**Comment by cpanato** [comment]
having the same issue when using goreleaser

**Comment by blacktop** [comment]
Still getting this error

**Comment by Zangetsu38** [comment]
i have same, i using recreate but it said already exist...

>  
--> Uploading: app_compat_db.xml
Failed to upload one of assets: one of the goroutines failed: failed to upload asset: D:\a\compatibility\compatibility\app_compat_db.xml: failed to upload release asset: D:\a\compatibility\compatibility\app_compat_db.xml: POST https://uploads.github.com/repos/Vita3K/compatibility/releases/92110749/assets?name=app_compat_db.xml: 422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}]

**Comment by gmlewis** [comment]
According to the official documentation here: https://docs.github.com/en/rest/releases/assets?apiVersion=2022-11-28#upload-a-release-asset

> If you upload an asset with the same filename as another uploaded asset, you'll receive an error and must delete the old file before you can re-upload the new asset.

So I don't believe these reported errors are a fault of this client library, as the GitHub v3 API provides no apparent mechanism to overwrite an existing file using `UploadReleaseAsset`.

**Comment by ysmilda** [comment]
Running into the same issue, from what I gather the only "fix" is to wait and hope that this behaviour passes?

In my use case I create a release via `client.Repositories.CreateRelease` and with the release ID that I retrieve from there I try to upload a file using `client.Repositories.UploadReleaseAsset` after which I get an 
```
http2: Transport: cannot retry err [stream error: stream ID 1; PROTOCOL_ERROR; received from peer] after Request.Body was written; define Request.GetBody to avoid this error
``` 
error every single time (so far). Seeing the above comment mentions files with the same name, that is not the case here as no assets have been uploaded yet.
