### ISSUE TITLE
Help Me integrate YouTube Music App Android with Power Amp Pro EQ

### ISSUE THREAD

**Issue by HammaFist70** [google/go-github#2122]
It's not my SRTONG SUIT...Ya Knows Guys?

**Comment by gmlewis** [comment]
Strike two - @HammaFist70 - you know that this is the wrong place to post this issue.
Your first strike ( #2120 ) I closed.
On your third strike, I will ban you from this repo and report you to GitHub as a spammer.
Do some Google searches to find the appropriate place to ask your questions and stop spamming random repos.
