### ISSUE TITLE
Support for creating reaction for a release

### ISSUE THREAD

**Issue by viveknathani** [google/go-github#2194]
Hi everybody!
I found that [this](https://docs.github.com/en/rest/reference/reactions#create-reaction-for-a-release) endpoint is missing its implementation over here. Do the maintainers intend to cover it? If yes, can I work on it?

**Comment by gmlewis** [comment]
Thank you, @viveknathani - sounds good.  Yes, it is your to implement.
Please check out our CONTRIBUTING.md guide if you haven't contributed before.
