### ISSUE TITLE
PushEventCommit is not unmarshalled correctly

### ISSUE THREAD

**Issue by tchap** [google/go-github#220]
`PushEventCommit` does not contain `sha`, it contains `id`, hence `*PushEventCommit.SHA` always panics. Don't have time to fix it now, will get to this tomorrow unless it is fixed by someone else...

**Comment by tchap** [comment]
Well, what is that struct representing exactly? What I am using it for is the webhook payload, maybe it's not intended for that use case...

**Comment by parkr** [comment]
Use github.WebHookPayload like here: https://github.com/parkr/jekyll-build-server/blob/master/jekyll-build-server.go

**Comment by tchap** [comment]
Ah, my bad, overlooked that one. Thanks, @parkr !
