### ISSUE TITLE
Enable or disable Secret Scanning for a repository

### ISSUE THREAD

**Issue by yogur** [google/go-github#2204]
The library doesn't seem to support enabling or disabling Secret Scanning. This is doable through the REST API by sending a PATCH request and setting the `status` in the object `secret_scanning` to `enabled` or `disabled`. https://docs.github.com/en/rest/reference/repos#update-a-repository 

Is this planned to be added to the library?

**Comment by gmlewis** [comment]
I believe this was recently added in #2133:
https://github.com/google/go-github/blob/master/github/repos.go#L193

**Comment by yogur** [comment]
Thanks @gmlewis! I just noticed I was searching in the v34 codebase. 🤦🏻
