### ISSUE TITLE
Support External Groups API

### ISSUE THREAD

**Issue by kabesan** [google/go-github#2213]
Enterprise Managed Users (EMU) was GA on September.
https://github.blog/2021-09-30-enterprise-managed-users-generally-available-github-enterprise-cloud/

Team Synchronization API cannot be used with EMU.
External Groups API must be used instead.
https://docs.github.com/en/enterprise-cloud@latest/rest/reference/teams#external-groups

**Comment by kabesan** [comment]
Can I create PR?

**Comment by gmlewis** [comment]
> Can I create PR?

Yes, thank you, @kabesan !
This issue is yours.
