### ISSUE TITLE
Branch Protection Rule Event doesn't serialize installation fields

### ISSUE THREAD

**Issue by nyarly** [google/go-github#2214]
The BranchProtectionRuleEvent doesn't serialize `installation` object and its fields, which means that an App consuming that event cannot authenticate to act on the event itself. Github support indicated, and I've confirmed in delivery logs, that the `installation` field does appear, just as it does in every other webhook event, despite not being documented.

**Comment by gmlewis** [comment]
Thank you, @nyarly !
Would you like to create a PR to fix this, or would you like me to open up this issue to other contributors to this repo?

**Comment by nyarly** [comment]
I think I'm happy to put together a PR.

**Comment by nyarly** [comment]
c.f. #2216
