### ISSUE TITLE
TextMatches is not populated after a CodeResult is returned

### ISSUE THREAD

**Issue by rafeeJ** [google/go-github#2215]
Relevant to #109

I am trying to retrieve the code fragments from a CodeResult object after a successful Code search. 

However, it seems that the TextMatches array is empty:
<img width="419" alt="image" src="https://user-images.githubusercontent.com/1508676/144650527-1725107f-5a87-41e9-b6c8-880f35035904.png">

More information:
- I am currently on go-github v39
- I am calling this on a GitHub Enterprise instance

I am happy to help fix this issue if it is a confirmed bug, but will wait for confirmation.

**Comment by gmlewis** [comment]
Can you please try the same call as a `curl` command to see if the data you seek is indeed being returned?

**Comment by rafeeJ** [comment]
So I followed the GitHub guide, here: https://docs.github.com/en/rest/reference/search#text-match-metadata

Creating the Curl command, making sure to use the `'Accept: application/vnd.github.v3.text-match+json'` header, it returns the text_matches and thus the fragment. However, it does not return the data in Windows CMD - only in Postman and WSL Ubuntu.

**Comment by gmlewis** [comment]
OK, thanks, @rafeeJ . Go ahead and create a PR to fix the issue, and we'll take a look at it.

**Comment by rafeeJ** [comment]
Turns out I completely missed the SearchOptions struct.
