### ISSUE TITLE
Support Discussions webhook event

### ISSUE THREAD

**Issue by maruTA-bis5** [google/go-github#2221]
GitHub Discussions was out of beta in August 2021 (https://github.blog/2021-08-17-github-discussions-out-of-beta/).

Webhook event document is here: https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#discussion

**Comment by gmlewis** [comment]
Thank you, @maruTA-bis5 ! 
Would you like to create a PR to support this feature, or shall I open this issue up to our volunteer contributors to implement?

**Comment by maniSbindra** [comment]
Hi @gmlewis I would like to start contributing to this repository. Can I take up this issue?

**Comment by gmlewis** [comment]
> Hi @gmlewis I would like to start contributing to this repository. Can I take up this issue?

Thanks, @maniSbindra , but let's please wait until @maruTA-bis5 has a chance to answer my question above.

**Comment by gmlewis** [comment]
> My bad I assumed that you and @maruTA-bis5 communicated outside this discussion, and then you moved issue to good first issue. sorry about that.

No problem, @maniSbindra .  We'll give @maruTA-bis5  another day or so, then feel free to remind me if we don't hear back, and the issue can be yours.

**Comment by maruTA-bis5** [comment]
Hi @gmlewis @maniSbindra 
I'm sorry to have kept you waiting! 
I have no time to provide a PR for the next few weeks. So you can take up this issue, @maniSbindra.

**Comment by gmlewis** [comment]
Thank you, @maruTA-bis5 and no problem.
@maniSbindra - this issue is yours.
