### ISSUE TITLE
List/Get/Redeliver App Webhook Deliveries

### ISSUE THREAD

**Issue by pierce-m** [google/go-github#2225]
Any plans to support the additional APIs around App Webhook Deliveries? https://docs.github.com/en/rest/reference/apps#list-deliveries-for-an-app-webhook

I noticed the functionality around App Webhook configuration was implemented already

**Comment by gmlewis** [comment]
Yes, we can certainly add support for App Webhook Deliveries.
Do you want to create a PR, @pierce-m , or would you like me to open up this issue to one of our other contributors?

**Comment by pierce-m** [comment]
I'm happy to open one up! It'll take a little while though for me most likely.

**Comment by gmlewis** [comment]
> I'm happy to open one up! It'll take a little while though for me most likely.

Sounds great!  It's yours.  No rush. :smile:
