### ISSUE TITLE
ListPullRequestsWithCommit removed from API docs? 

### ISSUE THREAD

**Issue by mengmichael1** [google/go-github#2227]
👋 I am trying to use the `ListPullRequestsWithCommit` API. I noticed that information about it got removed from the API docs (it used to live in https://docs.github.com/en/rest/reference/repos#list-pull-requests-associated-with-a-commit). However, the API is still present within in the master go-github https://github.com/google/go-github/blob/ff33a554ef2c24c1710238b69942fe51e70d89da/github/pulls.go#L168-L194

What's the situation? Is it about to get deprecated? Is there a better/cleaner way of determining the pull request associated with a commit SHA (given that I know the owner and repo)?

**Comment by gmlewis** [comment]
Take a look at the top of the page for the first URL you listed. It says they have moved the documentation around.

It now appears to be here: https://docs.github.com/en/rest/reference/commits#list-pull-requests-associated-with-a-commit

**Comment by mengmichael1** [comment]
Ah thank you so much @gmlewis, I was combing through https://github.com/github/docs to get to the bottom of this, but now I see :D
