### ISSUE TITLE
add AppID field to ListCheckRunsOptions

### ISSUE THREAD

**Issue by dmitshur** [google/go-github#2231]
Both https://docs.github.com/en/rest/reference/checks#list-check-runs-for-a-git-reference and  https://docs.github.com/en/rest/reference/checks#list-check-suites-for-a-git-reference endpoints document the following query parameter:

Name | Type | In | Description
------|------|----|------
app_id | integer | query | Filters check suites by GitHub App `id`.

(Though the former is missing a description; perhaps it was added at a different time.)

The `ListCheckSuiteOptions` struct already has this field:

https://github.com/google/go-github/blob/fef3638524ab6c27e005edbe752c35b37f85894d/github/checks.go#L298

I wanted to report that there's an opportunity to add it to the `ListCheckRunsOptions` struct for listing check runs, because it's not there yet:

https://github.com/google/go-github/blob/fef3638524ab6c27e005edbe752c35b37f85894d/github/checks.go#L232-L239

**Comment by rojanDinc** [comment]
Hi I can help out.

**Comment by gmlewis** [comment]
> Hi I can help out.

Great, thank you, @rojanDinc !  It's yours.
