### ISSUE TITLE
Add changes to RepositoryEvent

### ISSUE THREAD

**Issue by ecrupper** [google/go-github#2232]
In the case of a repository being renamed, there is a `changes` block in the webhook payload. Since Go-GitHub doesn't have this field in their [RepositoryEvent struct](https://github.com/google/go-github/blob/ff33a554ef2c24c1710238b69942fe51e70d89da/github/event_types.go#L933-L944), one must create a custom struct to unmarshal the old name of the repository. 

I'm not sure if this is potentially a recurring issue for other repository events, but it would be nice to have Go-GitHub handle all the webhook information associated with renaming a repo.

**Comment by gmlewis** [comment]
Thank you, @ecrupper .

Since this appears to be [undocumented](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#repository) as far as I can tell,
do you have an example response that shows the data returned?  Or is `changes` just a string?

**Comment by ecrupper** [comment]
Thanks for the response! Here is an example payload for a repository being renamed: https://github.com/go-vela/server/blob/feat/handle-rename-repo/scm/github/testdata/hooks/repository_rename.json. It's very similar to the example payload in the documentation, apart from that `changes` block at the top.
