### ISSUE TITLE
Incorrect type in HookDelivery

### ISSUE THREAD

**Issue by pierce-m** [google/go-github#2234]
[Here](https://github.com/google/go-github/blob/1d9884e7ac8ca3c6d3d469af28af227fc773a246/github/repos_hooks_deliveries.go#L29) the `HookDelivery` defines the `InstallationID` as type `string`, but from the [documentation](https://docs.github.com/en/rest/reference/webhooks#list-deliveries-for-a-repository-webhook) it seems like a number. When testing I receive the error string 

```
json: cannot unmarshal number into Go struct field HookDelivery.installation_id of type string
```

Is this a possible bug?

**Comment by gmlewis** [comment]
> Is this a possible bug?

Yes, would you like to create a PR?
Thank you, @pierce-m !

**Comment by pierce-m** [comment]
Sure I'm happy to. Thanks!

**Comment by gmlewis** [comment]
> Sure I'm happy to. Thanks!

Awesome... thanks again!  It is yours. :smile:
