### ISSUE TITLE
Request: Support for dependabot repository secrets

### ISSUE THREAD

**Issue by liath** [google/go-github#2246]
Dependabot has a separate set of secrets that are managed under a slightly different path: `https://api.github.com/repos/<org>/<repo>/dependabot/secrets` vs `https://api.github.com/repos/<org>/<repo>/actions/secrets`. As far as I can tell, calls are identical to what you would expect for the normal repo secrets API. This API is undocumented, but I think there's a lot of value in adding support for it.

**Comment by gmlewis** [comment]
Sounds useful. Do you want to submit a PR, @liath , or do you want me to open this up to our contributors?

**Comment by liath** [comment]
I submitted a PR for it :)

**Comment by jurre** [comment]
fwiw the documentation lives here: https://docs.github.com/en/rest/reference/dependabot

**Comment by liath** [comment]
Because I'm a petty creature I would like to state for the record that the docs were posted after I filed this issue :P
[dependabot/dependabot-core#3297 (comment)
](https://github.com/dependabot/dependabot-core/issues/3297#issuecomment-1009308206)

**Comment by gmlewis** [comment]
> Because I'm a petty creature I would like to state for the record that the docs were posted after I filed this issue :P [dependabot/dependabot-core#3297 (comment) ](https://github.com/dependabot/dependabot-core/issues/3297#issuecomment-1009308206)

Totally fine!!!  Thank you, @liath !  :smile:
