### ISSUE TITLE
Release Request

### ISSUE THREAD

**Issue by pierce-m** [google/go-github#2249]
Hello -- sorry if this is the wrong place for this. Is it possible to create a release? Would like to use some of the new features getting merged.

**Comment by gmlewis** [comment]
Yes, I can work on that later today after work.

**Comment by pierce-m** [comment]
Thank you!

**Comment by gmlewis** [comment]
We have one more breaking change coming in shortly (#2250) and I'd like to minimize the number of major version bumps, so if you don't mind, I'll wait for that one to go in before a release.

**Comment by gmlewis** [comment]
@pierce-m - please check out the latest release: https://github.com/google/go-github/releases/tag/v42.0.0
