### ISSUE TITLE
Basic Auth Tokens Integrated with Oauth Lib

### ISSUE THREAD

**Issue by mcqueenorama** [google/go-github#225]
I have to get my oauth2 tokens via the basic auth api documented here:

https://developer.github.com/v3/oauth_authorizations/#create-a-new-authorization

I couldn't see a way to do it so I made a tokenSource and put in a pull request:

https://github.com/google/go-github/pull/221

I tried putting it into the oauth2 lib, but it doesn't meet the oauth2 spec, so they said to try to get it in over here.  It seems to fit in pretty well over here.

**Comment by gmlewis** [comment]
Closing issue in light of comment: https://github.com/google/go-github/pull/221#issuecomment-217496347
