### ISSUE TITLE
Cannot retrive all package versions owned by the authenticated use

### ISSUE THREAD

**Issue by lpmatos** [google/go-github#2251]
# Problem

In the current implementation we cannot retrieve all versions of a package for a `user` using the function `PackageGetAllVersions` present in the `users_packages.go` file.

The `PackageGetAllVersions` function has no parameters to allow pagination and retrieve all versions of a package, being limited to a return of 30 elements `[]*PackageVersion`, which is the default value of the [GitHub API](https://docs.github.com/pt/rest/reference/packages#get-all-package-versions-for-a-package-owned-by-the-authenticated-user).

# Context

I'm creating a CLI tool to clean up my GitHub container packages and I find this limitation.

## Code 

```Go
// Getting all packages version
pkgVersions, _, err := client.Users.PackageGetAllVersions(ctx, name, "container", container)
if err != nil {
  log.Fatal(err)
}
size := len(pkgVersions)

log.Infof("Package: %s", utils.DecodeParam(container))
log.Infof("We have %v versions in this package", size)
```

## Results

<img width="713" alt="Screen Shot 2022-01-12 at 00 26 37" src="https://user-images.githubusercontent.com/58797390/149058646-10374377-b3a3-436d-9eae-f65b22e1d920.png">

**Comment by gmlewis** [comment]
Thank you, @lpmatos for the detailed report and PR!
