### ISSUE TITLE
Support pagination for ListEnvironments

### ISSUE THREAD

**Issue by chelnak** [google/go-github#2257]
Hey,

Would you consider supporting pagination for the ListEnvironments method? I appreciate that it is probably an edge case request but it would be nice to be able to pass in opts to the request for pagination in the instance where you have a lot of environments.

`func (s *RepositoriesService) ListEnvironments(ctx context.Context, owner, repo string, opts *ListOptions)`

**Comment by gmlewis** [comment]
As far as I can tell, the GitHub v3 API does not support pagination for this endpoint:
https://docs.github.com/en/rest/reference/repos#get-all-environments

therefore it would be of no use to add pagination support to this Go client library.

You may wish to contact GitHub tech support to make your request. Once the official endpoint supports pagination then we can surely add support for it in this Go client library.

**Comment by chelnak** [comment]
Interesting, I hadn't noticed the absence of pagination from that document. I was going from the response headers.

Here are the response headers where the request was set to 2 environments per page:

``` javascript
{
  'access-control-allow-origin': '*',
  'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
  'cache-control': 'private, max-age=60, s-maxage=60',
  connection: 'close',
  'content-encoding': 'gzip',
  'content-security-policy': "default-src 'none'",
  'content-type': 'application/json; charset=utf-8',
  date: 'Mon, 17 Jan 2022 09:08:20 GMT',
  etag: 'W/"ac5180209bc77bddcb14468cfc9b58c40dca3df7c0bea9de5e05e37c236ad5bd"',
  'github-authentication-token-expiration': '2022-02-12 17:06:04 UTC',
  link: '<https://api.github.com/repositories/xxxx/environments?per_page=2&page=2>; rel="next", <https://api.github.com/repositories/xxxx/environments?per_page=2&page=22>; rel="last"',
  'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
  server: 'GitHub.com',
  'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
  'transfer-encoding': 'chunked',
  vary: 'Accept, Authorization, Cookie, X-GitHub-OTP, Accept-Encoding, Accept, X-Requested-With',
  'x-accepted-oauth-scopes': '',
  'x-content-type-options': 'nosniff',
  'x-frame-options': 'deny',
  'x-github-media-type': 'github.v3; format=json',
  'x-github-request-id': 'EFE4:6262:23374FA:2473395:61E53203',
  'x-oauth-scopes': 'delete:packages, repo, write:packages',
  'x-ratelimit-limit': '5000',
  'x-ratelimit-remaining': '4978',
  'x-ratelimit-reset': '1642413842',
  'x-ratelimit-resource': 'core',
  'x-ratelimit-used': '22',
  'x-xss-protection': '0'
}
```

**Comment by gmlewis** [comment]
Ah!  OK then... that's a completely different story.  :smile: 
Thank you for the extra details.

Yes, we can support them.  Could you please contact GitHub support and ask them to update their documentation?

Meanwhile, would you like to create a PR or would you like me to open up this issue for one of our other contributors to implement this?

**Comment by chelnak** [comment]
Excellent!

I'll take a shot at a PR if that's ok?

Will also open a support request today 👍

**Comment by gmlewis** [comment]
> I'll take a shot at a PR if that's ok?

Yes, perfect. It is yours. 😁

**Comment by chelnak** [comment]
@gmlewis First PR attempt has just been pushed. 😄
