### ISSUE TITLE
[Feature Request] Add checks field to RequiredStatusChecks

### ISSUE THREAD

**Issue by k24dizzle** [google/go-github#2274]
According to the [Github API](https://docs.github.com/en/rest/reference/branches#update-branch-protection), there is a new `checks` field that is supposed to replace the `contexts` field when setting required status checks.
<img width="798" alt="Screen Shot 2022-01-27 at 12 16 01 PM" src="https://user-images.githubusercontent.com/15153943/151436727-3034f3bd-4f1d-453f-90f4-c5c9c430e2b2.png">

Note: if `contexts` is required, not sure how that will interact with the `checks` field.

Add this field [here](https://github.com/google/go-github/blob/295020540d58efd38acedd29f5cdd4e2852b5c00/github/repos.go#L876).
<img width="1097" alt="Screen Shot 2022-01-27 at 12 14 26 PM" src="https://user-images.githubusercontent.com/15153943/151436525-9ca9d387-8919-46c1-af46-ca8f57a31ad3.png">

**Comment by gmlewis** [comment]
Thank you, @k24dizzle !  Would you like to make a PR, or shall I open this up to other contributors to this repo?

**Comment by k24dizzle** [comment]
Hi @gmlewis, new to contributing to this repo but I can give it a shot

**Comment by gmlewis** [comment]
Excellent, @k24dizzle !
Please make sure to check out our CONTRIBUTING.md file for how to get started.

**Comment by k24dizzle** [comment]
I did some more research, with some CURLs and realized that in `required_status_checks` you must supply either `contexts` or `checks`, but you cannot supply both at the same time:

```
curl   -X PUT   -H "Accept: application/vnd.github.v3+json" \
  -H "Authorization: token REDACTED" \
    https://api.github.com/repos/ORG/REPO_NAME/branches/BRANCH_NAME/protection  \
  -d '{"enforce_admins": null, "required_pull_request_reviews": null,
     "required_status_checks":{"strict":true,"contexts":["contexts"],"checks":[{"context":"contexts"}]}, 
     "restrictions": null}'
{
  "message": "Invalid request.\n\nNo subschema in \"anyOf\" matched.\nMore than one subschema in \"oneOf\" matched.\nNot all subschemas of \"allOf\" matched.\nFor 'anyOf/1', {\"strict\"=>true, \"contexts\"=>[\"contexts\"], \"checks\"=>[{\"context\"=>\"contexts\"}]} is not a null.",
  "documentation_url": "https://docs.github.com/rest/reference/repos#update-branch-protection"
}
```

So the [documentation given by github](https://docs.github.com/en/rest/reference/branches#update-branch-protection) is a little misleading:

<img width="790" alt="Screen Shot 2022-01-27 at 3 34 29 PM" src="https://user-images.githubusercontent.com/15153943/151460913-05f17064-286f-4d54-81f9-a7de7fdc21fc.png">

You could just provide `checks` (without `contexts`) for example and this should work:
```
curl   -X PUT   -H "Accept: application/vnd.github.v3+json" \
  -H "Authorization: token REDACTED" \
    https://api.github.com/repos/ORG/REPO_NAME/branches/BRANCH_NAME/protection  \
  -d '{"enforce_admins": null, "required_pull_request_reviews": null,
     "required_status_checks":{"strict":true,"checks":[{"context":"contexts"}]}, 
     "restrictions": null}'
```

Right now, I'm kind of stuck on figuring out how to enforce this logic/rule in `go-github` to help prevent these `invalid request` errors. Is there an example of how to specify a `required one or the other field` logic?

**Comment by gmlewis** [comment]
If both fields are slices with `omitempty`, then you could set one or the other to `nil` and they should not be passed to the endpoint (which you can confirm with a unit test).
