### ISSUE TITLE
Support "secret_scanning_alert" webhooks and event payloads

### ISSUE THREAD

**Issue by IainSteers** [google/go-github#2277]
Secret scanning has been GA since April 2021 (https://github.blog/changelog/2021-04-01-secret-scanning-for-private-repositories-is-generally-available/) for Advanced Security and since 3.1 in Enterprise.

The webhook payload is documented here
https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#secret_scanning_alert

**Comment by gmlewis** [comment]
Thank you, @IainSteers !
Would you like to put together a PR, or would you like me to open this up to other contributors of this repo to address?

**Comment by IainSteers** [comment]
Hey @gmlewis,

Thanks, I'd like to take a run at it please, it'll be a couple of days before I can free up to do it though. Should have something by Friday!

**Comment by gmlewis** [comment]
No rush, @IainSteers ... sounds great... thank you!  It is yours.
