### ISSUE TITLE
Support Secret Scanning endpoints

### ISSUE THREAD

**Issue by crqra** [google/go-github#2278]
Add support to retrieve and update secret scanning alerts for an enterprise, organization or repository ([Secret Scanning API reference](https://docs.github.com/en/rest/reference/secret-scanning#list-secret-scanning-alerts-for-a-repository)).

This is useful to automate tasks around security analysis and reporting.

**Comment by crqra** [comment]
I can pick this up, if no one is working on it already.

**Comment by gmlewis** [comment]
Thank you, @crqra !
It is yours.
