### ISSUE TITLE
Add support for getting content of a repository's license

### ISSUE THREAD

**Issue by willnorris** [google/go-github#228]
announcement: https://developer.github.com/changes/2015-08-04-get-license-contents/
docs: https://developer.github.com/v3/licenses/#get-the-contents-of-a-repositorys-license

**Comment by parkr** [comment]
Is this the raw output, i.e. with `Accept: application/vnd.github.drax-preview.raw` in the headers?

**Comment by willnorris** [comment]
probably just duplicate the existing [`GetReadme`](https://github.com/google/go-github/blob/7277108aa3e8823e0e028f6c74aea2f4ce4a1b5a/github/repos_contents.go#L75-L94) with whatever changes needed to get the license.  It doesn't look like we get the raw content there, so I probably wouldn't here either.

**Comment by willnorris** [comment]
(that of course assumes that the two methods are effectively identical on GitHub's side.  I think they are, but haven't looked closely)

**Comment by willnorris** [comment]
Our normal naming convention of following the GitHub docs would say that this belongs on the `LicenseService`, but I actually like what you have better... 

```go
client.Repositories.License("owner", "repo")
```

so let's go with this.  I do think this is one of the first times we've broken from that convention. :shrug:
