### ISSUE TITLE
RequireCodeOwnerReviews cannot be set to false when updating

### ISSUE THREAD

**Issue by leopoldwang** [google/go-github#2286]
RequireCodeOwnerReviews field does not use pointer type causing json encode to omit the field. Request was then rejected by github rest api

https://github.com/google/go-github/blob/2be8000e79e36b1ae7df87194566694b3783cd92/github/repos.go#L948

**Comment by gmlewis** [comment]
Thank you, @leopoldwang !
Would you like to create a PR to fix this issue, or shall I open this up to anyone to create a PR?
