### ISSUE TITLE
not able to activate advanced security

### ISSUE THREAD

**Issue by dustincrogers** [google/go-github#2292]
Forgive my naivety as an amateur developer, especially in go.

I am trying to use `Repositories.Edit` to update the `SecurityAndAnalysis.AdvancedSecurity.Status` to `enabled` and even though I get 200 status, I receive an empty response. The field does not update as expected. 

The response body appears to not have the field available, which is probably the issue. 

I am definitely able to see the status of the field, using `SecurityAndAnalysis.GetAdvancedSecurity()`

Does anyone know what I may be doing wrong or if this is maybe a bug somewhere?
Thanks in advance!

**Comment by gmlewis** [comment]
Two options: 

* try the curl-only version and see if you get the same results.
* post an example snippet of your request here so we can see what you are attempting

**Comment by dustincrogers** [comment]
Thanks for taking a look and for the advice! This is working fine to enable/disable github advanced security with curl, so I am not getting the same results. Probably just something with my code then. 

Here is my snippet, please excuse the fact that its messy still:
```
// ActivateSecurityAndAnalysis activates the security and analysis object for the given repo
func (r *Repo) ActivateSecurityAndAnalysis(client *ghtools.Client) error {
	repo, _, err := client.API.Repositories.Get(context.Background(), r.Owner, r.Name)
	if err != nil {
		return errors.Wrap(err, "could not get repository definition")
	}

	if repo.GetSecurityAndAnalysis() == nil {
		repo.SecurityAndAnalysis = &github.SecurityAndAnalysis{}
	}

	if repo.SecurityAndAnalysis.GetAdvancedSecurity() == nil {
		repo.SecurityAndAnalysis.AdvancedSecurity = &github.AdvancedSecurity{}
	}

	// now we know that repo.SecurityAndAnalysis.AdvancedSecurity is initialized
	// we are finally positive there are no nil pointers along the chain
	//set it to enabled
	enabled := "enabled"
	fmt.Printf("Before repo.SecurityAndAnalysis.AdvancedSecurity.Status: %v\n", *repo.SecurityAndAnalysis.AdvancedSecurity.Status)
	repo.SecurityAndAnalysis.AdvancedSecurity.Status = &enabled
	fmt.Printf("After repo.SecurityAndAnalysis.AdvancedSecurity.Status: %v\n", *repo.SecurityAndAnalysis.AdvancedSecurity.Status)
	//repo.SecurityAndAnalysis.SecretScanning.Status = &enabled

	// patch := PatchSecurityAndAnalysis{
	// 	SecurityAndAnalysis: repo.SecurityAndAnalysis,
	// }

	_, response, err := client.API.Repositories.Edit(context.Background(), r.Owner, r.Name, repo)
	if err != nil {
		return errors.Wrap(err, "could not edit repository")
	}

	saa := repo.SecurityAndAnalysis.GetAdvancedSecurity()

	log.Infof("Security and Analysis Activated: %d - %v", response.StatusCode, saa)
	fmt.Printf("After repo.SecurityAndAnalysis.AdvancedSecurity.Status: %v\n", *repo.SecurityAndAnalysis.AdvancedSecurity.Status)
	return nil
}
```

**Comment by gmlewis** [comment]
One thing I just mentioned here: https://github.com/google/go-github/issues/2291#issuecomment-1040778417
is that you have to be super-careful when modifying something in GitHub with the v3 API and then immediately checking its value, as the results in GitHub's servers are "eventually consistent" and not "immediately consistent".

Please try checking the value with an exponential backoff on the GET calls.

I'm betting that the value actually _is_ getting changed but the change doesn't get propagated fast enough for your program to immediately see it with the GET call.

Oh, and just FYI ... I added the word "go" after your initial three backticks to add syntax highlighting to your code above, which is a super-cool GitHub feature.  :smile: 

(Obviously, you can also manually verify that the change has been made after a single call just to see if it is working.)

I hope this helps.

**Comment by dustincrogers** [comment]
Absolutely it helps. I am grateful. However it is not enabling via API as one would expect, and I am manually confirming that fact in the UI. 
>I'm betting that the value actually is getting changed but the change doesn't get propagated fast enough for your program to immediately see it with the GET call.

Thank you. I believe you about the propagation latency and will keep this in mind.

If I manually enable Advanced Security, and similarly try to use the API to set secret scanning to `enabled`, it is also not enabling. ie. `repo.SecurityAndAnalysis.SecretScanning.Status = &enabled`
![Screen Shot 2022-02-16 at 7 33 35 PM](https://user-images.githubusercontent.com/42478126/154401326-a513b7b0-839e-48fd-b13c-5c981521e793.png)
Again, the GET call is reporting the manually set status back correctly, Its very possible there is a knowledge gap on my part about how to use `Edit()` to set the security object `Status` properly.
>Oh, and just FYI ... I added the word "go" after your initial three backticks to add syntax highlighting to your code above, which is a super-cool GitHub feature.

Thank you friend, always feel free to make things nicer 😄 

Also feel free to let me know if I can provide more info.

**Comment by gmlewis** [comment]
> Also feel free to let me know if I can provide more info.

Thank you for ruling out the delayed-propagation scenario.

Later today I will attempt to recreate the problem and let you know what I discover.  But the bottom line is that if you were able to make things work using `curl`, then this repo's method should also work... so let's get to the bottom of this and fix it. 😊

**Comment by dustincrogers** [comment]
@gmlewis Thats great replication. I actually get the same results, but when i manually confirm the actual field is not being  updated.  I apologize if Im insulting your intelligence, but are you manually verifying? 
```go
Before repo.SecurityAndAnalysis.AdvancedSecurity.Status: disabled
After repo.SecurityAndAnalysis.AdvancedSecurity.Status: enabled
INFO[0010] Security and Analysis Activated: 200 - github.AdvancedSecurity{Status:"enabled"}
After repo.SecurityAndAnalysis.AdvancedSecurity.Status: enabled
INFO[0020] Security and Analysis Activated: 200 - github.AdvancedSecurity{Status:"enabled"}
After repo.SecurityAndAnalysis.AdvancedSecurity.Status: enabled
INFO[0030] Security and Analysis Activated: 200 - github.AdvancedSecurity{Status:"enabled"}
After repo.SecurityAndAnalysis.AdvancedSecurity.Status: enabled
INFO[0040] Security and Analysis Activated: 200 - github.AdvancedSecurity{Status:"enabled"}
After repo.SecurityAndAnalysis.AdvancedSecurity.Status: enabled
INFO[0050] Security and Analysis Activated: 200 - github.AdvancedSecurity{Status:"enabled"}
After repo.SecurityAndAnalysis.AdvancedSecurity.Status: enabled
```
![Screen Shot 2022-02-17 at 9 31 00 AM](https://user-images.githubusercontent.com/42478126/154537798-e27645c5-6b81-44a1-80bd-dc0a300ae9f0.png)

**Comment by gmlewis** [comment]
@dustincrogers - I actually couldn't find it.  Where are you seeing this setting?
Here's what I see:

![ksnip_20220217-125301](https://user-images.githubusercontent.com/6598971/154541528-46495993-ce11-4063-acb1-168946a7792f.png)

**Comment by gmlewis** [comment]
So if this is what you see with this endpoint, what do you see using `curl`?  Does it still say "enabled"?

**Comment by gmlewis** [comment]
Ah, thanks!  I'll try again on a private repo, and report back to you here.

**Comment by gmlewis** [comment]
In cases like these, I sometimes just dump the JSON that is being sent over the wire and compare it to `curl`... I'll try that later, but I think something else might be going on here... but I don't know what.

**Comment by gmlewis** [comment]
I found an org-owned repo, and still get an error:

```bash
go run main.go
2022/02/18 12:09:09 curl -X GET \
  https://api.github.com/repos/irmf/irmf-vscode \
  -H 'Accept: application/vnd.github.scarlet-witch-preview+json, application/vnd.github.mercy-preview+json, application/vnd.github.baptiste-preview+json, application/vnd.github.nebula-preview+json' \
  -H 'User-Agent: go-github'
Before repo.SecurityAndAnalysis.AdvancedSecurity.Status: 
After repo.SecurityAndAnalysis.AdvancedSecurity.Status: enabled
2022/02/18 12:09:09 curl -X PATCH \
  https://api.github.com/repos/irmf/irmf-vscode \
  -H 'Accept: application/vnd.github.baptiste-preview+json, application/vnd.github.nebula-preview+json' \
  -H 'Content-Type: application/json' \
  -H 'User-Agent: go-github' \
  -d '{"id":245520298,...lots-and-lots-deleted...,"security_and_analysis":{"advanced_security":{"status":"enabled"}},...lots-more-deleted...,"visibility":"public"}'
2022/02/18 12:09:09 could not edit repository: PATCH https://api.github.com/repos/irmf/irmf-vscode: 422 This organization does not allow private repository forking []
exit status 1
```

So at this point, I'm rather stumped.  As far as I can tell, the problem is not with this repo.  Please let me know if you find otherwise.

**Comment by gmlewis** [comment]
OK, this looks _MUCH_ better... please try this out:

```go
// ActivateSecurityAndAnalysis activates the security and analysis object for the given repo
func ActivateSecurityAndAnalysis(ctx context.Context, client *github.Client, owner, name string) error {
	repo := &github.Repository{
		SecurityAndAnalysis: &github.SecurityAndAnalysis{
			AdvancedSecurity: &github.AdvancedSecurity{
				Status: github.String("enabled"),
			},
		},
	}

	_, response, err := client.Repositories.Edit(ctx, owner, name, repo)
	if err != nil {
		return fmt.Errorf("could not edit repository: %v", err)
	}

	for i := 0; i < 5; i++ {
		saa := repo.SecurityAndAnalysis.GetAdvancedSecurity()

		log.Printf("Security and Analysis Activated: %d - %v", response.StatusCode, saa)
		fmt.Printf("After repo.SecurityAndAnalysis.AdvancedSecurity.Status: %v\n", *repo.SecurityAndAnalysis.AdvancedSecurity.Status)
		time.Sleep(10 * time.Second)
	}
	return nil
}
```

and here's what I see:

```bash
$ go run main.go
2022/02/18 12:49:31 curl -X PATCH \
  https://api.github.com/repos/irmf/irmf-vscode \
  -H 'Accept: application/vnd.github.baptiste-preview+json, application/vnd.github.nebula-preview+json' \
  -H 'Content-Type: application/json' \
  -H 'User-Agent: go-github' \
  -d '{"security_and_analysis":{"advanced_security":{"status":"enabled"}}}
'
2022/02/18 12:49:31 could not edit repository: PATCH https://api.github.com/repos/irmf/irmf-vscode: 422 Advanced security is always available for public repos []
exit status 1
```

Note that the actual equivalent `curl` command looks much more reasonable.

**Comment by dustincrogers** [comment]
It works!
I had a feeling it was something like that. I was trying to create a smaller body object with just those fields and couldnt figure that out. Thank you so much!

**Comment by gmlewis** [comment]
> It works! I had a feeling it was something like that. I was trying to create a smaller body object with just those fields and couldnt figure that out. Thank you so much!

I think this might be encouragement to continue the pursuit of #2295 . Feel free to comment over there if you agree or disagree. Thank you!
