### ISSUE TITLE
Support for setting actions permissions for a repository

### ISSUE THREAD

**Issue by cfarrend** [google/go-github#2297]
Currently in [`action_runners.go`](https://github.com/google/go-github/blob/master/github/actions_runners.go), there is support for getting and setting actions permissions on the **organization** level but not on the **repository** level.

Endpoints to add:
https://docs.github.com/en/rest/reference/actions#get-github-actions-permissions-for-a-repository
https://docs.github.com/en/rest/reference/actions#set-github-actions-permissions-for-a-repository

Additionally for `allowed_actions: selected` (not required for myself as I'm only setting `enabled: false`):
https://docs.github.com/en/rest/reference/actions#get-allowed-actions-for-a-repository
https://docs.github.com/en/rest/reference/actions#set-allowed-actions-for-a-repository

Happy to pick up the first part of this issue and additionally the second later on. If I am missing something, please let me know, but I'm pretty sure there isn't support based on my basic searching of the repo and issues.

**Comment by gmlewis** [comment]
Thank you, @cfarrend - it looks like you are right.
Yes, that would be great!  Please check out the CONTRIBUTING.md guide for tips on making PRs for this repo.
You will particularly want to know about `go generate ./...` and try not to use force-push since we squash as many commits as you have all into one upon merge.

**Comment by gmlewis** [comment]
I apologize, @cfarrend , as we normally discuss change-of-ownership for open issues before actually switching owners, and I'm sorry if you have already invested time and effort into this issue.

However, @h2floh has submitted a PR for this open issue.  Once @h2floh signs the CLA, I will switch ownership of this issue from you to @h2floh unless you object (in which case we can discuss the situation).

**Comment by cfarrend** [comment]
@gmlewis No issues from my side 🙂

**Comment by h2floh** [comment]
👋  Again my apologies!

@gmlewis, I internally requested that I will be added on our company's contributor list, we have an existing CLA. Should be done within a few days.

**Comment by gmlewis** [comment]
> :wave: Again my apologies!
> 
> @gmlewis, I internally requested that I will be added on our company's contributor list, we have an existing CLA. Should be done within a few days.

No problem, @h2floh - please remind me in a couple days if you see that this hasn't moved forward, and I'll check again.

Thank you!
