### ISSUE TITLE
Release Request

### ISSUE THREAD

**Issue by raynigon** [google/go-github#2298]
Is it possible to create a release? 
Would like to use some of the new features getting merged.
I suggest to wait for the following open PR:
- https://github.com/google/go-github/pull/2295

**Comment by ewan-chalmers** [comment]
Likewise. I'm hoping to see this one appear in v43 :) 
- https://github.com/google/go-github/issues/2255

**Comment by gmlewis** [comment]
If anyone has opinions on #2295 vs #2302, please voice them (on their respective pages) in the hopes that more interest will move one or the other along. Thank you!

**Comment by uptycs-rmack** [comment]
+1 Would like to see the SecretScanning stuff in a release.

**Comment by gmlewis** [comment]
`v43.0.0` has now been released: https://pkg.go.dev/github.com/google/go-github/v43/github
Sorry for the delay.
