### ISSUE TITLE
Tree doesn't contain any file entries

### ISSUE THREAD

**Issue by Integralist** [google/go-github#2299]
👋🏻 

I'm trying to list out the files in [a repo](https://github.com/fastly/cli) but I'm getting back an empty list when I expect a bunch of files to be listed. Can anyone advise on what I'm doing wrong?

Thanks.

```go
package main

import (
	"context"
	"fmt"
	"log"
	"os"

	"github.com/google/go-github/v42/github"
	"golang.org/x/oauth2"
)

func main() {
	ctx := context.Background()
	ts := oauth2.StaticTokenSource(
		&oauth2.Token{AccessToken: os.Getenv("GITHUB_TOKEN")},
	)
	tc := oauth2.NewClient(ctx, ts)
	client := github.NewClient(tc)

	b, _, err := client.Repositories.GetBranch(context.Background(), "fastly", "cli", "main", true)
	if err != nil {
		log.Fatal(err)
	}
	rc := b.GetCommit()
	c := rc.GetCommit()
	t := c.GetTree()
	fmt.Printf("%+v\n", t.Entries) // []
}
```

**Comment by Integralist** [comment]
Thanks @gmlewis 

So it looks like what I needed was the 'contents' endpoint of the repository API:

https://docs.github.com/en/rest/reference/repos#get-repository-content

```bash
$ curl -su $user:$api_token https://api.github.com/repos/fastly/$private_repo/contents/ | jq

[{...}, {...}]
```

Which equates to:

```go
_, directoryContent, _, err := client.Repositories.GetContents(context.Background(), org, repo, path, nil)
if err != nil {
	log.Fatal(err)
}
fmt.Printf("%+v\n", directoryContent)
```

Apologies for wasting your time. I should have checked using curl first.

Thanks for the guidance!

**Comment by gmlewis** [comment]
> Apologies for wasting your time. I should have checked using curl first.

No apology necessary!  That's what I'm here for.  :smile: 
I'm glad you found the solution, and thank you very much for reporting back... it is greatly appreciated!
