### ISSUE TITLE
Add Support for "Affiliation" in RepositoryListOptions

### ISSUE THREAD

**Issue by jmburges** [google/go-github#231]
In the [Github API Docs](https://developer.github.com/v3/repos/#list-your-repositories) there is a field for `affiliation` when doing a list of all your repositories. As far as I can tell, this doesn't exist in the `RepositoryListOptions` struct though. 

Am I missing something?

**Comment by willnorris** [comment]
don't think you're missing anything... I just don't think that parameter existed with that part of the library was first written.
