### ISSUE TITLE
Add more more location-specific fields to the PullRequestComment struct

### ISSUE THREAD

**Issue by ojarjur** [google/go-github#232]
Pull request comments have multiple fields that are important for the location of a comment but that are currently omitted from that struct:

    * diff_hunk: This is important as the position field is actually the position *within-the-hunk* rather than within the file.
    * original_commit_id: This is important, as "commit_id" tracks the pull request, so after additional changes are pushed to the pull-request, the "commit_id" changes and no longer points to the commit at which the comment was made.
    * original_position: This is similar to original_commit_id, and is important as the "position" field gets cleared out after the pull request is updated (since the comment is no longer at the current commit).

**Comment by willnorris** [comment]
fixed in 08bb599b461f73841736d7269029562423ae9037
