### ISSUE TITLE
Webhook event type `pull_request_review_thread` missing

### ISSUE THREAD

**Issue by taisph** [google/go-github#2324]
It seems like GitHub is sending the webhook event type `pull_request_review_thread` when someone resolves a comment in a PR.

Webhook event schema can be seen here: https://github.com/octokit/webhooks/blob/d93eebf4c48dc3c36f9c7ceffab356fa444bf9fc/payload-schemas/api.github.com/pull_request_review_thread/resolved.schema.json

The event doesn't seem to be documented in [Webhook events and payload](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request_review_thread) though.

**Comment by gmlewis** [comment]
Thank you, @taisph !
Could you please ask GitHub tech support to document this webhook event type?

**Comment by taisph** [comment]
> Thank you, @taisph ! Could you please ask GitHub tech support to document this webhook event type?

GitHub Support have created an internal issue to get the documentation updated.

**Comment by gmlewis** [comment]
Excellent, thank you, @taisph !
Do you want to make a PR for this, or shall I open it up for other contributors?

**Comment by taisph** [comment]
> Excellent, thank you, @taisph ! Do you want to make a PR for this, or shall I open it up for other contributors?

I'll give it a shot.
