### ISSUE TITLE
How are you supposed to access the output of ListSCIMProvisionedIdentities?

### ISSUE THREAD

**Issue by Osipion** [google/go-github#2338]
Hi all. Thanks so much for your work on this. QQ: `ListSCIMProvisionedIdentities` appears to not return any entities and also closes the underlying HTTP response body reader. What's the expected way to read the list of identities returned by the API?

**Comment by gmlewis** [comment]
Hi @Osipion , and thank you for the report!

This is totally my fault... I let #2062 go through code review without returning a populated struct. I apologize.

This needs to be implemented... would you like to submit a PR, or shall I open this up to any other contributor to this repo?

**Comment by Osipion** [comment]
Thanks for getting back to me. I may have a chance to look into submitting a PR this weekend but don't wait up for me

**Comment by gmlewis** [comment]
No rush, @Osipion - it is yours. Thank you!
