### ISSUE TITLE
Add fields to RateLimits struct

### ISSUE THREAD

**Issue by shokada** [google/go-github#2339]
Hi there.

Currently the `/rate_limit` response looks like this.
```
-> % curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ghs_xxx" https://api.github.com/rate_limit
{
  "resources": {
    "core": {
      "limit": 15000,
      "used": 9406,
      "remaining": 5594,
      "reset": 1650339361
    },
    "search": {
      "limit": 30,
      "used": 0,
      "remaining": 30,
      "reset": 1650337238
    },
    "graphql": {
      "limit": 12500,
      "used": 0,
      "remaining": 12500,
      "reset": 1650340778
    },
    "integration_manifest": {
      "limit": 5000,
      "used": 0,
      "remaining": 5000,
      "reset": 1650340778
    },
    "source_import": {
      "limit": 100,
      "used": 0,
      "remaining": 100,
      "reset": 1650337238
    },
    "code_scanning_upload": {
      "limit": 1000,
      "used": 0,
      "remaining": 1000,
      "reset": 1650340778
    },
    "actions_runner_registration": {
      "limit": 10000,
      "used": 71,
      "remaining": 9929,
      "reset": 1650340715
    },
    "scim": {
      "limit": 15000,
      "used": 0,
      "remaining": 15000,
      "reset": 1650340778
    }
  },
  "rate": {
    "limit": 15000,
    "used": 9406,
    "remaining": 5594,
    "reset": 1650339361
  }
}
```

However, the `RateLimits` struct defines only the `core` and `search` fields.
https://github.com/google/go-github/blob/00e42332e405cdd73bc6cd45a4cc555a4cfd613e/github/github.go#L1080-L1094

Can items other than `core` and `search` be added to the `RateLimits` struct?

**Comment by gmlewis** [comment]
Thank you for the report, @shokada !
Yes, they can.

Would you like to submit a PR or would you like me to open up this issue to other contributors to this repo?

**Comment by shokada** [comment]
@gmlewis Thank you for the reply!

> Would you like to submit a PR or would you like me to open up this issue to other contributors to this repo?

Yes, I will try to submit a PR.

**Comment by gmlewis** [comment]
Great! It's yours.

**Comment by xun-guo-anzx** [comment]
Thanks @shokada @gmlewis . May I request a release for this feature once the PR is merged?

**Comment by gmlewis** [comment]
> Thanks @shokada @gmlewis . May I request a release for this feature once the PR is merged?

Sure, no problem.
