### ISSUE TITLE
Reduce code duplication (DRY) in favor of interface casting?

### ISSUE THREAD

**Issue by andygrunwald** [google/go-github#234]
Hey,

this is not a real issue. More like a small discussion what you think about.
First of all thanks for this package. Very useful and well written.
After i had a look into the code i stumbled upon a lot of code duplication for very similar methods like

* define the url
* add options
* get a request
* allocate a pointer to a struct
* make the request
* return it

Like in:
```go
func (s *IssuesService) ListByRepo(owner string, repo string, opt *IssueListByRepoOptions) ([]Issue, *Response, error) {
	u := fmt.Sprintf("repos/%v/%v/issues", owner, repo)
	u, err := addOptions(u, opt)
	if err != nil {
		return nil, nil, err
	}

	req, err := s.client.NewRequest("GET", u, nil)
	if err != nil {
		return nil, nil, err
	}

	issues := new([]Issue)
	resp, err := s.client.Do(req, issues)
	if err != nil {
		return nil, resp, err
	}

	return *issues, resp, err
}
```

All this can be stripped down to something like (attention: this code is not from this repo, but it shows an example:

```go
func (s *ProjectsService) GetCommit(projectName, commitID string) (*CommitInfo, *Response, error) {
    u := fmt.Sprintf("projects/%s/commits/%s", projectName, commitID)
    p := new(CommitInfo)
    v, resp, err := test(s, u, p)
    return v.(*CommitInfo), resp, err
}

func test(s *ProjectsService, u string, v interface{}) (interface{}, *Response, error) {
    req, err := s.client.NewRequest("GET", u, nil)
    if err != nil {
        return nil, nil, err
    }

    resp, err := s.client.Do(req, v)
    if err != nil {
        return nil, resp, err
    }

    return v, resp, err
}
```

Something like this can avoid a lot of code duplication and reduce the code base.
I started a small discussion on the go-nuts mailing list. See [Reduce code duplication for pointer allocation: Pro and Cons](https://groups.google.com/forum/#!topic/golang-nuts/vEPPZ18CbcI). But sadly there was no such a big discussion about this.
That is the reason why i try this way. I want to get your opinion about this or maybe an answer why this way wasn`t chosen.
Or maybe: Does it make sense for you?

**Comment by willnorris** [comment]
There was some discussion some time ago about refactoring some of that duplicate code... it's probably on a pull request or issue somewhere.  I think the way we had talked about doing it was to add a new method onto the `Client` type that combined the `NewRequest` and `Do` calls.  So, using a modified version of your func, something like:

```go
func (c *Client) Call(u string, v interface{}) (interface{}, *Response, error) {
    req, err := c.NewRequest("GET", u, nil)
    if err != nil {
        return nil, nil, err
    }

    resp, err := c.Do(req, v)
    if err != nil {
        return nil, resp, err
    }

    return v, resp, err
}
```

One downside of this approach is that there are a handful of functions in the go-github library that don't fit the mold... many that send custom Accept headers in the request and such.  You could use the above approach for the simpler methods and then let the outliers do the full work, or just pass an `http.Header` to the `Call` method (though that is kind of annoying since most cases won't use it).

I'm not sure that there would be much benefit to changing the go-github library at this point, since the work has already been done, but for other libraries it seems like a reasonable approach.

**Comment by willnorris** [comment]
oh, you would also need to add the request body, so that would make the signature more like: 

```go
func (c *Client) Call(u string, req interface{}, resp interface{}) (*Response, error) {
```

You should also be able to drop the returned `interface{}`... it's a pointer anyway, so the caller already has a copy of it.

**Comment by willnorris** [comment]
ah, missed the http method too, so now you're up to:

```go
func (c *Client) Call(method, u string, req interface{}, resp interface{}) (*Response, error)
```

**Comment by andygrunwald** [comment]
> You should also be able to drop the returned interface{}... it's a pointer anyway, so the caller already has a copy of it.
Yes you are true.

But thanks for your answer. Your answer proves (to me) that there is no real technical issue here (as disadvantage).
Of course you can generalize it more and more, like making the method (GET, etc.) exchangeable as well.

**Comment by andygrunwald** [comment]
For me this issue can be solved / closed, because you answered all my points.
And maybe a change in this direction would be a micro optimization, so this decision is more up to you. :)
But thanks for your feedback.
