### ISSUE TITLE
Add support for rerun failed jobs and single job for workflow run

### ISSUE THREAD

**Issue by guo-chris** [google/go-github#2344]
New endpoints to rerun all failed jobs or a single job from a workflow run
https://docs.github.com/en/rest/actions/workflow-runs#re-run-failed-jobs-from-a-workflow-run
https://docs.github.com/en/rest/actions/workflow-runs#re-run-a-job-from-a-workflow-run

I'll create the PR for this

**Comment by gmlewis** [comment]
> I'll create the PR for this

Thank you, @guo-chris !
