### ISSUE TITLE
CreateInstallationToken returns 401 when authed via github app installation

### ISSUE THREAD

**Issue by nickofthyme** [google/go-github#2359]
When authenticated as a GitHub app installation via [`bradleyfalzon/ghinstallation/v2`](https://github.com/bradleyfalzon/ghinstallation) as described in the [docs](https://pkg.go.dev/github.com/google/go-github@v17.0.0+incompatible/github#hdr-Authentication), seen below...

```go
import "github.com/bradleyfalzon/ghinstallation"

func main() {
	// Wrap the shared transport for use with the integration ID 1 authenticating with installation ID 99.
	itr, err := ghinstallation.NewKeyFromFile(http.DefaultTransport, 1, 99, "2016-10-19.private-key.pem")
	if err != nil {
		// Handle error.
	}

	// Use installation transport with client
	client := github.NewClient(&http.Client{Transport: itr})

	// Use client...
}
```

The call to `githubClient.Apps.CreateInstallationToken` fails with the error below...

```
POST https://api.github.com/installations/123456/access_tokens: 401 A JSON web token could not be decoded []
```

**Comment by gmlewis** [comment]
It might be better to report this issue on the https://github.com/bradleyfalzon/ghinstallation repo as you are more likely to get assistance there for use of that package.

**Comment by nickofthyme** [comment]
Closing in favor of https://github.com/bradleyfalzon/ghinstallation/issues/68
