### ISSUE TITLE
Documentation links have changed

### ISSUE THREAD

**Issue by Jille** [google/go-github#2360]
The documentation links in the Godoc seem to have broken.

For example "https://docs.github.com/en/free-pro-team@latest/rest/reference/apps/#delete-an-app-token" should now be /rest/**apps**/apps/.

**Comment by gmlewis** [comment]
> The documentation links in the Godoc seem to have broken.
> 
> For example "https://docs.github.com/en/free-pro-team@latest/rest/reference/apps/#delete-an-app-token" should now be /rest/**apps**/apps/.

Yes, the URLs on the GitHub documentation website change quite frequently. PRs are welcome to fix the links.
Thanks.
