### ISSUE TITLE
Unable to set Pages to main /docs via API

### ISSUE THREAD

**Issue by ghostinthewires** [google/go-github#2371]
https://github.com/google/go-github/blob/6931fad1bba0d6a311d99a34e9e3aa61619d9512/github/repos_pages.go#L90

	CNAME *string `json:"cname"`
	// Source must include the branch name, and may optionally specify the subdirectory "/docs".
	// Possible values are: "gh-pages", "master", and "master /docs".
	
I can set this using the UI "main /docs" but trying to do it with the API gives the above error.

Happy to update myself via PR if you can point me in the right direction.

**Comment by gmlewis** [comment]
> can set this using the UI "main /docs" but trying to do it with the API gives the above error.

Have you tried using the GitHub v3 API with `curl` ?
https://docs.github.com/en/rest/pages#update-information-about-a-github-pages-site

First try this, and if that works but it still doesn't work with this repo, please give more details on what you tried. (A minimal working example would be great.)

You might find https://github.com/gmlewis/go-httpdebug useful in debugging.

**Comment by ghostinthewires** [comment]
Hi,

This is been used via Terraform, like in this example: https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository#example-usage-with-github-pages-enabled

**Comment by gmlewis** [comment]
I'm not seeing any example using this repo at the link you provided.

Here's why I tried:

```go
// -*- compile-command: "go run main.go"; -*-

package main

import (
	"context"
	"io/ioutil"
	"log"

	dbg "github.com/gmlewis/go-httpdebug/httpdebug"
	"github.com/google/go-github/v44/github"
	"golang.org/x/oauth2"
)

const SECRET = "..."

func main() {
	ts := oauth2.StaticTokenSource(
		&oauth2.Token{AccessToken: SECRET},
	)
	tc := oauth2.NewClient(oauth2.NoContext, ts)
	tp := dbg.New(dbg.WithTransport(tc.Transport))
	client := github.NewClient(tp.Client())
	ctx := context.Background()

	owner := "gmlewis"
	name := "my-test-repo"

	opts := &github.PagesUpdate{
		Source:        github.String("master /docs"),
		Public:        github.Bool(true),
		HTTPSEnforced: github.Bool(true),
	}
	resp, err := client.Repositories.UpdatePages(ctx, owner, name, opts)
	if err != nil {
		log.Fatal(err)
	}
	b, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("resp.StatusCode=%v, b=%s", resp.StatusCode, b)
}
```

and this is what I get:

```bash
go run main.go
2022/05/24 08:58:17 curl -X PUT \
  https://api.github.com/repos/gmlewis/my-test-repo/pages \
  -H 'Accept: application/vnd.github.v3+json' \
  -H 'Content-Type: application/json' \
  -H 'User-Agent: go-github' \
  -d '{"cname":null,"source":"master /docs","public":true,"https_enforced":true}
'
2022/05/24 08:58:17 PUT https://api.github.com/repos/gmlewis/my-test-repo/pages: 404 The certificate does not exist yet []
exit status 1
```

Can you please give me a bit more detail about what you are trying and what the errors are that you are seeing so that I can attempt to help?

**Comment by gmlewis** [comment]
Here's what I get:

```bash
go run main.go
2022/05/24 09:13:46 curl -X PUT \
  https://api.github.com/repos/gmlewis/my-test-repo/pages \
  -H 'Accept: application/vnd.github.v3+json' \
  -H 'Content-Type: application/json' \
  -H 'User-Agent: go-github' \
  -d '{"cname":null,"source":"main /docs","public":true,"https_enforced":true}
'
2022/05/24 09:13:46 PUT https://api.github.com/repos/gmlewis/my-test-repo/pages: 422 Invalid request.

Invalid property /source: `main /docs` is not a possible value. Must be one of the following: gh-pages, master, master /docs. []
exit status 1
```

I'll try changing the primary branch from "master" to "main" and then try again.

**Comment by gmlewis** [comment]
OK, even after changing my default branch from "master" to "main", I get the same error:

```bash
go run main.go
2022/05/24 09:16:47 curl -X PUT \
  https://api.github.com/repos/gmlewis/my-test-repo/pages \
  -H 'Accept: application/vnd.github.v3+json' \
  -H 'Content-Type: application/json' \
  -H 'User-Agent: go-github' \
  -d '{"cname":null,"source":"main /docs","public":true,"https_enforced":true}
'
2022/05/24 09:16:47 PUT https://api.github.com/repos/gmlewis/my-test-repo/pages: 422 Invalid request.

Invalid property /source: `main /docs` is not a possible value. Must be one of the following: gh-pages, master, master /docs. []
exit status 1
```

Please contact GitHub tech support and let them know about this bug.

Feel free to report back here when you get an answer... I'll leave the issue open for a while.

**Comment by gmlewis** [comment]
> That is why I have raised this issue here.
> 
> I am happy to contribute to any code via a PR to fix it, or a dev at GitHub can fix it. Happy either way

Well, no.  This is actually the wrong place to post this issue.

This repo has no affiliation with GitHub and is completely supported by volunteers. It is a Go client library for the GitHub v3 API.

We have proven that the problem is not with this repo, but is with the GitHub v3 API itself.
No PR into this repo will solve this bug.

So you will need to actually contact GitHub tech support and raise an issue for them to fix it on their servers, at which point this repo will automatically work.

**Comment by ghostinthewires** [comment]
Ah cool understood, thanks very much for the heads up -didnt know that.
