### ISSUE TITLE
[Question/Help] How do I check out a created branch/ref?

### ISSUE THREAD

**Issue by Skarlso** [google/go-github#2372]
Hi!

Lovely project, been using it for a while now, but something I can't figure out is how do I check out a branch?

I know how to create it... And then changes are applied to it. But the changes remain on the main branch even after push occurs since all that is being done in memory.

I'm wondering how do I check out a branch so local changes don't just stay where they are / where they occurred?

Thanks!

**Comment by gmlewis** [comment]
> Lovely project, been using it for a while now, but something I can't figure out is how do I check out a branch?

Thanks.  When you say "check out a branch", are you talking about the equivalent of "git checkout"?
If so, this repo is probably not what you are looking for.

This repo is a client library for the GitHub v3 API: https://docs.github.com/en/rest

If you can figure out how to do what you want with the v3 API, then this repo should be able to help you do that.

Otherwise, you probably just want to call "git" or something like https://github.com/go-git/go-git .

**Comment by Skarlso** [comment]
Hi!

Thanks! So, what I would like to do is as follows... Right now, when I create a ref and then generate a tree and then commit and push that tree, the changes remain locally. Here is the entire thing: https://github.com/Skarlso/dependabot-bundler/blob/main/pkg/bundler.go#L96

So `getRef` creates a ref, then getTree creates the tree then `pushCommit` creates the commit. But the changes remain locally on the branch where you run this cli instead of staging them into the ref that was created. Is there a way to deal with that, or do I have to manually discard them?

**Comment by gmlewis** [comment]
Ah!  OK, I think I understand, but would like to debug this locally and get it working before I share with you some theory of mine. :smile: 

Is this the issue that prompted this question? https://github.com/Skarlso/dependabot-bundler/issues/13

Is there an easy way to duplicate this scenario locally from scratch so I can attempt to solve this?

**Comment by Skarlso** [comment]
Yepp! Exactly :D That's the one.

I don't have a small script. :/ The only way to reproduce is create a ref, do a commit, push and check what remained locally. The change can be something like `echo "bla" > bla.txt` and stage that file and push it to a PR.

I'll try to write a script and share a gist of it. :)

**Comment by Skarlso** [comment]
Okay, so here is the gist: https://gist.github.com/Skarlso/5d579d6e236a694b11dcf49b75201776

And here is the pr it created: https://github.com/Skarlso/test/pull/28

And here is the result after running it in said repository: 

```
➜  test git:(main) ✗ git status
On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        file.txt
        main

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by gmlewis** [comment]
OK, I pointed it to my repo, and ran it and got this: https://github.com/gmlewis/my-test-repo/pull/10

```bash
go run commit.go
PR created: https://github.com/gmlewis/my-test-repo/pull/10
PR opened. Thank you for using Bundler, goodbye.
```

I'll have to go back and read the thread to see if that is correct or not... unless you see something right off.

**Comment by gmlewis** [comment]
However, note that this is a _completely unrelated_ git repo that I ran your command within... so I didn't expect it to do anything locally.  But maybe this is the issue you are talking about.

**Comment by gmlewis** [comment]
If this is true, then let me remind you that this repo is a Go client for the GitHub v3 API and is not _meant_ to manipulate local git repos... so I would not expect it to do anything locally.

With this client library, you are "remote-controlling" GitHub itself through its v3 API... you are not controlling or modifying a local git repository.

For that, you really do need a git client or https://github.com/go-git/go-git

Or am I still not understanding you correctly?

**Comment by Skarlso** [comment]
🤦 

No, you're right. :D I see now. Uh. I'm an idiot. :D Thank you @gmlewis for taking the time to point me to the error of my ways. :D

**Comment by gmlewis** [comment]
> facepalm
> 
> Uh. I'm an idiot. :D Thank you @gmlewis for taking the time to point me to the error of my ways. :D

No, you obviously are _not_ an idiot, as you are writing a very cool tool!

No problem at all... it is actually a common source of confusion... so don't give it another thought.  

Good luck to you, and keep up the great work!

**Comment by Skarlso** [comment]
Thank you! <3 Very much appreciate your words. :)
