### ISSUE TITLE
Issues created are not picked up by webhooks

### ISSUE THREAD

**Issue by Limess** [google/go-github#2377]
I've been pointed here by Github support due to the following issue:

When we open issues using go-github, they are not propagated to Slack via the official Github Slack notification.
An equivalent API call using cURL does propagate the issues as expected.

## Example

After subscribing to `issues` in Slack on a given github repository

`/github subscribe signal-ai/data-platform-documentation issues`

The following works, producing a slack message:
```
curl --location --request POST 'https://api.github.com/repos/signal-ai/data-platform-documentation/issues' --header 'Authorization: Bearer <token>' --header 'Content-Type: application/json' --data-raw '{"title":"Testing Notification","body":"I'\''m testing with this."}'
```

![Screenshot 2022-06-06 at 11-41-31 Issues · signal-ai_data-platform-documentation](https://user-images.githubusercontent.com/3199181/172147404-9ad1b3f1-e17b-4734-a447-3cc3e8903720.png)

but a request using the same Github API token does not produce a message in slack.

The code used to create issues using go-github is here: https://github.com/signal-ai/alertmanager-to-github/blob/5a031c0e8f9a5ff776b1c7002813d4cc60934532/pkg/notifier/github.go#L148=

```go
req := &github.IssueRequest{
	  Title:  &title,
	  Body:   &body,
	  Labels: &labels,
}
issue, response, err = n.GitHubClient.Issues.Create(ctx, owner, repo, req)
```

**Comment by gmlewis** [comment]
Can you please temporarily inject https://github.com/gmlewis/go-httpdebug
and see the equivalent curl command that is being issues, then report back with the differences?

**Comment by Limess** [comment]
Thanks for the suggestion @gmlewis, this revealed this is not a go-github bug, but a Github issue where if a newline exists in the title, the integration does not work.

Closing this, thanks again.
