### ISSUE TITLE
Teams.IsTeamRepoByID support for custom roles

### ISSUE THREAD

**Issue by joshuahancox** [google/go-github#2378]
Now that GitHub has created the custom roles feature, I think the implementation of Teams.IsTeamRepoByID (and BySlug) may need to be changed, or a new function added.

https://github.com/google/go-github/blob/master/github/teams.go#L411L427

Currently, we return a `repository` object, which contains information about which `permissions` the specified `team` has on the repository. 

e.g.
```json
    "permissions": {
        "admin": true,
        "maintain": true,
        "push": true,
        "triage": true,
        "pull": true
    }
```

However, the [API that we interact with](https://docs.github.com/en/rest/teams/teams#check-team-permissions-for-a-repository) here also returns the name of the role that is assigned to that team on that repository.

e.g
```json
    "role_name": "admin"
```

Previously this was not an issue, as it was possible to work out what the role name would be based on the permissions object. (since all role names are included there.) Now that custom roles are available, a role based on the `admin` role may be created, but with a custom name.

e.g.
```json
    "permissions": {
        "admin": true,
        "maintain": true,
        "push": true,
        "triage": true,
        "pull": true
    }
    "role_name": "super-admin"
```

Based on what is returned from this function currently, we cannot get the name of the role, and the permissions object looks identical to the one returned when the built-in `admin` role is assigned.

Should we extend the `Repository` type to include the `role_name`? It seems a bit strange to me that the `permissions` object is included there since that describes an assignment between a team and a repo rather than just an attribute of the repo. But if we wanted to follow that pattern would the change to include `role_name` make sense?

**Comment by joshuahancox** [comment]
I wondered if this function should really return a `Repository` struct at all? Since we're checking what permissions a specific team has on a specific repository, should we create/use a new struct like `TeamRepositoryPermissions`.

e.g.
```golang
type TeamRepositoryPermissions struct {
	Permissions         map[string]bool `json:"permissions,omitempty"`
	RoleName            *string `json:"role_name,omitempty"`
}
```

But understand that would be a breaking change so maybe not ideal.

**Comment by gmlewis** [comment]
Looking at the example response here: https://docs.github.com/en/rest/teams/teams#check-team-permissions-for-a-repository
I don't see how we cannot return a `Repository` struct.

For some reason, the GitHub v3 API team decided that all that information needed to be returned, so I don't think we want to discard the vast majority of it.

**Comment by joshuahancox** [comment]
OK sure, understood. That being the case I guess we have no choice but to include `role_name` in the exiting `repository` struct?

I'd also like to include the below function in `github-accessors.go`:

```golang
// GetRoleName returns the role_name field if it's non-nil, zero value otherwise.
func (r *Repository) GetRoleName() string {
	if r == nil || r.RoleName == nil {
		return ""
	}
	return *r.RoleName
}
```

If you agree, I'll raise a PR sometime today.

**Comment by gmlewis** [comment]
Yes, go ahead with a PR but do not manually edit the accessors file as it is autogenerated. Please read CONTRIBUTING.md for details.

**Comment by joshuahancox** [comment]
Ahh, I see. Thanks 😃 .

PR is here whenever you get a second.

https://github.com/google/go-github/pull/2379

**Comment by gmlewis** [comment]
> Thankyou @gmlewis! Any idea when your next release will be?

Right now: https://github.com/google/go-github/releases/tag/v45.1.0
:smile:

**Comment by joshuahancox** [comment]
Amazing! Thankyou
