### ISSUE TITLE
`code_scanning_alert` missing in `eventTypeMapping` 

### ISSUE THREAD

**Issue by emilva** [google/go-github#2391]
Hi team,

I am using `github.com/google/go-github/v45 v45.1.0` and I am getting the error `=unknown X-Github-Event in message: code_scanning_alert` when running `ParseWebHook`.

The alert type was already added in https://github.com/google/go-github/pull/2311 so I think it is just a matter of adding the mapping to the parsing of the webhook.

Cheers,

emil

**Comment by gmlewis** [comment]
Ah, yes, thank you, @emilva !
Would you like to submit a PR to rectify this, or shall I open it up to the rest of the contributors to this repo?

**Comment by emilva** [comment]
Yes, I will try to open PR shortly!

**Comment by emilva** [comment]
PR: https://github.com/google/go-github/pull/2392
