### ISSUE TITLE
Listing Repos doesn't include private repositories

### ISSUE THREAD

**Issue by pputman-clabs** [google/go-github#2396]
I'm using the following:

repos, _, err := client.Repositories.List(ctx, "my-org", nil) but its only printing out public repos.

I've also tried creating a repo options struct with visibility for private, even though it should print all by default, still no luck.

I know its not an authentication issue, because I can use

client.repositories.Get and pull down a private repo, so my oauth token is correct.

**Comment by gmlewis** [comment]
Please use https://github.com/gmlewis/go-httpdebug to validate that the `curl`-equivalent command operates as you expect, and then report back here with your findings and I can help you debug this.

**Comment by pputman-clabs** [comment]
Hi gmlewis,

Thank you for your reply.  I did that, and I'm getting the following.  I tried https://api.github.com/users/celo-org/repos?visibility=private in the browser authenticated and it still only shows public repos.  It seems I'm using the sdk right, but its using the wrong option to view private/public repos?

patrick@R90XQ0G937 github-scanner % go run main.go                                 
2022/06/23 15:21:22 curl -X GET \
  https://api.github.com/users/celo-org/repos?visibility=private \
  -H 'Accept: application/vnd.github.mercy-preview+json, application/vnd.github.nebula-preview+json' \
  -H 'Authorization: <REDACTED>' \
  -H 'User-Agent: go-github'
0x-monorepo: public
akeyless-token-from-JWT: public
algebra: public
blake2s-js: public
blind-threshold-bls-neon: public
blind-threshold-bls-wasm: public
blockscout: public
bls-crypto: public
bls-embedded: public
bls12377js: public

**Comment by gmlewis** [comment]
When creating a Personal Access Token here: https://github.com/settings/tokens/new
did you make sure to enable access to private repos?

![ksnip_20220623-205435](https://user-images.githubusercontent.com/6598971/175438764-fb45744d-fc3e-4088-8508-151f21aff67d.png)

**Comment by pputman-clabs** [comment]
Hello,

  I'm using oauth app tokens, but I did a Repository.Get to pull down a
private repo and it worked:

    //repos, _, err := client.Repositories.Get(ctx, "my-org",
"okta-live-config")

^^ This pulled down my repo, which is private, so its only the list that
doesn't work, meaning its not an authentication issue.

**Comment by gmlewis** [comment]
I just created a new personal access token, then wrote this program to test it out:

```go
package main

import (
	"context"
	"log"

	dbg "github.com/gmlewis/go-httpdebug/httpdebug"
	"github.com/google/go-github/v44/github"
	"golang.org/x/oauth2"
)

const SECRET = "..."

func main() {
	ts := oauth2.StaticTokenSource(
		&oauth2.Token{AccessToken: SECRET},
	)
	tc := oauth2.NewClient(oauth2.NoContext, ts)
	tp := dbg.New(dbg.WithTransport(tc.Transport))
	client := github.NewClient(tp.Client())
	ctx := context.Background()

	owner := "gmlewis"

	opts := &github.RepositoryListOptions{Visibility: "private", Type: "private"}
	repos, _, err := client.Repositories.List(ctx, owner, opts)
	if err != nil {
		log.Fatal(err)
	}

	for _, repo := range repos {
		log.Printf("repo: %v", repo.GetFullName())
	}
}
```

and I was also unable to list private repos.

Could you please contact GitHub v3 API Technical Support and report the problem, then report back here with their response?

Thank you!

**Comment by pputman-clabs** [comment]
Hi Glenn,

   So I'm not crazy!  Thank you so much for confirming its not working.
Yep, I'll reach out to them and let you know.

**Comment by gmlewis** [comment]
Actually, it looks like this is a recurring problem: #1382.

**Comment by pputman-clabs** [comment]
Hi Glenn,

  I got a message from github support.  the issue was I thought organizations just used the regular user endpoint.

<img width="807" alt="image" src="https://user-images.githubusercontent.com/99900942/176982185-c1ad3919-5c4f-4fcd-98d2-dc86725ac404.png">

**Comment by gmlewis** [comment]
Thank you for reporting back, @pputman-clabs .
Closing issue as resolved.

**Comment by wqsz7xn** [comment]
Running into this issue. I can't seem to find anything under the current go-github code for the following endpoint: https://docs.github.com/en/rest/repos/repos#list-organization-repositories
As mentioned the fetch endpoints are different but the org one don't seem supported in this project?

**Comment by gmlewis** [comment]
@wqsz7xn - are you looking for `client.Repositories.ListByOrg`?
https://github.com/google/go-github/blob/master/github/repos.go#L287-L313

**Comment by wqsz7xn** [comment]
My bad! Came across it when searching for the endpoint string. Thank you!
