### ISSUE TITLE
List CODEOWNERS errors

### ISSUE THREAD

**Issue by cbrgm** [google/go-github#2405]
Hi there,

I was wondering whether this endpoint is available in the google/go-github client.
https://docs.github.com/en/rest/repos/repos#list-codeowners-errors

If it's not the case, I'd be happy to contribute!

**Comment by gmlewis** [comment]
> If it's not the case, I'd be happy to contribute!

No, it doesn't appear to be.  Thank you, @cbrgm !  It's all yours.

**Comment by cbrgm** [comment]
@gmlewis It took me a while, but I finally found some time preparing a PR. I'm looking forward to a review sometime 😄 Happy weekend!
