### ISSUE TITLE
Cannot authenticate with Personal token

### ISSUE THREAD

**Issue by OlegGulevskyy** [google/go-github#2415]
Hi,
I am having the same issue, from the looks of it, as [here](https://github.com/google/go-github/issues/2396)
When I retrieve repositories, I only get public repositories.

This is the code I am using
```go
	ts := oauth2.StaticTokenSource(
		&oauth2.Token{AccessToken: GITHUB_PAT},
	)
	tc := oauth2.NewClient(context.Background(), ts)
	tp := dbg.New(dbg.WithTransport(tc.Transport))
	client := github.NewClient(tp.Client())
	ctx := context.Background()

	owner := "OlegGulevskyy"

	opts := &github.RepositoryListOptions{Visibility: "private", Type: "private"}
	repos, _, err := client.Repositories.List(ctx, owner, opts)
	if err != nil {
		log.Fatal(err)
	}

	for _, repo := range repos {
		log.Printf("repo: %v", repo.GetFullName())
	}
```
Where GITHUB_PAT = is the token from Settings, that starts with `ghp_...`
I have listed all possible permissions in the token
<img width="654" alt="image" src="https://user-images.githubusercontent.com/43781031/180489545-b1ee17a8-80cf-45dd-a812-445ff909873b.png">

The call looks like this I think

```
19:04:22 httpdebug.go:110: curl -X GET \
  https://api.github.com/users/OlegGulevskyy/repos?type=private&visibility=private \
  -H 'Accept: application/vnd.github.mercy-preview+json, application/vnd.github.nebula-preview+json' \
  -H 'User-Agent: go-github'
19:04:22 main.go:52: repo: OlegGulevskyy/alfred-github-go
19:04:22 main.go:52: repo: OlegGulevskyy/blog
19:04:22 main.go:52: repo: OlegGulevskyy/custom-zat-tools-docker
19:04:22 main.go:52: repo: OlegGulevskyy/friendly-waffle
19:04:22 main.go:52: repo: OlegGulevskyy/grep
19:04:22 main.go:52: repo: OlegGulevskyy/lite-grep
19:04:22 main.go:52: repo: OlegGulevskyy/mantine
19:04:22 main.go:52: repo: OlegGulevskyy/neovim-config
19:04:22 main.go:52: repo: OlegGulevskyy/tauri-docs
19:04:22 main.go:52: repo: OlegGulevskyy/tauri-plugin-store
19:04:22 main.go:52: repo: OlegGulevskyy/test-stuff
19:04:22 main.go:52: repo: OlegGulevskyy/trpc
19:04:22 main.go:52: repo: OlegGulevskyy/truegit-test
19:04:22 main.go:52: repo: OlegGulevskyy/uniqtools
19:04:22 main.go:52: repo: OlegGulevskyy/Zendesk-React-App-Boilerplate
19:04:22 main.go:52: repo: OlegGulevskyy/zendesk-vite-boilerplate

```
I don't see a token attached to the call.
Any ideas what am I doing wrong? Sorry in advance if I missed something obvious.

**Comment by OlegGulevskyy** [comment]
What is weird that if I mess up the token on purpose, I get `401` error of invalid credentials. So credentials are being checked by the library, I guess, but maybe just no used in the call?..

**Comment by OlegGulevskyy** [comment]
If I change options to
```go
opts := &github.RepositoryListOptions{Visibility: "all", Type: "all"}
```
I will get panic (I am pretty new to Go, just learning what's what)

```
19:31:00 httpdebug.go:110: curl -X GET \
  https://api.github.com/users/OlegGulevskyy/repos?type=all&visibility=all \
  -H 'Accept: application/vnd.github.mercy-preview+json, application/vnd.github.nebula-preview+json' \
  -H 'User-Agent: go-github'
19:31:01 main.go:39: 19
19:31:01 workflow.go:343: ------------------ FATAL ERROR -------------------
19:31:01 workflow.go:344: 19
 : goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x68
github.com/deanishe/awgo.(*Workflow).Run.func2()
	/Users/oleggulevskyy/go/pkg/mod/github.com/deanishe/awgo@v0.29.1/workflow.go:344 +0xc0
panic({0x10457b3c0, 0x14000331d40})
	/usr/local/go/src/runtime/panic.go:838 +0x204
log.Panicln({0x140002f5e60?, 0x1045db588?, 0x1400018a000?})
	/usr/local/go/src/log/log.go:399 +0x68
main.run()
	/Users/oleggulevskyy/Documents/dev/alfred-wfs/github-wf/main.go:39 +0x1e0
github.com/deanishe/awgo.(*Workflow).Run(0x140001c45a0, 0x1045d7a40)
	/Users/oleggulevskyy/go/pkg/mod/github.com/deanishe/awgo@v0.29.1/workflow.go:358 +0x294
main.main()
	/Users/oleggulevskyy/Documents/dev/alfred-wfs/github-wf/main.go:55 +0x34
```

**Comment by gmlewis** [comment]
To debug issues like this, it is tremendously helpful to see the equivalent `curl` commands that are being issued to the GitHub v3 API.

Then, if you can get a `curl` command to do what you want, we should be able to figure out how to get this client library to do the same thing.

An easy way to see the equivalent `curl` commands is to use: [https://github.com/gmlewis/go-httpdebug](https://github.com/gmlewis/go-httpdebug#go-httpdebug).

Please try it out and let me know if you discover anything through this process.

**Comment by OlegGulevskyy** [comment]
Thanks for getting back to me @gmlewis  !
I found out what's causing this by looking into the code that makes request and I should have not provided my GitHub hander and just pass an empty string
```go
	if user != "" {
		u = fmt.Sprintf("users/%v/repos", user)
	} else {
		u = "user/repos"
	}
```
However the only feedback here is that it's not intuitive at all. When I call `Repositories.List` I am not expecting it to jungle inside different endpoints and returning completely different results based on logical branching.
Apart from that - it's working :)
Thanks

**Comment by gmlewis** [comment]
> However the only feedback here is that it's not intuitive at all.

I'm glad you found and fixed the problem, and I apologize for the frustration, @OlegGulevskyy .

We would love to improve our documentation to help people using this client library and hopefully prevent problems before they occur.

If you can think of ways to improve the documentation or make the developer experience better, we truly welcome PRs.  Thank you!
