### ISSUE TITLE
Add support for simple enum values

### ISSUE THREAD

**Issue by alshdavid** [google/go-github#2426]
In Go you can assign constants but when you have many they tend to:
- Pollute the global namespace with many values
- Can become confusing if you have multiple "groups" of constants flattened on the namespace (think status codes + common headers)
- Requiring compile-time validation of values through a repetitive, non-performant operation

Objective:
```go
package main

import (
	"fmt"
)

type MyType string

const (
	A MyType = "A"
	B MyType = "B"
	C MyType = "C"
)

// foo can accept any string however ideally you'd want to check the value it's passed 
// matches an item within the the constants group you consider it belonging to
func foo(bar MyType) {
	fmt.Println(bar)
}

func main() {
	foo(A)
	foo("D")
}
``` 

A common way around this is to use a runtime validation strategy, however it's still a bit cumbersome and you tend to have a lot of package namespace pollution (imagine if you wanted to collect a list of common HTTP header names, header values and status codes - or all of the country codes in the iso spec, or all the currency codes in the iso spec. The package namespace would be nothing but constants).

```go
type MyType int

const (
	A MyType = iota
	B
	C
)

func GetMyType(v MyType) (string, error) {
	switch v {
	case 0:
		return "A", nil
	case 1:
		return "B", nil
	case 2:
		return "C", nil
	default:
		return "", fmt.Errorf("Not found")
	}
}

func foo(bar MyType) {
	fmt.Println(GetMyType(bar))
}

func main() {
	foo(A)
	 foo("D")
}

```

You can also group properties in Go using duck-typed structs - however they are heap allocated and still require runtime validation.
```go
var TooType = struct {
  A string
  B string
  C string
}{"A",  "B", "C"}
```

If Go could introduce a method to group constants (simple values) and allow for value types which can be validated at compile time, that would improve the performance and management of Go applications that require the use of grouped constants that require validation.

_Note: I don't know how to include it without adding a new keyword, that's the magic of the brilliant people behind Go, so I will just suggest it using my own pseudo-syntax_

```Go
const StatusCode = enum {
  OK int = 200
  NoContent = 201
  NotFound = 404
}

func foo(f StatusCode) {}
func bar(f int) {}

func main() {
  fmt.Println(StatusCode.OK) // "200"
  foo(StatusCode.OK) // valid
  foo(200) // Invalid, must come from group
  bar(StatusCode.OK) // valid
}
```

**Comment by gmlewis** [comment]
It almost sounds like you are proposing a change to the Go programming language here, which unfortunately not the correct location to do so.

This repo is a client library to the GitHub v3 API using the Go programming language.

If you wish to propose changes to the Go programming language, I suggest you start here:
https://github.com/golang/proposal

Closing issue.
