### ISSUE TITLE
Unable to create empty file

### ISSUE THREAD

**Issue by Ashvin-Ranjan** [google/go-github#2427]
When attempting to commit an empty file to a repository using `ghClient.Repositories.CreateFile` and passing in `[]byte{}` under the `Content` field of a `github.RepositoryContentFileOptions` the GitHub API will return a `422` error stating that `content` was not supplied. This is most likely due to the line:

https://github.com/google/go-github/blob/7a7a7f0943f3fcffc4b8f30feaaed7333b035a99/github/repos_contents.go#L54

Which adds `omitempty` to the `Content` field of `github.RepositoryContentFileOptions`, even though it is a necessary field of the request.

**Comment by gmlewis** [comment]
Have you tried calculating the SHA of an empty byte slice?

```bash
$ touch bogus
$ shasum bogus
da39a3ee5e6b4b0d3255bfef95601890afd80709  bogus
$ ls -la bogus
-rw-rw-r-- 1 glenn glenn 0 Aug  1 19:06 bogus
```

Try passing in this SHA when your file is empty and see if that works.

**Comment by Ashvin-Ranjan** [comment]
That does not work, I continue to get a `422` from the GitHub API because the `"content"` field was not supplied, here is the error message I get:

```
PUT https://api.github.com/repos/OWNER/REPO/contents/FILE: 422 Invalid request.

"content" wasn't supplied.
```

**Comment by gmlewis** [comment]
OK, gotcha. Then I think we have a bug that needs to be fixed. My main concern is that we don't break existing behavior where `content` should not be passed.

Do you want to submit a PR or would you like me to open this up to other contributors to this repo to address?

**Comment by Ashvin-Ranjan** [comment]
I do not think there should be any problems with breaking existing behavior with this because looking at the [update file contents endpoint](https://docs.github.com/en/rest/repos/contents#create-or-update-file-contents) it does appear that they label the `content` field required, unless I am mistaken. Also I can submit a PR for this. Thank you for your help.
