### ISSUE TITLE
IssueActivityEvent struct is missing the label field

### ISSUE THREAD

**Issue by tchap** [google/go-github#243]
In case the event action is `labeled`, there is a `label` object included in the webhook. This is not accessible through `IssueActivityEvent` in any way. It should include `Label *Label` with `json:"label"`. Or is some other struct supposed to be used to unmarshal that webhook?

**Comment by bithavoc** [comment]
:+1:

**Comment by gmlewis** [comment]
`IssueActivityEvent` is deprecated. Please use `IssuesEvent` instead which does have a `Label *Label` field. I recommend closing this issue.
