### ISSUE TITLE
Additional options available for pull request reviews / branch protection rules

### ISSUE THREAD

**Issue by Starttoaster** [google/go-github#2431]
One such rule that is currently not supported is `bypass_pull_request_allowances` (https://docs.github.com/en/rest/branches/branch-protection#update-pull-request-review-protection)

The library should be updated to include additional fields.

I'm more than happy to take a stab at doing this myself as a first contribution, just using this Issue to document the request.

**Comment by gmlewis** [comment]
Thank you, @Starttoaster !
It's yours.
