### ISSUE TITLE
Release Request

### ISSUE THREAD

**Issue by gesellix** [google/go-github#2436]
Is it possible to create a release?

I'm mainly interested in #2407 (breaking api change) to be available for the [integrations/terraform-provider-github](https://github.com/integrations/terraform-provider-github/).

**Comment by gmlewis** [comment]
Yes, I'll start working on it.

**Comment by gmlewis** [comment]
@gesellix - https://github.com/google/go-github/releases/tag/v46.0.0 has been released.

**Comment by gesellix** [comment]
That's fast! Thanks a lot!
