### ISSUE TITLE
Support Autolinks with alphanumeric or numeric IDs

### ISSUE THREAD

**Issue by douglascayers** [google/go-github#2449]
GitHub updated their [autolink feature](https://github.blog/changelog/2022-08-31-autolinks-with-alphanumeric-or-numeric-ids/) to support either alphanumeric or numeric IDs.

This is a request to add support for the new `is_alphanumeric: boolean` argument, which indicates whether this autolink reference matches alphanumeric characters. If false, this autolink reference is a legacy autolink that only matches numeric characters.

Example Payload:
```json
{
  "id": 1,
  "key_prefix": "TICKET-",
  "url_template": "https://example.com/TICKET?query=<num>",
  "is_alphanumeric": true
}
```

---

I'm interested in working on adding this feature. I'm a complete `go` novice, so I'm thankful 99% of the work for calling this API is already done 😅 

Thanks!

**Comment by gmlewis** [comment]
Welcome to Go and to this repo, @douglascayers - and thank you in advance for your contributions! :smile:
