### ISSUE TITLE
Segfault when using Filter and ListOptions at the same time with Issues.List

### ISSUE THREAD

**Issue by niwla23** [google/go-github#2456]
```go
opt := &github.IssueListOptions{
	Filter:      "all",
	Sort:        "updated",
	ListOptions: github.ListOptions{PerPage: 10},
}

issues, resp, err := client.Issues.List(ctx, true, opt)
```

this lead to the following error:

``` 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x652c15]

goroutine 1 [running]:
todo_aggregator/src/providers.GetTasksFromGithub(0x0?)
        /mnt/ssd2/trash/todolist aggregator/backend/src/providers/github.go:46 +0x2d5
main.main()
        /mnt/ssd2/trash/todolist aggregator/backend/src/main.go:14 +0x6a
exit status 2
```

When removing `Filter` it works as well as when removing ListOptions. It works with e.g. ListOptions and Sort.

**Comment by niwla23** [comment]
When setting Filter to "assigned" (the default value) it works. Settomg it to mentioned gives no results for me (empty list). All other options lead to the error

**Comment by gmlewis** [comment]
What does this line look like: `aggregator/backend/src/providers/github.go:46` ?
Are you sure the panic is happening within this repo?

**Comment by niwla23** [comment]
Oh sorry, I totally missed that. For some reason I was convinced that the error happened in the List method. 
Actual issue was that I was not checking for nil pointers in Body and State of the issues
