### ISSUE TITLE
Missing option to Create Pull Request as Draft

### ISSUE THREAD

**Issue by isaacismaelx14** [google/go-github#2479]
It's looks like there is not any way to create a new PR as a Draft. 

This is the current `NewPullRequest`  interface

https://github.com/google/go-github/blob/v17.0.0/github/pulls.go#L188
```go
type NewPullRequest struct {
	Title               *string `json:"title,omitempty"`
	Head                *string `json:"head,omitempty"`
	Base                *string `json:"base,omitempty"`
	Body                *string `json:"body,omitempty"`
	Issue               *int    `json:"issue,omitempty"`
	MaintainerCanModify *bool   `json:"maintainer_can_modify,omitempty"`
}
```

I think this only need to add the Draft option to the interface like: 
```go
type NewPullRequest struct {
	Title               *string `json:"title,omitempty"`
	Head                *string `json:"head,omitempty"`
	Base                *string `json:"base,omitempty"`
	Body                *string `json:"body,omitempty"`
	Issue               *int    `json:"issue,omitempty"`
	Draft               *bool   `json:"draft,omitempty"` // <- this line
	MaintainerCanModify *bool   `json:"maintainer_can_modify,omitempty"`
}
```

There is the Github API Rest Documentation:
https://docs.github.com/en/rest/pulls/pulls#create-a-pull-request

**Comment by gmlewis** [comment]
Version `v17.0.0` is quite a long time ago.  You probably want a more recent version:
https://github.com/google/go-github/blob/master/github/pulls.go#L244-L252

**Comment by isaacismaelx14** [comment]
@gmlewis After creating a folk I realized that! Thanks
