### ISSUE TITLE
unable to update the or specific version from 1.14.2 go version

### ISSUE THREAD

**Issue by raja444** [google/go-github#2481]
I need 1.18.2 or 1.18 -   crypto and sys packages.
I m trying to update from 1.14.2 version.
unable to update the or get specific packages.

go get -v golang.org/x/crypto/ed25519 
go get -v golang.org/x/sys/unix

or 

go install -v golang.org/x/crypto/ed25519 
go install -v golang.org/x/sys/unix

Tried to list the package as well. it shows nothing
go list -m -versions github.com/golang/sys/unix

Tried to perform below operations , tried other possible paths as well.
go install -v github.com/golang.org/x/crypto/ed25519@v1.18.2
go install -v github.com/golang.org/x/sys/unix@v1.18.2
or
go install -v github.com/golang.org/x/crypto/ed25519@v1.18
go install -v github.com/golang.org/x/sys/unix@v1.18

could you please help me on this?
how to get the specific crypto and sys packages from 1.18.2 or 1.18???

**Comment by gmlewis** [comment]
This issue isn't related to this repo, but this works for me when you are in a directory containing a valid `go.mod` file:

```bash
$ mkdir test
$ cd test
$ go mod init example.com/mymodule
go: creating new go.mod: module example.com/mymodule
$ go get golang.org/x/crypto/ed25519@latest
go: downloading golang.org/x/crypto v0.0.0-20220926161630-eccd6366d1be
go: added golang.org/x/crypto v0.0.0-20220926161630-eccd6366d1be
$ go get golang.org/x/sys/unix@latest
go: downloading golang.org/x/sys v0.0.0-20220927170352-d9d178bc13c6
go: upgraded golang.org/x/sys v0.0.0-20210615035016-665e8c7367d1 => v0.0.0-20220927170352-d9d178bc13c6
```

But maybe you should take a moment and read this: https://go.dev/ref/mod
Closing.

**Comment by raja444** [comment]
I m able to get the latest code but **the problem is unable to update 1.18.2 or 1.18 version code from 1.1.4.2**

could you please resolve this ?

**Comment by gmlewis** [comment]
@raja444 - If you want help, you need to provide more information... however if your problem does not involve this repo, then this is the wrong place to be asking for help, and a Google search would probably be more fruitful.

Did you read the link I pointed you to about Go modules? That one document should answer your questions.

What do your "1.18.2, 1.18, and 1.1.4.2" version numbers represent?
What do those numbers have to do with this repo?
