### ISSUE TITLE
Error with otp in scrape example 

### ISSUE THREAD

**Issue by nettrino** [google/go-github#2483]
Hello, 

I am trying to replicate the [scrape example](https://github.com/google/go-github/blob/master/scrape/example/scrape/main.go) and if I use the OTP from an authenticator app (Google, Authy or otherwise) I get `panic: decode secret failed`, and if I use my yubikey I get `received 422 response submitting otp form`. Anything I am missing on how otp should be passed?

Thanks!

**Comment by gmlewis** [comment]
Sorry, I am not very familiar with the scrape example. Hopefully someone else with more experience can comment on this issue.

**Comment by nettrino** [comment]
Thanks @gmlewis. I've created a wrapper using rsc.io/2fa as a temporary quickfix (some of the classes in scraping are outdated anyhow due to selectors having changed (e.g., `.oath-application-allowlist` instead of `whitelist`) so I had to make changes to the scrape package anyhow). The process for registering the token was to run `go install rsc.io/2fa@latest` and then register github using `2fa -add github`. Subsequently, in the github 2fa settings, instead of scanning the QR code, select the "text key" option, and paste that to the CLI. From that point on, `2fa github` should give you an OTP. I modified the `Authenticate` function to patch the otp part directly passing hte output from 2fa:
```golang
	setOTP := func(values url.Values) {
		values.Set("otp", otpcode)
	}
```

Hopefully the above is useful, I can try and make a PR if you think the above flow makes sense, however waiting for someone else from the maintainers to comment on this.

**Comment by nettrino** [comment]
@gmlewis the code in the repo for the login part works fine. We don't need to register a separate 2fa as I mentioned in my previous comment all we need to do is when subscribing to github, _before scanning the QR code_ select the text key option, and then get the secret key and pass that as an input for the OTP seed if that makes sense. Thus we would scan the QR code via the app, and use the secret key to bootstrap the OTP for any CLI use. Don't know why I had gotten confused previously about this. Are you open for Wiki / Readme PRs for this? I can add steps with screenshots for documentation

**Comment by nettrino** [comment]
@gmlewis opened https://github.com/google/go-github/pull/2488 to address the outdated selector issue
