### ISSUE TITLE
RepositoryCreateForkOptions is should be body parameters

### ISSUE THREAD

**Issue by valbeat** [google/go-github#2489]
Hi Team!
RepositoryCreateForkOptions is not working. because it is not url params but body params. 
[docs.github.com/en/rest/repos/forks#create-a-fork](https://docs.github.com/en/rest/repos/forks#create-a-fork)

Sorry I didn't realize this when I added it before.

I will create a pull request for this issue. 
Thanks.

**Comment by TruRelax** [comment]
@valbeat Any progress on this issue?

**Comment by valbeat** [comment]
@TruRelax it is awaiting review. could you review this one? https://github.com/google/go-github/pull/2490
