### ISSUE TITLE
Add support to create / update / delete custom roles for organisations

### ISSUE THREAD

**Issue by mohaldu** [google/go-github#2493]
API can be found here - https://docs.github.com/en/rest/orgs/custom-roles#create-a-custom-role

I plan on working on this feature

**Comment by mohaldu** [comment]
Hi @gmlewis , could we have this released? We would like to leverage the new API in the terraform github provider.

**Comment by gmlewis** [comment]
> Hi @gmlewis , could we have this released? We would like to leverage the new API in the terraform github provider.

Yes, I'll work on a new release.

**Comment by gmlewis** [comment]
This has been released here: https://github.com/google/go-github/releases/tag/v48.0.0
