### ISSUE TITLE
Support for discussion_comment

### ISSUE THREAD

**Issue by lionelvillard** [google/go-github#2497]
The event discussion_comment is not supported yet. See https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#discussion_comment for more information

**Comment by gmlewis** [comment]
Thanl you, @lionelvillard . Would you like to create a PR to address this or would you like me to open this up to other contributors of this repo?

**Comment by qascade** [comment]
Hi, if no body else is working on this. May I take a look at this issue?

**Comment by lionelvillard** [comment]
thanks @qascade !!

**Comment by apurwaj2** [comment]
I would like to take this up. I've already started working on it. Let me know if that should be okay.

**Comment by gmlewis** [comment]
> I would like to take this up. I've already started working on it. Let me know if that should be okay. @gmlewis Could you please assign it to me?

@qascade - are you OK with this?

**Comment by qascade** [comment]
Sure, should not keep blocked for long time. I suddenly got health emergency back when this was assigned to me. Couldn't pick it up again.

**Comment by gmlewis** [comment]
> Sure, should not keep blocked for long time. I suddenly got health emergency back when this was assigned to me. Couldn't pick it up again.

Thank you, @qascade !
OK, @apurwaj2 - the issue is yours.  Thank you!

**Comment by gmlewis** [comment]
Oh, and I hope you feel better fast, @qascade !
