### ISSUE TITLE
Repositories.ListCommitActivity throwing Unmarshal error: 

### ISSUE THREAD

**Issue by hblankenship** [google/go-github#2510]
json: cannot unmarshal object into Go value of type []*github.WeeklyCommitActivity

more info:
*encoding/json.UnmarshalTypeError {Value: "object", Type: reflect.Type(*reflect.rtype) *{size: 24, ptrdata: 8, hash: 3339529106, tflag: tflagExtraStar (2), align: 8, fieldAlign: 8, kind: 23, equal: nil, gcdata: *1, str: 78188, ptrToThis: 93696}, Offset: 1, Struct: "", Field: ""}

code used was simple: ws, _, err := client.Repositories.ListCommitActivity(ctx, owner, repo)

OS: MacOS 12.1
Chip: Apple M1
Golang version: 1.19.2

**Comment by gmlewis** [comment]
Thank you, @hblankenship , for the reported issue.

Would you like to create a PR, or shall I open this issue up to any other contributor to this repo to address the problem?

**Comment by hblankenship** [comment]
You can open it up. Thanks.

**Comment by gmlewis** [comment]
Thank you, @hblankenship.

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

**Comment by akshit2410** [comment]
Hello, 

I am freshly new to open source.
I wanted to know more about this issue and how to set up and run this repo on my local.

Thanks.

**Comment by gmlewis** [comment]
> Hello,
> 
> I am freshly new to open source. I wanted to know more about this issue and how to set up and run this repo on my local.
> 
> Thanks.

Step one: completely read through our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md).
Step two: if you still have specific questions, please feel free to post them here.

**Comment by akshit2410** [comment]
I have gone through CONTRIBUTING.md and have also completed cloning, run three commands generate, test, vet.
I can see that the update-urls folder has the main.go file which will be the entry point for the project.
I wanted how I can run that on my local or if there is some way to do it as I can't do it with go run main.go cmd.

**Comment by gmlewis** [comment]
This repo is a client library to access the GitHub v3 API.  As a result, there is really nothing locally for you to run, per-se, unless you want to take a look at the examples found in the "examples" directory, but really those are not intended for you to run them like a demo... they are just examples of things you can accomplish with this client library.

I hope that helps set expectations for what this repo is for.

**Comment by gmlewis** [comment]
> I can see that the update-urls folder has the main.go file which will be the entry point for the project.

No, that is not correct.  If you read the provided documentation for `update-urls`, it says:

```go
// update-urls updates GitHub URL docs for each service endpoint.
//
// It is meant to be used periodically by go-github repo maintainers
// to update stale GitHub Developer v3 API documentation URLs.
```

There is no demo for you to run.

**Comment by akshit2410** [comment]
So for example, I find and write a fix for this issue related to ListCommitActivity , and now i have to check that my fix will give the desired output how will i accomplish that test ?

**Comment by gmlewis** [comment]
You could write a very small Go program that calls your modified endpoint and operates on one of your own personal repos to test it out.

**Comment by akshit2410** [comment]
Okay so basically I have to get my fixed merged in the client library first for that as there is no way to run it locally .
am I understanding this correctly?

**Comment by gmlewis** [comment]
No. You simply create a branch locally and make your change. Then create a go program anywhere else on your system and point it to your local repo by using "replace" in the `go.mod` file.

See documentation here: https://go.dev/ref/mod#:~:text=A%20replace%20directive%20replaces%20the,a%20platform%2Dspecific%20file%20path.

**Comment by krishnaindani** [comment]
is thi issue being worked on else I would like to give a shot?

**Comment by gmlewis** [comment]
> is this issue being worked on else I would like to give a shot?

Well, from the above conversation, I got the impression that @akshit2410 wants to work on this one. Let's give time for @akshit2410 to let us know if this is true.

**Comment by krishnaindani** [comment]
> > is this issue being worked on else I would like to give a shot?
> 
> Well, from the above conversation, I got the impression that @akshit2410 wants to work on this one. Let's give time for @akshit2410 to let us know if this is true.

sure thing. sounds good

**Comment by akshit2410** [comment]
@krishnaindani  please go ahead and give it a try, I am more inclined towards understanding things better before making any contributions. I will be trying to come up with a solution and will also learn from the solution you will provide.
Thanks.

**Comment by gmlewis** [comment]
Thank you, @akshit2410 !

@krishnaindani - this issue is yours. Thank you!

**Comment by krishnaindani** [comment]
> Thank you, @akshit2410 !
> 
> @krishnaindani - this issue is yours. Thank you!

Thank you, I will start working on this first by duplicating these errors and working on the fix and will post questions if I have meanwhile

**Comment by krishnaindani** [comment]
I have started to work on this, I see this behavior and its looks quite random. 

I get the results back with no error and sometimes it throws unmarshalling error 

`json: cannot unmarshal object into Go value of type []*github.WeeklyCommitActivity` . 

@hblankenship are you seeing unmarshalling error everytime or is that quite random?

@gmlewis I am still thinking and looking why is this behaviour but would you be able to provide any guidance to this?

**Comment by krishnaindani** [comment]
Here is more context on this:

So when it returns the 200 status code that means we get the response data and it is able to unmarshall the response. 

The error is when we get the status code 202 when the response is not ready and we get the error `job scheduled on GitHub side; try again later`

Here it looks like `ListCommitActivity` method uses `Do` method https://github.com/google/go-github/blob/master/github/repos_stats.go#L96 which is in turn calling `BareDo` which handles AcceptedError https://github.com/google/go-github/blob/43edea6a5df60596c9eca2f69d4a85b2394180f4/github/github.go#L703 here. I am bit confused here with this checkResponse function with the AcceptedError

**Comment by krishnaindani** [comment]
> I have started to work on this, I see this behavior and its looks quite random.
> 
> I get the results back with no error and sometimes it throws unmarshalling error
> 
> `json: cannot unmarshal object into Go value of type []*github.WeeklyCommitActivity` .
> 
> @hblankenship are you seeing unmarshalling error everytime or is that quite random?
> 
> @gmlewis I am still thinking and looking why is this behaviour but would you be able to provide any guidance to this?

Update on this: I was running this on old github package version

**Comment by krishnaindani** [comment]
> Here is more context on this:
> 
> So when it returns the 200 status code that means we get the response data and it is able to unmarshall the response.
> 
> The error is when we get the status code 202 when the response is not ready and we get the error `job scheduled on GitHub side; try again later`
> 
> Here it looks like `ListCommitActivity` method uses `Do` method https://github.com/google/go-github/blob/master/github/repos_stats.go#L96 which is in turn calling `BareDo` which handles AcceptedError
> 
> https://github.com/google/go-github/blob/43edea6a5df60596c9eca2f69d4a85b2394180f4/github/github.go#L703
> 
> here. I am bit confused here with this checkResponse function with the AcceptedError

I ran this with `v48` version and it looks good to me when the respons is not ready it throws 202 and error `job scheduled on GitHub side; try again later`. 

@hblankenship which package version are you using? I believe if you are using old version you might see this behaviour

**Comment by hblankenship** [comment]
I think you are right. Updated package and just receiving the standard 202 or 404, depending on the timing. The error seems to be gone (fwiw, it looks like I had installed a default 'incompatible' package...). It won't be the last time, I am sure.

**Comment by gmlewis** [comment]
Thanks, @krishnaindani and @hblankenship - I'm thinking this issue can safely be closed.  Agreed?

**Comment by krishnaindani** [comment]
> Thanks, @krishnaindani and @hblankenship - I'm thinking this issue can safely be closed. Agreed?

yes I feel can be closed
