### ISSUE TITLE
github.Client is not safe for concurrent use; is that intended or a bug?

### ISSUE THREAD

**Issue by shurcooL** [google/go-github#253]
From https://godoc.org/net/http:

> Clients and Transports are safe for concurrent use by multiple goroutines and for efficiency should only be created once and re-used.

https://godoc.org/github.com/google/go-github/github#Client makes no such claims, which is why I'm unsure if this is a bug or intended behavior.

However, given that it looks and feels a lot like `http.Client`, I thought it might also support concurrent use by multiple goroutines and for efficiency should only be created once and re-used.

That's not the case. If you look at the source of [`github.Client.Do`](https://github.com/google/go-github/blob/44b1ede22d71e26fa5d7af7a50204f7e6daadfc8/github/github.go#L310):

```
c.Rate = response.Rate
```

It writes to `c.Rate` without any mutexes, which is not safe and will cause data races:

```
WARNING: DATA RACE
Write by goroutine 93:
  github.com/google/go-github/github.(*Client).Do()
      .../src/github.com/google/go-github/github/github.go:310 +0x16b
```

Is that intended, or is this a bug?

If I want to make concurrent calls to GitHub API via multiple goroutines, should I create multiple `github.Client`s?

**Comment by willnorris** [comment]
It's certainly the case that a single client shouldn't be used to make calls on behalf of different users, since in most cases the auth token is baked into the `oauth2.Transport`.  As for data races surrounding c.Rate, that's a bug which I'd happily merge a patch for.  I don't know if there are other such race conditions, as I haven't used this myself to make concurrent calls very often.

**Comment by shurcooL** [comment]
I see, thanks.

I want to make use of a single GitHub client for the same GitHub user/auth token, not different ones.

I'll try to make a patch and see if I find any other race conditions.

**Comment by shurcooL** [comment]
> As for data races surrounding c.Rate, that's a bug which I'd happily merge a patch for. I don't know if there are other such race conditions, as I haven't used this myself to make concurrent calls very often.

I've made such a patch locally and have been using/testing it for the last week or two, and I haven't spotted any other issues with concurrency.

I've created PR #255 with it.
