### ISSUE TITLE
use go-github API clone a repo.

### ISSUE THREAD

**Issue by czxichen** [google/go-github#254]
How do I use go-github API clone a repo?

**Comment by willnorris** [comment]
you generally  wouldn't use go-github for that.  go-github is a client for the [GitHub API](https://developer.github.com/v3/), not the git protocol.  

If you don't mind using cgo, [libgit2/git2go](https://github.com/libgit2/git2go) provides go bindings for libgit2, which is a very complete git library.  There's also [gogits/git](https://github.com/gogits/git) which is pure go, but I think it is focused on manipulating a git repo on disk... I'm not sure that it supports cloning.

**Comment by czxichen** [comment]
Thanks.
