### ISSUE TITLE
Users.Get(): An attempt was made to access a socket in a way forbidden by its access permissions

### ISSUE THREAD

**Issue by CravateRouge** [google/go-github#2555]
When attempting to call `(github.NewEnterpriseClient(apiEndpoint, apiEndpoint, tc)).Users.Get(context.TODO(), ""))` I have the following error:
```
Get \"https://<github endpoint>/api/v3/user\": dial tcp <ip address>: connectex: An attempt was made to access a socket in a way forbidden by its access permissions.
```

I don't understand why this error is happening because this function doesn't need to bind to any port of my Windows right? Could someone enlighten me on the subject?

**Comment by gmlewis** [comment]
The `baseURL` should be the base URL of your GitHub Enterprise server, and _that_ server is most likely the one that is complaining. You first need to verify that you got the `baseURL` of your server correct. If it is correct, then try a `curl` command against it and see if you can get a successful response.

When debugging problems like this, it is sometimes helpful to get a dump of the equivalent `curl` command being called using something like https://github.com/gmlewis/go-httpdebug#go-httpdebug

**Comment by CravateRouge** [comment]
Thank you for taking time answering me. After more investigation I noticed it's more an issue about untrusted/trusted software on my system. For example `(WebRequest.Create("https://<github endpoint>")).GetResponse()` will fail in an executable but will work as a powershell object.
