### ISSUE TITLE
Support users and teams in branch protection access restrictions

### ISSUE THREAD

**Issue by jporzucek** [google/go-github#2560]
At the moment only `App` type users are supported in CRUD operations on branch protection restrictions, for example: https://docs.github.com/en/rest/branches/branch-protection#get-apps-with-access-to-the-protected-branch

`Users` and `Teams` type users should also be supported to stay up to date with GitHub REST API docs.

**Comment by gmlewis** [comment]
Thanks, @jporzucek . Do you want to create a PR or would you like this issue to be opened up to other contributors of this repo?
