### ISSUE TITLE
[Question] about the "struct field" or "func parameter" pointer or not

### ISSUE THREAD

**Issue by mamh2021** [google/go-github#2563]
Hi, all,

I have some questions about some questions about the "struct field" or "func parameter" pointer or not,

I found that all outputs are of pointer type  which is no doubt.

# Question 1

but some xxxOptions struct sometimes the pointer was used, sometimes not, most are non pointer types.

but like below struct ListCheckRunsOptions
```
// ListCheckRunsOptions represents parameters to list check runs.
type ListCheckRunsOptions struct {
	CheckName *string `url:"check_name,omitempty"` // Returns check runs with the specified name.
	Status    *string `url:"status,omitempty"`     // Returns check runs with the specified status. Can be one of "queued", "in_progress", or "completed".
	Filter    *string `url:"filter,omitempty"`     // Filters check runs by their completed_at timestamp. Can be one of "latest" (returning the most recent check runs) or "all". Default: "latest"
	AppID     *int64  `url:"app_id,omitempty"`     // Filters check runs by GitHub App ID.

	ListOptions
}
```

and this struct ListCheckSuiteOptions
```
// ListCheckSuiteOptions represents parameters to list check suites.
type ListCheckSuiteOptions struct {
	CheckName *string `url:"check_name,omitempty"` // Filters checks suites by the name of the check run.
	AppID     *int    `url:"app_id,omitempty"`     // Filters check suites by GitHub App id.

	ListOptions
}
```
and this struct HeadSHA is not pointer, but HeadBranch is pointer.
```
// CreateCheckSuiteOptions sets up parameters to manually create a check suites
type CreateCheckSuiteOptions struct {
	HeadSHA    string  `json:"head_sha"`              // The sha of the head commit. (Required.) ?????? ????????????
	HeadBranch *string `json:"head_branch,omitempty"` // The name of the head branch where the code changes are implemented.
}
```

and like this one is ` Permission *string ` and another is ` Permission string ` 
```
type TeamProjectOptions struct {
	Permission *string `json:"permission,omitempty"`
}

type TeamAddTeamRepoOptions struct {
	Permission string `json:"permission,omitempty"`
}
```

# Question 2 

and as func parameter  I found the xxxOptions sometimes the pointer is used, sometimes not,

```

func (c *Client) Markdown(ctx context.Context, text string, opts *MarkdownOptions) (string, *Response, error) {

```
this below opts is not pointer type:
```

this opts pass to client.NewRequest() func,  but use &opts then pass to NewRequest()
func (s *RepositoriesService) Dispatch(ctx context.Context, owner, repo string, opts DispatchRequestOptions) (*Repository, *Response, error) {

// this opts pass to client.NewRequest() func, 
func (s *ChecksService) CreateCheckRun(ctx context.Context, owner, repo string, opts CreateCheckRunOptions) (*CheckRun, *Response, error) {
func (s *ChecksService) UpdateCheckRun(ctx context.Context, owner, repo string, checkRunID int64, opts UpdateCheckRunOptions) (*CheckRun, *Response, error) {
func (s *ChecksService) SetCheckSuitePreferences(ctx context.Context, owner, repo string, opts CheckSuitePreferenceOptions) (*CheckSuitePreferenceResults, *Response, error) {


// this opts not to NewRequest () or not to addOptions() 
func (s *PullRequestsService) GetRaw(ctx context.Context, owner string, repo string, number int, opts RawOptions) (string, *Response, error)

// this opts pass to client.NewRequest() func, 
func (s *TeamsService) CreateTeam(ctx context.Context, org string, team NewTeam) (*Team, *Response, error) {

```

Why is there such a difference?

I'm looking forward to your reply,Thank you.

**Comment by gmlewis** [comment]
To simplify access to fields, we recommend using the auto-generated accessors, thereby making it essentially irrelevant whether they are pointers or not.

As to reasoning for pointers versus not pointers, structs used for requests typically need pointers to optionally not send the respective fields.

However, on the receive side, we use pointers for structs to facilitate iteration... There is a closed issue that discuss this if you want to search for it. For simple fields, though, it is simply a matter that the official GitHub documentation has not historically always been clear about when a field is going to be populated and returned versus when it will not. Therefore, using pointers is the only way in Go to determine if the field was actually sent back or not from the server.

I hope this helps. If you have no other questions, I believe this issue can be closed.

**Comment by mamh2021** [comment]
Thank you very much.
