### ISSUE TITLE
Release Request

### ISSUE THREAD

**Issue by jeremyhayes** [google/go-github#2565]
🙏 Apologies if this is not the appropriate forum for such a request, but can we get a new release created?

I'd like to use https://github.com/google/go-github/pull/2530 on a downstream change in https://github.com/integrations/terraform-provider-github/issues/1210

**Comment by gmlewis** [comment]
Yes, I can work on putting together a release.

**Comment by gmlewis** [comment]
This release contains the changes you requested: https://github.com/google/go-github/releases/tag/v48.1.0

Closing issue as resolved.
