### ISSUE TITLE
getting "json: unsupported type: func() (io.ReadCloser, error)" on DeleteHook

### ISSUE THREAD

**Issue by raffaelespazzoli** [google/go-github#2572]
As the title says, I get `json: unsupported type: func() (io.ReadCloser, error)` as part of the response (not the error) of the `DeleteHook` function.
So here is a fragment of my code:
```golang
	response, err := git.Repositories.DeleteHook(ctx, m.gitWebhook.Spec.RepositoryOwner, m.gitWebhook.Spec.RepositoryName, *hook.ID)
	log.V(1).Info("DeleteHook", "response", response, "err", err)
```
the output is:
```
[manager] 1.6689558493826857e+09	DEBUG	DeleteHook	{"controller": "gitwebhook", "controllerGroup": "redhatcop.redhat.io", "controllerKind": "GitWebhook", "GitWebhook": {"name":"gitwebhook-github","namespace":"test-gitwebhook-github"}, "namespace": "test-gitwebhook-github", "name": "gitwebhook-github", "reconcileID": "a9d29c20-49e0-490c-8dc9-25a17e2947f9", "responseError": "json: unsupported type: func() (io.ReadCloser, error)", "err": null}
```
the same client works with the other hook related functions. Looking around it seems that this error is due to not setting the content type correctly in the headers. I'm testing with the latest version and against the public instance of github.
Thanks for the help.

**Comment by gmlewis** [comment]
Thanks for the report, @raffaelespazzoli !

It might help to use https://github.com/gmlewis/go-httpdebug to debug this.

**Comment by raffaelespazzoli** [comment]
this is what I got: 
```
[manager]   https://api.github.com/repos/raffaelespazzoli/helloworld-tonic/hooks/389245677 \
[manager]   -H 'Accept: application/vnd.github.v3+json' \
[manager]   -H 'Authorization: <REDACTED>' \
[manager]   -H 'User-Agent: go-github/v48.0.0'
[manager] 1.6689576382338324e+09	DEBUG	DeleteHook	{"controller": "gitwebhook", "controllerGroup": "redhatcop.redhat.io", "controllerKind": "GitWebhook", "GitWebhook": {"name":"gitwebhook-github","namespace":"test-gitwebhook-github"}, "namespace": "test-gitwebhook-github", "name": "gitwebhook-github", "reconcileID": "e5f04e83-79f6-4181-9bd1-256868fdce7f", "responseError": "json: unsupported type: func() (io.ReadCloser, error)", "err": null}
```
looks good to me and yet the error...

**Comment by gmlewis** [comment]
What do you get when you call directly with `curl`?

**Comment by raffaelespazzoli** [comment]
is there a way for this library to print the curl command, it looks like so, but the above is all I get...

**Comment by gmlewis** [comment]
That is exactly what the other repo is doing.
There was a discussion that it would be better to keep that helper function outside of this repo.

**Comment by raffaelespazzoli** [comment]
yeah that's what I meant the other repo, anyway it gives me enough to build the curl command.

**Comment by raffaelespazzoli** [comment]
when  execute with curl, I get the following:
```
{"message":"Not Found","documentation_url":"https://docs.github.com/rest/webhooks/repos#delete-a-repository-webhook"}
```

**Comment by raffaelespazzoli** [comment]
ok, so I had some issue in my code. everything works now. that weird response message remains unexplained, but the delete actually works. closing....
