### ISSUE TITLE
Support for repository actions permissions access

### ISSUE THREAD

**Issue by s4nji** [google/go-github#2575]
Looks like this was added to github.com around [March 2022][1] and Enterprise Server in [May 2022][2].  
It allows other repositories in the same organization or enterprise to access actions in said repository

Endpoints:  
[`GET` `/repos/{owner}/{repo}/actions/permissions/access`](https://docs.github.com/en/enterprise-cloud@latest/rest/actions/permissions#get-the-level-of-access-for-workflows-outside-of-the-repository)  
[`PUT` `/repos/{owner}/{repo}/actions/permissions/access`](https://docs.github.com/en/enterprise-cloud@latest/rest/actions/permissions#set-the-level-of-access-for-workflows-outside-of-the-repository)

I imagine this should be added as `repos_actions_permissions_access.go` 🤔 

#### Additional Links & References
https://github.com/github/roadmap/issues/74  
https://docs.github.com/en/enterprise-cloud@latest/actions/creating-actions/sharing-actions-and-workflows-with-your-enterprise  

[1]: https://github.blog/changelog/2022-03-04-sharing-github-actions-within-your-enterprise-is-now-ga/
[2]: https://docs.github.com/enterprise-server@3.5/admin/release-notes#sharing-github-actions-within-your-enterprise-is-generally-available

**Comment by gmlewis** [comment]
Sounds good, except how about if we name the file `repos_actions_access.go` instead?
Based on your questions, I'll assign this issue to you, but let me know if you don't want to work on it, and I'll open it up to other contributors.
Thank you, @s4nji !
