### ISSUE TITLE
Add team repository permission failed

### ISSUE THREAD

**Issue by klepiz** [google/go-github#2582]
```
	teamPermission := &github.TeamAddTeamRepoOptions{
		Permission: "write",
	}

	gh.session.Teams.AddTeamRepoBySlug(gh.ctx, org, teamSlug, owner, repo,teamPermission )

```
Seem like the way is parsing TeamAddTeamRepoOptions is causing an error on the endpoint: 
```
PUT https://api.github.com/orgs/<my-org>/teams/<my team>/repos/<my-org>/<my-repo>: 422 Validation Failed []
exit status 1
```
 Im using Admin permissions for edit the teams. Am I doing something wrong?

**Comment by gmlewis** [comment]
Can you please try the `curl` equivalent of the command (using https://github.com/gmlewis/go-httpdebug) to see if it works that way?
That will help us determine if it is an API issue or an issue in this repo.

Thank you!

**Comment by klepiz** [comment]
I ran the same endpoint on postman and I get this issue 
```
{
    "message": "Problems parsing JSON",
    "documentation_url": "https://docs.github.com/rest/reference/teams/#add-or-update-team-repository-permissions"
}
```
So, it may be an API issue instead?

**Comment by gmlewis** [comment]
> So, it may be an API issue instead?

Yes, that sounds right.  Please contact GitHub tech support and see if they have a solution for you.

Feel free to report your findings back here in this issue to help out others who might encounter the same problem.

**Comment by klepiz** [comment]
Hello!!  So I was setting wrong the dara-raw on postman and thats why I was getting the issue, which means that the GH API is working as it should, so it could be a bug on this repo then

**Comment by gmlewis** [comment]
Can you post an example of a working `curl` call, making sure to remove all tokens and secrets?

The next step is to compare that working `curl` call to the equivalent call made by this repo and looking at its "curl equivalent" (using `go-httpdebug`) to see how it differs.

**Comment by klepiz** [comment]
```
curl \
  -X PUT \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer <YOUR-TOKEN>" \
  https://api.github.com/orgs/ORG/teams/TEAM_SLUG/repos/OWNER/REPO \
  -d '{"permission":"write"}'
```
that curl works for me ^

**Comment by gmlewis** [comment]
> that curl works for me ^

OK, then if `go-httpdebug` shows you the exact same call is being made through this client library, then the next thought is that the personal access token you are using for the call with this client library doesn't have the right permissions. 
Unless, of course, you are using the exact same personal access token.
If you are, then the only way to verify that the call is truly identical, that I'm aware of, is to instrument it with `go-httpdebug` as described above.

**Comment by bfrancom** [comment]
Found out after a long while today that `write` isn't a permission body parameter. From the [docs](https://docs.github.com/en/rest/teams/teams?apiVersion=2022-11-28#add-or-update-team-repository-permissions), it shows only: `pull`, `triage`, `push`, `maintain`, and `admin`. 
I really thought I was going crazy.

**Comment by gmlewis** [comment]
Ah!  OK, thanks, @bfrancom - It looks to me like this issue can be closed since our docs don't mistakenly mention `write`.
Agreed, @bfrancom ?

**Comment by bfrancom** [comment]
Ah, gotcha, my bad. Thanks!

**Comment by gmlewis** [comment]
Closing.
