### ISSUE TITLE
Actions.Cache from github API v3 is not implemented

### ISSUE THREAD

**Issue by alidevhere** [google/go-github#2584]
Hii @gmlewis 

Any endpoint in  Actions.Cache is not implemented yet. [ See in official docs ](https://docs.github.com/en/rest/actions/cache?apiVersion=2022-11-28#about-the-cache-api) 

I would like to contribute this 😍

Thanks.

**Comment by gmlewis** [comment]
> I would like to contribute this

Thank you, @alidevhere !  It is yours.
