### ISSUE TITLE
Support new Audit Log fields for Dependabot Alerts

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#2585]
GitHub Announcement: https://github.blog/changelog/2022-11-29-audit-log-improvements-for-dependabot-alerts/
New fields: `alert_number`, `ghsa_id`, `dismiss_reason`, and `dismiss_comment`.

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

**Comment by SaumyaBhushan** [comment]
Hi @gmlewis Can you please tell me more about this . how to get started?

**Comment by gmlewis** [comment]
* First, read through CONTRIBUTING.md,
* then browse through the code and see how it is structured.
* Look at the announcement and figure out what it is saying.
* Look at relevant endpoints and see if you can figure out where and how to address this issue.
* If you still have specific questions, feel free to ask here.

Note that we attempt to give guidance in our CONTRIBUTING.md document, since it is not possible to give specific, detailed advice for each and every open issue, as that is simply not a scalable solution.

If, after having done your due diligence as outlined above, you still feel lost, then please take a look at some of the other open issues, as maybe there is one that makes more sense to you. Alternatively, look at past successful closed PRs and closed issues to see how others have gone about solving past issues.

I hope this helps even if it doesn't give you the level of detail that you were hoping.
I hope you also understand that this repo is maintained by volunteers and we do our best to keep the repo healthy and valuable for end users, but we also rely on the assistance and contributions of others.
Thank you for your understanding and for your contributions!

**Comment by SaumyaBhushan** [comment]
Thanks @gmlewis

**Comment by gronsy** [comment]
If this issue is not assigned yet to @SaumyaBhushan and isn't being worked on at the moment I'd like to dig into the issue.

**Comment by gmlewis** [comment]
@SaumyaBhushan - would you like this to be assigned to you, or shall we give it to @gronsy ?

**Comment by SaumyaBhushan** [comment]
@gmlewis Its ok You can assign it to @gronsy .

**Comment by gmlewis** [comment]
> @gmlewis Its ok You can assign it to @gronsy .

Thank you, @SaumyaBhushan !  It is yours, @gronsy .

**Comment by gronsy** [comment]
Hello sorry for taking a while but holiday stuff with family. I got to sit today to look at this and from what I see DismissedReason and DismissedComment fields exist in DependabotAlert fields and I added only Alert number field. GHSAID field is exposed in DependabotSecurityAdvisory that is part of DependabotAlert. I just wanted to check that I was looking at correct structure with DependabotAlerts where to add things and not something else since this was a bit of new part of GH for me and I gathered that this is what I should do from looking at code and docs so if you could just give me a bit of direction if I'm right or not?

**Comment by gmlewis** [comment]
I have been reading through all the announcements and REST API documentation, and I can't find the "new fields" anywhere.

@gronsy - can you please contact GitHub technical support and ask them where these new fields are listed in the GitHub v3 REST API documentation?

Maybe I'm just looking in the wrong places, but searching for those fields didn't help much either.
I see them in the requests, but I'm expecting to see them in the example results.
Feel free to point them to this issue if you think that would be helpful.

Thank you!

**Comment by gronsy** [comment]
Sure I will contact them regarding this then. Thank you.

**Comment by gronsy** [comment]
I tried contacting support, but didn't really get straight answers and also asking around on forums didn't really get me far. Maybe I'm looking at wrong places, but do you have example of that request that you see or point me to docs just to check if I'm looking at right places?

**Comment by gmlewis** [comment]
I'm sorry, I don't. I only have the announcement.
Maybe we should just close this issue for now.
Thoughts?

**Comment by gronsy** [comment]
Yeah I think it's best to close it now because it doesn't make sense to me to "eyeball" things. If I or someone else notices that docs are actually up to date I can get this assigned back to myself until then it's best closed. I can find something else to work on otherwise.

**Comment by gmlewis** [comment]
Closing due to not enough information in official documentation.
