### ISSUE TITLE
Support code scanning organizational-level API 

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#2588]
GitHub announcement: https://github.blog/changelog/2022-12-01-code-scanning-organization-level-rest-api-is-available-for-public-repositories/

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

**Comment by gmlewis** [comment]
Please first read https://github.com/google/go-github/issues/2585#issuecomment-1334059117
and then see if you still want to contribute. Thanks.

**Comment by shogohida** [comment]
Thanks for your comment. I read the comment you shared. I will follow the instructions you gave

**Comment by gmlewis** [comment]
> Thanks for your comment. I read the comment you shared. I will follow the instructions you gave

Great, thanks. The issue is yours.

**Comment by shogohida** [comment]
I made a draft pull request just to show I'm working on this issue. Please let me know if my approach is doing well or not.

https://github.com/google/go-github/pull/2592

**Comment by gmlewis** [comment]
As discussed in #2592, this has already been implemented and should not have been raised as a new issue in the first place.

Obviously this was totally my fault, @shogohida - I should have seen that this was already implemented.
I apologize.

Closing as already implemented.
