### ISSUE TITLE
Support unarchive a repo via the REST API 

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#2598]
GitHub Changelog announcement:
https://github.blog/changelog/2022-12-13-unarchive-a-repository-via-the-rest-api/

**Comment by gmlewis** [comment]
This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

**Comment by Gaikanomer9** [comment]
Hello @gmlewis !

I would love to take this one if that's alright 😄

**Comment by gmlewis** [comment]
> Hello @gmlewis !
> 
> I would love to take this one if that's alright smile

Absolutely!  Thank you , @Gaikanomer9 !  It's yours.

**Comment by gmlewis** [comment]
Awesome, @Gaikanomer9 ... Thank you for checking this!
I believe we already have tests for this, correct?
If so, I think we can close this issue as already resolved. 
Sorry for the false alarm. I'm trying to stay current with the Changelog announcements, but often our contributors are beating the announcements by implementing them ahead of time.

**Comment by Gaikanomer9** [comment]
Yes, there is already a test for the `Edit` function 👍

Agree, I think, this issue can be closed. No worries and thank you for maintaining this project. I will keep an eye on other issues 😊

**Comment by gmlewis** [comment]
Thanks again, @Gaikanomer9 !
Closing as already implemented.
