### ISSUE TITLE
Can't unmarshal Branch Protection Response lock_branch

### ISSUE THREAD

**Issue by liaodaniel** [google/go-github#2612]
In version `v48.2.0`, we are getting an error trying to unmarshal the UpdateBranchProtection response:

`
json: cannot unmarshal object into Go struct field Protection.lock_branch of type bool: the action couldn't be fully processed, please retry command
`

Code snippet:
```
protection, res, err := c.githubClient.Repositories.UpdateBranchProtection(context.TODO(), "org", "repo", "main", request)
if err != nil {
  return err
}
```

**Comment by gmlewis** [comment]
I believe this will be fixed by this breaking API change: https://github.com/google/go-github/pull/2606
in the next release.

**Comment by liaodaniel** [comment]
Looks like the fix is released already.
