### ISSUE TITLE
Support setting customization template for OIDC subject claims in GitHub Actions

### ISSUE THREAD

**Issue by F21** [google/go-github#2614]
This issue proposes to add the following methods to the `ActionsService`:
- `GetOrganizationOIDCSubjectClaimCustomizationTemplate`
- `SetOrganizationOIDCSubjectClaimCustomizationTemplate`
- `GetRepoOIDCSubjectClaimCustomizationTemplate`
- `SetRepoOIDCSubjectClaimCustomizationTemplate`

API: https://docs.github.com/en/rest/actions/oidc

This feature would enable the customization of OIDC subject claims in GitHub Actions: https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#customizing-the-subject-claims-for-an-organization-or-repository

**Comment by gmlewis** [comment]
Thank you, @F21 !
Would you like to write a PR or shall we open this up to other contributors to this repo?

**Comment by F21** [comment]
@gmlewis Happy to open a PR for this, it should be a pretty straight forward implementation 👍

**Comment by gmlewis** [comment]
Great, thank you, @F21 .
If you haven't already, please check out our CONTRIBUTING.md guide.
