### ISSUE TITLE
remove org permission content type

### ISSUE THREAD

**Issue by willnorris** [google/go-github#262]
The org permissions changes are now official, so the custom media type is no longer necessary.  This would also be a good time to make sure that we have coverage for all of those changes (though I'm pretty sure we do, since we use this part of the API pretty extensively inside Google)

announcement: https://developer.github.com/changes/2016-01-05-api-enhancements-for-working-with-organization-permissions-are-now-official/

**Comment by gmlewis** [comment]
I've implemented these changes, and while testing out all the API calls, I ran across one issue:

`Organizations.IsTeamRepo` still requires a custom header that is not documented anywhere that I can find:
`application/vnd.github.ironman-preview.repository+json`.  Thus, I'll leave it in. That will make this PR look odd, but this is the reason.

**Comment by shurcooL** [comment]
@gmlewis If it's not documented, perhaps it's an issue on the GitHub API side? If so, the best course of action might be to email their support and confirm whether it's intended or not.

That announcement states:

> If you have any questions or feedback, please [get in touch with us](https://github.com/contact?form%5Bsubject%5D=Organization+Permissions+API)!

**Comment by gmlewis** [comment]
Thanks, @shurcooL, I have requested more information from GitHub support about `Organizations.IsTeamRepo` and will report back here what they say (or they can comment directly... I linked to this issue in my request).

**Comment by gmlewis** [comment]
GitHub Tech Support has cleared things up for me.  I said:

> We are using
> "application/vnd.github.ironman-preview.repository+json" for this API
> but the GitHub documentation that [you linked](https://developer.github.com/v3/orgs/teams/#check-if-a-team-manages-a-repository) says to use
> "application/vnd.github.v3.repository+json" (yet ours works).

and GitHub Support replied:

> Yeah that works because the ironman-preview part is ignored because the preview ended, but the "repository" part is used still since that's the relevant bit for this functionality. I recommend you switch to the documented media type (v3.repository) instead of using ironman-preview.repository. I don't expect ironman-preview.repository to stop working, but using documented media types is always recommended.

So I will update this PR with the documented media type and update this issue when it is ready to review.

**Comment by gmlewis** [comment]
I made the changes mentioned above.
