### ISSUE TITLE
Tag new release

### ISSUE THREAD

**Issue by F21** [google/go-github#2622]
I am trying to get support for GitHub Actions OpenID Connect merged in https://github.com/integrations/terraform-provider-github/pull/1473

The latest release does not include support for OpenID Connect implemented in e4ff2a27f7699954c87d81d723012c1c3f0de0f1 and 93166f499694cf079d03543bc007f9c0065f6e16. Would it be possible to tag a new release, so that we can move https://github.com/integrations/terraform-provider-github/pull/1473 forward?

**Comment by gmlewis** [comment]
Sure.  One moment.

**Comment by gmlewis** [comment]
Here you are: https://github.com/google/go-github/releases/tag/v49.1.0

**Comment by F21** [comment]
Thanks so much @gmlewis !
