### ISSUE TITLE
PullRequestReviewsEnforcementRequest struct should also include the RequireLastPushApproval field

### ISSUE THREAD

**Issue by liaodaniel** [google/go-github#2628]
Currently, the only way to enable the `RequireLastPushApproval` feature is to use [UpdatePullRequestReviewEnforcement](https://pkg.go.dev/github.com/google/go-github/v49/github#RepositoriesService.UpdatePullRequestReviewEnforcement).

According to the [docs](https://docs.github.com/en/rest/branches/branch-protection#update-branch-protection), we should be able to do it via [UpdateBranchProtection](https://pkg.go.dev/github.com/google/go-github/v49/github#RepositoriesService.UpdateBranchProtection). This would require updating the [PullRequestReviewsEnforcementRequest](https://pkg.go.dev/github.com/google/go-github/v49/github#PullRequestReviewsEnforcementRequest) struct.

**Comment by gmlewis** [comment]
Thank you, @liaodaniel !
Do you want to put together a PR for this issue, or shall I open it up to other contributors to this repo?

**Comment by liaodaniel** [comment]
@gmlewis, happy to submit the PR

**Comment by gmlewis** [comment]
> @gmlewis, happy to submit the PR

Thank you, @liaodaniel !
It's yours.
