### ISSUE TITLE
document that RepositoriesService.UpdateFile doesn't need base64-encoded Content field

### ISSUE THREAD

**Issue by parkr** [google/go-github#263]
Hey,

I just ran into a weird issue where I used `RepositoriesService.UpdateFile` to update a file. Per the GitHub docs, I base64-encoded the `Content` myself – this [ended up breaking things](https://github.com/jekyll/jekyll/commit/a12ee551399eadd2b970f08629b39cb02f8381f8). Whoops.

Just for kicks, I added the unencoded content to `Content` in my `RepositoryContentFileOptions` and [it worked!](https://github.com/jekyll/jekyll/commit/bfc07a39c6bf1b57e88a470fc6d0334ee628c9c3#diff-365ba2ab054c575b20327b92fb90aef6R71).

It would be lovely to document that go-github will take care of base64 encoding this for you.

What say you, @willnorris?

**Comment by willnorris** [comment]
but go-github *doesn't* take care of base64 encoding this... it just passes along whatever you provide it.  It sounds like a bug in the GitHub API docs, maybe?

**Comment by parkr** [comment]
@willnorris We can't seem to repro with just straight cURL. Hm. Here's my problematic code: https://gist.github.com/parkr/a02b54febbe5396f6cd5 (don't forget to fill in the var's)

**Comment by captncraig** [comment]
the base64 encoding is a natural consequence of how `encoding/json` serializes a `[]byte`. Since [`Content`](https://github.com/google/go-github/blob/master/github/repos_contents.go#L46) is a slice of bytes, it is naturally base 64 encoded for you.
