### ISSUE TITLE
Question: How to use conditional requests with httpcache?

### ISSUE THREAD

**Issue by luebken** [google/go-github#2631]
I understand that conditional requests / etags are not supported directly, but instead we should use https://github.com/gregjones/httpcache (https://github.com/google/go-github/issues/2625). 

Would someone have an example on how to use it? Especially in combination with static token source as shown in the [readme](https://github.com/google/go-github#authentication). I fail to understand on how I would create a new client with both token support and conditional request support.

**Comment by gmlewis** [comment]
The following repo shows an example of using an external transport with this client library: https://github.com/gmlewis/go-httpdebug

Here is the example I'm referring to:

```go
import (
  dbg "github.com/gmlewis/go-httpdebug/httpdebug"
  "github.com/google/go-github/v49/github"
  "golang.org/x/oauth2"
)
...
ctx := context.Background()
ts := oauth2.StaticTokenSource(
	&oauth2.Token{AccessToken: token},
)
tc := &oauth2.Transport{Source: ts, Base: dbg.New()}

client := github.NewClient(&http.Client{Transport: tc})
```

Now in theory, you could replace the `dbg.New()` with the transport provided by https://github.com/gregjones/httpcache

Hopefully this is enough to get you up and running.

Either way, please comment back with your success.

Also, feel free to add more information to our `README.md` and `github/doc.go` (in a PR) giving a more detailed example for how to do this if you think it will help others in the future.

**Comment by luebken** [comment]
Never mind. I've used in memory cache. Testing with `diskcache` right now.

**Comment by gmlewis** [comment]
Closing as resolved.

**Comment by andygrunwald** [comment]
@luebken Did you have success running httpcache to use conditions requests now?

**Comment by exageraldo** [comment]
It seems to be caching certain resources and not others.
It's not caching for SCIM API routes here.
