### ISSUE TITLE
Fail to parse time expirations

### ISSUE THREAD

**Issue by chmouel** [google/go-github#2649]
One token i have is getting this expiration from `/rate_limit` : 

```
% export TOKEN=github_pat_*********;curl -v -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer $TOKEN" https://api.github.com/rate_limit 2>&1|grep -n expiration
97:< github-authentication-token-expiration: 2023-04-26 23:23:18 +0200
```

the code that parse the token expiration here: 

https://github.com/google/go-github/blob/a67a565/github/github.go#L677
 
is not working for me since : 

```
2006-01-02 03:04:05 MST
```

would not parse that value, 

on another token I get the expiration token as UTC:

```
github-authentication-token-expiration: 2023-01-31 23:00:00 UTC
```
the parsing would fail as well since it's not using a AM/PM thing. A parsing like that instead in this case would work : 

```
"2006-01-02 15:04:05 MST"
```

I wonder if it's a misconfigured Github server and if we should handle all those use cases. All of those happen on public github not on public enteprise.

**Comment by gmlewis** [comment]
Thanks for the report, @chmouel !
Do you feel like writing a PR to fix this issue?
I don't see the harm in attempting to parse using the existing format, then if it fails, attempting to use a second format, and if that succeeds, then return the successful parse.

**Comment by chmouel** [comment]
@gmlewis yeah i just did that in our project https://github.com/openshift-pipelines/pipelines-as-code/pull/1132/files#diff-5b6abe4f3dd00e71b0bce9400ca69023651eda401e8b9149734dbe65d79f66dcR176 I

**Comment by jerolimov** [comment]
@chmouel @gmlewis I opened #2650 to address this bug. Open to any feedback.
