### ISSUE TITLE
Support milestoned/demilestoned actions in IssuesEvent

### ISSUE THREAD

**Issue by matt-simons** [google/go-github#2662]
When an issue is milestoned or demilestoned the issues event contains the associated milestone. https://docs.github.com/developers/webhooks-and-events/webhooks/webhook-events-and-payloads?actionType=milestoned#issues

I'm happy to raise a PR to add this to IssuesEvent if that's supported?

**Comment by gmlewis** [comment]
Sounds great, @matt-simons !
It's yours.
