### ISSUE TITLE
Timeline type does not contain requested_team

### ISSUE THREAD

**Issue by jwenz723** [google/go-github#2664]
The [Timeline](https://github.com/google/go-github/blob/175f3bf4a3791c35b60dc71d3b87c39c08d23b2e/github/issues_timeline.go#L18) type does not contain the `requested_team` attribute. This attribute can be seen in the github documentation [here](https://docs.github.com/en/rest/issues/timeline?apiVersion=2022-11-28#list-timeline-events-for-an-issue).

**Comment by gmlewis** [comment]
I'm not finding `requested_team` anywhere on that page.  Can you please take a screenshot?

**Comment by jwenz723** [comment]
![image](https://user-images.githubusercontent.com/8587171/219502595-caee507e-0dd8-4c74-b155-61f314c46f6b.png)

The documentation on the individual fields within the response is pretty limited. I only see it in the response schema.

**Comment by gmlewis** [comment]
Ah!  Thank you, @jwenz723 !!!  I only looked at their example response.
