### ISSUE TITLE
Source Object for cross-referenced timeline events

### ISSUE THREAD

**Issue by uchi-mata** [google/go-github#2668]
Hi,

I'm trying to access the source of a cross-referenced event on macos 13.2.1 with `go1.19.6 darwin/arm64`. 

I tried to minimize my example to this:
```
package main

import (
	"context"
	"net/http"
	"os"
	"strconv"

	ghinstallation "github.com/bradleyfalzon/ghinstallation/v2"
	"github.com/google/go-github/v50/github"
	log "github.com/sirupsen/logrus"
)

func main() {
	ctx := context.Background()
	privateKey := os.Getenv("PRIVATE_KEY")
	appIdI, _ := strconv.ParseInt(os.Getenv("APP_ID"), 10, 0)
	installIdI, _ := strconv.ParseInt(os.Getenv("INSTALL_ID"), 10, 0)
	appId := int64(appIdI)
	installationId := int64(installIdI)
	org := os.Getenv("GH_ORG")
	repo := os.Getenv("GH_REPO")
	itr, err := ghinstallation.NewKeyFromFile(http.DefaultTransport, appId, installationId, privateKey)

	if err != nil {
		log.Error(err)
	}
	client := github.NewClient(&http.Client{Transport: itr})

	tl, _, err := client.Issues.ListIssueTimeline(ctx, org, repo, 1, nil)
	if err != nil {
		log.Error(err)
	}	
	for _, tlitem := range tl {
		log.Info(tlitem.GetSource().GetIssue().GetRepository())
	}
}
```

The source object for timeline items `tlitem` is always returning information about the repository that was cross-referenced, i.e. the source of the event. However, if I read the [docs](https://docs.github.com/en/webhooks-and-events/events/issue-event-types#properties-for-cross-referenced) correctly, I should be able to get the repository URL of the issue which cross-referenced the issue I'm currently looking at. The data seems to be there when I look at the raw response of `gh api https://api.github.com/repos/ORG/REPO/issues/1/timeline`

Am I missing something here/using the client incorrectly? Happy to dig through the code but wanted to check first whether I messed something up 🙃 

Thanks & Cheers,
Matthias

**Comment by gmlewis** [comment]
To debug these kinds of things where you are getting a raw response that appears to have what you need versus using this client library that is missing the information, your very best way to debug it is to use something like https://github.com/gmlewis/go-httpdebug where you can dump out the "curl-equivalent" version of a command that this client is issuing.

Your simplified example unfortunately uses ghinstallation which I have not personally used, and I don't have any app installations handy that I can test this out on.

So your best bet is to first, try debugging using "go-httpdebug".  If you are still unable to figure out what the difference is, then please post the raw response here and also the "go-httpdebug" output that shows the curl equivalent, and we can try to figure it out together. Obviously, strip out any secrets or orgs/repos that you don't want to share publicly before posting.

**Comment by uchi-mata** [comment]
Hi @gmlewis, thanks for the response! I was actually just about to post again as I want down the exact route that you recommended 😄 My GitHub App did not have access to the repository which the timeline event was referencing which caused the event to be silently stripped from the response. Definitely some impressive scrubbing setup/ACL enforcement, but tricky to troubleshoot.
