### ISSUE TITLE
List workflow runs for a repository by SHA

### ISSUE THREAD

**Issue by alexellis** [google/go-github#2687]
Hi, I want to trigger a workflow for a given SHA, then query the ID of the run, to eventually collect the logs and status.

This is available in the API now, however the latest version of go-github doesn't have it available in the struct yet.
 
https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#list-workflow-runs-for-a-repository

```go
// ListWorkflowRunsOptions specifies optional parameters to ListWorkflowRuns.
type ListWorkflowRunsOptions struct {
	Actor   string `url:"actor,omitempty"`
	Branch  string `url:"branch,omitempty"`
	Event   string `url:"event,omitempty"`
	Status  string `url:"status,omitempty"`
	Created string `url:"created,omitempty"`
	ListOptions
}
```

I don't know how to contribute to this library, or whether external contributions are welcome/harder for the maintainers than adding this themselves.

What would be a good next step to get this in?

**Comment by gmlewis** [comment]
> I don't know how to contribute to this library, or whether external contributions are welcome/harder for the maintainers than adding this themselves.

We welcome and encourage people to contribute to this repo.  Please start by reading CONTRIBUTING.md, then go ahead and submit your PR.

Thank you, @alexellis !  We look forward to your contributions!
