### ISSUE TITLE
Support new Custom Repository Rules API changes

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#2700]
GitHub Blog Changelog announcement: https://github.blog/changelog/2023-03-07-custom-repository-roles-api-ga-and-breaking-change/

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

**Comment by exageraldo** [comment]
It seems that not much has changed.
I just submitted a PR with the changes.

**Comment by gmlewis** [comment]
Thank you, @exageraldo - please remove the "Draft" label from all your PRs when they are ready for review.

**Comment by exageraldo** [comment]
Done! ✅
