### ISSUE TITLE
could not refresh installation id

### ISSUE THREAD

**Issue by emmjohnson** [google/go-github#2705]
I'm sure this is user error, but I'm unsure where to engage with the community.

I created a Github app, a private key, installed the app and now I'm attempting to use go-github to interact with the api.

I have followed this example - https://github.com/google/go-github#as-a-github-app

and I am getting the error - 
```
panic: Get "https://api.github.com/user/repos": could not refresh installation id 35074536's token: received non 2xx response status "404 Not Found" when fetching https://api.github.com/installations/35074536/access_tokens

goroutine 1 [running]:
main.main()
        /Users/emjohnson/sandbox/play/go-github-use/main.go:20 +0xb0

```

Here is my code -
```
package main

import (
	"context"
	"net/http"

	"github.com/DataDog/ghinstallation"
	"github.com/google/go-github/v32/github"
)

func main() {
	client := Client{
		privateKeyPath: "app-emj.2023-03-09.private-key.pem",
		appID:          303362,
	}
	
	githubClient := client.CreateInstallationClient(35074536)
	_, _, err := githubClient.Repositories.List(context.TODO(), "", &github.RepositoryListOptions{})
	if err != nil {
		panic(err)
	}
}

type Client struct {
	privateKeyPath string
	appID          int
}

func (c *Client) CreateInstallationClient(installationID int) *github.Client {
	itr, err := ghinstallation.NewKeyFromFile(http.DefaultTransport, c.appID, installationID, c.privateKeyPath)
	if err != nil {
		panic("Failed to parse private key from file.")
	}

	return github.NewClient(&http.Client{Transport: itr})
}
```

**Comment by gmlewis** [comment]
Hmm... I've never accessed the GitHub v3 API using a private key.

I always create a Personal Access Token (https://github.com/settings/tokens) and give it the necessary scopes (usually 'repo...' scopes), and then use the StaticToken-way of accessing the API as described in our documentation.

Sorry for the short answer... heading out now... back later. I hope this helps point you in the right direction. Good luck!

**Comment by emmjohnson** [comment]
Trying to access authenticated as a Github app! So not sure what I'm missing...

**Comment by gmlewis** [comment]
Ah, gotcha.  Hopefully someone else can comment.

**Comment by emmjohnson** [comment]
closing because my ide did me dirty and imported `"github.com/DataDog/ghinstallation"` instead of `"github.com/bradleyfalzon/ghinstallation"`

**Comment by gmlewis** [comment]
Glad you found the problem and fixed it!
