### ISSUE TITLE
Question - webhook ordering from GitHub

### ISSUE THREAD

**Issue by alexellis** [google/go-github#2706]
We've been receiving webhooks from GitHub from GitHub Actions for several months and have processed 40k-50k events for builds.

Last week there was an outage on ~ 9th March at which point we started to get events in the "wrong" order such as:

queued
completed
in_progress

Or:

completed
in_progress
queued

Or:

in_progress
queued
completed

As a rule, do the maintainers / users of this library tend to encounter correct ordering or have you also seen events coming out of order on a regular basis?

I found some links on the Internet suggesting that webhooks should be considered as eventually consistent.

cc @gmlewis

**Comment by gmlewis** [comment]
It has been many years since I've used this package to receive webhooks. Please raise a request ticket to GitHub tech support and ask them.  Feel free to report back here to help alert other users of this package as to what you find out. Thank you!
