### ISSUE TITLE
How to Paginate using ListAlertsOptions

### ISSUE THREAD

**Issue by pputman-clabs** [google/go-github#2712]
I can't figure out how to paginate this on https://github.com/google/go-github/blob/master/github/dependabot_alerts.go

When I call listAlerts, I get this response:

&{Response:0x140001f2090 NextPage:0 PrevPage:0 FirstPage:0 LastPage:0 NextPageToken: Cursor: Before: After:Y3Vyc29yOnYyOpHO0VeZ6w== Rate:github.Rate{Limit:5000, Remaining:4898, Reset:github.Timestamp{2023-03-20 12:28:55 -0500 CDT}} TokenExpiration:2023-04-16 22:14:55 -0500 CDT}

I'm trying this:
        opt.ListCursorOptions.Cursor = resp.After

in a loop, to set Cursor to After, to move through the pagination.  However I get the following:

```&{Response:0x1400009e360 NextPage:0 PrevPage:0 FirstPage:0 LastPage:0 NextPageToken: Cursor: Before: After:Y3Vyc29yOnYyOpHO0VeZ6w== Rate:github.Rate{Limit:5000, Remaining:4884, Reset:github.Timestamp{2023-03-20 12:28:55 -0500 CDT}} TokenExpiration:2023-04-16 22:14:55 -0500 CDT}
&{Response:0x1400009e240 NextPage:0 PrevPage:0 FirstPage:0 LastPage:0 NextPageToken: Cursor:Y3Vyc29yOnYyOpHO0VeZ6w== Before: After: Rate:github.Rate{Limit:5000, Remaining:4883, Reset:github.Timestamp{2023-03-20 12:28:55 -0500 CDT}} TokenExpiration:2023-04-16 22:14:55 -0500 CDT}
&{Response:0x1400018c480 NextPage:0 PrevPage:0 FirstPage:0 LastPage:0 NextPageToken: Cursor: Before: After:Y3Vyc29yOnYyOpHO0VeZ6w== Rate:github.Rate{Limit:5000, Remaining:4882, Reset:github.Timestamp{2023-03-20 12:28:55 -0500 CDT}} TokenExpiration:2023-04-16 22:14:55 -0500 CDT}
&{Response:0x1400018c630 NextPage:0 PrevPage:0 FirstPage:0 LastPage:0 NextPageToken: Cursor:Y3Vyc29yOnYyOpHO0VeZ6w== Before: After: Rate:github.Rate{Limit:5000, Remaining:4881, Reset:github.Timestamp{2023-03-20 12:28:55 -0500 CDT}} TokenExpiration:2023-04-16 22:14:55 -0500 CDT}
&{Response:0x1400018c480 NextPage:0 PrevPage:0 FirstPage:0 LastPage:0 NextPageToken: Cursor: Before: After:Y3Vyc29yOnYyOpHO0VeZ6w== Rate:github.Rate{Limit:5000, Remaining:4880, Reset:github.Timestamp{2023-03-20 12:28:55 -0500 CDT}} TokenExpiration:2023-04-16 22:14:55 -0500 CDT}
```

Showing that even though I move the After from the Response, to "Cursor" in the options, it's just stuck in a loop.  Should After in the Response be added to "After" in the options?  If so, wouldn't that skip and do every other page?

**Comment by gmlewis** [comment]
If I'm reading this correctly: https://docs.github.com/en/rest/guides/using-pagination-in-the-rest-api?apiVersion=2022-11-28
then you need to set the `After` field, no the `Cursor` field, like so:

```go
opt.ListCursorOptions.After = resp.After
```

source: https://github.com/google/go-github/blob/master/github/github.go#L251-L252

If you still can't figure it out, please post a minimal complete, reproducible, working example of what you are attempting, and I will try to help debug it.

**Comment by pputman-clabs** [comment]
That seems to work, thank you.

**Comment by gmlewis** [comment]
Glad to hear it, and I'm sorry for the delay in responding.  😞 
Closing as resolved.
