### ISSUE TITLE
Add download capability for workflow attempt logs 

### ISSUE THREAD

**Issue by btacyildiz** [google/go-github#2715]
Currently we are able to use `GetWorkflowRunLogs` function to download latest attempt logs. 
To be able to download specific workflow attempt logs implementation of the [Download workflow attempt logs](https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#download-workflow-run-attempt-logs) is required.

**Comment by btacyildiz** [comment]
Hello @gmlewis, I am planing to submit a PR soon 🙏

**Comment by gmlewis** [comment]
> Hello @gmlewis, I am planing to submit a PR soon 🙏

Sounds great!  Thank you, @btacyildiz !
Please see our CONTRIBUTING.md guide if you have any troubles.

**Comment by btacyildiz** [comment]
Hello @gmlewis, PR is ready for review 🙏
