### ISSUE TITLE
Add support for deleting an organization.

### ISSUE THREAD

**Issue by tjcorr** [google/go-github#2726]
A new REST endpoint was added to delete an organization at `/orgs/{org}'`. The documentation doesn't seem to have gone live quite yet but I'll update the issue as soon as I see it. In the meantime the endpoint can be evoked like:

`curl -X DELETE https://api.github.com/orgs/:org`

Now with [documentation](https://docs.github.com/en/rest/orgs/orgs?apiVersion=2022-11-28#delete-an-organization)!

**Comment by gmlewis** [comment]
Wow, that sounds dangerous! 😂

**Comment by tjcorr** [comment]
With great power comes great responsibility....

Anyways this has been available through the UI for awhile this is just adding it to the API too. For my use case of automating the provisioning of test/demo organizations it will be hugely valuable tough.

**Comment by gmlewis** [comment]
https://docs.github.com/en/rest/orgs/orgs?apiVersion=2022-11-28#delete-an-organization
