### ISSUE TITLE
Required Workflow Support

### ISSUE THREAD

**Issue by avivek** [google/go-github#2729]
Github introduced Org Required Workflow that enables a Github Action to be defined in one place and applied across applicable repos in the entire org.

Here is the link for the  API documentation for the same:

https://docs.github.com/en/rest/actions/required-workflows?apiVersion=2022-11-28

Being able to call these API's from this repo would enable progress on the below issue in Github Terraform provider:

https://github.com/integrations/terraform-provider-github/issues/1475

**Comment by gmlewis** [comment]
Thank you, @avivek - do you want to provide a PR to resolve this issue, or would you like me to open this up to other contributors to this repo?

**Comment by avivek** [comment]
Hi @gmlewis,
Thanks for getting this merged
Is there a release planned?? 
We can use this in the terraform github provider once released.

**Comment by gmlewis** [comment]
Yes. I can work on putting together a release shortly.

**Comment by gmlewis** [comment]
@avivek - this should now be available in: https://github.com/google/go-github/releases/tag/v51.0.0
