### ISSUE TITLE
Add support for DNS health checks on Pages.

### ISSUE THREAD

**Issue by oslowalk** [google/go-github#2745]
Hi :wave:

Currently, the `RepositoriesService` doesn't support [getting DNS health checks for Github pages](https://docs.github.com/en/rest/pages#get-a-dns-health-check-for-github-pages).

@gmlewis, I would like to implement this feature, if you agree.

**Comment by gmlewis** [comment]
Thank you, @oslowalk !
Sounds great. It's yours.
