### ISSUE TITLE
Add `Owner` to `EditChange` struct for repository transfer webhook event payloads

### ISSUE THREAD

**Issue by ecrupper** [google/go-github#2749]
When a repository has a transfer of ownership, it will send a [repository event webhook](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads?actionType=transferred#repository). The structure ends up looking like this:

```json
{
  "action": "transferred",
  "changes": {
    "owner": {
      "from": {
        "user": {
          "login": "octocat",
          ... etc
``` 
OR
```json
{
  "action": "transferred",
  "changes": {
    "owner": {
      "from": {
        "organization": {
          "login": "github",
          ... etc
```

I'd like to add the missing `Owner` field to the [`EditChange`](https://github.com/google/go-github/blob/683c2d7d7d40e2018285d356d0a45abaa5a9c286/github/event_types.go#L330-L335) struct. I was thinking it would look something like this:

```go
type EditChange struct {
	Title *EditTitle `json:"title,omitempty"`
	Body  *EditBody  `json:"body,omitempty"`
	Base  *EditBase  `json:"base,omitempty"`
	Repo  *EditRepo  `json:"repository,omitempty"`
	Owner *EditOwner `json:"owner,omitempty"`
}

type EditOwner struct {
	OwnerInfo *OwnerInfo `json:"from,omitempty"`
}

type OwnerInfo struct {
	Actor *User `json:"user,omitempty"`
	Org   *User `json:"organization,omitempty"`
}
```

Unfortunately, due to the structure of the payload, `OwnerInfo` will have to account for those two different options, even though they both refer to [owners](https://github.com/google/go-github/blob/683c2d7d7d40e2018285d356d0a45abaa5a9c286/github/repos.go#L31).

**Comment by gmlewis** [comment]
Thank you, @ecrupper - that sounds reasonable.
