### ISSUE TITLE
Org Required workflow create and update api's should return the workflow object

### ISSUE THREAD

**Issue by avivek** [google/go-github#2756]
The api for required workflow, for both create and update , returns the created workflow object in the response.
Currently the code for these do not return the create object back in an object instead only return the JSON version of these objects.
It would be good to return a typed object as this would enable us to get the details of the created workflow such as name, id etc.

**Comment by gmlewis** [comment]
Is #2755 related?

**Comment by avivek** [comment]
Hi @gmlewis ,

This is for  CreateRequiredWorkflow and UpdateRequiredWorkflow methods in the actions_required_workflows file.
I dont think this is related to 2755.

**Comment by avivek** [comment]
Hi @gmlewis ,

I have raised PR#2759 for this.
Pls take a look.
Thanks.
