### ISSUE TITLE
DependabotAlert missing repository

### ISSUE THREAD

**Issue by salamachinas** [google/go-github#2769]
DependabotAlert missing GetRepository - is it missing feature ? 
API documentation says repository is [available](https://docs.github.com/en/rest/dependabot/alerts#about-dependabot-alerts).

**Comment by gmlewis** [comment]
Yes, it looks like the "repository" field has been added to the official response.

Would you like to create a PR, @salamachinas , or would you like me to open up this issue to other contributors to this repo?

**Comment by salamachinas** [comment]
I would like create PR.

**Comment by gmlewis** [comment]
Thank you, @salamachinas !
This issue is yours.
