### ISSUE TITLE
Support for rulesets API

### ISSUE THREAD

**Issue by liaodaniel** [google/go-github#2789]
GitHub has recently released rule sets at both the organization and repository level.

References:
* https://docs.github.com/en/rest/orgs/rules?apiVersion=2022-11-28
* https://docs.github.com/en/rest/repos/rules?apiVersion=2022-11-28

Would be nice to have support for this feature.

**Comment by gmlewis** [comment]
Would you like to submit a PR or would you rather that we open this issue up to another contributor to this repo?

**Comment by liaodaniel** [comment]
Happy to take a look at this one.

**Comment by gmlewis** [comment]
> Happy to take a look at this one.

Great! Thank you, @liaodaniel.
It's yours.

**Comment by gmlewis** [comment]
> Happy to take a look at this one.

Great! Thank you, @liaodaniel.
It's yours.
