### ISSUE TITLE
Add support for issue locking / unlocking

### ISSUE THREAD

**Issue by willnorris** [google/go-github#279]
Announcement: https://developer.github.com/changes/2016-02-11-issue-locking-api/

Docs: https://developer.github.com/v3/issues/#lock-an-issue

**Comment by willnorris** [comment]
This would be a good task for a first-time contributor since it mainly involves copying an existing similar method that and updating the the URL, docs, etc.  Don't forget to add tests as well.

**Comment by gmlewis** [comment]
SGTM.  I'll work on it.
