### ISSUE TITLE
dependabot_alert Event missing in eventTypeMapping

### ISSUE THREAD

**Issue by pragmaticivan** [google/go-github#2790]
Trying to use this package to parse events, but `dependabot_alert` is not included.

Ref: https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#dependabot_alert

**Comment by gmlewis** [comment]
Would you like to create a PR, or shall I open this up to other contributors to this repo?

**Comment by gronsy** [comment]
I could do this probably, I had this basically few months back, but at that point it was a new feature and Github didn't update docs, they seem up to date now so I could take a look at this one.

**Comment by gmlewis** [comment]
Thank you, @gronsy , it is yours.

**Comment by nikpivkin** [comment]
Hi @gronsy ! Are you still going to work on it? I could take it on myself.

**Comment by gronsy** [comment]
@nikpivkin hello yes sorry you can take it. I have had pretty dynamic things on job with big version releases coming and didn't manage to take a better look at this as I should. I have some code written, but something weird is happening with my go install so probably will have to reinstall it so you just take it over. If you want I can share what I have written?

**Comment by nikpivkin** [comment]
@gronsy Hi, thanks. I don't think adding an event will require much change.
