### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by sam-robson** [google/go-github#2796]
Hi 👋🏻 

I am looking to add support for required workflows to the GitHub Terraform Provider (related issue [here](https://github.com/integrations/terraform-provider-github/issues/1475)). 

There's a little bug in the latest release that is preventing me moving forward (fixed in https://github.com/google/go-github/commit/daa96df75b7cd073beac60ebd619343fe7d4491f). Could we create a new release?

**Comment by gmlewis** [comment]
Yes, I'll work on a release.

**Comment by gmlewis** [comment]
Done: https://github.com/google/go-github/releases/tag/v53.0.0
