### ISSUE TITLE
messages.go header constants typo

### ISSUE THREAD

**Issue by medifle** [google/go-github#2802]
https://github.com/google/go-github/blob/master/github/messages.go#L39

According to the [documentation](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#delivery-headers), webhook delivery headers should use `GitHub`, not `Github`.

`EventTypeHeader` should be `X-GitHub-Event`, not `X-Github-Event`.
`DeliveryIDHeader` should be `X-GitHub-Delivery`, not `X-Github-Delivery`.

**Comment by gmlewis** [comment]
Header names are not case sensitive:
https://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive

At Google, we always capitalized the first word (separated by hyphens) of every header name, so I believe what we have is already correct.

**Comment by gmlewis** [comment]
Closing.
