### ISSUE TITLE
Using Github Search Issues Api does not work with repo

### ISSUE THREAD

**Issue by dangcq-2578** [google/go-github#2830]
I am using github.com/google/go-github/v52 to query Github Issues in my repository, the following code was able to search issues of repo `dangcq-2578/grpc-demo`, but Github return `422 Validation Failed`:
```
issues, _, err := client.Search.Issues(ctx, "repo:dangcq-2578/grpc-demo+type:issue", nil)
```

I checked debug log and my search url missing my repository name.
```
error: GET https://api.github.com/search/issues?page=1\u0026per_page=100\u0026q=repo%3Adangcq-2578%2F+is%3Aissue: 422 Validation Failed [{Resource:Search Field:q Code:invalid Message:The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.
```

**Comment by gmlewis** [comment]
Please try: `"user:dangcq-2578 repo:grpc-demo type:issue"`.

```
go run main.go
2023/07/11 08:07:05 q=user:dangcq-2578 repo:grpc-demo type:issue
2023/07/11 08:07:05 curl -X GET \
  https://api.github.com/search/issues?q=user%3Adangcq-2578+repo%3Agrpc-demo+type%3Aissue \
  -H 'Accept: application/vnd.github.squirrel-girl-preview, application/vnd.github.v3.text-match+json' \
  -H 'User-Agent: go-github/v53.2.0' \
  -H 'X-Github-Api-Version: 2022-11-28'
2023/07/11 08:07:06 Total: 1
2023/07/11 08:07:06 Incomplete Results: false
2023/07/11 08:07:06 

PullRequest #1:
2023/07/11 08:07:06   URL: https://github.com/dangcq-2578/grpc-demo/issues/3
```

**Comment by palexvs** [comment]
I just had the same issue, it's so unexpected that in `https://github.com/search?q=` I should use `+` to concatenate params and  ` ` (space) for https://api.github.com/search/issues?q=

**Comment by gmlewis** [comment]
Maybe the confusion is that the query itself is like what you would type into a search input box, but the URL is then "escaped" so spaces get turned into plus signs.

Closing issue as resolved.
