### ISSUE TITLE
Branch protection on branch pattern

### ISSUE THREAD

**Issue by dillonbarker-te** [google/go-github#2838]
Currently there is no way to create branch protection of a branch pattern (of a branch that doesn't exist). 

This is functionality that you can do through the Github UI so would be good to have through the `UpdateBranchProtection` or a new function `CreateBranchPatternProtection`.

I saw this issue was raised against v2 but have not seen anything about this in v3.

**Comment by gmlewis** [comment]
This functionally can obviously only be added to this client library if the functionally exists in the GitHub v3 API.

I'll leave this open so that any contributor to this repo can investigate the official documentation to see if this is possible.

**Comment by harveysanders** [comment]
It appears that wildcards are only available on the GraphQL API.
https://docs.github.com/en/rest/branches/branch-protection?apiVersion=2022-11-28#update-branch-protection

> ### `branch` 
> The name of the branch. Cannot contain wildcard characters. To use wildcard characters in branch names, use [the GraphQL API](https://docs.github.com/graphql).
