### ISSUE TITLE
Allow deletion of protected branches

### ISSUE THREAD

**Issue by ded-jajmera** [google/go-github#2841]
Currently, protected branches created using go-github cannot be easily deleted. To delete these branches, the associated branch protection rule needs to be deleted first. This makes it very difficult to delete stale protected branches.

As per [this](https://github.com/orgs/community/discussions/21793#discussioncomment-3234419) thread, this feature was added to the GitHub API. The ["Update branch protection"](https://docs.github.com/en/rest/branches/branch-protection?apiVersion=2022-11-28#update-branch-protection) endpoint has a parameter `allow_deletions` that enables the deletion of the protected branch by anyone with write access to the repository.

However, this functionality is not supported by go-github's [`UpdateBranchProtection`](https://pkg.go.dev/github.com/google/go-github/github#RepositoriesService.UpdateBranchProtection). It would be good to support this for consistency with GitHub's REST API.

**Comment by ded-jajmera** [comment]
> Thank you, @ded-jajmera . Would you like to make a PR, or shall I open this issue up to other contributors to this repo?

@gmlewis looks like I was misreading. It seems that this functionality has been implemented in versions since. It seems that the documentation I was referring to was linked to a [blob](https://github.com/google/go-github/blob/v17.0.0/github/repos.go#L541) from `v17.0.0`.

**Comment by gmlewis** [comment]
OK, cool.  Closing as already-implemented.
