### ISSUE TITLE
dependabot_security_updates field missing in repo's security_and_analysis

### ISSUE THREAD

**Issue by jporzucek** [google/go-github#2845]
[SecurityAndAnalysis](https://github.com/google/go-github/blob/4074b7c3a0a8c0da1663fe490ccfc6f20abed5b2/github/repos.go#L209) struct is missing `dependabot_security_updates` field.

**Note:** The field is not yet documented in docs but is returned when requesting https://api.github.com/repos/{owner}/{repo} so we may wait until new API revision is released.

**Comment by gmlewis** [comment]
Just FYI, this repo has historically implemented features regularly based upon empirical evidence, so we're fine to add this before it is officially documented. 😁
