### ISSUE TITLE
Support new Get global security advisories API

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#2851]
GitHub blog announcement:
https://github.blog/changelog/2023-07-28-get-global-security-advisories-via-rest-api/
GitHub v3 API documentation:
https://docs.github.com/en/rest/security-advisories/global-advisories?apiVersion=2022-11-28

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

**Comment by mrasoolmirzaei** [comment]
Hi @gmlewis 
Would you pls assign this to me?

**Comment by gmlewis** [comment]
Thank you, @mrasoolmirzaei !
It is yours.

**Comment by himsngh** [comment]
Hi @gmlewis , @mrasoolmirzaei 
I would also like to work on it. 
Is it still available ?

**Comment by mrasoolmirzaei** [comment]
Hi @himsngh
I'm currently working on it and create a pull request very soon next week.

**Comment by mrasoolmirzaei** [comment]
Hi @gmlewis 
I'm defining "Advisory" type based on the response in the API documentation and other defined type. There is a little inconsistency between my new type and one other defined type that I need your advice for solving it. 

This is a part of #get-a-global-security-advisory response:
`"vulnerabilities": [
    {
      "package": {
        "ecosystem": "npm",
        "name": "a-package"
      },`

I defined a struct type called Package but it is already defined in "packages.go" but there is no "ecosystem" field. What should I do?

**Comment by gmlewis** [comment]
> I defined a struct type called Package but it is already defined in "packages.go" but there is no "ecosystem" field. What should I do?

Note that in `event_types.go` you should already have all the structs you need:

* `SecurityAdvisory`
* `AdvisoryIdentifier`
* `AdvisoryReference`
* `AdvisoryVulnerability`
* `VulnerabilityPackage`
etc.

So please use these and there should be no need to create your own.
Let me know if you find otherwise and we'll figure it out.

Thanks.

**Comment by mrasoolmirzaei** [comment]
Thank you for your guidance @gmlewis 

`SecurityAdvisory` type is not enough to cover all fields. So I need to define a `GlobalSecurityAdvisory` type and embed the `SecurityAdvisory` type into it. Something like this:

```
type GlobalSecurityAdvisory struct {
	SecurityAdvisory	  
	URL                   *string         `json:"url,omitempty"`
	HTMLURL               *string         `json:"html_url,omitempty"`
	RepositoryAdvisoryURL *string         `json:"repository_advisory_url,omitempty"`
	Type                  *string         `json:"type,omitempty"`
	SourceCodeLocation    *string         `json:"source_code_location,omitempty"`
	GitHubReviewedAt      *Timestamp      `json:"github_reviewed_at,omitempty"`
	NVDPublishedAt        *Timestamp      `json:"nvd_published_at,omitempty"`
	CVSS                  *CVSS           `json:"cvss,omitempty"`
	CWEs                  []*CWE          `json:"cwes,omitempty"`
	Credits               []*Credit       `json:"credits,omitempty"`
}
```
Am I right?

**Comment by gmlewis** [comment]
> Am I right?

With this number of new fields, I'm thinking maybe this is the best way to move forward.

We do need to make one change, though... the trademarked name `GitHub` uses this capitalization in all comments.
However, for naming fields, it was decided long ago that whenever a field has `github_` or `_github` (or both underscores) in the name, we capitalize it as `Github` for the Go field name.  So yours would be:

```go
	GithubReviewedAt      *Timestamp      `json:"github_reviewed_at,omitempty"`
```

We do this to maximize predictabiity within this repo.

Thanks for investigating this further, @mrasoolmirzaei !

**Comment by nikpivkin** [comment]
@mrasoolmirzaei `cwes` and `affects` are arrays of strings.

**Comment by mrasoolmirzaei** [comment]
Thank you @nikpivkin @gmlewis. There is another thing I want to mention. In the list response example, there is an `id` field but this field is not present in the get response. Also, I've checked the response schema in the list API and there isn't any `id` field there too. So, should I consider it a mistake in the example response provided in the list API?
![image](https://github.com/google/go-github/assets/45166822/41c3a13e-bff9-416d-b70d-68078dafc0d3)

**Comment by gmlewis** [comment]
GitHub, over the years, regularly tweaks their response bodies which is one of the reasons why we use pointers and `omitempty` in the `json` tags to define the fields. I would say to proceed as if the `id` field really does exist and that it is an `int64` to be consistent with the rest of the repo, and forge ahead.

Alternatively, you can contact GitHub tech support if you want to and point out the discrepancy and see what they say.

I'm fine either way.

**Comment by cpanato** [comment]
I checked and looks like no one was working on this issue

so, I did the work and PR is here https://github.com/google/go-github/pull/2993
