### ISSUE TITLE
List Dependabot alerts endpoint stopped supporting cursor pagination

### ISSUE THREAD

**Issue by jporzucek** [google/go-github#2852]
Contradictory to GitHub API [documentation](https://docs.github.com/en/rest/dependabot/alerts?apiVersion=2022-11-28), the "List Dependabot alerts for an organization" endpoint for all enterprise, organization, and repository no longer supports cursor pagination.

All list Dependabot endpoints return the following Link header:

```
Link: <https://api.github.com/organizations/myOrg/dependabot/alerts?page=1>; rel="next", <https://api.github.com/organizations/myOrg/dependabot/alerts?page=100>; rel="last"
```

**Comment by gmlewis** [comment]
Some endpoints support both, for example: https://github.com/google/go-github/blob/master/github/code-scanning.go#L131-L135

I'm wondering if it would be better to support both?  Do you want to contact GitHub tech support and see if they have any recommendations for this situation?
