### ISSUE TITLE
Support new API to Request a CVE for a repository security advisory 

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#2855]
GitHub Blog post: https://github.blog/changelog/2023-08-03-request-a-cve-identifier-for-your-repository-security-advisory-via-rest-api/
Rest API docs: https://docs.github.com/en/rest/security-advisories/repository-advisories?apiVersion=2022-11-28#request-a-cve-for-a-repository-security-advisory

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

**Comment by be0x74a** [comment]
Hey @gmlewis can I pick this one?

**Comment by be0x74a** [comment]
Opened the PR, hope that's okay :)
