### ISSUE TITLE
Feature Request: Repository SBOM generation

### ISSUE THREAD

**Issue by vandanrohatgi** [google/go-github#2864]
While using the package v53.2.0 I was trying to fetch [SBOM for a repository](https://docs.github.com/en/rest/dependency-graph/sboms?apiVersion=2022-11-28#export-a-software-bill-of-materials-sbom-for-a-repository). But looks like that method is not yet implemented.

Please let me know if this is a valid feature request. If it is, I would love to open a PR.

**Comment by gmlewis** [comment]
> Please let me know if this is a valid feature request. If it is, I would love to open a PR.

Yes it is. Thank you, @vandanrohatgi !  It's yours.
Please see CONTRIBUTING.md for details about writing PRs for this repo.

**Comment by marians** [comment]
This would be an appreciated addition!
