### ISSUE TITLE
Support enable or disable private vulnerability reporting on repositories

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#2883]
GitHub blog announcement: https://github.blog/changelog/2023-08-16-enable-or-disable-private-vulnerability-reporting-on-repositories-via-rest-api/

New PUT endpoint: https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#enable-private-vulnerability-reporting-for-a-repository

New DELETE endpoint: https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#disable-private-vulnerability-reporting-for-a-repository

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

**Comment by vandanrohatgi** [comment]
Hi @gmlewis , I can take this up!

**Comment by gmlewis** [comment]
Wonderful, @vandanrohatgi ... thank you!  ❤️ 
It's yours.
