### ISSUE TITLE
Support for organization, repository webhook configuration

### ISSUE THREAD

**Issue by mnafees** [google/go-github#2884]
I would like to add support for the following missing API implementations

- [Get a webhook configuration for an organization](https://docs.github.com/en/rest/orgs/webhooks?apiVersion=2022-11-28#get-a-webhook-configuration-for-an-organization)
- [Update a webhook configuration for an organization](https://docs.github.com/en/rest/orgs/webhooks?apiVersion=2022-11-28#update-a-webhook-configuration-for-an-organization)
- [Get a webhook configuration for a repository](https://docs.github.com/en/rest/webhooks/repo-config?apiVersion=2022-11-28#get-a-webhook-configuration-for-a-repository)
- [Update a webhook configuration for a repository](https://docs.github.com/en/rest/webhooks/repo-config?apiVersion=2022-11-28#update-a-webhook-configuration-for-a-repository)

Please let me know if I can proceed with a PR for the same.

**Comment by gmlewis** [comment]
Sounds great, @mnafees, and thank you!
It's yours.

**Comment by mnafees** [comment]
Thanks @gmlewis, updated the issue with 2 more APIs for repository webhooks as well.
