### ISSUE TITLE
Support for `x-accepted-github-permissions` header

### ISSUE THREAD

**Issue by andygrunwald** [google/go-github#2886]
GitHub blog announcement: https://github.blog/changelog/2023-08-10-x-accepted-github-permissions-header-for-fine-grained-permission-actors/

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to go generate ./... and don't use force-push to your PRs.)

Thank you!

**Comment by RickleAndMortimer** [comment]
I can take this one unless any new contributor wants to go for it

**Comment by gmlewis** [comment]
Thank you, @RickleAndMortimer - it's yours.

**Comment by RickleAndMortimer** [comment]
When we want to add support for the header, do we mean something like a struct of strings for different resources to their permissions? Or a function that returns a Map of the resources to their permissions?

**Comment by gmlewis** [comment]
Thank you for the confirmation, @WillAbides - closing with apologies as "nothing to be done here."

**Comment by RickleAndMortimer** [comment]
Agreed 👍
