### ISSUE TITLE
Remove dependency on golang.org/x/oauth2 

### ISSUE THREAD

**Issue by WillAbides** [google/go-github#2893]
golang.org/x/oauth2 is a pretty big module with its own dependencies including "google.golang.org/appengine" and "cloud.google.com/go/compute/metadata", but go-github only uses a very small part of it to add a static value to the Authorization header.

The oauth2 dependency can be replaced with a simple RoundTripper that adds the Authorization header.

**Comment by gmlewis** [comment]
Would you like to propose a PR, @WillAbides ?

**Comment by WillAbides** [comment]
@gmlewis Thanks for the reminder. I meant to create the PR at the same time but got called to dinner.
