### ISSUE TITLE
Unable to create Repo Ruleset if RepositoryName fields are empty

### ISSUE THREAD

**Issue by ysoldak** [google/go-github#2909]
Same as #2809 but for `RepositoryName` conditions.

Receiving same error `422 Validation Failed [{Resource: Field: Code: Message:Invalid target patterns: ''}]` when "exclude" is empty and omitted.

**Expected Behavior:**
The `github.Ruleset` struct should include all the necessary fields to create a GitHub Ruleset, ensuring that no required fields are omitted, allow users to create ruleset successfully without encountering any errors.

**Steps to Reproduce:**
Both `conditions.repository_name.include` and `conditions.repository_name.exclude` fields are required even when empty.

**Additional Information:**
go-github library version: v54.0.0

**Comment by gmlewis** [comment]
@ysoldak - would you like to submit a PR yourself, or shall I open this up to our wonderful community of contributors to this repo?

**Comment by ysoldak** [comment]
@gmlewis yes, I shall make a PR, no prob. Filed the issue late Friday so I don't forget :D

**Comment by gmlewis** [comment]
> @gmlewis yes, I shall make a PR, no prob. Filed the issue late Friday so I don't forget :D

Excellent, @ysoldak !  Thank you!
It's yours.

**Comment by gmlewis** [comment]
Check out our CONTRIBUTING.md guide for writing a PR - it has some helpful tips like the reminder to run `go generate ./...` and push the results along with running tests locally with `go test ./...` to make sure everything is working.  Oh, and of course, running `gofmt` on your code in case you don't already have that integrated with your editor on-save (which I much prefer - actually I use `goimports`).

**Comment by gmlewis** [comment]
> It's yours now, @gmlewis :P

That was fast.  :joy:
