### ISSUE TITLE
Add support for Source Import API

### ISSUE THREAD

**Issue by willnorris** [google/go-github#291]
Announcement: https://developer.github.com/changes/2016-02-19-source-import-preview-api/

Docs: https://developer.github.com/v3/migration/source_imports/

I'll take this myself, as we've been using it for quite a while internally at Google to power https://code.google.com/export-to-github/ and have a working implementation.

/cc @imjasonh in case you care to take it

**Comment by ImJasonH** [comment]
All yours. :)
