### ISSUE TITLE
WithAuthToken NewClient method replaced with NewTokenClient?

### ISSUE THREAD

**Issue by BlancEleven** [google/go-github#2911]
I was going over the documentation (README.md) and noticed that to create a client with a token, the WithAuthToken method must be used:

```golang
client := github.NewClient(nil).WithAuthToken("... your access token ...")
```

After using the library, WithAuthToken seems to not be available anymore. Has this been replaced with NewTokenClient? If so, should the documentation be changed to reflect this?

**Comment by gmlewis** [comment]
This was recently changed in #2904.

**Comment by BlancEleven** [comment]
Okay, thank you. For whatever reason, this didn't show up in my searches.
