### ISSUE TITLE
ListServiceHooks appears to no longer be supported

### ISSUE THREAD

**Issue by WillAbides** [google/go-github#2916]
Client.ListServiceHooks appears to be no longer supported by github. The backing endpoint is GET https://api.github.com/hooks. That is currently 404 and not mentioned in any of the published openapi descriptions for enterprise server.

I think it can be safely removed from go-github along with the supporting ServiceHook struct.

I can create a PR for this.

**Comment by gmlewis** [comment]
Agreed, thank you, @WillAbides!

Here's a little more background on what is being removed:
* https://developer.github.com/changes/2018-10-01-denying-new-github-services/
* https://docs.github.com/en/webhooks/replacing-github-services
