### ISSUE TITLE
CreateOrUpdateEnvSecret results in secrets with incorrect values

### ISSUE THREAD

**Issue by petar** [google/go-github#2918]
I attempted executing the [example](https://github.com/google/go-github/blob/master/example/newreposecretwithxcrypto/main.go) which demonstrates the use of `Actions.CreateOrUpdateRepoSecret`. This worked correctly and I verified that the resulting secret value on GitHub matches the input.

I also attempted using the example code substituting `Actions.CreateOrUpdateRepoSecret` with `Actions.CreateOrUpdateEnvSecret`, modifying the code to target a test GitHub actions environment. In this case, the operation completed successfully. However, on GitHub the environment secret which was created contained the empty string as a value, as opposed to the non-empty input that I provided.

**Comment by WillAbides** [comment]
Did you also change out the `GetRepoPublicKey` call with `GetEnvPublicKey`?

Also, you said it completed successfully. Are you going by it not returning an error or did you check that the response code is 2XX?

**Comment by gmlewis** [comment]
It worked for me.  See screenshots.
Now, as for why `repoID` is an `int` and not an `int64` is beyond me, and should probably be fixed sometime, but that's another issue.
<img width="1727" alt="worked-2" src="https://github.com/google/go-github/assets/6598971/56e43f4b-54f8-4645-b249-5ae0a9c8d0cb">
<img width="1728" alt="worked-for-me" src="https://github.com/google/go-github/assets/6598971/6ed0f7f0-f776-4118-8b9a-d6c589d3b477">

**Comment by petar** [comment]
@WillAbides I did not use GetEnvPublicKey (I used GetRepoPublicKey). Thank you! This resolves the issue.
