### ISSUE TITLE
Workflow Runs API returns duplicates 

### ISSUE THREAD

**Issue by MytsYurii** [google/go-github#2921]
we are using client.Actions.ListRepositoryWorkflowRuns and for some reason in whole our list from 70000 builds there are few duplicates: 
the whole data is the same ID, RunAttempt and other fields like HeadCommit and etc.
How can it happen?

**Comment by MytsYurii** [comment]
@gmlewis check it out , please.

**Comment by MytsYurii** [comment]
@WillAbides

**Comment by WillAbides** [comment]
I suspect this is a pagination issue. The API operation backing `ListRepositoryWorkflowRuns` uses offset-based pagination with the newest runs first. If a new run is created while you are iterating through pages, it shifts the contents of subsequent pages.

With offset-based pagination, there is no guarantee of avoiding duplicates. It is up to the caller to handle them. If you need a slice of all results without duplicates, you can use a map to keep track of the ids you've already seen to avoid appending duplicates.

Here's an untested example of what a function to get all workflow runs without dups might look like:

```go
func getAllWorkflowRuns(
	ctx context.Context,
	client *github.Client,
	owner, repo string,
	opts *github.ListWorkflowRunsOptions,
) ([]*github.WorkflowRun, error) {
	if opts == nil {
		opts = &github.ListWorkflowRunsOptions{}
	}
	opts.ListOptions.Page = 1
	var runs []*github.WorkflowRun
	runIds := map[int64]struct{}{}
	for opts.ListOptions.Page > 0 {
		page, resp, err := client.Actions.ListRepositoryWorkflowRuns(ctx, owner, repo, opts)
		if err != nil {
			return nil, err
		}
		if resp.StatusCode != 200 {
			return nil, fmt.Errorf("unexpected status code: %d", resp.StatusCode)
		}
		for _, run := range page.WorkflowRuns {
			id := run.GetID()
			_, seen := runIds[id]
			if seen {
				continue
			}
			runIds[id] = struct{}{}
			runs = append(runs, run)
		}
		opts.ListOptions.Page = resp.NextPage
	}
	return runs, nil
}
```
