### ISSUE TITLE
Missing function to update dependabot alerts

### ISSUE THREAD

**Issue by himazawa** [google/go-github#2922]
Reading [this file](https://github.com/google/go-github/blob/fd33b81221685302178ba197dbabe71326ca9051/github/dependabot_alerts.go
) there is no reference to a function to [Update a Dependabot Alerts](https://docs.github.com/en/rest/dependabot/alerts?apiVersion=2022-11-28#update-a-dependabot-alert
)

I would like to implement it but I am opening an issue first to ask if there is any other way to do it that I am currently missing.

**Comment by WillAbides** [comment]
It looks like you are correct and there is no method covering `PATCH /repos/{owner}/{repo}/dependabot/alerts/{alert_number}`, and it would be a welcome addition.

It looks like this would be your first contribution. Please have a look at [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) and post back here if you have questions or need any help.
