### ISSUE TITLE
Support for Copilot API

### ISSUE THREAD

**Issue by xNoga** [google/go-github#2938]
Any timeline for support of the new [Copilot](https://docs.github.com/en/rest/copilot/copilot-for-business?apiVersion=2022-11-28) part of the API?

**Comment by WillAbides** [comment]
There isn't a timeline for covering new endpoints, but by creating this issue you moved go-github one step closer to supporting the copilot APIs.

Now we need somebody to create a PR for it. If you want to implement it yourself, let us know on this issue. I can help you with any issues you run into. No worries if you aren't up for creating a new PR. Somebody will be up for it.

**Comment by gmlewis** [comment]
This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

**Comment by o-sama** [comment]
I can work on this in the coming week or so, unless someone has more free time and can get to it sooner 🙂

**Comment by gmlewis** [comment]
Thank you, @o-sama !
It's yours.

**Comment by GalihFajar** [comment]
Hi can I also work on this issue? Would not mind if @o-sama has made the PR (and get accepted eventually) though, just want to know I'm about to work on the same issue. Thanks!

**Comment by gmlewis** [comment]
@GalihFajar - before you waste a lot of time duplicating work, let's please give @o-sama a day or two to respond to your request.

**Comment by GalihFajar** [comment]
sure, thanks @gmlewis

**Comment by gmlewis** [comment]
Thanks for the update @o-sama - I hope you feel better fast.

**Comment by GalihFajar** [comment]
@o-sama sorry, didn't mean to bother you, please keep on doing your work, I'll try to find another (good first) issue to work on.

**Comment by CrypticPoet** [comment]
If @o-sama isn't working on the issue anymore. I'd love to take it up

**Comment by gmlewis** [comment]
@CrypticPoet - before you waste a lot of time duplicating work, let's please give @o-sama a day or two to respond to your request.

**Comment by o-sama** [comment]
I should have a PR out for this within the next couple of days, a few things had piled up on me while I was away.
