### ISSUE TITLE
copilot suddenly stopped working

### ISSUE THREAD

**Issue by shaulispitzer** [google/go-github#2940]
I started using copilot about 2 weeks ago, it was working fine until yesterday, when I start typing code then it doesn't show any suggestions anymore, when I check the log for github copilot it has this: `[INFO] [ghostText] [2023-09-27T10:05:27.285Z] Cancelled during debounce
[INFO] [default] [2023-09-27T10:05:27.407Z] [fetchCompletions] engine https://copilot-proxy.githubusercontent.com/v1/engines/copilot-codex
[INFO] [default] [2023-09-27T10:05:27.952Z] [fetchCompletions] engine https://copilot-proxy.githubusercontent.com/v1/engines/copilot-codex
[ERROR] [ghostText] [2023-09-27T10:05:31.222Z] Error on ghost text request: (FetchError) Client network socket disconnected before secure TLS connection was established`.  does anyone have any ideas of how I could fix it, I am still signed in to github

**Comment by gmlewis** [comment]
This repo is for a Go client library called `go-github` and does not handle GitHub tech support for Copilot or any of GitHub's products.

A [quick search](https://letmegooglethat.com/?q=github+copilot+Cancelled+during+debounce), however, might help you out.

Closing.
