### ISSUE TITLE
IssueEvents missing "performed_via_github_app" value

### ISSUE THREAD

**Issue by Shyclyde** [google/go-github#2945]
It would be handy if the IssueEvent struct were to actually contain the `"performed_via_github_app"` response that appears to already be in the response:

https://docs.github.com/en/rest/issues/events?apiVersion=2022-11-28#list-issue-events

If this is available elsewhere, please lead me in the right direction because I have missed it :)

Use case: this can help determine if any sensitive events on a pull request -- like removing a sensitive label or required reviewer -- were performed by a human or a bot. For instance, if the bots are tightly managed, these events might be expected by a bot, but if a human did this it might need review.

Cheers!

**Comment by gmlewis** [comment]
Would you like to create a PR, or shall I open this up to our other contributors? (This would also be a great Hacktoberfest PR.)

**Comment by Shyclyde** [comment]
I can work on a PR. I also noticed that depending on the event the `"requested_team"` attribute might be returned as well that isn't included. I'll block some time out and try my hand at this :)

> Would you like to create a PR, or shall I open this up to our other contributors? (This would also be a great Hacktoberfest PR.)

**Comment by gmlewis** [comment]
Excellent, thank you, @Shyclyde ! It's yours. 💜
Please take a look at our CONTRIBUTING.md guide for helpful advice.

**Comment by Shyclyde** [comment]
PR: https://github.com/google/go-github/pull/2946. 👀 are appreciated when available :)

**Comment by gmlewis** [comment]
Fixed by #2946.
