### ISSUE TITLE
Support for Repository Custom Properties

### ISSUE THREAD

**Issue by liaodaniel** [google/go-github#2965]
GitHub has recently released https://github.blog/changelog/2023-10-12-github-repository-custom-properties-beta/. It would be nice to have support for this feature. With the feature in beta,  we may expect API changes over time but I'll be happy to get a draft PR for now.

References:
* [Properties API docs](https://docs.github.com/en/rest/orgs/properties?apiVersion=2022-11-28)
* [Repository Custom Properties Beta Feedback](https://github.com/orgs/community/discussions/69914)

**Comment by gmlewis** [comment]
Thank you, @liaodaniel !
It's yours.
