### ISSUE TITLE
Move RateLimits method to a service

### ISSUE THREAD

**Issue by WillAbides** [google/go-github#2968]
I missed the RateLimits method in #2937. It should be moved to a service struct.

Docs are at [rate-limit/rate-limit#get-rate-limit-status-for-the-authenticated-user](https://docs.github.com/rest/rate-limit/rate-limit#get-rate-limit-status-for-the-authenticated-user), so according to our existing pattern, we should move it to a new service called `RateLimitService` and name it `Get`

`Client.RateLimits` should be marked as deprecated and its body should be updated to `return c.RateLimit.Get(ctx)`

This may be a candidate for "good first issue" with the slight complication of creating a new service.

/cc #2936

**Comment by nhAnik** [comment]
Hi @WillAbides, can I work on this?

**Comment by gmlewis** [comment]
> Hi @WillAbides, can I work on this?

Thank you, @nhAnik ! It is yours.
