### ISSUE TITLE
Add support for commit reference SHA-1 method

### ISSUE THREAD

**Issue by willnorris** [google/go-github#297]
Announcement: https://developer.github.com/changes/2016-02-24-commit-reference-sha-api/

Docs: https://developer.github.com/v3/repos/commits/#get-the-sha-1-of-a-commit-reference

**Comment by gmlewis** [comment]
If you agree, can you please assign this to me?

**Comment by willnorris** [comment]
This is [no longer in preview](https://developer.github.com/changes/2016-04-12-commit-reference-sha-api-is-now-official/), so the custom accept header can be dropped

**Comment by gmlewis** [comment]
Reopening issue to track removal of header.
