### ISSUE TITLE
Issue Listing Private Repositories for User

### ISSUE THREAD

**Issue by untamed-theory** [google/go-github#2980]
I am attempting to list all repositories (private and public) for an installed GitHub app using the `client.Repositories.List()` function.

Problem: It is only returning public repositories. Not private ones, which the app has permission to access.

```go
tr := http.DefaultTransport

//using ghinstallation for auth
itr, err := ghinstallation.NewKeyFromFile(tr, viper.GetInt64("APP_ID"), installationid, viper.GetString("KEY_PATH"))
if err != nil {
	log.Fatal("Error Generating new GitHub key from file: ", err)
}

client := github.NewClient(&http.Client{Transport: itr})

// Make the call to list repositories
opt := &github.RepositoryListOptions{Type: "all"}
orgs, resp, err = newclient.Repositories.List(ctx, p.Org, opt)

```

I have even tried the following:
* using `.WithAuthToken()` instead of ghinstallation library
* Using the token to make a raw HTTP call, not using the `go-github` library.

No matter what, it won't return private repos in the list. Could it be a GitHub API problem? The Installation token that is generated is legitimate, and actually allows me to clone repositories.

Any help would be massively appreciated. I feel like I'm taking crazy pills 😆

**Comment by WillAbides** [comment]
The issue here is that `client.Repositories.List` calls an endpoint that only lists public repos when the `user` argument is specified. For a github app, you need to use a different endpoint to find repos it has access to. See below.

```go
func listUserReposForApp(ctx context.Context, appID int64, pemPath, user string) ([]*github.Repository, error) {
	pem, err := os.ReadFile(pemPath)
	if err != nil {
		return nil, err
	}
	transport := http.DefaultTransport
	appTransport, err := ghinstallation.NewAppsTransport(transport, appID, pem)
	if err != nil {
		return nil, err
	}
	appClient := github.NewClient(&http.Client{Transport: appTransport})
	inst, _, err := appClient.Apps.FindUserInstallation(ctx, user)
	if err != nil {
		return nil, err
	}
	if inst == nil {
		return nil, fmt.Errorf("no installation found for user %s", user)
	}
	instClient := github.NewClient(
		&http.Client{
			Transport: ghinstallation.NewFromAppsTransport(appTransport, inst.GetID()),
		},
	)
	var userRepos []*github.Repository
	listOpts := &github.ListOptions{PerPage: 3}
	for {
		reposList, resp, err := instClient.Apps.ListRepos(ctx, listOpts)
		if err != nil {
			return nil, err
		}
		userRepos = append(userRepos, reposList.Repositories...)
		if resp.NextPage == 0 {
			break
		}
		listOpts.Page = resp.NextPage
	}
	return userRepos, nil
}
```

**Comment by gmlewis** [comment]
Thank you, @WillAbides !
Closing issue as resolved.

**Comment by untamed-theory** [comment]
Ok. The documentation for `client.Repositories.List` does claim however that you can specify the condition of private in the listOptions. So either the docs are wrong. I solved this one today by switching to graphql calls 🙃

Thank you both for your insight here @gmlewis  and @WillAbides
