### ISSUE TITLE
Missing `SponsorshipEvent` in events types

### ISSUE THREAD

**Issue by jpmcb** [google/go-github#2982]
There appears to be a new event type, the `SponsorshipEvent` as defined by the GitHub docs:

https://docs.github.com/en/rest/overview/github-event-types?apiVersion=2022-11-28#sponsorshipevent

This doesn't seem to be implemented:

```
undefined: github.SponsorshipEvent
```

and I don't see it in `event_types.go`: https://github.com/google/go-github/blob/master/github/event_types.go

I'd be happy to pick this up 👍🏼

**Comment by gmlewis** [comment]
That sounds great.  Thank you, @jpmcb !
It's yours. Please see our CONTRIBUTING.md guide, as it has recently changed a fair amount.

**Comment by CodeDiego15** [comment]
@gmlewis Shouldn't this issue be closed already?

**Comment by gmlewis** [comment]
> @gmlewis Shouldn't this issue be closed already?

@CodeDiego15 - why do you say that? 
`SponsorshipEvent` still seems to be missing from the code as far as I can tell.  Agreed?

**Comment by CodeDiego15** [comment]
well, I understood that `SponsorshipEvent` is not used, and that I would have to remove it something like that? and excuse me if you don't.

**Comment by gmlewis** [comment]
> @gmlewis well, I understood that `SponsorshipEvent` is not used, and that I would have to remove it something like that? and excuse me if you don't.

I'm sorry, I must be confused.  Do you have more context to this topic than just this one issue, because that is all I'm basing my question upon.

**Comment by CodeDiego15** [comment]
Sorry, I don't have any more information on the topic, I was just looking for a topic to collaborate with and I went into this one and saw that it was simple and I checked the code and realized that ``SponsorshipEvent`` wasn't there. We can verify the code. https://github.com/google/go-github/blob/master/github/event_types.go

**Comment by CodeDiego15** [comment]
> > @gmlewis well, I understood that `SponsorshipEvent` is not used, and that I would have to remove it something like that? and excuse me if you don't.
> 
> I'm sorry, I must be confused. Do you have more context to this topic than just this one issue, because that is all I'm basing my question upon.

**Comment by gmlewis** [comment]
OK, in that case, I mis-interpreted your original question.

This issue remains open because it indeed has not been implemented yet.

I think it is safe to say that @jpmcb is not planning on working on it afterall, but let's give @jpmcb one day to respond.
If there is no response, then we can assign the issue to you, @CodeDiego15 .

**Comment by CodeDiego15** [comment]
> OK, in that case, I mis-interpreted your original question.
> 
> This issue remains open because it indeed has not been implemented yet.
> 
> I think it is safe to say that @jpmcb is not planning on working on it afterall, but let's give @jpmcb one day to respond. If there is no response, then we can assign the issue to you, @CodeDiego15 .

>Ok I think it's perfect I have no problem working on it, if you assign me the problem would you give me more details about it?

**Comment by CodeDiego15** [comment]
> OK, in that case, I mis-interpreted your original question.
> 
> This issue remains open because it indeed has not been implemented yet.
> 
> I think it is safe to say that @jpmcb is not planning on working on it afterall, but let's give @jpmcb one day to respond. If there is no response, then we can assign the issue to you, @CodeDiego15 .

Ok I think it's perfect I have no problem working on it, if you assign me the problem would you give me more details about it?

**Comment by CodeDiego15** [comment]
@gmlewis I was reviewing the code, if I do a PR you have to include the tests also in:  https://github.com/google/go-github/blob/master/github/event_types_test.go ??

**Comment by CodeDiego15** [comment]
> OK, in that case, I mis-interpreted your original question.
> 
> This issue remains open because it indeed has not been implemented yet.
> 
> I think it is safe to say that @jpmcb is not planning on working on it afterall, but let's give @jpmcb one day to respond. If there is no response, then we can assign the issue to you, @CodeDiego15 .

Hello, sorry the time it's a bit late, but I'm done implementing 'SponsorshipEvent', do the pr?

**Comment by gmlewis** [comment]
> Hello, sorry the time it's a bit late, but I'm done implementing 'SponsorshipEvent', do the pr?

OK, sounds good to me.  It's yours.  Thank you, @CodeDiego15.

**Comment by gmlewis** [comment]
> @gmlewis I was reviewing the code, if I do a PR you have to include the tests also in: https://github.com/google/go-github/blob/master/github/event_types_test.go ??

Yes, please include tests similar to what we already have. We like to keep this repo heavily tested.  Thank you.

**Comment by CodeDiego15** [comment]
> > @gmlewis I was reviewing the code, if I do a PR you have to include the tests also in: https://github.com/google/go-github/blob/master/github/event_types_test.go ??
> 
> Yes, please include tests similar to what we already have. We like to keep this repo heavily tested. Thank you.

Okay thank you very much for the opportunity, I just need to do the tests in:  https://github.com/google/go-github/blob/master/github/event_types_test.go

**Comment by gmlewis** [comment]
You're welcome. And if you haven't checked out our CONTRIBUTING.md tips already, it is a great resource.

**Comment by CodeDiego15** [comment]
> You're welcome. And if you haven't checked out our CONTRIBUTING.md tips already, it is a great resource.

Dude, I just did the PR
