### ISSUE TITLE
`AuthorizationsService.Check` should use basic auth with client ID and client secret

### ISSUE THREAD

**Issue by Blarc** [google/go-github#2989]
GitHub documentation is a bit confusing regarding the endpoint for checking OAuth access token. The example in the [documentation](https://docs.github.com/en/rest/apps/oauth-applications?apiVersion=2022-11-28#check-a-token) is misleading, because it says you need to send `Authorization: Bearer` header which is **not** true.

As written, you need to send header for **basic** authentication, like this:
```sh
curl -L \
  -X POST \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Basic <base64(clientId:clientSecret)>" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/applications/<clientId>/token \
  -d '{"access_token":"e72e16c7e42f292c6912e7710c838347ae178b4a"}'
```

I believe similar error is made in: https://github.com/google/go-github/blob/a5b1cea2fe8d05dc2a9e0190abd6f17d519b2696/github/authorizations.go#L138-L169

Edit: At least I can't find the code that adds the basic authentication header.

**Comment by gmlewis** [comment]
Did you try [BasicAuthTransport](https://pkg.go.dev/github.com/google/go-github/v56/github#BasicAuthTransport) ?

**Comment by Blarc** [comment]
The following seems to be working:
```go
basicAuthTransport := github.BasicAuthTransport {
  Username: ginOauth2Verifier.GithubConfig.ClientID,
  Password: ginOauth2Verifier.GithubConfig.ClientSecret,
}
githubClient := github.NewClient(basicAuthTransport.Client())

// https://docs.github.com/en/rest/apps/oauth-applications?apiVersion=2022-11-28#check-a-token
check, r, err := githubClient.Authorizations.Check(ctx, ginOauth2Verifier.GithubConfig.ClientID, token)
if err != nil {
  println(err.Error())
  ctx.AbortWithStatus(http.StatusUnauthorized)
  return
}
```
Thanks :pray: .

**Comment by gmlewis** [comment]
Closed as resolved. Thanks for reporting back, @Blarc!
