### ISSUE TITLE
Question: Is the legacy Timeline API supported?

### ISSUE THREAD

**Issue by jpmcb** [google/go-github#2992]
I'm looking at some old data in the [GitHub archive](https://www.gharchive.org/) and the first few years of it is in the legacy "Timeline API":

> Activity archives for dates between 2/12/2011-12/31/2014 was recorded from the (now deprecated) Timeline API.

For example, here's what a `PushEvent` looks like in this json format from sometime in 2011:

```json
{
    "repo": {
        "id": 1369674,
        "url": "https://api.github.dev/repos/recortable/Cuentas",
        "name": "recortable/Cuentas"
    },
    "type": "PushEvent",
    "org": {
        "gravatar_id": "2e329ef465590c48ae2a74feaf5b30e3",
        "id": 609679,
        "url": "https://api.github.dev/orgs/recortable",
        "avatar_url": "https://secure.gravatar.com/avatar/2e329ef465590c48ae2a74feaf5b30e3?d=http://github.dev%2Fimages%2Fgravatars%2Fgravatar-org-420.png",
        "login": "recortable"
    },
    "public": true,
    "created_at": "2011-03-01T12:00:07Z",
    "payload": {
        "shas": [
            [
                "0d5884ca6c2700062b7d1940e73806cb2786aec7",
                "01c4fc51997addeeb9a817291b031b1c40a68fa1@gmail.com",
                "joder",
                "Danigb"
            ]
        ],
        "repo": "recortable/Cuentas",
        "actor": "danigb",
        "ref": "refs/heads/master",
        "size": 1,
        "head": "0d5884ca6c2700062b7d1940e73806cb2786aec7",
        "actor_gravatar": "a0847513c8bcdf52bc95fa8f5af79066",
        "push_id": 25765857
    },
    "actor": {
        "gravatar_id": "a0847513c8bcdf52bc95fa8f5af79066",
        "id": 7457,
        "url": "https://api.github.dev/users/danigb",
        "avatar_url": "https://secure.gravatar.com/avatar/a0847513c8bcdf52bc95fa8f5af79066?d=http://github.dev%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
        "login": "danigb"
    },
    "id": "1159358907"
}
```

Note that the metadata looks similar to a `github.Event` but the payload is much different: there's no `commits` array, just a single `shas` array with a mix of shas, emails, and user logins.

The metadata looks _really_ close to what we have in `github.Event` types and unmarshaling this data into a `github.Event` works. But then it will panic when attempting to parse the payload (since it has different fields / formats / etc.)

---

1. Is this legacy Timeline API supported by go-github? My assumption is no since I didn't find anything obvious in the libraries API
2. Any recommendations in working with this legacy data? I'm also having a hard time finding any documentation of this API (probably since it's well over 10 years old now) and I'd hate to have to reverse engineer the types if there's an easier way

Thanks so much!

**Comment by bdougie** [comment]
Per our chat, let's keep this issue open for now but ignore it unless a user really needs data that is between 2011-2014

**Comment by gmlewis** [comment]
1. No, not officially, as we try to keep current with the latest GitHub v3 API.  However, nothing in this repo should panic, and if you are seeing panics caused by this repo, then please report bugs, as we would like to eliminate them.  If, however, it is your own code that is panic'ing, one possible way to avoid that is to use the auto-generated getters, as those will tremendously reduce your chances of panics.
2. Ah, yes, use the auto-generated getters instead of using struct pointers directly.
