### ISSUE TITLE
Support secret scanning validity checks API

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#3006]
GitHub Blog post: https://github.blog/changelog/2023-11-29-enable-or-disable-secret-scanning-validity-checks-with-the-rest-api/

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

**Comment by tomasz-adam-skrzypczak** [comment]
Hello @gmlewis I would like to attack this issue

**Comment by gmlewis** [comment]
Thank you, @tomasz-adam-skrzypczak !
It's yours.

**Comment by gmlewis** [comment]
Note: Please check first that it hasn't already been implemented... Sometimes I unfortunately post these issues in a hurry without verifying that they have already been done.  Feel free to close if already completed.  Thanks.
