### ISSUE TITLE
Support temporary private fork creation via API

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#3007]
GitHub Blog post: https://github.blog/changelog/2023-11-27-creating-temporary-private-forks-via-the-rest-api/

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

**Comment by gmlewis** [comment]
Note: Please check first that it hasn't already been implemented... Sometimes I unfortunately post these issues in a hurry without verifying that they have already been done.  Feel free to close if already completed.  Thanks.

**Comment by Kiyo510** [comment]
Hello, @gmlewis!
May I work on this issue?

From looking at the files below, I don't think it has been implemented yet.
https://github.com/google/go-github/blob/062b6119e47d73486fe40193262708332f1dc9be/github/security_advisories.go

I think I can submit a PR in about a week.

**Comment by gmlewis** [comment]
> Hello, @gmlewis! May I work on this issue?
> 
> From looking at the files below, I don't think it has been implemented yet. https://github.com/google/go-github/blob/062b6119e47d73486fe40193262708332f1dc9be/github/security_advisories.go
> 
> I think I can submit a PR in about a week.

Thank you, @Kiyo510 !  It's yours.
