### ISSUE TITLE
commits api

### ISSUE THREAD

**Issue by Jerry-yz** [google/go-github#3008]
https://api.github.com/repos/OWNER/REPO/commits
i can not find this github api in go-github project

**Comment by gmlewis** [comment]
I think you are looking for this: https://github.com/google/go-github/blob/master/github/repos_commits.go#L125-L131
Alternatively, the godoc version is here:
https://pkg.go.dev/github.com/google/go-github/v56/github#RepositoriesService.ListCommits

**Comment by Jerry-yz** [comment]
thinks, but it look like respository commits list
