### ISSUE TITLE
Support for Get All Custom Property Values for a Repository

### ISSUE THREAD

**Issue by liaodaniel** [google/go-github#3014]
Looks like one new API was added for Custom Properties under https://docs.github.com/en/rest/repos/custom-properties?apiVersion=2022-11-28#get-all-custom-property-values-for-a-repository. Would be nice to have support for this feature.

**Comment by liaodaniel** [comment]
Happy to take this one @gmlewis

**Comment by gmlewis** [comment]
Thank you, @liaodaniel !
It's yours.
