### ISSUE TITLE
Failed to unmarshal audit log entry

### ISSUE THREAD

**Issue by peter-aglen** [google/go-github#3016]
Using v57 of the package, we have a problem reading the audit log using `Organizations.GetAuditLog`. 

The `AuditEntry` struct has a field `Permission *string`, but we have found a scenario in which the API returns a bool in the permission field (see example below). This naturally leads to the error `cannot unmarshal bool into Go struct field AuditEntry.permission of type string`, which basically blocks us from reading the audit log.

```json
{
  "@timestamp": 1701766234196,
  "_document_id": "abc",
  "action": "org.update_member_repository_creation_permission",
  "actor": "ole-olsen",
  "actor_id": 123456789,
  "actor_location": {
    "country_code": "NO"
  },
  "business": "business",
  "business_id": 123456,
  "created_at": 1701766234196,
  "external_identity_nameid": "ole.olsen@a.com",
  "external_identity_username": "ole.olsen@a.com",
  "operation_type": "modify",
  "org": "myorg",
  "org_id": 123456789,
  "permission": true,
  "user_agent": "Mozilla/5.0 ...",
  "visibility": "public_internal"
}

**Comment by WillAbides** [comment]
There are a lot of inconsistencies between fields in audit log entries for different actions. IMO go-github shouldn't try to unmarshal any fields that aren't in the API definition because of inconsistencies like this.

**Comment by peter-aglen** [comment]
Current response from tech support:

> Thank you for reaching out. I agree this field is particularly confusing and I am also not sure about this boolean value. I have asked our engineers to take a second look and provide a definitive answer. Once I get further confirmation as to what this field is supposed to be, I will reach out to you.
