### ISSUE TITLE
Support for code_search and dependency_snapshots for RateLimits

### ISSUE THREAD

**Issue by rufusnufus** [google/go-github#3018]
Looks like there are more options under /rate_limit to return - https://docs.github.com/en/rest/rate-limit/rate-limit?apiVersion=2022-11-28. Particularly, there are code_search and dependency_snapshots that are not implemented now. Would be nice to support them as well

**Comment by gmlewis** [comment]
Thank you, @rufusnufus .
Would you like to create a PR or you like me to open up this issue to our other contributors to this repo?

**Comment by gmlewis** [comment]
> Would be happy to contribute😃

Thank you, @rufusnufus !
It's yours.
