### ISSUE TITLE
Bug in CreateOrUpdateRepoCustomPropertyValues?

### ISSUE THREAD

**Issue by peter-aglen** [google/go-github#3021]
We are looking to replace our custom-built methods for listing and updating custom property values, with the methods provided in v57.

It seems the CreateOrUpdateRepoCustomPropertyValues method has a bug however. We haven't actually tested it yet, but shouldn't the last argument be `properties []*CustomPropertyValue`?

```go
// Wrong type in last arg?
func (s *OrganizationsService) CreateOrUpdateRepoCustomPropertyValues(ctx context.Context, org string, repoNames []string, properties []*CustomProperty) (*Response, error) {
	u := fmt.Sprintf("orgs/%v/properties/values", org)

	params := struct {
		RepositoryNames []string          `json:"repository_names"`
		Properties      []*CustomProperty `json:"properties"`
	}{
		RepositoryNames: repoNames,
		Properties:      properties,
	}

	req, err := s.client.NewRequest("PATCH", u, params)
	if err != nil {
		return nil, err
	}

	return s.client.Do(ctx, req, nil)
}
```

**Comment by gmlewis** [comment]
Looking at the corresponding unit test: https://github.com/google/go-github/blob/master/github/orgs_properties_test.go#L350
I see that it does not match the signature of the official docs, so you are absolutely correct.

I apologize for letting this slip past code reviews.

Would you like to create a PR to fix this, or shall I open it up to other contributors to our repo?

**Comment by peter-aglen** [comment]
Sure, I can have a PR ready tomorrow.

**Comment by gmlewis** [comment]
Thank you, @peter-aglen !
It's yours.
