### ISSUE TITLE
UploadSarif Always Returns An Error

### ISSUE THREAD

**Issue by Rigdon** [google/go-github#3036]
In version 57.0.0 of go-github, [UploadSarif](https://github.com/google/go-github/blob/v57.0.0/github/code-scanning.go#L384) never returns a valid SarifID object because it's propagating the AcceptedError instead of deserializing the body because [this endpoint](https://docs.github.com/en/rest/code-scanning/code-scanning?apiVersion=2022-11-28#upload-an-analysis-as-sarif-data) returns a 202. It seems to exhibit the same behavior that was fixed for CreateFork in #878.

**Comment by gmlewis** [comment]
Thank you, @Rigdon . Would you like to submit a PR to fix this, or shall we open this up to other contributors?

**Comment by Rigdon** [comment]
I'll actually try to get a PR open this week.

**Comment by gmlewis** [comment]
Thank you, @Rigdon !
