### ISSUE TITLE
Could you release new version more frequently?

### ISSUE THREAD

**Issue by kazuki-hanai** [google/go-github#3044]
It's not a request, just a question. I tried to use function introduced by [this PR](https://github.com/google/go-github/pull/3020), but it wasn't released yet. We can use it by specifying commit hash, but it's not good from the viewpoint of dependencies which relate multiple repositories. So I think better to release more frequently, if you can. How do you think?

**Comment by gmlewis** [comment]
We try to release every 3-4 weeks (unless someone says there is an urgent need), so it looks like it is time again.
I'll work on a release.

**Comment by gmlewis** [comment]
Here's the new release: https://github.com/google/go-github/releases/tag/v58.0.0

**Comment by kazuki-hanai** [comment]
@gmlewis Thank you for your quick response🙇‍♂️
