### ISSUE TITLE
Add Topics to EditChange struct

### ISSUE THREAD

**Issue by riaje** [google/go-github#3056]
Hi,

I want to add the missing `Topics` field for the [EditChange](https://github.com/google/go-github/blob/master/github/event_types.go#L390) `struct`.

In my case, it will allow me to retrieve the previous topics when I receive the [repository edited event](https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=edited#repository).

I already have the branch ready for review.

Thanks

**Comment by gmlewis** [comment]
Sounds great, thanks, @riaje !
Our CONTRIBUTING.md guide has helpful information in it for submitting PRs if you are new to this repo.
Specifically, step 4 seems to be a commonly-missed step.

**Comment by riaje** [comment]
Already read :+1: thanks for the reminder of course !
The PR is submit, it's my first contribution to an open project on GitHub so I discover the process in the same time :laughing: 
Thanks
