### ISSUE TITLE
Listing Projects in a Repository

### ISSUE THREAD

**Issue by Kartikey-star** [google/go-github#3063]
Hi,
We are trying to list projects in a repository using github api https://docs.github.com/en/rest/projects/projects?apiVersion=2022-11-28#list-repository-projects.
We tried with multiple parameters but the following curl requests returns an empty list.

curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer <YOUR-TOKEN>" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/OWNER/REPO/projects

For example the following project https://github.com/Golang-Prac/concurrency/projects?query=is%3Aopen , the OWNER must be Golang-Prac and REPO concurrency. I am expecting to get the response with the list of projects in the repo.But still get an empty response. Is it something which is missing from my side?Thanks.

**Comment by Sairaviteja27** [comment]
Hi @Kartikey-star 

As per my understanding

GitHub offers two tools for managing project workflow: Projects and Projects (classic). Projects represents the latest evolution, a feature-rich environment encompassing configurable boards, lists, customizable fields, and seamless integration with other GitHub functionalities. It elevates project management to a strategic level, akin to a comprehensive suite that empowers informed decision-making and streamlined collaboration. Projects (classic), on the other hand, offers a more rudimentary experience through traditional kanban boards with limited customization options. While gradually being transitioned to the newer platform, it remains a readily available option for users accustomed to its straightforward, visual approach, akin to a reliable, albeit basic, task organizer. Regardless of preference, both solutions effectively facilitate workflow management, but Projects provides a more future-proof and versatile path for organizations and individuals seeking a robust project management experience within the GitHub ecosystem.
![image](https://github.com/google/go-github/assets/44663543/c3e46f30-21dd-47d5-9efd-6c5a22ee5104)

The api you were trying supports only projects(classic) as mentioned in docs.  
![image](https://github.com/google/go-github/assets/44663543/a28f7e05-04a7-4afc-b9bd-d7a7e4d1b6bd)

Alternatively, you can can try [Using the API to manage Projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/using-the-api-to-manage-projects)

Correct me if I am wrong.

**Comment by baijum** [comment]
Thanks @Sairaviteja27 for the detailed response. I want to know if GraphQL based queries are supported in the `go-github` project? 

I am getting a response like this with curl and GraphQL query.

```
curl --request POST   --url https://api.github.com/graphql   --header 'Authorization: Bearer <MY-TOKEN>'   --data '{"query":"{organization(login: \"open-connectors\") {projectsV2(first: 20) {nodes {id title}}}}"}'
{"data":{"organization":{"projectsV2":{"nodes":[null,null,null]}}}}
```

We have a project created under this organization, but the result is empty. Any idea?

**Comment by Sairaviteja27** [comment]
Hi @baijum 
I believe you tried with fine-grained personal access token
In the docs, it is mentioned that the `The token can be a personal access token (classic) for a user or an installation access token for a GitHub App.`

I just tried with personal access token(classic) and it did work !!!
![image](https://github.com/google/go-github/assets/44663543/4e9a6a6d-72df-4ede-a727-02701b2af372)

**Comment by Kartikey-star** [comment]
Thanks a lot @Sairaviteja27 . I do get a response using personal access token (classic). Is there a recommended way to use this functionality of graphql (are some package available ) or need to do so using http clients if we are manage these projects programmatically?

**Comment by gmlewis** [comment]
I assume you have already looked at https://github.com/shurcooL/githubv4

**Comment by Kartikey-star** [comment]
Thanks a lot guys. I think i can close the issue and look at the  https://github.com/shurcooL/githubv4 for integration.
