### ISSUE TITLE
Hook should contain Config of type HookConfig

### ISSUE THREAD

**Issue by himazawa** [google/go-github#3072]
The `CreateHook` method
https://github.com/google/go-github/blob/6ca4d142bef57e88f87290837796a54a0296fcc4/github/repos_hooks.go#L85

currently wants a `Hook` parameter that has `Config` of type `map[string]interface{}`
https://github.com/google/go-github/blob/6ca4d142bef57e88f87290837796a54a0296fcc4/github/repos_hooks.go#L54

This forces the user to manually define each config properties.

My proposal is to change the `Config` to `HookConfig`, that for some reasons I'm not aware of is defined here:

https://github.com/google/go-github/blob/6ca4d142bef57e88f87290837796a54a0296fcc4/github/orgs_audit_log.go#L24-L31

This could be a breaking change for people currently using the `CreateHook` function (and every other functions taking `Hook` as input) so I am asking first how you want to proceed about it.

**Comment by gmlewis** [comment]
Hmmm... excellent point.  From the official docs, I don't see any reason why we shouldn't switch `Config` over to `*HookConfig` and have a breaking API change.

You might also want to provide a godoc comment for the `InsecureSSL` field since the warnings in the official docs look pretty serious.

Would you like to make a PR, @himazawa, or shall I open this issue up to other contributors?

**Comment by himazawa** [comment]
On it.

I also noticed that:

https://github.com/google/go-github/blob/master/github/apps_hooks.go#L18
https://github.com/google/go-github/blob/master/github/orgs_hooks_configuration.go#L18
https://github.com/google/go-github/blob/master/github/repos_hooks_configuration.go#L18

and 

https://github.com/google/go-github/blob/master/github/apps_hooks.go#L39
https://github.com/google/go-github/blob/master/github/orgs_hooks_configuration.go#L39
https://github.com/google/go-github/blob/master/github/repos_hooks_configuration.go#L39

are basically the same code. Do you want to create two generic function for them?

**Comment by gmlewis** [comment]
> Do you want to create two generic function for them?

I'm this repo, we have consciously tried to always support the most recent two minor versions of the Go compiler, and now with the release of Go 1.22.0 I think it is now safe to say that Go generics are a welcome addition! 

Later tonight I will try to update the maintenance scripts and GitHub Action workflow scripts to support versions 1.21.x and 1.22.x of the Go compiler.
After that gets merged, we should be able to accept PRs with generics.

🎉

**Comment by himazawa** [comment]
Wait, I was not talking about "generic" in that way. There is no need for them in this specific case, but we can use a a common function for all of them.
The real question is: is it ok if we aggregate this 3 functions into one?
