### ISSUE TITLE
Update deprecated endpoints in github/action_variables.go

### ISSUE THREAD

**Issue by HariCharan-001** [google/go-github#3103]
```
$ ./script/metadata.sh update-go
could not find operation "GET /repositories/{repository_id}/environments/{environment_name}/variables" in openapi_operations.yaml
could not find operation "GET /repositories/{repository_id}/environments/{environment_name}/variables/{name}" in openapi_operations.yaml
could not find operation "POST /repositories/{repository_id}/environments/{environment_name}/variables" in openapi_operations.yaml
could not find operation "PATCH /repositories/{repository_id}/environments/{environment_name}/variables/{name}" in openapi_operations.yaml
could not find operation "DELETE /repositories/{repository_id}/environments/{environment_name}/variables/{name}" in openapi_operations.yaml
```

The official GitHub v3 API documentation has moved the endpoints above and now needs updating.

Detailed discussion around this can be traced to comments under #3102

**Comment by HariCharan-001** [comment]
I'm working on a fix. Just giving a heads-up to avoid duplicate work.

**Comment by HariCharan-001** [comment]
@gmlewis 

Quick question on backward compatibility. Should we keep the older function signatures as they are and return an error _"This endpoint has been moved, please use this new function instead"_ ?

I feel it's unnecessary, as the older API does not work anyway.

**Comment by gmlewis** [comment]
If we can keep the same API and not break it, but just use the new endpoint URL, that would be ideal.

However, if the old API is broken anyway, and you need to break the API, then that's OK, just not ideal.

**Comment by HariCharan-001** [comment]
The old API is broken anyway. We have to take a new parameter, `github-userId`, from the user to feed to the updated endpoint URL. 

I raised a PR. 

Also, it looks like this check has been failing for quite a few PRs recently, even some merged ones. Not sure why, bringing to your notice just in case.

<img width="1161" alt="Screenshot 2024-03-16 at 6 30 05 AM" src="https://github.com/google/go-github/assets/80394987/bb9da7ac-d099-4d8b-8710-f80bb3f637a2">
