### ISSUE TITLE
`omitempty` tag on `InstallationAccessTokenOptions.Repositories` masking functionality of GitHub API 

### ISSUE THREAD

**Issue by gillisandrew** [google/go-github#3106]
When creating an app installation access token through the REST API (`POST /app/installations/{installation_id}/access_tokens`), if the `repositories` parameter is set to an empty array, the API returns a list of all accessible repositories. However, the client currently strips empty arrays (`omitempty`) when marshaling the `InstallationAccessTokenOptions.Repositories` value making that functionality inaccessible through the client.

https://github.com/google/go-github/blob/169ad4d74d0fad23559bac97d8ad2095999a4f29/github/apps.go#L45-L57

**Comment by gmlewis** [comment]
According to the [official docs](https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#create-an-installation-access-token-for-an-app):

> Optionally, you can use the repositories or repository_ids body parameters to specify individual repositories that the installation access token can access. If you don't use repositories or repository_ids to grant access to specific repositories, the installation access token will have access to all repositories that the installation was granted access to. The installation access token cannot be granted access to repositories that the installation was not granted access to. Up to 500 repositories can be listed in this manner.

so these fields are optional, hence the `omitempty`, and it's not clear (to me) what the behavior is if you _were_ to send it an empty array (as opposed to not sending the field at all, which `omitempty` does).

You didn't state what you are trying to do by providing it an empty array.

Are you trying to _remove_ access to all repositories? If so, I'm wondering if that might be a different endpoint, such as [this one](https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#delete-an-installation-for-the-authenticated-app)?

If you are trying to do something else, then I need to warn you against removing `omitempty` from optional body parameters, as that has historically wreaked havoc with other uses of the endpoint, and we've had to create additional endpoints to address the other behavior.

So please clarify what you are trying to do, and if you would like to create a PR to address the issue.

Thanks.

**Comment by gillisandrew** [comment]
So the documentation doesn't actually specify this behavior but basically you can have the endpoint return the list of all accessible repositories in the installation by specifying an empty array for the repositories parameter.

Command with empty array
```bash
curl -s "https://api.github.com/app/installations/$APP_INSTALL_ID/access_tokens" \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer $APP_JWT" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  -d '{"repositories":[],"permissions":{"contents":"read"}}' 
```
Output
```json
{
  "token": "<token>",
  "expires_at": "2024-03-17T02:30:32Z",
  "permissions": {
    "contents": "read",
    "metadata": "read"
  },
  "repositories": ["<all repos in installation...>"],
  "repository_selection": "all"
}
```

Command with null or no repositories
```bash
curl -s "https://api.github.com/app/installations/$APP_INSTALL_ID/access_tokens" \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer $APP_JWT" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  -d '{"repositories":null,"permissions":{"contents":"read"}}'
# OR
curl -s "https://api.github.com/app/installations/$APP_INSTALL_ID/access_tokens" \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer $APP_JWT" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  -d '{"permissions":{"contents":"read"}}'
```
Output
```json
{
  "token": "<token>",
  "expires_at": "2024-03-17T02:30:32Z",
  "permissions": {
    "contents": "read",
    "metadata": "read"
  },
  "repository_selection": "all"
}
```

**Comment by gmlewis** [comment]
Awesome... Thank you for the detailed example!

Then I'm thinking we need to have a new, separate endpoint that handles this special case... with a name that makes the distinction clear.
What do you think?

Do you want to write it, @gillisandrew ?

**Comment by Matthew-Reidy** [comment]
Hello. If @gillisandrew doesn't want to take this I'd like to have a crack at it. Thanks!

**Comment by gmlewis** [comment]
Thank you, @Matthew-Reidy !  It's yours.

**Comment by Matthew-Reidy** [comment]
Hey all, I will begin working on this today but I just want to make sure I understand what the ask is here before I start. Basically passing an empty array of repositories as a parameter should return a list of all repos that are a part of an installation but the client discards empty arrays?

**Comment by gmlewis** [comment]
> Hey all, I will begin working on this today but I just want to make sure I understand what the problem is here before I start. Basically passing an empty array of repositories as a parameter should return a list of all repos that are a part of an installation but the client discards empty arrays?

Actually, I'm a bit confused now myself.  The [original description](https://github.com/google/go-github/issues/3106#issue-2190300411) talks about a `POST` call, but the [example given](https://github.com/google/go-github/issues/3106#issuecomment-2002258652) is a `GET` call.

@gillisandrew - can you please clarify what your ask is here, and exactly which `go-github` endpoint(s) you are talking about?

**Comment by gillisandrew** [comment]
@gmlewis Hi thanks for following up. The examples given are correct, the `-d` argument changes the request method to `POST` as demonstrated in the examples on the [man page](https://curl.se/docs/manpage.html#-d).

Sorry for the confusion.

**Comment by gmlewis** [comment]
Oh, cool!  TIL.  Sorry, @gillisandrew - my bad... both are the `POST` case.

OK, so @Matthew-Reidy - we need a new endpoint...
The endpoint we are talking about is [`CreateInstallationToken`](https://github.com/google/go-github/blob/master/github/apps.go#L325-L345).

Now the hard part - what should the name be?

Maybe `CreateInstallationTokenListRepos` ?  @gillisandrew - ideas?

Now the easy part is that this new method will have an internal anonymous struct almost identical to [`InstallationTokenOptions`](https://github.com/google/go-github/blob/master/github/apps.go#L44-L57) with the one modification:

```go
RepositoryIDs []int64 `json:"repository_ids"`
```

and this field will not be assigned a value.

@gillisandrew - have I got all this right?

**Comment by Matthew-Reidy** [comment]
Got it. If there are no objections I'll just move forward with CreateInstallationTokenListRepos as a name for the new endpoint function. If my week goes to plan hopefully I can get a PR in by Friday.

**Comment by Matthew-Reidy** [comment]
Submitted a PR to fix this. Take a look!
