### ISSUE TITLE
`NewTeam` missing `notification_setting` field

### ISSUE THREAD

**Issue by ggabijaa** [google/go-github#3107]
When creating a new team Github API let's to disable notifications for the team by setting `notification_setting` to `notifications_disabled`. 
https://docs.github.com/en/rest/teams/teams?apiVersion=2022-11-28#create-a-team

However, this field is missing from `NewTeam` struct and prevents disabling it
 https://pkg.go.dev/github.com/google/go-github/v60@v60.0.0/github#NewTeam

Would it be possible to add it?

**Comment by gmlewis** [comment]
Absolutely!  Would you like to create a PR, or shall I open this up to our other contributors to this repo?
