### ISSUE TITLE
Stop Supporting Genocide. Stop Nimbus Project.

### ISSUE THREAD

**Issue by sukmapradana** [google/go-github#3132]
Stop Supporting Genocide. Stop Nimbus Project.
Stop Supporting Genocide. Stop Nimbus Project.
Stop Supporting Genocide. Stop Nimbus Project.
Stop Supporting Genocide. Stop Nimbus Project.

**Comment by gmlewis** [comment]
This is inappropriate use of GitHub, @sukmapradana .
This is strike 1 of 3, at which point you will be banned from this repo.

**Comment by sukmapradana** [comment]
> This is inappropriate use of GitHub, @sukmapradana . This is strike 1 of 3, at which point you will be banned from this repo.

Lol, who cares about this shippy repo, damb ship
