### ISSUE TITLE
Support new REST API endpoint that evaluates if private vulnerability reporting is enabled

### ISSUE THREAD

**Issue by diogoteles08** [google/go-github#3152]
GitHub blog announcement: https://github.blog/changelog/2024-03-08-check-if-private-vulnerability-reporting-is-enabled-via-rest-api/

New GET endpoint: https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#check-if-private-vulnerability-reporting-is-enabled-for-a-repository

**Comment by gmlewis** [comment]
Thank you, @diogoteles08 !
Do you want to create a PR for this, or shall I open it up to other contributors?

**Comment by diogoteles08** [comment]
No problem! ^^
Well I might take some time to implement it, as I'll probably use this feature in my project. But wouldn't be able to start **right now**, so let's leave it open in case someone else can start this work sooner than me.

**Comment by Sairaviteja27** [comment]
[gmlewis](https://github.com/gmlewis) I'd be happy to take a look at this and see if I can implement a REST API endpoint to check if private vulnerability reporting is enabled. Is [diogoteles08](https://github.com/diogoteles08) currently working on this? If not, I'm ready to jump in.

**Comment by diogoteles08** [comment]
>  Is @diogoteles08 currently working on this? If not, I'm ready to jump in.

I'm not! Please feel free to work on this, that'd be great 😊
