### ISSUE TITLE
`ListRunnersOption` change omits consideration of Enterprise Runner

### ISSUE THREAD

**Issue by ponkio-o** [google/go-github#3166]
The following PR made changes to support query parameters, but appears to omit consideration of Enterprise Runner.
https://github.com/google/go-github/pull/3094

https://github.com/google/go-github/blob/51bedebff81b00a204050e6b50399f673f719b94/github/enterprise_actions_runners.go#L83

**Comment by gmlewis** [comment]
Thank you, @ponkio-o. Do you want to create a PR that fixes this issue?

**Comment by ponkio-o** [comment]
@gmlewis Thank you for your response. 
Yes. I'm working in progress for this issue.

**Comment by gmlewis** [comment]
> @gmlewis Thank you for your response. Yes. I'm working in progress for this issue.

Excellent, thank you!

**Comment by ponkio-o** [comment]
@gmlewis I fixed this issue in the following PR. Could you please review this?
https://github.com/google/go-github/pull/3167
