### ISSUE TITLE
Support for merge queues.

### ISSUE THREAD

**Issue by mikhail-khodorovskiy** [google/go-github#3170]
What's the PullRequest's method to achieve the click on that "Merge When Ready" button to submit the PR onto the merge queue?  Are the APIs from Github are still missing to make this happen - is that way the library does not yet support it?
![Screenshot 2024-05-14 at 9 34 55 AM](https://github.com/google/go-github/assets/44823822/ed61cce5-4ac1-4ee4-8383-8e84f460c42d)

By looking in the developer console in the UI it looks like the browser submits a form POST to https://github.com/owner/repo/pull/pr-id/auto_merge_requests.

**Comment by gmlewis** [comment]
I don't know. You might want to contact the GitHub v3 API tech support team and ask them.
Feel free to report back here once you have an answer.

**Comment by mikhail-khodorovskiy** [comment]
https://docs.github.com/en/graphql/reference/mutations#enablepullrequestautomerge - they say this is the API to add PR to merge queue.   Is this something that can be added to the library?

**Comment by gmlewis** [comment]
No, unfortunately that is the GitHub v4 GraphQL API, not the v3 RESTful API.
Please see our README.md for more information about the GraphQL API.

Closing as not possible in this repo.
