### ISSUE TITLE
Bug: GetArchiveLink returns a status code 200, not 302, when link is requested with an installation token rather than personal/bearer token

### ISSUE THREAD

**Issue by assembly-winston** [google/go-github#3171]
Inside: `func (s *RepositoriesService) GetArchiveLink(ctx context.Context, owner, repo string, archiveformat ArchiveFormat, opts *RepositoryContentGetOptions, maxRedirects int) (*url.URL, *Response, error)`, it checks for an HTTP code 302:

```
if resp.StatusCode != http.StatusFound {
    return nil, newResponse(resp), fmt.Errorf("unexpected status code: %s", resp.Status)
}
```

When testing with curl, it seems the curl calls returns 200 when they are an installation, rather than 302.

**Comment by gmlewis** [comment]
Do you wish to submit a PR to support both return codes?

**Comment by assembly-winston** [comment]
This behavior is not documented. If I were to submit this PR, would we want to check for either code, or to do a match on what type of token was used and the expected code?

**Comment by gmlewis** [comment]
Over the history of this client library, we have often had to adapt to undocumented behavior from the GitHub v3 API.

It seems to me that the simplest and probably most flexible and robust way to handle this would be to accept either status code without any other restrictions.
