### ISSUE TITLE
GetEnterpriseRunner method appears to be missing

### ISSUE THREAD

**Issue by matt-simons** [google/go-github#3182]
The docs describe the following api https://docs.github.com/en/enterprise-server@3.10/rest/actions/self-hosted-runners?apiVersion=2022-11-28#get-a-self-hosted-runner-for-an-enterprise

however the EnterpriseService does not appear to have a corresponding method https://github.com/google/go-github/blob/master/github/enterprise_actions_runners.go

Happy to raise a PR to add this capability

**Comment by gmlewis** [comment]
Thank you, @matt-simons!
