### ISSUE TITLE
Bug: Multi-select Custom Properties are not supported

### ISSUE THREAD

**Issue by darend** [google/go-github#3198]
## Issue

The Github API supports organizational custom properties with the following types: `string, single_select, multi_select, true_false`. Creating a property with type `multi_select` or `true_false` breaks many of the library interactions due to unmarshalling errors

API Reference: https://docs.github.com/en/rest/orgs/custom-properties?apiVersion=2022-11-28#create-or-update-custom-properties-for-an-organization

## Reproducing

- Create a custom property of type `multi_select` via the UI
- Use library to get organizational custom properties
  - Unmarshalling error
- Assign the custom property a value on a repository
-  Use the library to get the Repository
  - Unmarshalling error

**Comment by gmlewis** [comment]
Thank you, @darend.
Would you like to create a PR, or shall I open this issue up to other contributors to this repo?

**Comment by darend** [comment]
@gmlewis , you can open to the community

**Comment by gmlewis** [comment]
This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

**Comment by arymoraes** [comment]
> This would be a great PR for any new contributor to this repo or a new Go developer. All contributions are greatly appreciated!
> 
> Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.
> 
> Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)
> 
> Thank you!

@gmlewis I am a new Go developer and would like to volunteer to work on this issue if possible. Thank you!

**Comment by gmlewis** [comment]
> @gmlewis I am a new Go developer and would like to volunteer to work on this issue if possible. Thank you!

Thank you, @arymoraes!  It's yours.

**Comment by gmlewis** [comment]
Welcome to Go, @arymoraes!  It's one of my favorite languages and I'm sure you will enjoy the experience after you spend a bit of time with it.

**Comment by arymoraes** [comment]
> Welcome to Go, @arymoraes! It's one of my favorite languages and I'm sure you will enjoy the experience after you spend a bit of time with it.

Awesome, thank you. Looking forward for the experience!
