### ISSUE TITLE
adding the support to custom_property_values webhooks

### ISSUE THREAD

**Issue by hazemarian** [google/go-github#3207]
When there is a webhook event for `custom_property_values` the pkg will return `unknown X-Github-Event in message: custom_property_values`

I think adding this for support will be simple

**Comment by gmlewis** [comment]
Would you like to create a PR for this, @hazemarian, or shall I open this up to other contributors to this repo?

**Comment by hazemarian** [comment]
i will take care of it

**Comment by gmlewis** [comment]
> i will take care of it

Great, thank you, @hazemarian! It's yours.

**Comment by gmlewis** [comment]
@acouvreur - normally, we like to give the original assignee a chance to report on their status before writing a new PR to address an issue assigned to someone else.
However, seeing that you already implemented this, and we haven't heard from @hazemarian for five months, I'll reassign it to you.

**Comment by acouvreur** [comment]
> [@acouvreur](https://github.com/acouvreur) - normally, we like to give the original assignee a chance to report on their status before writing a new PR to address an issue assigned to someone else. However, seeing that you already implemented this, and we haven't heard from [@hazemarian](https://github.com/hazemarian) for five months, I'll reassign it to you.
> 
> EDIT: for some reason, I can't assign it to you, so I've simply unassigned it from [@hazemarian](https://github.com/hazemarian) .

That make sense, given the time elapsed during the initial issue and now I didn't bother asking if I could implement it.

If this happens again, I'll ask first :)
