### ISSUE TITLE
Add support for new Code Security Configurations API

### ISSUE THREAD

**Issue by RickleAndMortimer** [google/go-github#3211]
https://github.blog/changelog/2024-07-17-code-security-configurations-api-now-includes-validity-checks-enforcement-and-removal/

The blog describes added support for three new API endpoints:

[/orgs/{org}/code-security/configurations/detach](https://docs.github.com/en/rest/code-security/configurations?apiVersion=2022-11-28#detach-configurations-from-repositories)

[/orgs/{org}/code-security/configurations
](https://docs.github.com/en/rest/code-security/configurations?apiVersion=2022-11-28#create-a-code-security-configuration)

[/orgs/{org}/code-security/configurations/{configuration_id}](https://docs.github.com/en/rest/code-security/configurations?apiVersion=2022-11-28#detach-configurations-from-repositories)

I can work on this task if we are interested in implementing these endpoints to this repo

**Comment by gmlewis** [comment]
Great, thank you, @RickleAndMortimer !
It's yours.
