### ISSUE TITLE
Missing fields in structure

### ISSUE THREAD

**Issue by AbhishekAg** [google/go-github#3214]
1. https://docs.github.com/en/enterprise-cloud@latest/rest/orgs/custom-roles?apiVersion=2022-11-28#list-custom-repository-roles-in-an-organization
File: orgs_custom_roles.go
Problem: Missing fields in the CustomRepoRoles structure

I have modified the structure to below struct as per the schema.
```
type CustomRepoRoles struct {
	ID          *int64        `json:"id,omitempty"`
	Name        *string       `json:"name,omitempty"`
	Description *string       `json:"description,omitempty"`
	BaseRole    *string       `json:"base_role,omitempty"`
	Permissions []string      `json:"permissions,omitempty"`
	Org         *Organization `json:"organization,omitempty"`
	CreatedAt   *Timestamp    `json:"created_at,omitempty"`
	UpdatedAt   *Timestamp    `json:"updated_at,omitempty"`
}
```

2. https://docs.github.com/en/enterprise-cloud@latest/rest/orgs/organization-roles?apiVersion=2022-11-28#get-all-organization-roles-for-an-organization
File: orgs_custom_roles.go
Problem: Missing fields in the CustomOrgRoles structure

I have modified the structure to below struct as per the schema.

```
type CustomOrgRoles struct {
	ID          *int64        `json:"id,omitempty"`
	Name        *string       `json:"name,omitempty"`
	Description *string       `json:"description,omitempty"`
	Permissions []string      `json:"permissions,omitempty"`
	Org         *Organization `json:"organization,omitempty"`
	CreatedAt   *Timestamp    `json:"created_at,omitempty"`
	UpdatedAt   *Timestamp    `json:"updated_at,omitempty"`
	Source      *string       `json:"source,omitempty"`
	BaseRole    *string       `json:"base_role,omitempty"`
}
```

I want someone to commit the changes in go-github codebase

**Comment by gmlewis** [comment]
You don't want to create a PR even though you have already done all the work?

**Comment by AbhishekAg** [comment]
I don't have permissions to push the changes for the review.
Below are my changes
[custom_roles_changes.txt](https://github.com/user-attachments/files/16323908/custom_roles_changes.txt)

**Comment by gmlewis** [comment]
This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

**Comment by AbhishekAg** [comment]
@gmlewis I have signed the agreement, but still I am unable to submit my changes for review.

```
remote: Permission to google/go-github.git denied to AbhishekAg.
fatal: unable to access 'https://github.com/google/go-github.git/': The requested URL returned error: 403
```

**Comment by gmlewis** [comment]
To make a PR, you first make a fork of the repo.
I believe this is explained in the CONTRIBUTING.md guide. Have you read that guide?

**Comment by AbhishekAg** [comment]
@gmlewis I am able to open the [PR](https://github.com/google/go-github/pull/3216)
