### ISSUE TITLE
Revert mistakenly added fields in DraftReviewComment

### ISSUE THREAD

**Issue by matt-simons** [google/go-github#3219]
In https://github.com/google/go-github/pull/3169 I mistakenly added `CommitID`, `InReplyTo`, and `SubjectType` to `DraftReviewComment` while referring to https://docs.github.com/en/rest/pulls/reviews?apiVersion=2022-11-28#create-a-review-for-a-pull-request. These fields are not however supported in the comments array of https://docs.github.com/en/rest/pulls/reviews?apiVersion=2022-11-28#create-a-review-for-a-pull-request which is what `DraftReviewComment` was intended for. Sorry for the confusion and time wasted.

My intention was to mimic the workflow in the github UI where you can submit a pull request review with review comments on files instead of a line numbers, however on second look I don't think this is possible to do via the API, please correct me if I'm wrong again.

Revert for PR https://github.com/google/go-github/pull/3218

**Comment by gmlewis** [comment]
> My intention was to mimic the workflow in the github UI where you can submit a pull request review with review comments on files instead of a line numbers, however on second look I don't think this is possible to do via the API, please correct me if I'm wrong again.

I believe you are correct.  The GitHub UI appears to take advantage of many of the GitHub v4 GraphQL API, which this repo doesn't support. See README.md for more information about this other API.
