### ISSUE TITLE
Improve godocs based on my experiences

### ISSUE THREAD

**Issue by mjbrender** [google/go-github#322]
I'd like to open a PR with some more clarification around RepositoryContent functions. I misunderstood when I needed to call Decode() and I still confused on when someone might call String(). If others agree, I'd like to capture a few more notes in the comments so godocs captures it. 

Thoughts?

Thanks again for the help on Slack @willnorris :+1:

**Comment by willnorris** [comment]
sounds good to me.  When I was looking at that myself, I also thought that the Content field should probably be documented more clearly.  I also wonder if it's always base64 encoded, or only sometimes.  I wonder if Decode() should always return the content, regardless of encoding.  If it's not encoded at all, then it should just return the plain bytes.  In which case "Decode" might not be the best name for that, but it's probably not worth changing at this point.

**Comment by mjbrender** [comment]
Sounds good. +1 to not worrying about the naming convention and I can't vouch for any other return types. Might be nice to get some test coverage there. I'll open a PR with some additional notes while it's fresh in my mind. 

Is there a use case for needing String() that I haven't seen? I want to add a little explanation there too.

**Comment by willnorris** [comment]
On Wed, Mar 30, 2016 at 11:13 AM, Matt Brender <notifications@github.com>
wrote:

> Is there a use case for needing String() that I haven't seen? I want to
> add a little explanation there too.
>
Mostly just debugging.
