### ISSUE TITLE
Add support for merge queue parameters for organization and repository ruleset

### ISSUE THREAD

**Issue by zhpeng811** [google/go-github#3225]
GitHub recently added full support for merge queue configurations in REST API for organization and repository ruleset

organization: https://docs.github.com/en/rest/orgs/rules?apiVersion=2022-11-28#create-an-organization-repository-ruleset
repository: https://docs.github.com/en/rest/orgs/rules?apiVersion=2022-11-28#create-an-organization-repository-ruleset

<details><summary> Example Screenshot from GitHub's API doc </summary>
<p>

![image](https://github.com/user-attachments/assets/6bbe1dd4-8246-48f8-aea4-bf9bbb2f6201)

</p>
</details> 

merge queue support was previously added in https://github.com/google/go-github/pull/3131, however at that time the REST API did not officially support merge queue, and no parameter support was added at that time.

---
this issue is related to https://github.com/integrations/terraform-provider-github/issues/1481

I'm willing to take this issue and implement it

**Comment by gmlewis** [comment]
Thank you, @zhpeng811 !
It's yours.

**Comment by icep87** [comment]
@zhpeng811 how is the progress on this?
