### ISSUE TITLE
Adding beta feature for rulesets

### ISSUE THREAD

**Issue by grahamhar** [google/go-github#3231]
Hi,

I looked over the readme and contributing guide but couldn't find anything to cover this. Before working on the PR I wanted to check if you accept the addition of features that are flagged as beta in the GitHub API docs. In this case it is the `file_path_restriction` feature in [rulesets API](https://docs.github.com/en/rest/repos/rules?apiVersion=2022-11-28#create-a-repository-ruleset)

**Comment by gmlewis** [comment]
Sure, we welcome new beta features. Thank you for checking, and go right ahead.
