### ISSUE TITLE
Idea: auto fix for fmt and codegen

### ISSUE THREAD

**Issue by spalberg** [google/go-github#3232]
Just an idea, simply close the issue if it does not make sense to you or its overkill :smiley: 

In order to make sure that the generated files are always up to date without any ping-pong in the pull requests, this project could configure an auto fix workflow using github actions - the same goes for fmt if this is ever an issue or any other automatable tasks.

This can be done using the [autofix github app](https://autofix.ci/#:~:text=including%20from%20forks) which also works on PRs from forks. 

Here is an example for a workflow fixing golang PR: https://autofix.ci/setup#go

Since you seem to squash PRs on merge anyway, the potential extra commits fixing the PR should not matter to the history.
The downsides of this approach are that some people might be confused about automated commits on their PRs and  that the app needs to be installed in the github org - although it can be scoped to single repositories, I'm not sure how flexible google is which such things.

**Comment by gmlewis** [comment]
Thank you for the suggestion, @spalberg.
I'm a big fan of automation and would normally want to try this out.

However, this repo is a bit unusual in that I'm the primary maintainer but have no permissions to actually administer the repo settings myself.

I don't know if you have noticed, but we have had an ongoing [Codecov issue](https://github.com/google/go-github/pull/3221#issuecomment-2256325236) in this repo where we are relying upon getting support from the organization that actually owns this repo and has the ability to update its token secrets.

So although I think this is an idea we might want to try out, this repo is probably not a good fit for it and I'll close the issue.

Thanks again, though, @spalberg. Your ideas and contributions are greatly appreciated.
