### ISSUE TITLE
GetHasWiki returns true/false based only on the repository setting

### ISSUE THREAD

**Issue by AkashRajpurohit** [google/go-github#3237]
So what I have noticed is that in GitHub you need to first enable Wiki from repository settings and then go and create the Wiki page, if a user does the first task of enabling the Wiki option from settings and do not create any wiki page, the repo essentially does not "truly" have wiki yet i.e cloning the Wiki from `https://github.com/REPO-OWNER/REPO-NAME.wiki.git` will return 404 since it doesn't exist.

This confused me a bit because I expected `GetHasWiki` will tell me if the repository has a Wiki or not. So wanted to understand if there is any API exposed by this SDK which tells if a repo truly has a wiki?

EDIT:

Was going through the codebase and noticed it is just mapping the `has_wiki` response from the GitHub v3 API. Verified that on API level it just returns based on the repository setting value and not if the wiki is actually enabled or not.
Does seem to be an issue with this SDK, feel free to close it if it doesn't make sense to expose an API from the SDK which returns true wiki enabled or not.

**Comment by gmlewis** [comment]
Indeed, this repo is a Go client library for the GitHub v3 API and can only report back responses it gets from this API.

Therefore, closing this issue.  I suggest that you contact GitHub Tech Support if you would like them to change their API.
