### ISSUE TITLE
Add support for commit squashing

### ISSUE THREAD

**Issue by willnorris** [google/go-github#324]
Announcement: https://developer.github.com/changes/2016-04-01-squash-api-preview/
API Docs: https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button

Unfortunately, this will almost certainly require a breaking change to https://godoc.org/github.com/google/go-github/github#PullRequestsService.Merge

**Comment by gsquire** [comment]
I can work on this. Would providing another function such that the existing merge function doesn't change be beneficial?

**Comment by willnorris** [comment]
I think a breaking change is okay here.
