### ISSUE TITLE
'Mark Thread As Done' is missing.

### ISSUE THREAD

**Issue by danhcole** [google/go-github#3264]
As documented in [Mark a thread as done](https://docs.github.com/en/rest/activity/notifications?apiVersion=2022-11-28#mark-a-thread-as-done), it would be very nice to be able to mark threads as done via this package.  

I'm happy to put up a PR for this (and have one working locally), but wanted to open an issue first.

**Comment by gmlewis** [comment]
Thank you, @danhcole !  It is yours.
