### ISSUE TITLE
Specify type as "PR" when doing an issue search

### ISSUE THREAD

**Issue by ianwalter** [google/go-github#327]
I'm trying to search for pull requests and, if I'm not mistaken, they are really issues with the type of `pr`. It seems the issue search accepts `SearchOptions` which is general and doesn't allow you to specify a type. I plan to submit a PR to fix this but I wanted to create this issue in the meantime to make sure I'm not missing something. Thanks.

**Comment by gmlewis** [comment]
According to https://developer.github.com/v3/search/#search-issues it appears that there are a large number of options that could be added to the `q` query parameter, and as far as I can tell, it is currently not possible to add them (neither by `SearchOptions` nor the embedded `ListOptions`).  @willnorris will be able to state definitively if this is correct.

So a PR to fix this SGTM.

**Comment by willnorris** [comment]
As Glenn notes, these are expected to be part of the query.  So, 

```go
client.Search.Issues("foo type:pr")
```

**Comment by ianwalter** [comment]
Ahh I see, thanks for your help.

**Comment by willnorris** [comment]
we could probably stand to better document that fact though, so if you wanted to do a pull request to update the docs, that'd be great.

**Comment by ianwalter** [comment]
Alright, I'll see if I can make it clearer.
