### ISSUE TITLE
Feature: Add support for Repo/Org Push rulesets

### ISSUE THREAD

**Issue by srgustafson8** [google/go-github#3274]
GitHub launched [push rules](https://github.blog/changelog/2024-09-10-push-rules-are-now-generally-available-and-updates-to-custom-properties/) for rulesets to GA recently where you can allow only a certain team or group to push particular paths or files. The API has documentation now to support `push` rule targets for both [Repository](https://docs.github.com/en/rest/repos/rules?apiVersion=2022-11-28#create-a-repository-ruleset--parameters) and [Organisation](https://docs.github.com/en/rest/orgs/rules?apiVersion=2022-11-28#create-an-organization-repository-ruleset--parameters). 

It would be great to be able to support creating and managing these programatically.

**Comment by gmlewis** [comment]
Yes, this is already supported, by setting the `Ruleset.Target` field to "push".

However, I've made #3275 to update the comment to make this more clear.

**Comment by gmlewis** [comment]
Please let me know if I've missed something, @srgustafson8 .

**Comment by srgustafson8** [comment]
@gmlewis thank you - I should have looked a bit deeper. Great to see this is already supported!

**Comment by gmlewis** [comment]
> @gmlewis thank you - I should have looked a bit deeper. Great to see this is already supported!

No worries!  It is also great to have the comments up-to-date to make things easier to find, so thank you for reporting the issue.

**Comment by srgustafson8** [comment]
Hi @gmlewis - having done a bit more digging, I believe there is some work required to fully support the push rulesets. The target can be set to `push` already, but I see https://github.com/google/go-github/pull/3233 was needed to implement support for _Restrict file paths_ rules. There are three other push ruleset rule types that would be good to support, _Restrict file path length_, _Restrict file extensions_ and _Restrict file size_. 

If you agree and this gets reopened, then I'm happy to give this a go when I get a chance.

**Comment by gmlewis** [comment]
> If you agree and this gets reopened, then I'm happy to give this a go when I get a chance.

Thank you, @srgustafson8 !
It's yours.
