### ISSUE TITLE
Add support for `assignment` on teams and users assigned to organization roles

### ISSUE THREAD

**Issue by stevehipwell** [google/go-github#3364]
When listing teams or users assigned to an organization role the ~~`assigned`~~ `assignment` field isn't getting set and the team `parent` and user `inherited_from` are also not getting set. I assume that this is because these endpoints are being mapped back to `Team` and `User` structs instead of being a custom type.

**Comment by gmlewis** [comment]
I'm assuming you are talking about these endpoints:

* https://github.com/google/go-github/blob/c6856bc9e29aeba0999a959f7a892098b18ff965/github/orgs_organization_roles.go#L243-L268
* https://github.com/google/go-github/blob/c6856bc9e29aeba0999a959f7a892098b18ff965/github/orgs_organization_roles.go#L270-L295

which correspond with these official docs:

* https://docs.github.com/rest/orgs/organization-roles#list-teams-that-are-assigned-to-an-organization-role
* https://docs.github.com/rest/orgs/organization-roles#list-users-that-are-assigned-to-an-organization-role

and I'm not seeing any mention of a field called `assigned`.

Therefore, could you please be a bit more specific about which exact endpoints you are talking about and where in the documentation it documents the returned field called `assigned`?

**Comment by stevehipwell** [comment]
@gmlewis thanks for the quick response, those are the endpoints. Sorry I typoed the issue (but not the title), it's `assignment`. The schema for both of the endpoints you linked above have it defined but it's not present in the examples.

I may be incorrect about the team `parent` not being correctly set here as the logic to use it is dependent on `assignment`.

**Comment by gmlewis** [comment]
Excellent, thank you for the clarification, @stevehipwell !  I see it now in the schema definitions.

Would you like to submit a PR to add a new `Assignment` field to both `User` and `Team`, or would you like me to do this?

It should most likely look like this:

```go
Assignment *string `json:"assignment,omitempty"`
```

**Comment by gmlewis** [comment]
Yes, I would add the new field to the end of the `User` and `Team` structs in their corresponding Go files, with a comment as to why this field is being added.

Something like `// Assignment is populated by the ListUsersAssignedToOrgRole method. Its possible values are: "direct", "indirect", "mixed".` I would also add a blank line before this (at the very end of the struct) to separate it out from the "normal" usage.

Awesome, it is yours. Thank you, @stevehipwell !
