### ISSUE TITLE
Add missing function to get a custom repository role for an org

### ISSUE THREAD

**Issue by stevehipwell** [google/go-github#3370]
The function to [Get a custom repository role](https://docs.github.com/en/enterprise-cloud@latest/rest/orgs/custom-roles?apiVersion=2022-11-28#get-a-custom-repository-role) for an organization is currently missing. I'd expect to see a `GetCustomRepoRole` function.

**Comment by gmlewis** [comment]
Yes, would you like to add it, @stevehipwell ?

**Comment by stevehipwell** [comment]
@gmlewis I'll add it to the list.
