### ISSUE TITLE
make sure we support the new webhook changes

### ISSUE THREAD

**Issue by willnorris** [google/go-github#339]
I can't remember if we already talked about these or not, but can't find an existing issue for it.

Announcement: https://developer.github.com/changes/2016-04-18-new-webhook-actions-are-live/

**Comment by willnorris** [comment]
oh, actually now that I look more closely, I guess these are *only* changes to the action values?  So in that case, it's probably just a documentation change.

**Comment by willnorris** [comment]
Looks like these changes haven't been made in the library yet.  Oh and look, an event for when repos are deleted.  😄 👍

**Comment by gmlewis** [comment]
Woohoo!  I'll work on adding these.  Thanks, Will! 👍
