### ISSUE TITLE
`CommitStats` in the `Commit` struct is always nil

### ISSUE THREAD

**Issue by acouvreur** [google/go-github#3394]
The `CommitStats` in the `Commit` struct is always nil.

Comparing the current `Commit` struct:

https://github.com/google/go-github/blob/c4a49db9ca5d5f737f459fa97e3b86c52339b978/github/git_commits.go#L44-L62

With the GitHub OpenAPI Spec:
![Image](https://github.com/user-attachments/assets/47e0bb63-8653-4fac-bc64-707d42d3486e)

The `Stats` field is not on the OpenAPI Contract.

---

I know that structs can be used to represents objects that look alike a lot (hence the `CommentCount` field).

So I'm not sure if the `Stats` field is also one of these exceptions. If that's the case, it should be explained just like `CommentCount`.

**Comment by gmlewis** [comment]
I'm not sure I would call this issue a "bug".

According to GitHub, that line was added in 2013 in this commit:
https://github.com/google/go-github/commit/1eaf38380d74925650bee1593df74e1a1c0dc3a7#diff-58a05e976d34ffef86ba94037754253cc9c33d354c78296018a375577ead4b19R21
entitled "implement repos_commits API".

So apparently it was once used by GitHub.  As to its current usage, that would definitely require some investigation.
I'm happy to leave this issue open in case anyone would like to perform some investigation into this field's usage
and add a comment as to how and when it is used.

**Comment by acouvreur** [comment]
> I'm not sure I would call this issue a "bug".
> 
> According to GitHub, that line was added in 2013 in this commit: [1eaf383#diff-58a05e976d34ffef86ba94037754253cc9c33d354c78296018a375577ead4b19R21](https://github.com/google/go-github/commit/1eaf38380d74925650bee1593df74e1a1c0dc3a7#diff-58a05e976d34ffef86ba94037754253cc9c33d354c78296018a375577ead4b19R21) entitled "implement repos_commits API".
> 
> So apparently it was once used by GitHub. As to its current usage, that would definitely require some investigation. I'm happy to leave this issue open in case anyone would like to perform some investigation into this field's usage and add a comment as to how and when it is used.

Thanks for the quick answer @gmlewis. I will investigate as it wrongly put me into assuming I could check a created commit stats from the response.

I do think that it is not populated at all in any case. If that's the case I can submit a PR removing that field, otherwise a PR explaining where it is used.

**Comment by gmlewis** [comment]
> I do think that it is not populated at all in any case. If that's the case I can submit a PR removing that field, otherwise a PR explaining where it is used.

Excellent.  Thanks, @acouvreur . Sounds good.  It's yours.

**Comment by acouvreur** [comment]
`Commit` struct analysis:

<details>
  <summary>Usage in struct `CheckSuite`: ✅ No usage</summary>

  The `Commit` struct is used in `CheckSuite.HeadCommit`:
  https://github.com/google/go-github/blob/c4a49db9ca5d5f737f459fa97e3b86c52339b978/github/checks.go#L71-L92

  As mentionned, the `HeadCommit` field is only populated by Webhook events, so let's check [CheckSuite Webhooks events](https://docs.github.com/en/webhooks/webhook-events-and-payloads#check_suite):
  ![Image](https://github.com/user-attachments/assets/0ea4a182-ce6f-4efe-a722-c8bbab767b1e)

  This is the same for `completed`, `requested` and `rerequested`.
  Conclusion: no usage of `Stats` in `CheckSuite.HeadCommit`
</details>
<details>
  <summary>Usage in struct `MergeGroup`: ✅ No usage</summary>

  The `Commit` struct is used in `MergeGroup.HeadCommit`:
  https://github.com/google/go-github/blob/c4a49db9ca5d5f737f459fa97e3b86c52339b978/github/event_types.go#L842-L854

  The `MergeGroup` structure is only used through the `MergeGroupEvent` struct, so let's check [MergeGroup Webhooks events](https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=checks_requested#merge_group):
  ![Image](https://github.com/user-attachments/assets/801825b5-d007-47c9-9afa-c366649914cc)


  This is the same for `checks_requested` and `destroyed`.
  Conclusion: no usage of `Stats` in `MergeGroup.HeadCommit`
</details>
<details>
  <summary>Usage in struct `Commit`: ✅ No usage</summary>

  The `Commit` struct is used in `Commit.Parents`:
  https://github.com/google/go-github/blob/c4a49db9ca5d5f737f459fa97e3b86c52339b978/github/git_commits.go#L44-L62

 `Parents` in Commit look like this (from the OpenAPI Contract):
  ![Image](https://github.com/user-attachments/assets/19932ba3-1932-43b0-94ec-09e85750afa2)

  This could be refined to be a `CommitRef` instead of `Commit` though.

  Conclusion: no usage of `Stats` in `Commit.Parents`
</details>
<details>
  <summary>Usage in struct `Timeline`: ✅ No usage</summary>

  The `Timeline` struct is used in `Timeline.Parents`:
  https://github.com/google/go-github/blob/c4a49db9ca5d5f737f459fa97e3b86c52339b978/github/issues_timeline.go#L18-L38

  This is only used in a single Timeline event, which is `committed`: https://docs.github.com/en/rest/using-the-rest-api/issue-event-types?apiVersion=2022-11-28#properties-for-committed

 `Parents` in the Timeline Committed event look like this (from the OpenAPI Contract):
  ![Image](https://github.com/user-attachments/assets/8afd4e4c-378a-4b5c-88f8-5629a2922f63)

  This could be refined to be a `CommitRef` instead of `Commit` though, just like the one in Parents.

  Conclusion: no usage of `Stats` in `Timeline.Parents`
</details>
<details>
  <summary>Usage in struct `RepositoryTag`: ✅ No usage</summary>

  The `RepositoryTag` struct is used in `RepositoryTag.Commit`:
  https://github.com/google/go-github/blob/master/github/repos.go#L967-L973

  This is only used in listing the tags in a repository: https://docs.github.com/en/rest/repos/repos#list-repository-tags

 `Commit` look like this (from the OpenAPI Contract):
  ![Image](https://github.com/user-attachments/assets/2eeb2b49-4337-4e22-b453-4f6dc06a1d69)

  This could be refined to be a `CommitRef` instead of `Commit` again to avoid confusion.

  Conclusion: no usage of `Stats` in `RepositoryTag.Commit`
</details>
<details>
  <summary>Usage in struct `BranchCommit`: ✅ No usage</summary>

  The `BranchCommit` struct is used in `BranchCommit.Commit`:
  https://github.com/google/go-github/blob/master/github/repos_commits.go#L118-L123

  This is only used in listing branches for HEAD commit: https://docs.github.com/en/rest/commits/commits#list-branches-for-head-commit

 `Commit` look like this (from the OpenAPI Contract):
  ![Image](https://github.com/user-attachments/assets/2c59a3fc-3ea9-4232-b4ab-fe8ea2c7a707)


  This could be refined to be a `CommitRef` instead of `Commit` again to avoid confusion.

  Conclusion: no usage of `Stats` in `BranchCommit.Commit`
  </details>
  <details>
  <summary>Usage in struct `RepositoryCommit`: ✅ No usage</summary>

  The `RepositoryCommit` struct is used in `RepositoryCommit.Commit` and `RepositoryCommit.Parents`:
  https://github.com/google/go-github/blob/c4a49db9ca5d5f737f459fa97e3b86c52339b978/github/repos_commits.go#L16-L34

  `RepositoryCommit` is used in a lot of different places:
  <details>
  <summary>Usage in struct `StatusEvent`: ✅ No usage</summary>
  The `StatusEvent` struct is not used directly by any function or struct.

  And the [event schema](https://docs.github.com/en/webhooks/webhook-events-and-payloads#status) is defined as:
  ![Image](https://github.com/user-attachments/assets/f5964828-ee03-4e04-9548-71ca43aa79bb)
  ![Image](https://github.com/user-attachments/assets/ac504233-800e-4a6f-af75-1bd5865a3a10)
  ![Image](https://github.com/user-attachments/assets/b2e7c710-5d1d-4e1b-9752-5d93eb0b4b52)
  Conclusion: no usage of `Stats` in `StatusEvent.Commit`, `StatusEvent.Parents` and `StatusEvent.Branches.Commit`
  </details>
  <details>
  <summary>Usage in function `RepositoriesService.ListBranches`: ✅ No usage</summary>
  The `RepositoriesService.ListBranches` function returns a `Branch` which contains a `RepositoryCommit`.

  The OpenAPI Schema defines the following:
  ![Image](https://github.com/user-attachments/assets/2c86d3c3-292f-4eb2-a816-9be845501bc7)

  This could be refined to be a `CommitRef` instead of `Commit` again to avoid confusion.
  
  Conclusion: no usage of `Stats` in `Branch.Commit.Commit` when called through `RepositoriesService.ListBranches`
  </details>
  <details>
  <summary>Usage in function `RepositoriesService.GetBranch`: ✅ No usage</summary>
  The `RepositoriesService.GetBranch` function returns a `Branch` which contains a `RepositoryCommit`.

  The OpenAPI Schema defines the following:
  ![Image](https://github.com/user-attachments/assets/614ddc5a-a872-45b7-8931-d8ac03758412)
  
  Conclusion: no usage of `Stats` in `Branch.Commit.Commit` when called through `RepositoriesService.GetBranch`
  </details>
  <details>
  <summary>Usage in function `RepositoriesService.RenameBranch`: ✅ No usage</summary>
  The `RepositoriesService.RenameBranch` function returns a `Branch` which contains a `RepositoryCommit`.

  The OpenAPI Schema defines the following:
  ![Image](https://github.com/user-attachments/assets/cceece8a-2691-4740-9f50-95dcfab9913c)
  
  Conclusion: no usage of `Stats` in `Branch.Commit.Commit` when called through `RepositoriesService.RenameBranch`
  </details>
  <details>
  <summary>Usage in function `RepositoriesService.CompareCommits`: ✅ No usage</summary>

  The `RepositoriesService.CompareCommits` function returns a `CommitsComparison` which contains two `RepositoryCommit` (`BaseCommit` and `MergeBaseCommit` fields).

  The OpenAPI Schema defines the following:
  ![Image](https://github.com/user-attachments/assets/67161bde-d295-4145-8200-436f36795dd8)
  ![Image](https://github.com/user-attachments/assets/ffad7334-f657-490a-a6c1-d08a93221997)
  
  Conclusion: no usage of `Stats` in `CommitComparaison.BaseCommit.Commit` and `CommitComparaison.MergeBaseCommit.Commit` when called through `RepositoriesService.CompareCommits`
  </details>
  <details>
  <summary>Usage in function `PullRequestsService.ListCommits`: ✅ No usage</summary>

  The `PullRequestsService.ListCommits` function returns a `CommitsComparison` which contains two `RepositoryCommit` (`BaseCommit` and `MergeBaseCommit` fields).

  The OpenAPI Schema defines the following:
  ![Image](https://github.com/user-attachments/assets/67161bde-d295-4145-8200-436f36795dd8)
  ![Image](https://github.com/user-attachments/assets/ffad7334-f657-490a-a6c1-d08a93221997)
  
  Conclusion: no usage of `Stats` in `CommitComparaison.BaseCommit.Commit` and `CommitComparaison.MergeBaseCommit.Commit` when called through `RepositoriesService.CompareCommits`
  </details>
</details>

I have a few more structs to go through, but overall it looks like Stats inside Commit is never actually used in any circumstances.

Does that make sense to deprecate or even remove the field at all ?

**Comment by gmlewis** [comment]
> Does that make sense to deprecate or even remove the field at all ?

With this detailed analysis, I'm totally fine with you creating a PR to remove the field. 

Thank you for doing this deep dive, @acouvreur !
