### ISSUE TITLE
Repository Discussions

### ISSUE THREAD

**Issue by incognick** [google/go-github#3399]
Hey all, I'm having a hard time trying to locate documentation for Discussions API at the repository level.  I do see it at the teams level and also I see this library provides that.  What I can't seem to find is API docs even on GitHub's site for repository level discussion.  

I can query the REST endpoint here using `httpie`

```
 http https://api.github.com/repos/go-chi/chi/discussions
```

Is this hidden in this repo somewhere that I'm not seeing? 

I appreciate the help!

**Comment by gmlewis** [comment]
As far as I can tell, the official GitHub v3 REST API only provides methods to access "Teams Discussions" and not "Repository Discussions".

![Image](https://github.com/user-attachments/assets/d4531649-26d0-4146-bfe2-5e82d357420b)

You might want to contact GitHub Tech Support and ask them if they support repository discussions with the v3 API.

**Comment by incognick** [comment]
Ok great,  so I'm not the only one!  It's really confusing that the API is there and I can hit it. Thanks, I'll ping them.

**Comment by gmlewis** [comment]
Thanks, @incognick !

Feel free to report back to this issue any findings you may get, and we can reopen the issue to support the API if it exists.

**Comment by incognick** [comment]
Thanks for the quick response Glenn!
