### ISSUE TITLE
DownloadReleaseAsset swallows API errors & returns io.ReadCloser of error payload

### ISSUE THREAD

**Issue by rodaine** [google/go-github#343]
If the API request to download a release asset fails, no `error` is returned but the `io.ReadCloser` of the error JSON payload is:

```go
package main

import (
	"fmt"
	"io"
	"os"

	"github.com/google/go-github/github"
)

func main() {
	client := github.NewClient(nil)

	rc, url, err := client.Repositories.DownloadReleaseAsset("not-a", "real-repo", 0)
	if err != nil {
		fmt.Println("error:", err)
	}

	if rc != nil {
		fmt.Print("rc: ")
		io.Copy(os.Stdout, rc)
		fmt.Print("\n")
		rc.Close()
	}

	if url != "" {
		fmt.Println("url:", url)
	}
}
```

Would expect:

```
→ go run main.go
error: Not Found
```

But what is returned:

```
→ go run main.go
rc: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
```

**Comment by willnorris** [comment]
looks like a bug on https://github.com/google/go-github/blob/bf7dc3b8937bbfcfe5986ec3b3793d5c96a901f9/github/repos_releases.go#L251.  That should be:

```go
return nil, loc, err
```

could you try changing that locally and see if it fixes it?

**Comment by willnorris** [comment]
err, never mind.  I don't think that's right.  I was switching the error cases in my head.

**Comment by rodaine** [comment]
it appears on https://github.com/google/go-github/blob/bf7dc3b8937bbfcfe5986ec3b3793d5c96a901f9/github/repos_releases.go#L246, err is nil but the resp object has a 404 status code:

`&{Status:404 Not Found StatusCode:404 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Access-Control-Expose-Headers:[ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval] Content-Security-Policy:[default-src 'none'] X-Xss-Protection:[1; mode=block] Status:[404 Not Found] X-Ratelimit-Remaining:[42] X-Frame-Options:[deny] Strict-Transport-Security:[max-age=31536000; includeSubdomains; preload] X-Github-Request-Id:[2887EE2A:DA38:5852492:571925ED] Server:[GitHub.com] Content-Type:[application/json; charset=utf-8] X-Ratelimit-Reset:[1461267711] X-Github-Media-Type:[unknown] Access-Control-Allow-Origin:[*] Date:[Thu, 21 Apr 2016 19:11:41 GMT] X-Ratelimit-Limit:[60] X-Content-Type-Options:[nosniff]] Body:0xc82033c200 ContentLength:-1 TransferEncoding:[chunked] Close:false Trailer:map[] Request:0xc8200e8000 TLS:0xc8202622c0}`

**Comment by willnorris** [comment]
right.  a 404 response is not an error.  From https://golang.org/pkg/net/http/#Client.Do:

> An error is returned if caused by client policy (such as CheckRedirect), or if there was an HTTP protocol error. A non-2xx response doesn't cause an error.

**Comment by rodaine** [comment]
Right, but in this instance I think that's what we want. I'll create a patch to check the exit code, and if it's not a 200 or 302, return an error (per https://developer.github.com/v3/repos/releases/#get-a-single-release-asset)

**Comment by willnorris** [comment]
you don't want to just check for 200 or 302 here.  GitHub could change that to be any number of other redirect codes (301, 307, 308).  Similarly, a successful response could be somewhere else in the 200 range.  Instead, you want something like:

```go
if c := resp.StatusCode; c < 200 || 300 < c {
    // return error
}
```

**Comment by willnorris** [comment]
err, that should be:

```go
if c := resp.StatusCode; c < 200 || 400 <= c {
    // return error
}
```

**Comment by rodaine** [comment]
Ah, good point. Though thinking about it more, the 3XX codes should be handled by the CheckRedirect. Do you think it's reasonable to just verify the 2XX range?

**Comment by rodaine** [comment]
Better yet:

```go
	if err := CheckResponse(resp); err != nil {
		return nil, "", err
	}
```
