### ISSUE TITLE
Add support for Issue Timeline API

### ISSUE THREAD

**Issue by willnorris** [google/go-github#360]
announcement: https://developer.github.com/changes/2016-05-23-timeline-preview-api/

docs: https://developer.github.com/v3/issues/timeline/

**Comment by shurcooL** [comment]
Does anyone know how this differs from https://developer.github.com/v3/issues/events/#list-events-for-an-issue?

**Comment by willnorris** [comment]
no clue, I haven't looked too closely yet. I just saw the blog post announcing it this morning, so filed an issue for it.

**Comment by gmlewis** [comment]
From GitHub Tech Support:

> Those two endpoints are indeed very similar, but the Timeline API gives you more events, for example the cross-referenced event is not available in the Events API. We're also looking into providing more data for existing events and making some minor changes there, which would have been harder to do in the Events API since integrations are already relying on the behavior of that endpoint (and the Timeline API is a new endpoint noone is relying on yet).

So we can go ahead with this one.
