### ISSUE TITLE
Webhooks: Add example for signatures

### ISSUE THREAD

**Issue by parkr** [google/go-github#361]
Was just reading through ["Validating payloads from GitHub"](https://developer.github.com/webhooks/securing/#validating-payloads-from-github) and figured it would be nice to have that either built into the library or have an example in the repo which folks can copy.

In a perfect world, it'd be as simple as:

```go
package main

import (
    "github.com/google/go-github/github"
)

func main() {
    http.HandleFunc("/hook", func(w http.ResponseWriter, r *http.Request) {
        if !github.VerifyPayload(r, os.Getenv("GH_WEBHOOK_SIGNATURE")) {
            http.Error(w, "invalid signature", http.StatusForbidden)
        } 
    })

    log.Fatal(http.ListenAndServe(":8080", nil))
}
```

Then `github.VerifyPayload` would read the payload & secret, verify with something like `crypto/sha1`, and return whether things check out.

What do you think?

**Comment by willnorris** [comment]
see #294

**Comment by willnorris** [comment]
I started review that some time ago, but then got distracted and hadn't looked at the latest version of it

**Comment by parkr** [comment]
@willnorris 👋 

#294 is _exactly_ what I was looking for!!!
