### ISSUE TITLE
go vet violations on tip.

### ISSUE THREAD

**Issue by shurcooL** [google/go-github#386]
We have a few minor go vet violations when using vet from tip (1.7-ish) rather than 1.6.2. Can be seen in CI:

https://travis-ci.org/google/go-github/builds/140438111
https://travis-ci.org/google/go-github/jobs/140438114

```
$ go tool vet .
github/examples_test.go:15: ExampleClient_Markdown refers to unknown identifier: Client
github/examples_test.go:29: ExampleRepositoriesService_GetReadme refers to unknown identifier: RepositoriesService
github/examples_test.go:47: ExampleRepositoriesService_List refers to unknown identifier: RepositoriesService
github/examples_test.go:61: ExampleUsersService_ListAll refers to unknown identifier: UsersService
The command "go tool vet ." exited with 1.
```

**Comment by gmlewis** [comment]
As far as I can tell, this is a Go1.7tip bug.
We are adhering to the naming convention defined in the [Examples](https://golang.org/pkg/testing/#hdr-Examples) documentation.

Filed Go issue: https://github.com/golang/go/issues/16189

**Comment by shurcooL** [comment]
I've seen this issue [happen](https://travis-ci.org/shurcooL/Conception-go/builds/138006555) in some of my own packages too, and I suspected it might be a bug/regression in tip. I didn't have time to investigate.

> We are adhering to the naming convention defined in the [Examples](https://golang.org/pkg/testing/#hdr-Examples) documentation.

I agree with your assessment.

Thanks for looking into it and filing the issue upstream Glenn. 👍

**Comment by gmlewis** [comment]
Go1.7 has been fixed upstream and tip is now passing tests.
