### ISSUE TITLE
update to protected branches preview

### ISSUE THREAD

**Issue by willnorris** [google/go-github#387]
announcement: https://developer.github.com/changes/2016-06-27-protected-branches-api-update/

**Comment by gmlewis** [comment]
Note that this is a breaking API change so the version needs bumping by a whole number (i.e. "3").

**Comment by yozamacs** [comment]
can you assign this to me please?

**Comment by willnorris** [comment]
invite sent to collaborate on the repo.

**Comment by alindeman** [comment]
I took a stab at some of this in #476
