### ISSUE TITLE
User.ListEmails returns a 404

### ISSUE THREAD

**Issue by catchamonkey** [google/go-github#409]
Hi!

Loving the library, good work :)

Everything was fine and dandy, except i'm seeing a 404 when trying to list an authenticated users Emails.

```go
emails, _, err := client.User.ListEmails(nil)
```

Gives 

GET https://api.github.com/user/emails: 404 Not Found []
in my console running the app.

Scope requested is ```user:email``` which should be plenty.

Just wondering if you've seen anything like this before, or if it's an error in how i'm using it.

Many thanks.

**Comment by catchamonkey** [comment]
Yeah, so it was me 👯 

I have wrapped the client in a struct with an anonymous field so it encapsulates my auth header.
So I actually need to get back the Client from my struct.

My mistake!

**Comment by gmlewis** [comment]
Glad you found the problem and are enjoying the library!  Thanks for the kind words, @catchamonkey!
