### ISSUE TITLE
Support for shallow clone

### ISSUE THREAD

**Issue by apuigsech** [google/go-github#414]
Would be useful in some cases to have shallow clone with the same feature that implementes "git clone --depth".

**Comment by willnorris** [comment]
Sounds like maybe you're looking for https://github.com/gogits/git ?  go-github is focused pretty squarely on implementing the [GitHub API](https://developer.github.com/v3/), not git itself.

**Comment by apuigsech** [comment]
Sorry, I opened the issue on the wrong project 👎

**Comment by sona-tar** [comment]
gogits/git author said,
> it is out of maintenance, recommend https://github.com/src-d/go-git for now.

https://github.com/gogits/git/issues/17
