### ISSUE TITLE
Authorize failed in `(s *RepositoriesService) List () {}`

### ISSUE THREAD

**Issue by ccqpein** [google/go-github#429]
Hi, I want to use `go-github` to get the statistics data from GitHub. It works month ago, but not yesterday when I tried to use it. 

I get the nothing at beginning, then I change the code like below.

~~~
func GetAllRepos(userName string) []*github.Repository {
	fi, err := ioutil.ReadFile("./token")
	if err != nil {
		panic(err)
	}

	// Println(string(fi))
	ts := oauth2.StaticTokenSource(
		&oauth2.Token{AccessToken: string(fi)},
	)

	tc := oauth2.NewClient(oauth2.NoContext, ts)
	client := github.NewClient(tc)
	Println(*client)
	ReOption := &github.RepositoryListOptions{Type: "owner"}

	repos, _, err2 := client.Repositories.List(userName, ReOption)
	if err2 != nil {
		Println(err2)
	}

	return repos
}
~~~

Then I get the error(err2) message:

*Get https://api.github.com/users/userName/repos?type=owner: net/http: invalid header field value "Bearer [Token String]\n" for key Authorization*

I paste this authorization-code from document, but it cannot work now. 

Could you please help what is matter of this authorization-code?

Thank you!

**Comment by shurcooL** [comment]
Is your token in the `./token` file valid? Can you check it? (Don't paste it here since it's your sensitive access information.)

Your authentication setup code looks valid. I used https://godoc.org/github.com/google/go-github/github#hdr-Authentication as reference.

Can you ensure your dependencies are not out of date by running `go get -u github.com/google/go-github/github`?

What version of Go are you using (i.e., run `go version` and `go env`)?

**Comment by ccqpein** [comment]
My token file is valid, I didn't change anything until last night. After error happened, I re-token once and paste the token in `./token` file. I believe it is right.

I used https://godoc.org/github.com/google/go-github/github#hdr-Authentication as reference too. In fact, I almost copy and paste the authentication code in my code. And it works well in last month until I found it has some issues last night.

And yes, I run `go get -u all` last night immediately at the problem happened. Also I just run `go get -u github.com/google/go-github/github` for sure, the problem still exists.

My version information and environment information:

> go version go1.7.1 darwin/amd64


> GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/myname/gogot:/Users/myname/Desktop/goexci"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.1/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/2v/dzklvg4s3zv44j_4wypzffqm0000gn/T/go-build568645023=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

**Comment by ccqpein** [comment]
Addition information you might be interested in:

I used Print() to check the where the error information come from:

->client.Repositories.List()
->resp, err := s.client.Do(req, repos)  //170 lines in `github/repos.go`
->resp, err := c.client.Do(req)  //379 lines in `github/github.go`

**Comment by shurcooL** [comment]
I tried the following snippet right now, and it worked without issue for me:

```
package main

import (
	"fmt"

	"github.com/google/go-github/github"
	"golang.org/x/oauth2"
)

func GetAllRepos(userName string) ([]*github.Repository, error) {
	ts := oauth2.StaticTokenSource(
		&oauth2.Token{AccessToken: "<my access token>"}, // actual access token removed
	)

	tc := oauth2.NewClient(oauth2.NoContext, ts)
	client := github.NewClient(tc)
	opt := &github.RepositoryListOptions{Type: "owner"}

	repos, _, err := client.Repositories.List(userName, opt)
	if err != nil {
		return nil, err
	}

	return repos, nil
}

func main() {
	repos, err := GetAllRepos("shurcooL")
	if err != nil {
		fmt.Println("got error")
		fmt.Println(err)
		return
	}
	fmt.Printf("got %v repos\n", len(repos))

	// Output:
	// got 30 repos
}
```

So I think the issue is somewhere on your end, not in go-github.

**Comment by ccqpein** [comment]
I get it. 

~~~
fi, err := ioutil.ReadFile("./token")
    if err != nil {
        panic(err)
    }
~~~

`string(fi)` not equal "[token]" anymore, so the authorization is failed. I dont know why Go change this, but at least I know what's wrong with my code.

Thank you!
