### ISSUE TITLE
create issue using a token fails

### ISSUE THREAD

**Issue by mh-cbon** [google/go-github#435]
Hi,

I m not able to create an issue using an access token.

API will answer

```
POST https://api.github.com/repos/mh-cbon/demotest/issues: 401 Bad credentials []
```

My code is like this,

```go
    input := &github.IssueRequest{
        Title:    &g.IssueTitle,
        Body:     &body,
  }

    ts := oauth2.StaticTokenSource(
        &oauth2.Token{AccessToken: g.Token},
    )
  tc := oauth2.NewClient(oauth2.NoContext, ts)
  client := github.NewClient(tc)

  _, _, err = client.Issues.Create(g.Owner, g.Repo, input)
```

The token was created with those permissions,

```
repo
repo:status
repo:repo_deployment 
repo:public_repo

user
user:email
user:follow
```

Later i tried with basic auth,

```go
  	input := &github.IssueRequest{
  		Title:    github.String(g.IssueTitle),
  		Body:     github.String(body),
    }

  	// ts := oauth2.StaticTokenSource(
  	// 	&oauth2.Token{AccessToken: g.Token},
  	// )
    // tc := oauth2.NewClient(oauth2.NoContext, ts)
    tc := github.BasicAuthTransport{
      Username: "xxxx",
      Password: "yyy",
    }
    client := github.NewClient(tc.Client())
    
    _, _, err = client.Issues.Create(g.Owner, g.Repo, input)
```

It worked fine.

I saw somewhere people adds a `login=xxx` query string parameter. 
Could this be the problem ? 
How can i add a qs param to this create issue request ?

Any help appreciated, i really don t want to use a basic auth.

**Comment by parkr** [comment]
I use a token as well for all my requests and create a client this way: https://github.com/parkr/auto-reply/blob/bcefb6fb552c66262a925466aab61dcb8db0c53a/ctx/context.go#L113-L118

```go
client := github.NewClient(oauth2.NewClient(
			oauth2.NoContext,
			oauth2.StaticTokenSource(
				&oauth2.Token{AccessToken: GitHubToken()},
			),
		))
```

It's working for me! Perhaps there is an issue with your token's scopes after all. I do not use a `login` query string parameter. Make sure the user your token was generated for has access to repo `g.Owner/g.Repo`. Another thing to try is to try a request with `curl` with your token and see if you still get a 401.

**Comment by mh-cbon** [comment]
(omfg) shame on me i figured out an horrible mistake of mine.... a (space) was hanging around.. thanks a lot for the help!
