### ISSUE TITLE
How do you construct a complicated Search query?

### ISSUE THREAD

**Issue by catsby** [google/go-github#444]
I'm trying to search GitHub issues, similar to this `curl` request:

```
curl -s -i -u clint@email.com:$GH_TOKEN https://api.github.com/search/issues\?q\=repo:org/repo\
+state:open\
+-commenter:one\
+-commenter:other\
```

This code works fine:

```
	opts := &github.SearchOptions{Sort: "updated"}
	result, _, err := client.Search.Issues("repo:org/repo", opts)
```

but the moment I try to add `state` I get url encoding errors

```
	opts := &github.SearchOptions{Sort: "updated"}
	result, _, err := client.Search.Issues("repo:org/repo+state:open", opts)
```

The url gets form encoded and looks like this:

```
search/issues?q=repo%3Aorg%2Frepo%2Bstate%3Aopen&sort=updated
```

Am I using the library wrong? `&state=open` gave the same results 😢

**Comment by willnorris** [comment]
try space instead of `+`: `"repo:org/repo state:open"`

**Comment by catsby** [comment]
Thank you @willnorris , that works!
