### ISSUE TITLE
Shadowed error value in (RepositoriesService) IsCollaborator method

### ISSUE THREAD

**Issue by groob** [google/go-github#452]
Spotted this, probably worth fixing.

https://github.com/google/go-github/blob/1eaf38380d74925650bee1593df74e1a1c0dc3a7/github/repos_collaborators.go#L40

**Comment by gmlewis** [comment]
Check out `parseBoolResponse`: https://github.com/google/go-github/blob/1eaf38380d74925650bee1593df74e1a1c0dc3a7/github/github.go#L303
and I think this is OK.

**Comment by groob** [comment]
Ah, that makes more sense. Thanks
