### ISSUE TITLE
PullRequest add review_comment_url and review_comments_url fields

### ISSUE THREAD

**Issue by bradleyfalzon** [google/go-github#453]
The PullRequest object (https://developer.github.com/v3/pulls/#get-a-single-pull-request) defines two review comment fields `review_comments_url` and `review_comment_url`.

These currently do not exist in the `PullRequest` struct (https://godoc.org/github.com/google/go-github/github#PullRequest), but related URLs do.

If it's OK with the maintainers, I'd like to work on and send a PR for these two changes.

**Comment by shurcooL** [comment]
I've verified and this issue is valid.

> If it's OK with the maintainers, I'd like to work on and send a PR for these two changes.

Sounds good, feel free to go for it! Thanks!
