### ISSUE TITLE
Update Traffic API methods to use new timestamps

### ISSUE THREAD

**Issue by willnorris** [google/go-github#458]
There was a lot of discussion on #418 due to the fact that the Traffic API was using a different timestamp format than the rest of the API.  That's now been fixed: https://developer.github.com/changes/2016-10-26-traffic-api-update/

@succo: you wanna take a stab at updating this, since you're most familiar with that code?

**Comment by Succo** [comment]
@willnorris sure I should have time for that tomorrow or this WE.

**Comment by willnorris** [comment]
(@succo, I've invited you to be a collaborator on this repo so that I can assign this issue to you.  Let me know once you've accepted the invite)

**Comment by Succo** [comment]
@willnorris should be good.
