### ISSUE TITLE
Add Remove Assignee Functionality (Unassign) 

### ISSUE THREAD

**Issue by grodrigues3** [google/go-github#459]
It looks like github's api exposes functionality for unassigning PRs, but go-github does not yet implement this. 

https://developer.github.com/v3/issues/assignees/#remove-assignees-from-an-issue

**Comment by apelisse** [comment]
Done: https://github.com/google/go-github/blob/master/github/issues_assignees.go#L69
You're welcome. I accept checks. ;-)
