### ISSUE TITLE
Update Projects API to support organizations projects

### ISSUE THREAD

**Issue by willnorris** [google/go-github#461]
Announcement: https://developer.github.com/changes/2016-10-27-changes-to-projects-api/

/cc @balintant since you did the initial implementation of this.

**Edit by @shurcooL:** The initial implementation of this that we merged was #438 that @gmlewis made, not #433.

**Comment by lucasalcantara** [comment]
can you assign this issue to me?

**Comment by gmlewis** [comment]
Invitation sent.

**Comment by shurcooL** [comment]
> ### Changes to existing Projects API endpoints
>
>Previously, the "Get a project" endpoint was scoped to the project's owner. It looked like this:
>
>     GET /repos/:owner/:repo/projects/:number
>
> We're changing the "Get a project" endpoint to look like this:
>
>     GET /projects/:id

This change is going to require creating a new service, `ProjectsService`.
