### ISSUE TITLE
Question: How to get the user id using client

### ISSUE THREAD

**Issue by alok87** [google/go-github#473]
How to get the current user id if i have this object https://godoc.org/github.com/google/go-github/github#Client

Could not find it in docs.
Please suggest

Let me know the right place to ask this question if this is not the right place.

**Comment by heidmotron** [comment]
https://godoc.org/github.com/google/go-github/github#UsersService.Get

If you pass an empty string into Get it will return the current authenticated user object.

It might be worthwhile to have a UsersService.GetCurrentUser() method.

**Comment by alok87** [comment]
@heidmotron Awesome, it worked  thanks !
