### ISSUE TITLE
How to get a Deployment or DeploymentStatus by ID

### ISSUE THREAD

**Issue by ahume** [google/go-github#482]
https://developer.github.com/v3/repos/deployments/

The API supports looking up `Deployment` and `DeploymentStatus` by ID with a simple GET request... eg.

`https://api.github.com/repos/octocat/example/deployments/1`

This doesn't seem to be supported in the repos_deployments code.

**Comment by shurcooL** [comment]
Is this actually documented at https://developer.github.com/v3/repos/deployments/? I can't seem to find it there.

**Comment by ahume** [comment]
It's not explicitly documented as an endpoint for some reason. But it's returned as the `Location` header and the `url` field of a successful create action.

**Comment by ahume** [comment]
I reached out to Github support about this, and there's definitely some clarification needed in the documentation.

* The "get-single-status" endpoint, does *not* actually work (despite being returned as the URL field in a status). This seems like an obvious bug one way or the other, but either way, this definitely shouldn't be supported in the go client (since it won't work).

- The "get-single-deployment" endpoint *does* work, and they are raising an internal issue as to why it's not properly documented.

I think the current behaviour makes sense. Our workflows heavily rely on being able to look up a single Deployment, but I can't imagine a use case for looking up a single DeploymentStatus, as they are so heavily coupled to the parent Deployment. You don't typically need to deal with them as first-class things, only as metadata around a Deployment.

**Comment by shurcooL** [comment]
> I reached out to Github support about this

Thanks for doing that, it sounds like the right thing to do in this situation.

**Comment by gmlewis** [comment]
Reopening to track undocumented API merged in #483.
