### ISSUE TITLE
Add support for new Pull Request Reviews preview API.

### ISSUE THREAD

**Issue by shurcooL** [google/go-github#495]
Announcement: https://developer.github.com/changes/2016-12-14-reviews-api/.

Docs: https://developer.github.com/v3/pulls/reviews/.

This was announced today.

**Comment by sahildua2305** [comment]
I'd like to work on this @shurcooL. Can you please help me in getting started?
Will it be similar to `pulls_comments.go`?

**Comment by haya14busa** [comment]
Hi!

@sahildua2305 I started to work on this now to use this API for [my personal project](https://github.com/haya14busa/reviewdog/), and it's in progress. 
But, you commented first, so I think you can do this if you want, otherwise please let me handle it.

As for the progress, I just only implemented `PullRequestReviewService.List`, so progress is small.

**Comment by sahildua2305** [comment]
@haya14busa thanks for offering. I'd really like to work on this. However, I'll need help in getting started. I'm new to Go.

**Comment by haya14busa** [comment]
I think you can add rest of methods like this https://github.com/google/go-github/compare/master...haya14busa:pull-reviews

I guess we can also use `PullRequestsService` instead of adding new `PullRequestReviewService`.

**Comment by shurcooL** [comment]
Thanks for offering to work on this, @sahildua2305 and @haya14busa.

How about @sahildua2305 takes this and @haya14busa, you can help out with reviewing the PR and iterating on it as needed?

> Can you please help me in getting started?
> Will it be similar to `pulls_comments.go`?

I've looked at the new API. It's 6 new endpoints, and they're quite similar/related to pull requests.

I agree with @haya14busa, it looks like simply adding them to the existing `PullRequestsService` would be a good solution. It doesn't seem that a new service `PullRequestReviewService` is needed here. PR reviews are pretty similar to usual comments on PRs. It's also quite analogous to comments that issues have, and those are just a part of `IssuesService`.

So, let's go with adding 6 methods to `PullRequestsService`, similar to what's in `pulls_comments.go`.

@sahildua2305, you can look at @haya14busa's current implementation, it's quite good so far, with the exception that you want to go with the existing `PullRequestsService`.

Feel free to make a PR as soon as you have something started, if you'd like early feedback or to make sure you're on the right path. Thanks again!

**Comment by haya14busa** [comment]
Thank you for the response, @shurcooL!

Ok, I'm happy to help @sahildua2305! Please notify me when you open a pull request or want some helps.

**Comment by sahildua2305** [comment]
Thanks for your response, @shurcooL!

Also thank you for offering help, @haya14busa. I'll inform you as I open the PR soon.

**Comment by sahildua2305** [comment]
@shurcooL @haya14busa I am just getting started with my work on this. How do I test my changes?

**Comment by shurcooL** [comment]
First, make sure all existing tests pass by running `go test github.com/google/go-github/github`.

You can write a simple program that exercises your new code and hits the real GitHub API, and see if it works as expected.

Then write unit tests that are similar to the ones that exist. It helps to get a real GitHub API response and make your mock handler return something equivalent.

Also see the unit test that @haya14busa wrote in https://github.com/google/go-github/commit/ebd6006516e1d6a2e027886e22cd95d6dec757cc.

**Comment by sahildua2305** [comment]
Thanks @shurcooL! I got everything (related to environment and existing tests) working. I will test my changes, write tests and create a PR once at least one endpoint is covered. 😄

**Comment by haya14busa** [comment]
FYI: Preview Review Requests API is also released

Announcement: https://developer.github.com/changes/2016-12-16-review-requests-api/

Doc: https://developer.github.com/v3/pulls/review_requests/
