### ISSUE TITLE
Optional fields of pullRequestMergeRequest should not be populated

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#500]
In #456, I had given incorrect advice to the author of the PR and then merged the PR without allowing @shurcooL to review the requested changes, all of which was my fault.

As a result, the optional fields in `pullRequestMergeRequest` are being sent even if empty.

The GitHub API docs will need to be read to determine which fields are optional, and then only pass them in the JSON request if non-zero.

**Comment by shurcooL** [comment]
Looking at the [`pullRequestMergeRequest` type](https://gotools.org/github.com/google/go-github/github?rev=51a22b31becd9227cfca7ec8a5c195cb468af2d3#pullRequestMergeRequest):

```Go
type pullRequestMergeRequest struct {
	CommitMessage *string `json:"commit_message"`
	CommitTitle   *string `json:"commit_title,omitempty"`
	MergeMethod   *string `json:"merge_method,omitempty"`
	SHA           *string `json:"sha,omitempty"`
}
```

It appears that the intent is to have `CommitMessage` be mandatory, but `CommitTitle`, `MergeMethod` and `SHA` are optional. Does that look right?

Can CommitTitle ever be an empty string?

If not, then we can change `pullRequestMergeRequest` to the following:

```Go

type pullRequestMergeRequest struct {
	CommitMessage string `json:"commit_message"`
	CommitTitle   string `json:"commit_title,omitempty"`
	MergeMethod   string `json:"merge_method,omitempty"`
	SHA           string `json:"sha,omitempty"`
}
```

And that can lead to the resolution of the problem.

**Comment by gmlewis** [comment]
Yes, I believe that would is correct.
Note to other readers... the only change is making all fields `string`s instead of pointers to `string`s.
SGTM.

**Comment by shurcooL** [comment]
I'll make a PR for this. I'll write tests to make sure the new version works as expected, and so that it doesn't regress. :)
