### ISSUE TITLE
Add support for Commit Search preview API.

### ISSUE THREAD

**Issue by shurcooL** [google/go-github#508]
Announcement: https://developer.github.com/changes/2017-01-05-commit-search-api/.

Docs: https://developer.github.com/v3/search/#search-commits.

This was announced today.

**Comment by sahildua2305** [comment]
Since it's going to be similar to #497, I can work on it 😃

**Comment by sahildua2305** [comment]
@shurcooL can you please assign this to me? I have been busy last week. I will start working on this today.

**Comment by sahildua2305** [comment]
In earlier `commit` objects, GitHub used to send key `sha` which had the hash of the commit. However, in this new commits search endpoint, the returned `commit` object has `hash` key for the same.

I will get in touch with GitHub support to confirm the difference and to suggest to possibly have the same parameters to have consistency.

**Comment by shurcooL** [comment]
> @shurcooL can you please assign this to me?

In order to be able to assign you, you'll need to be invited by @gmlewis first.

**Comment by sahildua2305** [comment]
@shurcooL should we keep all the information available in the commit object or can we skip some fields?

**Comment by gmlewis** [comment]
@sahildua2305 - I'll send an invite.

**Comment by sahildua2305** [comment]
Thanks @gmlewis

**Comment by shurcooL** [comment]
> @shurcooL should we keep all the information available in the commit object or can we skip some fields?

It's okay to skip the `_url` fields if you think they're unlikely to be useful (and someone else can add them later if they need them). It's also okay to include them. It's up to you. See https://github.com/google/go-github/issues/419#issuecomment-241466941 for background on our stance regarding those fields.

That said, is there an existing struct we can use to parse the items in a commit search response, or will it have to be a new struct?

**Comment by sahildua2305** [comment]
> That said, is there an existing struct we can use to parse the items in a commit search response, or will it have to be a new struct?
As far as I have checked, the closest matching struct was `commit` from `git_commits.go`. However, the format of output for this search endpoint is completely different from that for the older commit output format. Hence, I will go with a new struct. Please let me know if you find something matching.

**Comment by shurcooL** [comment]
> Hence, I will go with a new struct.

I've looked a bit, and came to the same conclusion, @sahildua2305. SGTM. 👍
