### ISSUE TITLE
Support update to organization and team invitations APIs

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#514]
Announcement:
https://developer.github.com/changes/2017-01-12-organization-team-invitation-update/

**Comment by varadarajana** [comment]
Can this be assigned to me?

**Comment by gmlewis** [comment]
I'll send you an invite.

**Comment by varadarajana** [comment]
Since I already have a PR open, I am planning to create a  branch for this feature change, and then create the new PR on it. Is this the right approach?

**Comment by shurcooL** [comment]
Yep, that's the way to go. When creating the second PR, pick your new branch as the head branch.

**Comment by varadarajana** [comment]
First i wanted to started writing test cases for the ListPendingTeamInvitations. Here the method mock server returns only "id" which is compared in test case. It was not including values for Login, Email, Role, CreatedAt. Do I need to modify, since i need to now test with "inviter"?

**Comment by shurcooL** [comment]
Yes, feel free to expand `TestOrganizationsService_ListPendingTeamInvitations` test data to be more complete, and include the new `inviter` field there too.

**Comment by varadarajana** [comment]
@shurcooL , @gmlewis i have made the changes and submitted a PR. Can you please review the PR?

**Comment by shurcooL** [comment]
Yep, I've [done so](https://github.com/google/go-github/pull/527#pullrequestreview-18727976) just now.
