### ISSUE TITLE
Add support for Preview Review Requests API

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#516]
Announcement:
https://developer.github.com/changes/2016-12-16-review-requests-api/

**Comment by shurcooL** [comment]
Imagine the struct for "create a review request" endpoint options being named... `PullRequestReviewRequestRequest`. 😆

**Comment by gmlewis** [comment]
Looks like Java in Go!  :smile:

**Comment by varadarajana** [comment]
If this has not been assigned earlier, please assign it to me, I can work on it, as my integration tests are almost complete.

**Comment by varadarajana** [comment]
@gmlewis if this is not assigned already, please assign it to me. I am almost done with #530

**Comment by shurcooL** [comment]
It looks like #557 is related.

@varadarajana, @sevki, you should coordinate to avoid duplicate work.

**Comment by varadarajana** [comment]
@shurcooL this PR can be closed, as it is duplicate of #557

**Comment by shurcooL** [comment]
It's not a duplicate issue because #557 is a PR, not an issue. The issue tracks the completion of the relevant functionality. It shouldn't be closed until this functionality is implemented.

#557 is a PR that will resolve this issue.
