### ISSUE TITLE
Support preview Organizations Membership API and new filter

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#524]
Announcement: https://developer.github.com/changes/2017-01-16-audit-outside-collaborators-for-2fa/

**Comment by glapul** [comment]
Hi, I'd like to work on it.

**Comment by gmlewis** [comment]
Thank you, @glapul - I'll send you an invite so that I can assign it to you.

**Comment by gmlewis** [comment]
You are correct.  The new Organizations Membership API needs to be supported too.

Announcement: https://developer.github.com/changes/2016-11-28-preview-org-membership/
I'll change the label for this issue, and it can address both.

**Comment by glapul** [comment]
#538 I've implemented the support for listing outside collaborators. Feedback?

**Comment by e-beach** [comment]
Should this be closed, as #538 was closed and merged?

**Comment by gmlewis** [comment]
From a quick glance at this announcement: https://developer.github.com/changes/2016-11-28-preview-org-membership/ it appears that #538 did not fully support all the new API endpoints. For example, I don't think [Remove an outside collaborator](https://developer.github.com/v3/orgs/outside_collaborators/#remove-outside-collaborator) was addressed.  There may be more, and part of the ownership of an issue (in my opinion) is to investigate what all is needed to completely resolve the issue.

If @glapul would like to complete this issue, then @glapul is welcome to... otherwise if someone else would like to read the announcements and add the missing endpoints, that is fine with me too.
