### ISSUE TITLE
Prefer to explicitly return nil when there is no error for code readability

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#536]
A common pattern in this repo is:

```go
if err != nil {
  return ..., err
}
return ..., err
```

and we would like to change the last return to explicitly `return ..., nil` for Go readability.

**Comment by sahildua2305** [comment]
Oh! It's going to be a lot of work. I think we should split it up.

Also, we should have a static check for this, no?

**Comment by shurcooL** [comment]
> Oh! It's going to be a lot of work. I think we should split it up.

There can be multiple smaller PRs that help resolve this issue, if that's easier. It doesn't have to be just 1 change. A lot of the recent PRs, including #535, have helped this issue already.

> Also, we should have a static check for this, no?

I think @dominikh's `staticcheck` may be able to detect that `err` variable being returned has a constant `nil` value in the future.

**Comment by gmlewis** [comment]
I believe that @willnorris wants to keep the dependencies of `go-github` extremely small, and most likely will not agree to pull in a new dependency for `staticcheck`. He can certainly correct me if I've misinterpreted our conversations, though.

**Comment by shurcooL** [comment]
There is no reason to pull in `staticcheck` as a dependency of `go-github`. It's simply a tool similar to `go vet` that might get a check in the future that would detect this type of issue, and make it easier to find and resolve it.

**Comment by gmlewis** [comment]
Ah, thank you, @shurcooL!  This is excellent news. I need to check that out.

**Comment by shurcooL** [comment]
We're very close, but this is not fully resolved yet, see https://github.com/google/go-github/pull/546#issuecomment-279543260.
