### ISSUE TITLE
Provide capability to specify the `Accept` request header when retrieving issues. 

### ISSUE THREAD

**Issue by xcoulon** [google/go-github#545]
There is currently no way to specify a custom mime-type such as [html+json](https://developer.github.com/v3/media/#html) when retrieving GitHub issues. However, this is  needed when the client wants to retrieve the issue body rendered in HTML rather than in its input/raw format.

This issue has been discussed in https://github.com/google/go-github/issues/6#issuecomment-278333227

**Comment by sahildua2305** [comment]
@gmlewis what's the status on this?

**Comment by shurcooL** [comment]
We could probably address this in a similar way to #767 and #481.

**Comment by gmlewis** [comment]
See also #727.

**Comment by gmlewis** [comment]
Closing issue as obsolete.  Feel free to reopen if I'm mistaken.
