### ISSUE TITLE
Flag for dumping HTTPS traffic?

### ISSUE THREAD

**Issue by kevinburke** [google/go-github#552]
I find it pretty useful to be able to inspect the raw HTTP request/response being issued by a client library. This makes it easy to add integration tests to my own code, by copying the JSON responses from Github into my tests, then setting up a httptest.Server to replay those responses.

Here's how I implement this in my own API client - you can set DEBUG_HTTP_TRAFFIC=true in the environment to dump all requests/responses. https://github.com/kevinburke/rest/blob/master/client.go#L110-L134

And here's where I am using a response captured by that logic, in a test: https://github.com/saintpete/logrole/blob/master/server/messages_test.go#L88

Thoughts on adding something similar to this library?

**Comment by shurcooL** [comment]
Can this be done via a middleware [`http.RoundTripper`](https://godoc.org/net/http#Client.Transport) implementation? If so, it can be orthogonal from this specific library.

**Comment by willnorris** [comment]
We have exactly such a roundtripper internally at Google.

**Comment by kevinburke** [comment]
@willnorris bah haha, I just added https://github.com/kevinburke/rest/commit/da85e327c2c8c3668c19c41e17e6ea5b11e8f843 as a public implementation!

**Comment by shurcooL** [comment]
Is there anything left here, or can we close this?

**Comment by kevinburke** [comment]
nope you can close it
