### ISSUE TITLE
Support new Community Health preview API

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#553]
Announcement:
https://developer.github.com/changes/2017-02-09-community-health/
Docs:
https://developer.github.com/v3/repos/community/

**Comment by sahildua2305** [comment]
@gmlewis I will work on this. Please assign it to me. 😄

**Comment by gmlewis** [comment]
Thanks, @sahildua2305! Done.

**Comment by gmlewis** [comment]
Breaking updates to the preview API:
https://developer.github.com/changes/2017-03-07-community-health-api-enhancements/

**Comment by sahildua2305** [comment]
@gmlewis I am looking into it now and thinking about what `type` can I have for the response. In `files`, there are four keys which are the file names and if that file is present, there will be corresponding fields.

**Comment by shurcooL** [comment]
It can be a struct, something like this:

```Go
type CommunityHealthMetrics struct {
	HealthPercentage int `json:"health_percentage"`
	Files            struct {
		CodeOfConduct struct {
			Name    string `json:"name"`
			Key     string `json:"key"`
			URL     string `json:"url"`
			HTMLURL string `json:"html_url"`
		} `json:"code_of_conduct"`
		Contributing struct {
			URL     string `json:"url"`
			HTMLURL string `json:"html_url"`
		} `json:"contributing"`
		License struct {
			Name    string `json:"name"`
			Key     string `json:"key"`
			URL     string `json:"url"`
			HTMLURL string `json:"html_url"`
		} `json:"license"`
		Readme struct {
			URL     string `json:"url"`
			HTMLURL string `json:"html_url"`
		} `json:"readme"`
	} `json:"files"`
	UpdatedAt time.Time `json:"updated_at"`
}
```

And it looks like you'll need a slice of them, because the response is a JSON array, not a single object.

_(Thanks to @mholt for https://mholt.github.io/json-to-go/.)_

**Comment by sahildua2305** [comment]
Thanks @shurcooL! I didn't know about this json-to-go tool. It's very helpful.
