### ISSUE TITLE
Support new user blocking APIs and webhook

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#569]
Announcement:
https://developer.github.com/changes/2017-02-28-user-blocking-apis-and-webhook/

GitHub API docs:
- [x] https://developer.github.com/v3/users/blocking/
- [x] https://developer.github.com/v3/orgs/blocking/
- [ ] https://developer.github.com/v3/activity/events/types/#orgblockevent

**Comment by varadarajana** [comment]
@gmlewis please assign this to me, as this is similar to #530. I need one help with your review of Issue #530. Can you provide your comments on the usage of Changes struct?

**Comment by gmlewis** [comment]
Done.  Thanks, @varadarajana! I'll take a look at 530.

**Comment by varadarajana** [comment]
Today I came back to work after sometime and found difficulty in merging, here is what I get after I do  
'''
$ git fetch upstream
remote: Counting objects: 96, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 96 (delta 65), reused 60 (delta 60), pack-reused 21
Unpacking objects: 100% (96/96), done.
From https://github.com/google/go-github
 * [new branch]      master     -> upstream/master
'''
'''
$ git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
'''

'''
$ git merge upstream/master
Auto-merging github/orgs_teams_test.go
Auto-merging github/orgs_teams.go
Auto-merging github/orgs_members_test.go
CONFLICT (content): Merge conflict in github/orgs_members_test.go
Auto-merging github/orgs_members.go
Automatic merge failed; fix conflicts and then commit the result.
'''

I tried stash, checkout --theirs, reset and manually tried to change the files, somehow I get this error. Is there something I am doing wrong?

**Comment by shurcooL** [comment]
What are you trying to achieve?

If it were me, I would start with latest `upstream/master` (assuming your upstream remote is google/go-github), and work from there. If you had some previous work on a branch, I would rebase that on top of latest master.

**Comment by varadarajana** [comment]
@shurcooL 
I want to sync up my fork with the upstream and catch up to the latest version on upstream. So I fetch upstream and then checkout my fork, and merge.

**Comment by varadarajana** [comment]
@shurcooL 
This time I did a

'''
git add github/orgs_members_test.go
git commit
git merge upstream/master
'''
This worked. I hope I did the right way.

**Comment by shurcooL** [comment]
You should make sure there aren't unintended merge conflicts as part of that file.

As a side note, if you want to create fenced code blocks, you should use 3 backtick (\`\`\`) characters, not single quotes (\'\'\'). See https://help.github.com/articles/creating-and-highlighting-code-blocks/.

**Comment by varadarajana** [comment]
@shurcooL Thank you for pointing out. I need a help. I think my fork is having issues. I want to make a fresh fork from the upstream google master. How do I do it?
I tried 
git fetch upstream
Somehow my files are behind..

**Comment by shurcooL** [comment]
> I think my fork is having issues. I want to make a fresh fork from the upstream google master. How do I do it?

It's pretty hard to communicate how to fix that a git repo over text, compared to showing in person. Do you maybe have a resident git expert that could help you out get your fork in good shape?

**Comment by varadarajana** [comment]
I will continue to work with the remaining this week. I was not well for around 2 weeks.

**Comment by gmlewis** [comment]
Sorry to hear that, @varadarajana - I hope you feel better fast!

**Comment by varadarajana** [comment]
Thank you @gmlewis @shurcooL i am recovering now. 
I have a question. While i was reading the Blocking Users (Organizations) API, I find the following lines:
```
The token used to authenticate the call must have the admin:org scope in order to make any blocking calls for an organization. Otherwise, the response returns HTTP 404.
```
In authorizations.go we have all the scopes defines. I do not see any references to scope anywhere? Is there a central place where this scope validation is done?

**Comment by gmlewis** [comment]
Scope refers to how you create your OAuth2 client. Check out [`tests/integration/authorizations_test.go`](https://github.com/google/go-github/blob/master/tests/integration/authorizations_test.go) for an example.

**Comment by varadarajana** [comment]
I will work on the web hook this week.
