### ISSUE TITLE
With removal of deprecated client.Rate in #555, rate limit info needs more visibility

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#571]
It used to be that clients might make API calls like:

```go
	repos, resp, err := client.Repositories.ListByOrg(org, opt)
	if err != nil {
		rate := client.Rate()
		if rate.Remaining == 0 {
			//...
		}
		//...
	}
```

but after #555, it turns out that `checkRateLimitBeforeDo` will return an error without rate information.
I have a PR on the way that addresses this issue.

**Comment by gmlewis** [comment]
This change will make it easier and more consistent to check for a rate limit error, using:

```go
if resp != nil && resp.Rate.Remaining == 0 {
	//...
}
```

**Comment by shurcooL** [comment]
Just checking, but did you see this sentence in the docs of `Do`?

> If rate limit is exceeded and reset time is in the future, Do returns *RateLimitError immediately without making a network API call.

Also, the section on rate limiting in the package comment, and the example there?

https://godoc.org/github.com/google/go-github/github#hdr-Rate_Limiting

So, the way I'd check for rate limit errors is as shown in the provided example in the package documentation at https://godoc.org/github.com/google/go-github/github#hdr-Rate_Limiting:

```Go
repos, resp, err := client.Repositories.ListByOrg(org, opt)
if err != nil {
	if _, ok := err.(*github.RateLimitError); ok {
		// ...
	}
	// ...
}
```

I wanted to ask these questions first before I can comment further.

**Comment by shurcooL** [comment]
That section needs to be updated, since it still refers to a removed deprecated method:

> The Rate method on a client returns the rate limit information based on the most recent API call.

**Comment by gmlewis** [comment]
Ah, I see.  Hmmm... How do you feel about supporting both mechanisms?
I rather like the change in case someone is already used to checking the rate limit in the response... but if you feel strongly, I will just close this CL.

**Comment by shurcooL** [comment]
@gmlewis I replied in the PR https://github.com/google/go-github/pull/572#pullrequestreview-25107926, because I wanted to reference specific lines of code there.
