### ISSUE TITLE
How do I access issue/closed_by attribute?

### ISSUE THREAD

**Issue by Pezhin** [google/go-github#574]
API descripition here: https://developer.github.com/v3/issues/#get-a-single-issue

I want to use the `closed_by` attribute in `Get a single issue` which looks like this

```
  "closed_by": {
    "login": "octocat",
    "id": 1,
    "avatar_url": "https://github.com/images/error/octocat_happy.gif",
    "gravatar_id": "",
    "url": "https://api.github.com/users/octocat",
    "html_url": "https://github.com/octocat",
    .....
  }
```

How can I access it?

**Comment by shurcooL** [comment]
I am guessing it's a relatively new field. We don't have it in our `Issue` struct, so it's not possible to access it currently. See:

https://github.com/google/go-github/blob/d9c241b9c95cbd5996418f70223328a37cfb9bb3/github/issues.go#L20-L51

We should add it.

It would be quite similar to a recent issue #570 and the PR to resolve it #573. One addition is that we should run `go generate` as described in https://github.com/google/go-github/blob/master/CONTRIBUTING.md#submitting-a-patch.

If you're interested, you can take this on. Or leave it for someone else to resolve.

**Comment by Pezhin** [comment]
I would love to work on this. Do you want a new `Closed_by` type to handle it?

Addtionally, I added `	{"repos/google/go-github/issues/1", &github.Issue{}}` to `fields.go` testing  and run the field test. (I don't know if this is the correct way to do so, I am just doing it accordingly)

The output is 
```
*github.Issue missing field for key: locked (example value: false)  <---- this should disappper
*github.Issue missing field for key: events_url (example value: https://api.github.com/repos/google/go-github/issues/1/events)
*github.Issue missing field for key: labels_url (example value: https://api.github.com/repos/google/go-github/issues/1/labels{/name})
*github.Issue missing field for key: milestone (example value: <nil>)
*github.Issue missing field for key: closed_by (example value: map[login:willnorris organizations_url:https://api.github.com/users/willnorris/orgs events_url:https://api.github.com/users/willnorris/events{/privacy} id:1112 avatar_url:https://avatars1.githubusercontent.com/u/1112?v=3 gists_url:https://api.github.com/users/willnorris/gists{/gist_id} starred_url:https://api.github.com/users/willnorris/starred{/owner}{/repo} repos_url:https://api.github.com/users/willnorris/repos type:User subscriptions_url:https://api.github.com/users/willnorris/subscriptions received_events_url:https://api.github.com/users/willnorris/received_events gravatar_id: url:https://api.github.com/users/willnorris html_url:https://github.com/willnorris followers_url:https://api.github.com/users/willnorris/followers following_url:https://api.github.com/users/willnorris/following{/other_user} site_admin:false])
*github.Issue missing field for key: repository_url (example value: https://api.github.com/repos/google/go-github)
*github.Issue missing field for key: comments_url (example value: https://api.github.com/repos/google/go-github/issues/1/comments)
```
I wonder if #573 really works, can you confirm it?
I may help with handle other fields as well.

**Comment by shurcooL** [comment]
> I would love to work on this.

Great! Thanks! Be sure to read over https://github.com/google/go-github/blob/master/CONTRIBUTING.md#how-to-contribute so you're familiar with the contribution guidelines.

> Do you want a new Closed_by type to handle it?

It looks like [`User`](https://godoc.org/github.com/google/go-github/github#User) is a good matching type, so there's no need to create a new type.

> I wonder if #573 really works, can you confirm it?

Are you sure you ran with the latest version of go-github? #573 was merged very recently (7 hours ago).

However, Milestone was there since a long time ago, so I'm surprised to see that appear...

This is what I got with latest version of go-github:

```
*github.Issue missing field for key: events_url (example value: https://api.github.com/repos/google/go-github/issues/1/events)
*github.Issue missing field for key: closed_by (example value: map[gravatar_id: received_events_url:https://api.github.com/users/willnorris/received_events url:https://api.github.com/users/willnorris html_url:https://github.com/willnorris followers_url:https://api.github.com/users/willnorris/followers repos_url:https://api.github.com/users/willnorris/repos events_url:https://api.github.com/users/willnorris/events{/privacy} site_admin:false login:willnorris avatar_url:https://avatars1.githubusercontent.com/u/1112?v=3 organizations_url:https://api.github.com/users/willnorris/orgs gists_url:https://api.github.com/users/willnorris/gists{/gist_id} starred_url:https://api.github.com/users/willnorris/starred{/owner}{/repo} subscriptions_url:https://api.github.com/users/willnorris/subscriptions type:User id:1112 following_url:https://api.github.com/users/willnorris/following{/other_user}])
*github.Issue missing field for key: comments_url (example value: https://api.github.com/repos/google/go-github/issues/1/comments)
*github.Issue missing field for key: labels_url (example value: https://api.github.com/repos/google/go-github/issues/1/labels{/name})
*github.Issue missing field for key: milestone (example value: <nil>)
*github.Issue missing field for key: repository_url (example value: https://api.github.com/repos/google/go-github)
```

`locked` is not there, but `milestone` is... Strange, I'll look into that.

> I may help with handle other fields as well.

Thanks. It's not very important to add all missing _url fields, we usually add those when people actually need them, rather than in advance.

**Comment by shurcooL** [comment]
> but `milestone` is... Strange, I'll look into that.

I've looked into it. The reason `milestone` doesn't show up is because of a bug in the `fields` tool, see #576.
