### ISSUE TITLE
Question: Extract Stringify() helper?

### ISSUE THREAD

**Issue by hackebrot** [google/go-github#584]
Hey there! Thank you for making **go-github**! 😄 

I find the [Stringify()][stringify] function super useful and wonder whether it could be a separate project for other projects to import and use. I couldn't find an open or closed issue on this, apologies if this is the wrong place to ask.

I would be happy to implement the library, but want to give proper attribution.

What do you think?

[stringify]: https://github.com/google/go-github/blob/master/github/strings.go#L21

**Comment by gmlewis** [comment]
+cc @willnorris as he is the original author of `go-github` and `Stringify` in https://github.com/google/go-github/commit/8f77def830f742728ad2ffb1f0964a192b008ad6

**Comment by willnorris** [comment]
Fine with me.  The BSD license go-github is under certainly allows for that :)

**Comment by hackebrot** [comment]
Awesome! Thanks very much @willnorris @gmlewis 😃

**Comment by hackebrot** [comment]
https://github.com/hackebrot/go-repr 😄

**Comment by shurcooL** [comment]
> go-repr allows you to debug print your objects with a single line of code.

By the way, in case you're not already aware of them, there are some libraries for "deep pretty printing" Go structs, such as https://github.com/davecgh/go-spew and https://github.com/shurcooL/go-goon#readme. If you already knew that, carry on.

**Comment by hackebrot** [comment]
Thank you @shurcooL! 🙇 

I had come across [go-spew](https://github.com/davecgh/go-spew). I'll have a look at your project too!
