### ISSUE TITLE
NewPullRequest method does not support setting "maintainer_can_modify"

### ISSUE THREAD

**Issue by JamieH** [google/go-github#589]
As seen here: https://developer.github.com/v3/pulls/#create-a-pull-request this API supports a value called `maintainer_can_modify` - this isn't exposed via the `NewPullRequest` or `pullRequestUpdate` struct.

I'm gonna make a PR for this now.

**Comment by shurcooL** [comment]
This looks like a new field. We should definitely add it, thanks for reporting!
