### ISSUE TITLE
Installation struct is missing the HTMLURL field

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#591]
This field is useful in webhooks for linking to the event URL.

In this Webhook Payload example:
https://developer.github.com/early-access/integrations/webhooks/#integrationinstallationrepositoriesevent
you can see that `installation` has an `html_url` field.

This should be added to our `type Installation struct` in `integration_installation.go`.

**Comment by liubinyi** [comment]
Hi @gmlewis, go-github looks awesome! I would like to give it a try.

**Comment by gmlewis** [comment]
Thank you, @liubinyi !  We appreciate your help!

**Comment by shurcooL** [comment]
@gmlewis I've looked at https://developer.github.com/early-access/integrations/webhooks/#integrationinstallationevent and https://developer.github.com/early-access/integrations/webhooks/#integrationinstallationrepositoriesevent.

I don't see a `html_url` field at the top level in either of those two events, in those Webhook payload examples. It's there inside the inner objects like `installation` and `sender`, as expected, but not at the top level, which is what I understand this issue to be about, and I see #594 tries to resolve.

I've also looked at https://github.com/google/go-github/blob/839082db564f53df5b8b386f217c7c217b5a624f/github/event_types.go, and not a single event struct currently has an `html_url` JSON field there.

Do you have some evidence that real Webhook payloads actually include the `html_url`? If so, is it not documented on GitHub API, or am I missing it?

**Comment by gmlewis** [comment]
Wow.  I totally messed up on this one.  It is the `Installation` type that is missing the `HTMLURL` field.

Thank you very much, @shurcooL for the sanity check!  Obviously I was not thinking when I filed this.  Let me change the description and point to the docs correctly.

**Comment by gmlewis** [comment]
I've updated the issue description above. Sorry for the confusion.

**Comment by liubinyi** [comment]
@gmlewis no worries. I can update the pr and fix the commit message tonight!
@shurcooL thanks a lot for the sanity check!
