### ISSUE TITLE
handling custom media types

### ISSUE THREAD

**Issue by willnorris** [google/go-github#6]
A handful of API methods (like [issues](http://developer.github.com/v3/issues/)) support the use of [custom mime](http://developer.github.com/v3/media/) types to return additional fields in the response, using different formats.

As currently designed, go-github doesn't have a simple way to expose this, since most HTTP-specific details are hidden from the caller.  We could probably just add it to the Options parameter for the given method, but that feels a little weird.  Additionally, I don't yet have a real use-case for needing to use these custom mime-types.  Therefore, I'm currently leaning toward punting on this until someone actually needs it.

So if you need it, please comment here, and we can look at how to work that into the library.

**Comment by cburmeister** [comment]
@willnorris is there a way to specify a media type for `GetContents`?

```
client := github.NewClient(tc)
repo, _, _, err := client.Repositories.GetContents("username", "repository", "path", nil)
```

As is the `contents` are base64 encoded.

**Comment by willnorris** [comment]
We don't currently expose that for `GetContents`, but it wouldn't be too hard to add it to the existing [RepositoryContentGetOptions](https://godoc.org/github.com/google/go-github/github#RepositoryContentGetOptions)... just add a `MediaType` field like in the example above, then switch on that inside the method to set the Accept header.

Do you wanna take a pass at that?

**Comment by parkr** [comment]
What about a global toggle for each feature?

```go
github.Enable(github.BetaLicenses)
```

**Comment by willnorris** [comment]
@parkr this is a bit different than the media types that are used to enable pre-released APIs.  In those cases, we intentionally try to just enable those APIs transparently so that users of the library don't even realize that it's sending a custom media type.  So far this has worked well, and we haven't had any conflicts between multiple pre-release APIs running on the same endpoints.

What @cburmeister is asking for though is not a pre-release API, it's just an endpoint that supports responses in JSON, HTML, or raw (and just happens to use media type to indicate which one is preferred).  In this case we definitely do want to expose this to users of the library, since the desired response type is generally a conscious decision on the developer's part.

Of course now that I say all this, I realize that we might not simply be able to add MediaType to the Options struct and use the existing method, since the go method expects to return a `*RepositoryContent` and `[]*RepositoryContent`, which we won't have.  Maybe if a custom media type is specified, then we return nil for both of those, and the caller is expected to parse the body of the `*Response` manually?  I don't think there is really any other way to do it, we'll just need to make that clear on the docs for the MediaType field.

**Comment by parkr** [comment]
Ah! I misunderstood. Thanks for the explanation.

**Comment by willnorris** [comment]
actually... @cburmeister, have you seen [Repositories.DownloadContents](https://godoc.org/github.com/google/go-github/github#RepositoriesService.DownloadContents)?  It was just added a [couple of weeks ago](https://github.com/google/go-github/pull/183).  If you're mainly interested in the raw contents, It might work better since it handles files over 1 Mb in size (GetContents does not), and has a more straightforward API for just getting the contents of a file.  The only downside is that it incurs one additional API roundtrip per call, so may not be suitable for all cases.

**Comment by xcoulon** [comment]
@willnorris I'm actually looking for a way to pass the `Accept` header with the `application/vnd.github.VERSION.html+json` value to retrieve the issues with the `body_html` field containing the HTML version of `body`. Is there any way to do that in the current version of go-github, or does this needs an enhancement ?

**Comment by shurcooL** [comment]
@xcoulon That isn't currently possible, we don't have support for [`.html+json` media type](https://developer.github.com/v3/media/#html).

I imagine a solution might look similar to #481, I'd suggest you look at that. At least it's a starting point, we may want to handle the issue differently. @xcoulon, if you need this functionality, please open a new issue and describe in more detail what exactly you're looking for (and mention this issue for reference).

**Comment by xcoulon** [comment]
thanks for that very quick response, @shurcooL! I opened https://github.com/google/go-github/issues/545. Please let me know if you need more info.
