### ISSUE TITLE
Update Protected Branches API preview with Admin Enforcement

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#606]
GitHub Announcement:
https://developer.github.com/changes/2017-03-22-protected-branches-admin-improvements/

This will be a breaking API change and the package version will need to be bumped.

**Comment by amirilovic** [comment]
@gmlewis I can take this.

**Comment by gmlewis** [comment]
Let's close this issue and continue any discussion related to Protected Branches API in #617.
