### ISSUE TITLE
Remove custom media type for Merge Methods API

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#616]
GitHub Announcement:
https://developer.github.com/changes/2017-04-07-end-merge-methods-api-preview/

The `application/vnd.github.polaris-preview` custom media type can now be removed.

Regarding the note about `squash` vs `merge_method`, this has already been addressed in #446.

**Comment by RaviTezu** [comment]
Can we assign this to @ahmedhagii ? 
I see https://github.com/google/go-github/pull/621 is work in progress. 
@shurcooL @gmlewis

**Comment by gmlewis** [comment]
Invite sent.

**Comment by shurcooL** [comment]
That PR is 90% finished but he's not responding. I think we should just carry it ourselves.

**Comment by RaviTezu** [comment]
@shurcooL @gmlewis 
I can take this up, if there are no concerns.

**Comment by shurcooL** [comment]
I think we should just finish the existing PR and merge that. I'll do it now.

**Comment by shurcooL** [comment]
This is resolved now. Thanks for the offer to help @RaviTezu! If you want to work on another issue, we still have many open, so feel free.
