### ISSUE TITLE
Function to get the Delivery ID for a webhook request

### ISSUE THREAD

**Issue by drewfradette** [google/go-github#618]
I would like to add a function to get the Delivery ID header (`X-GitHub-Delivery`) for a webhook request. This would essentially be the same as [`WebHookType`](https://github.com/google/go-github/blob/master/github/messages.go#L162) but a different header.

If there are no problems with this, I would be glad to open a PR.

**Comment by gmlewis** [comment]
I'm not sure I understand the need for a new function. All that is needed is a single line:

```go
deliveryID := r.Header.Get("X-Github-Delivery")
```

Oh, I see... #427 added `WebHookType`.  Hmmm... I guess I missed that before. I'm not sure that was necessary, but I guess it shields clients from the details at the expense of a larger API surface.

I've got mixed feelings but could go either way.

@shurcooL - what do you think about adding a new function (maybe `DeliveryID`) to `messages.go` that is essentially a one-liner?

**Comment by shurcooL** [comment]
SGTM.
