### ISSUE TITLE
Support for user's permissions endpoint

### ISSUE THREAD

**Issue by treeder** [google/go-github#624]
Maybe I just can't find it, but it looks like this endpoint is not supported:

https://developer.github.com/v3/repos/collaborators/#review-a-users-permission-level

Was added fairly recently: https://developer.github.com/changes/2016-11-28-preview-org-membership/

**Comment by shurcooL** [comment]
I'm seeing it here:

https://godoc.org/github.com/google/go-github/github#RepositoriesService.GetPermissionLevel

Is that the one you're looking for?

**Comment by treeder** [comment]
That looks like the one, thanks!
