### ISSUE TITLE
Support new GitHub Apps (formerly Integrations) API.

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#627]
GitHub API Announcement:
https://developer.github.com/changes/2017-04-25-Integrations-Pre-Release/

**Comment by vogxn** [comment]
This would be invaluable! The change for user-to-server requests appears to be adding the headers for the media type `application/vnd.github.machine-man-preview+json`.  I have not looked deep into the library but how difficult would this change be for a new contributor to delve into?

**Comment by gmlewis** [comment]
Skimming the docs, this would be a fair amount of work to get this up and running, but would be a fantastic learning experience. :smiley:

**Comment by gmlewis** [comment]
The Integrations API has now been deprecated in favor of the new GitHub Apps API.
This issue should now focus on the latest GitHub Developer API announcement:
https://developer.github.com/changes/2017-05-22-github-apps-production-ship/

**Comment by shurcooL** [comment]
I think they were just renamed, not deprecated. But yes, it's called GitHub Apps now.

**Comment by bradleyfalzon** [comment]
Just on this, the [Breaking Changes](https://developer.github.com/changes/2017-05-22-github-apps-production-ship/#breaking-changes) will need to be addressed, in particular, the integration specific events introduced in b0b867f2d5ec7c0139fad20ab0fe9267dcd8312b by @cyberdelia will need to be renamed. From my understanding, they are sending both events for the moment (and I can see they're doing this on my own installations, receiving `installation_repositories` and `integration_installation_repositories` as well as `installation` and `integration_installation`).

I'm happy to take this on in time if other's aren't. The first question would be exactly how go-github wants to handle this transition, considering both deprecated and new events appear to be supported at the moment, is the first stage simply to implement the new name and remove the old later? Or just a breaking change to rename the events? 

> Skimming the docs, this would be a fair amount of work to get this up and running, but would be a fantastic learning experience.

In case you hadn't seen it, I've been maintaining and using https://github.com/bradleyfalzon/ghinstallation with go-github for some time quite successfully.

**Comment by shurcooL** [comment]
> In case you hadn't seen it, I've been maintaining and using https://github.com/bradleyfalzon/ghinstallation with go-github for some time quite successfully.

Do you think it's ready to be considered for addition to the README, in its own section? If so, want to send a PR that does that (and update both doc.go and README.md)?

**Comment by bradleyfalzon** [comment]
> Do you think it's ready to be considered for addition to the README, in its own section? If so, want to send a PR that does that (and update both doc.go and README.md)?

I've sent through a minor one-liner, as I did begin to write a larger section which mostly just duplicated the docs already in https://github.com/bradleyfalzon/ghinstallation, so just pared it back to a minor note. Let me know in the PR if you'd like me to expand upon the docs though, happy to.

**Comment by bradleyfalzon** [comment]
> I'm happy to take this on in time if others aren't. The first question would be exactly how go-github wants to handle this transition, considering both deprecated and new events appear to be supported at the moment, is the first stage simply to implement the new name and remove the old later? Or just a breaking change to rename the events?

I'm currently receiving the error `unknown X-Github-Event in message: installation_repositories` from `ParseWebhook`, this is the new name of the event and as mentioned previously it's a duplicate event sent by GitHub to help migration (so the event was still sent).

Potential migration strategy:

1. Edit `eventTypeMapping` to *rename* `integration_installation` and `integration_installation_repositories` keys (not values) to `installation` and `installation_repositories` respectively.
1. Rename the types `IntegrationInstallationEvent` and `IntegrationInstallationRepositoriesEvent`

Considering both of those changes could be written as a simple (for example) `gofmt -w -r 'IntegrationInstallationEvent -> InstallationEvent' ./internal/github/handlers.go`, and it was a preview feature, a breaking change IMHO would be fine.

Another option could include keeping the old events but parsing to the new renamed type (eg `installation_repositories` event parses to `InstallationRepositoriesEvent`), so we don't return an error and parse the old event correctly, then leave it up to the user to decide which event they want to parse and which they want to ignore. We could then continue to keep the old and new types too to have a zero breaking change migration option, and just remove the old types when GitHub stops sending them.

Thoughts or other options?

**Comment by shurcooL** [comment]
> Considering both of those changes could be written as a simple (for example) `gofmt -w -r 'IntegrationInstallationEvent -> InstallationEvent' ./internal/github/handlers.go`, and it was a preview feature, a breaking change IMHO would be fine.

Agreed. In general, for preview APIs, we should prefer breaking API to follow suit with any changes on GitHub side.

> Another option could include keeping the old events but parsing to the new renamed type (eg `installation_repositories` event parses to `InstallationRepositoriesEvent`), so we don't return an error and parse the old event correctly, then leave it up to the user to decide which event they want to parse and which they want to ignore. We could then continue to keep the old and new types too to have a zero breaking change migration option, and just remove the old types when GitHub stops sending them.

Honestly, I'll leave it up to you to decide if it's worth doing that. My suspicion is that it's okay not to, since this is still within preview API territory (if I understand correctly). So it depends on whether the benefits justify the amount of extra work.

**Comment by bradleyfalzon** [comment]
OK, leave it with me then, I'll make the breaking change as it's easy for clients to fix, and helps keep the history clearer (single one-liners, instead of giant copy/paste).

**Comment by kytrinyx** [comment]
> I think they were just renamed, not deprecated. But yes, it's called GitHub Apps now.

The old ones have been removed from the documentation, but they're still being sent along with the new ones according to https://platform.github.community/t/integration-installation-hook-event-name-changed-to-installation/1830

I confirmed that both are being sent with a test app yesterday.
