### ISSUE TITLE
Set profile picture

### ISSUE THREAD

**Issue by qianlnk** [google/go-github#634]
Is there anyway to upload profile picture?

**Comment by shurcooL** [comment]
[Update the authenticated user](https://developer.github.com/v3/users/#update-the-authenticated-user) GitHub API endpoint lists the following possible parameters:

![image](https://cloud.githubusercontent.com/assets/1924134/25789882/67bc7b26-3382-11e7-84a4-11e02ea6afbe.png)

So, it appears the answer is there's no API to do it.

**Comment by shurcooL** [comment]
Closing since this is answered. Let us know if something else comes up.
