### ISSUE TITLE
Allow for custom Git hosts for compatibility with enterprise systems

### ISSUE THREAD

**Issue by tao-lu** [google/go-github#642]
Perhaps allow `baseUrl` (https://github.com/google/go-github/blob/master/github/github.go#L205) to be a user-specified string.

**Comment by gmlewis** [comment]
Try: `client.BaseURL = url`:
https://github.com/google/go-github/blob/master/github/github.go#L107

**Comment by shurcooL** [comment]
`github.Client.BaseURL` documentation is [here](https://godoc.org/github.com/google/go-github/github#Client.BaseURL).

**Comment by tao-lu** [comment]
Ah, thanks.
