### ISSUE TITLE
CommitsComparison should have method GetHTMLURL()

### ISSUE THREAD

**Issue by Davejkane** [google/go-github#643]
It would be useful to have this method for CommitsComparison. Of course, you can build it yourself if you have the parameters necessary to call RepositoriesService.CompareCommits(), but it would be cleaner.

**Comment by shurcooL** [comment]
You're right, `CommitsComparison` struct is missing the `HTMLURL` field, and therefore also missing the `GetHTMLURL` method (which gets generated from the field).

The fix is to add the `HTMLURL` field to that struct and regenerate the package.
