### ISSUE TITLE
feat: add support for affiliation in the Repositories.ListCollaborators opts

### ISSUE THREAD

**Issue by dnwe** [google/go-github#647]
As per the [apidoc](https://developer.github.com/v3/repos/collaborators/#list-collaborators), at some point a request option was added for filtering the returned collaborators by `affiliation`. It would be useful if that was exposed as part of a custom ListCollaboratorOptions struct

**Comment by shurcooL** [comment]
This will have to be a breaking API change.

[`ListCollaborators`](https://godoc.org/github.com/google/go-github/github#RepositoriesService.ListCollaborators) method signature currently accepts a plain `opt *ListOptions`. We'll need to give it a custom `ListCollaboratorOptions` which embeds `ListOptions` and has the new `affiliation` parameter.

**Comment by sahildua2305** [comment]
I'll take this up, @shurcooL. Feel free to assign it to me.

**Comment by e-beach** [comment]
Is this issue being worked on? If not, could it be assigned to me?
