### ISSUE TITLE
Support preview Codes of Conduct API

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#648]
GitHub API announcement:
https://developer.github.com/changes/2017-05-23-coc-api/
GitHub Developers docs:
https://developer.github.com/v3/codes_of_conduct/

**Comment by liubinyi** [comment]
@gmlewis and @shurcooL i would like to give this one a try.

just want to make sure that we want to create a conduct service(conduct.go?) to support following routes
GET /codes_of_conduct
GET /codes_of_conduct/:key
GET /repos/:owner/:repo
GET /repos/:owner/:repo/community/code_of_conduct

**Comment by shurcooL** [comment]
GitHub docs list these under miscallenous.

I think we should just add them as methods of `Client`. Similar to [`ListEmojis`](https://github.com/google/go-github/blob/ebfec748347a9af6793c723f8859afcd906860fb/github/misc.go#L71), which is also just a method on `Client`. It seems overkill to create an entire service just for the 2 codes of conduct endpoints. It's likely there won't be more added.

The last two will be a part of `RepositoriesService`. 3rd endpoint already exists, you just need to set the preview header. 4th is going to be a new method.

**Comment by liubinyi** [comment]
Ah, make sense. Thanks for pointing it out for me! I will start it over the weekend.

**Comment by liubinyi** [comment]
@shurcooL and @gmlewis  pr sent.

Also seems like ```go generate github.com/google/go-github/...``` will not generate files in github-accessors.go
but running ``` go generate -x ./... ``` will do the work.

**Comment by shurcooL** [comment]
> Also seems like ```go generate github.com/google/go-github/...``` will not generate methods in github-accessors.go

Can you elaborate? What was the problem? Was there an error message? It should work.

The -x flag prints commands as they are executed. What's the output of `go generate -x github.com/google/go-github/...`?

**Comment by liubinyi** [comment]
yeah. when I created a new struct 
```
type someStruct struct {
 	Name *string `json:"name,omitempty"`
 }
```
if i run ``` go generate github.com/google/go-github/ ```
without -x flag
it will run without any error messages. but it doesn't  auto generate 

```
func (c *Conduct) GetName() string {
 	if c == nil || c.Name == nil {
 		return ""
 	}
 	return *c.Name
 }
``` in github-accessors.go

when i run ``` go generate -x ./... ```
it prints out ``` go run gen-accessors.go ```
and auto generates 
```
func (c *Conduct) GetName() string {
 	if c == nil || c.Name == nil {
 		return ""
 	}
 	return *c.Name
 }
``` in github-accessors.go

**Comment by shurcooL** [comment]
Did you see this question?

> What's the output of `go generate -x github.com/google/go-github/...`?

Also, what happens if you run `go list ./...` in the same directory as you ran `go generate -x ./...`?

Perhaps you've changed the import path of the package in your local dev environment?

**Comment by liubinyi** [comment]
oops i missed that.

running ```go generate -x github.com/google/go-github/...``` does  auto generates 
``` func (c *Conduct) GetName() string {
 	if c == nil || c.Name == nil {
 		return ""
 	}
 	return *c.Name
 }
```
if i run go list ./...
it outputs this
``` 
go-github/examples/basicauth
go-github/github
go-github/tests/fields
go-github/tests/integration

```

**Comment by shurcooL** [comment]
I see. You must've placed your `go-github` repository at the root of your GOPATH workspace, i.e., `$GOPATH/src/go-github`. It's meant to be at `$GOPATH/src/github.com/google/go-github`. The `go generate github.com/google/go-github/...` command will only work if the full import path matches. So, using `go generate ./...` is a fine workaround for you.

**Comment by liubinyi** [comment]
oh that's exactly how my local environment looks like.👍 Thanks for clearing out the confusion!
