### ISSUE TITLE
Support commit_id field in PullRequestReviewRequest in file pulls_reviews.go

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#651]
GitHub Developer Announcement:
https://developer.github.com/changes/2017-05-30-specify-commit-for-review/

The announcement was uncharacteristically terse this time and did not provide a link to the developer API docs. It appears to me that this is the API in question: 
https://developer.github.com/v3/pulls/reviews/#create-a-pull-request-review

A new (optional) `commit_id` field needs to be added to the `PullRequestReviewRequest` (sounds like Java 😄) struct.  Note that the Go version of the name would be `CommitID`.

**Comment by navarrano** [comment]
@gmlewis or @shurcooL: You can assign it to me

**Comment by haya14busa** [comment]
Sorry, i didn't notice this issue. I fixed the problem with #683

**Comment by shurcooL** [comment]
Thanks for pointing that out @haya14busa. I felt like I had already seen it somewhere, this explains that.

Closing because it's resolved in #683.
