### ISSUE TITLE
Support TeamEvent

### ISSUE THREAD

**Issue by kytrinyx** [google/go-github#652]
This event was announced in https://developer.github.com/changes/2016-11-29-user-management-webhooks/

The other events announced in that post (OrganizationEvent, MemberEvent) are already supported.

The API documentation is here:
https://developer.github.com/v3/activity/events/types/#teamevent

I'd like to tackle this one.

**Comment by gmlewis** [comment]
Thank you, @kytrinyx!

**Comment by gmlewis** [comment]
Are you speaking again at GopherCon this year, @kytrinyx?
If so, I'll see you there!

**Comment by kytrinyx** [comment]
@gmlewis Unfortunately no, I won't be making it at all this year. It's going to me the first GopherCon that I miss!

**Comment by gmlewis** [comment]
Bummer!  I really enjoyed your talk last time.  OK, hope to see you next year.
Thank you for helping out with go-github... we appreciate the help of all our contributors!
