### ISSUE TITLE
PullRequestReviewsEnforcementRequest.DismissalRestrictionsRequest set to nil results in 422 from GH

### ISSUE THREAD

**Issue by mslusarczyk** [google/go-github#664]
According to [doc](https://github.com/google/go-github/commit/b5b6d4c9c91636b0513e1c29fcfd243162331d36#diff-49ba3de83fa99f3d8bae2ece519a449fR571) user is able to pass nil to disable `DismissalRestrictions` and looking at [method](https://github.com/google/go-github/blame/b5b6d4c9c91636b0513e1c29fcfd243162331d36/github/repos.go#L579) below this `nil` is converted to empty array. 

Seems that this is not working properly because 
```
&github.ProtectionRequest{
		RequiredPullRequestReviews: &github.PullRequestReviewsEnforcementRequest{DismissalRestrictionsRequest: nil, DismissStaleReviews:false},
	}
```
results in:
```
No subschema in "anyOf" matched.
For 'properties/dismissal_restrictions', [] is not an object.
Not all subschemas of "allOf" matched.
For 'anyOf/1', {"dismissal_restrictions"=>[], "dismiss_stale_reviews"=>false} is not a null. []]
```
and '422 Invalid request' from GH 

@navarrano could you please take a look?

**Comment by iwata** [comment]
And I hope that `PullRequestReviewsEnforcementRequest` supports `require_code_owner_reviews` key 😄 .
https://developer.github.com/v3/repos/branches/#update-branch-protection

**Comment by shurcooL** [comment]
I ran into this issue as well in #674. See https://github.com/google/go-github/blob/e062a8cd852f0fb981c8c9f837c214c4d1031870/test/integration/repos_test.go#L111-L113.

**Comment by beiriannydd** [comment]
I have PR #703 in to fix this.  It seems to be failing because I added a new library go-spew which is essentially the recursive %+v I always wanted and that doesn't get pulled in during the build.

**Comment by beiriannydd** [comment]
Tests are passing :)

**Comment by shurcooL** [comment]
See my comment at https://github.com/google/go-github/pull/703#issuecomment-324064996.

I think in order to resolve this bug, we need to figure out how to reproduce a successful response from GitHub using REST API. Then, once we have that, we can work on the Go code to fix the code, if needed.

**Comment by shurcooL** [comment]
From my understanding of #703, the way to get a successful response from GitHub is to perform the API call involving DismissalRestrictionsRequest on an organization-owned repository. It doesn't work on personal repositories and gives 422 in that case. /cc @beiriannydd

**Comment by elliott-beach** [comment]
I think this is solved by #744.

**Comment by JaredReisinger** [comment]
I just started seeing a 422 when an empty array is passed for `dismissal_restrictions`.  The docs (https://developer.github.com/v3/repos/branches/#update-branch-protection) specifically mention that passing an empty array is the right way to disable dismissal restrictions (which is weird, IMO, since `null` would work just fine for this, and the object isn't normally an array).

In any case, I have a support request out to GitHub to try to find out what the expected behavior is/should be.  If the docs are wrong, and the property should be null (instead of an empty array), I'll provide a PR to make the change.

**Comment by shurcooL** [comment]
It seems to me that GitHub has updated the docs by now, and I'm not aware of what exactly we're waiting on them, so removed that label. I think PR #791 will resolve this issue (let me know if not).
