### ISSUE TITLE
Support preview Installations API - updated routes for adding or removing a repository

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#666]
GitHub Developers announcment:
https://developer.github.com/changes/2017-06-30-installations-adding-removing-a-repository/

GitHub API docs:
https://developer.github.com/v3/apps/installations/#add-repository-to-installation

**Comment by S2606** [comment]
@gmlewis I would love to contribute to this project.Pls assign me.

**Comment by shurcooL** [comment]
> I would love to contribute to this project.

Thanks! Feel free to take this issue.

You'll find relevant information in [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md). See previous PRs to get an idea of best practices.

**Comment by gmlewis** [comment]
Thank you, @S2606! Sending invite.

**Comment by vedantrathore** [comment]
@S2606 are you still working on this? if not, I'd like to get started on this?

**Comment by S2606** [comment]
@shurcooL Since i have been added as a collaborator, do i need to still follow the normal procedure for pull requet??

**Comment by shurcooL** [comment]
@S2606 I think you were added so you could be assigned to an issue (it's how GitHub permissions work). I'm not sure what you mean by "normal" procedure for PRs, but yes, you should just create a PR. That's what everyone does, including @gmlewis and myself.

**Comment by S2606** [comment]
Thank you @shurcooL .

**Comment by S2606** [comment]
@gmlewis I have a doubt. Can you tell me in which file is this API being used because i couldnt find them in `apps_installation.go`

**Comment by MorrisLaw** [comment]
Is this still being worked on , or is it up for grabs ? @S2606 @shurcooL @gmlewis

**Comment by gmlewis** [comment]
Let's say if we don't hear from @S2606 by this Wednesday, that we can reassign this issue. I hope that seems fair to everyone... If anyone wishes to point me to any standard policy for making decisions of this nature, I would gladly read up on them.  :smile:

**Comment by S2606** [comment]
You can take it @MorrisLaw.

**Comment by MorrisLaw** [comment]
I'm going to start working on this issue @gmlewis @shurcooL . When you get the chance, please assign it to me. Thank you, I will keep this thread updated on my progress if I have any issues.

**Comment by shurcooL** [comment]
Sounds good, thanks @MorrisLaw! I can't assign you to the issue, but it should be visible for anyone reading this that you're taking it on at this time.

(If/once @gmlewis invites you, then we can assign you. GitHub restrictions mean we can't assign someone until they're invited to the org.)

**Comment by gmlewis** [comment]
Invite sent, @MorrisLaw. Thank you!

**Comment by MorrisLaw** [comment]
I'm having some trouble testing my changes to the code. I run `go generate` and nothing appears to happen. When I run `go test` in my **~/Projects/go-workspace/src/go-github/github** directory I get the following error:

```
# go-github/github
examples_test.go:13:2: cannot find package "github.com/google/go-github/github" in any of:
	/usr/local/go/src/github.com/google/go-github/github (from $GOROOT)
	/home/morrislaw/Projects/go-workspace/src/github.com/google/go-github/github (from $GOPATH)
FAIL	go-github/github [setup failed]

```

If I run `go test` on a particular test file I get the following, and this is with any test file so I'm assuming that I shouldn't run `go test` on a particular file but instead, on a single package as I did above.
```
# command-line-arguments
go-github/github/admin_test.go:18: undefined: setup
go-github/github/admin_test.go:19: undefined: teardown
go-github/github/admin_test.go:21: undefined: UserLDAPMapping
go-github/github/admin_test.go:25: undefined: mux in mux.HandleFunc
go-github/github/admin_test.go:26: undefined: UserLDAPMapping
go-github/github/admin_test.go:29: undefined: testMethod
go-github/github/admin_test.go:36: undefined: client in client.Admin
go-github/github/admin_test.go:41: undefined: UserLDAPMapping
go-github/github/admin_test.go:51: undefined: setup
go-github/github/admin_test.go:52: undefined: teardown
go-github/github/admin_test.go:52: too many errors
FAIL	command-line-arguments [build failed]
```

Here are some things I've tried to troubleshoot my problem:
* I've ran `echo $GOPATH` to verify my path is as expected and this is what I get, **/home/morrislaw/Projects/go-workspace/**.
* I've ran `go get github.com/google/go-github/github` while inside my **~/Projects/go-workspace/src/** directory.
* I've ran `go list` inside of my **~/Projects/go-workspace/src/go-github/github** directory I get that I have one package **go-github/github/**.

If anyone could also give suggestions or point me to a test file dealing with a similar task. I've been referencing **users_emails_test.go** , **issues_test.go** , **authorization_tests.go** and **repos_test.go** and of course [gorilla/mux documentation](https://github.com/gorilla/mux/blob/master/README.md).

I realize these are very newbie type questions and I appreciate any help/guidance towards completing this task. Thank you! 

P.S. Here's the branch I've been working on https://github.com/MorrisLaw/go-github/tree/enhancement/add-remove-repository

**Comment by shurcooL** [comment]
It sounds sounds like the `go-github` repository that you're modifying is in the wrong location. Based on your GOPATH, it should be here:

```
~/Projects/go-workspace/src/github.com/google/go-github/github
```

But instead you've placed it here:

```
~/Projects/go-workspace/src/go-github/github
```

You should move the folder `go-github` in the right location. As is, its full import path is `go-github/github`, which is not what you want. It should match the full import path of this project, which is `github.com/google/go-github/github`.

**Comment by shurcooL** [comment]
@MorrisLaw Please read this post https://blog.sgmansfield.com/2016/06/working-with-forks-in-go/ by @ScottMansfield, it explains the best way to set things up so that you can send contributions.

Also, please take a look over https://github.com/google/go-github/blob/master/CONTRIBUTING.md as it may have additional relevant information.

**Comment by MorrisLaw** [comment]
Thank you for the fast response @shurcooL

**Comment by MorrisLaw** [comment]
I've attempted to tackle this issue but my changes have failed in travis checks. Can someone please point me in the right direction, the changes are located in PR #749. I am new to Go and this github client in general, so I may be missing something obvious. Thank you everyone for your patience and advice! (: @shurcooL @gmlewis

**Comment by theodesp** [comment]
Looks like PR #749 was merged. Shall we close this ticket?
