### ISSUE TITLE
ProjectCard missing attributes

### ISSUE THREAD

**Issue by XescuGC** [google/go-github#667]
First of all great job with this lib 👍 

Next, I've noticed that the [ProjectCard](https://github.com/google/go-github/blob/master/github/projects.go#L263) is missing some fields, checking the github [documentation](https://developer.github.com/v3/projects/cards/#response) I detect that: `url` and `creator` are missing. But when it comes from a webhook of [project_card](https://developer.github.com/v3/projects/cards/#response) it has also `column_id` and it's missing also.

The `creator` filed matches the struct for [`User`](https://github.com/google/go-github/blob/master/github/users.go#L20)

**Comment by shurcooL** [comment]
Thanks for reporting. I can confirm, `url` and `creator` are missing and should be added.

> But when it comes from a webhook of project_card it has also `column_id` and it's missing also.

Do you have a source for this? If you have a sample webhook object that includes that field, can you share it?

**Comment by XescuGC** [comment]
On the GH documentatio for the [`project_card`](https://developer.github.com/v3/activity/events/types/#webhook-payload-example-19) webhook you can see the `column_id` definded inside the `project_card` key.

**Comment by shurcooL** [comment]
Excellent, thanks for confirming!
