### ISSUE TITLE
Support preview Repository API - read and replace topics for a repository.

### ISSUE THREAD

**Issue by shurcooL** [google/go-github#670]
GitHub Announcement: https://developer.github.com/changes/2017-07-17-update-topics-on-repositories/

It looks like there are 4 changes/additions in this announcement:

- [ ] [Replace all the topics for a repository](https://developer.github.com/v3/repos/#replace-all-topics-for-a-repository).
- [ ] [List the topics for a repository](https://developer.github.com/v3/repos#list-all-topics-for-a-repository) specifically.
- [ ] Topics are also available as part of the payload in the [get repository](https://developer.github.com/v3/repos/#get) endpoint.
- [ ] Topics are also available as part of the payload in the [search repositories](https://developer.github.com/v3/search/#search-repositories) endpoint.

~~The get repository payload may be problematic for the same reason as https://github.com/google/go-github/pull/656#issuecomment-313720527, so it's completely okay to address it later/in a separate PR.~~ This has been resolved (see comments below).

/cc @kytrinyx FYI.

**Comment by kytrinyx** [comment]
I've asked some colleagues what happens if you need multiple different preview headers for a call.

**Comment by kytrinyx** [comment]
Confirmed: at the moment making a request with multiple preview headers is not supported. You'd have to make the same request with multiple accept headers.

**Comment by kytrinyx** [comment]
Actually, I take that back. It looks like we may have released a fix that should let you make a call with multiple preview headers:

```
curl -H "Accept: application/vnd.github.mockingbird-preview" -H "Accept: application/vnd.github.scarlet-witch-preview+json"
```

I just confirmed with this call:

curl -v -XGET "https://api.github.com/repos/:org/:repo" -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github.mercy-preview+json" -H "Accept:  application/vnd.github.drax-preview+json"

The response came back with both `licenses` and `topics`.

**Comment by shurcooL** [comment]
Awesome, thank you @kytrinyx! This is super helpful, because it would not be viable for us to make more than 1 remote API call per method, since each method is supposed to correspond to a single API call.

**Comment by RaviTezu** [comment]
Hi @shurcooL 
Can I tackle this one for my first contribution? Thanks in advance.

**Comment by bradleyfalzon** [comment]
Let me know how you go @RaviTezu, I'm interested in this functionality. I have a work around, so no pressure.

**Comment by shurcooL** [comment]
Feel free to go for it, @RaviTezu, and thanks!

Take a look over https://github.com/google/go-github/blob/master/CONTRIBUTING.md to be familiar with contributing guidelines.

**Comment by gmlewis** [comment]
@RaviTezu - invite sent. Thank you!

**Comment by RaviTezu** [comment]
@bradleyfalzon I have raised a PR for this. Please take a look and if there's something that can be improved, please feel free to let me know.
@shurcooL Thank you. PR sent. 
@gmlewis Thank you for the invite. I have accepted it.
