### ISSUE TITLE
examples, tests directories should use singular form.

### ISSUE THREAD

**Issue by shurcooL** [google/go-github#671]
This is a very minor/nitpicky issue that I'd like to fix, because it's bugging me, and because it's setting a bad example for new gophers.

The directories `examples`, `tests` in the repository root are containers of multiple packages. They should use singular form to follow idiomatic Go patterns. That way, it will be consistent with other Go projects, and `./example/basicauth`, `./test/integration`, `./test/fields` import paths read better.

See https://dmitri.shuralyov.com/idiomatic-go#use-singular-form-for-collection-repo-folder-name for rationale/proof. Also note that https://github.com/golang/go/tree/master/test directory is `test`, not `tests`, even though it contains many tests.

If this has approval from @willnorris and @gmlewis, I'll gladly work on a fix and make sure everything works after the rename.

**Comment by gmlewis** [comment]
SGTM.

**Comment by willnorris** [comment]
fine with me
