### ISSUE TITLE
Panic when BaseURL is missing the scheme prefix

### ISSUE THREAD

**Issue by RyanFrench** [google/go-github#680]
If I create a new client and explicitly set the BaseURL (for instance when using GitHub Enterprise) without the `https://` at the start of the URI, it allows me to create the client but then panics once a request is made.

`panic: runtime error: invalid memory address or nil pointer dereference`

```go
ts := oauth2.StaticTokenSource(&oauth2.Token{
    AccessToken: token,
})

tc := oauth2.NewClient(oauth2.NoContext, ts)

client := github.NewClient(tc)
if client.BaseURL, err = url.Parse("github.com"); err != nil {
    log.Fatal(err)
}
var repository *github.Repository
var res *github.Response
if repository, res, err = client.Repositories.Get(oauth2.NoContext, owner, repo); res.StatusCode != 200 {
    log.Fatal(err)
}
```

**Comment by shurcooL** [comment]
The panic is on this line:

```Go
if repository, res, err = client.Repositories.Get(oauth2.NoContext, owner, repo); res.StatusCode != 200 {
```

Specifically, you're accessing `res.StatusCode` without first checking `err`. If `err != nil`, then response may be `nil`, so doing `res.StatusCode` triggers a nil pointer dereference panic.

You should check error first, e.g.:

```Go
repository, res, err = client.Repositories.Get(oauth2.NoContext, owner, repo)
if err != nil {
	return err
}
if res.StatusCode != http.StatusOK {
	return fmt.Errorf("non-200 status code: %v", res.StatusCode)
}
```

(Also, note that `go-github` already checks the status code for you and returns non-`nil` error if it's not an expected value, so checking it manually yourself is not neccessary.)

Once that's fixed, I don't see another panic. So the problem isn't related to `BaseURL`, at least not in the snippet you've posted.

**Comment by RyanFrench** [comment]
Ah, thanks. That makes sense.
