### ISSUE TITLE
Error when creating a repository

### ISSUE THREAD

**Issue by scriptonist** [google/go-github#681]
When creating a repository using the following method
`repos, _, err := client.Repositories.Create(ctx, "", repo)`
It throws the following error

`
POST https://api.github.com/user/repos: 404 Not Found 
`
The client was created using the following method

```
        ctx := context.Background()
	ts := oauth2.StaticTokenSource(
		&oauth2.Token{AccessToken: <token returned from github after oauth>},
	)
	tc := oauth2.NewClient(ctx, ts)

	client := github.NewClient(tc)


```

**Comment by shurcooL** [comment]
404 is a strange response.

https://developer.github.com/v3/repos/#create are the GutHub API docs for that endpoint.

Do you have the right OAuth scopes? Did you provide the required `Repository.Name` field?

**Comment by scriptonist** [comment]
This is the repository var which i user
```
                repo := &github.Repository{
			Name:    github.String(RepoName),
			Private: github.Bool(false),
		}
```

**Comment by scriptonist** [comment]
@shurcooL the problem was with  OAuth scopes. I don't know how i missed it.Thank you so much.
