### ISSUE TITLE
Investigate breaking changes to creating webhooks

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#684]
GitHub Developer Announcement:
https://developer.github.com/changes/2017-08-09-breaking-changes-to-webhook-creation/

It looks to me like this might be a simple or possibly even a NO-OP issue for this repo, but needs investigation and is a great opportunity for a new contributor to take on an issue and contribute (for which we greatly appreciate).

To resolve this issue, the following endpoints need to be investigated:

    * POST /repos/:owner/:repo/hooks
    * PATCH /repos/:owner/:repo/hooks/:id
    * POST /orgs/:org/hooks
    * PATCH /orgs/:org/hooks/:id

and make sure that none of the following events are being sent:

    * download
    * follow
    * fork_apply
    * gist

If that is the case, this issue can be closed and we are good to go.
If, however, one or more of these events is capable of being sent through this package, then they need to be removed (or commented that they are illegal if the events are user-supplied as strings, which I highly doubt).

Feel free to ask to be assigned as owner for this issue to investigate and potentially fix, and you will be sent an invite to contribute to this repo (if you aren't already a contributor).
Thank you!

**Comment by scriptonist** [comment]
@gmlewis Can i take this up ?.

**Comment by gmlewis** [comment]
Absolutely!  Sending invite.  Thank you, @scriptonist!

**Comment by gmlewis** [comment]
We have some useful information for contributing here:
https://github.com/google/go-github/blob/master/CONTRIBUTING.md

**Comment by scriptonist** [comment]
@gmlewis I dont't know if i did it right.But these are the steps that i followed

- Created a webhook for one of my personnel repo.
- Accessed this with the `ListHooks` and `GetHook` functions.
- Studied the response

I did the same for an organizational repository.
I found that none of these responses had
-  download
- follow
- fork_apply
- gist

in their events array.
Was my approach right ? what more should I do ? please correct me for any mistakes.

**Comment by gmlewis** [comment]
Thank you, @scriptonist!  You went above and beyond.
I didn't actually expect GitHub to be sending those responses.
I wanted to make sure that we weren't simulating those responses anywhere or expecting them in our package.
It looks like we are totally in the clear.

Thanks again for investigating this, @scriptonist... we really appreciate it.
I'm going to close this issue as resolved.
Feel free to reopen if you (anyone) thinks that this issue has not been addressed correctly.
