### ISSUE TITLE
Create tags in this repository in order to pin the version when vendoring the library

### ISSUE THREAD

**Issue by JorritSalverda** [google/go-github#689]
To be able to run a predictable and repeatable build vendoring copies the whole repository in your own. I would be nice to be able to easily pin it to a specific version. Unfortunately right now there are no releases or tags that represent a version. Any plans to do so? Thx

**Comment by shurcooL** [comment]
We have an open issue #376 where this is being discussed, please use it. Closing as duplicate of #376.
