### ISSUE TITLE
archived releases have been removed?

### ISSUE THREAD

**Issue by marcindulak** [google/go-github#705]
I used to access the particular tarball at https://github.com/google/go-github/archive/30a21ee1a3839fb4a408efe331f226b73faac379/go-github-30a21ee.tar.gz - what happened to the archived releases, is this a github change?

**Comment by e-beach** [comment]
The `500: Internal Server Error` response suggests that this was an issue with github.com. 
I just tested and it is now working for me.

**Comment by marcindulak** [comment]
Works for me now, too.
