### ISSUE TITLE
Include more advanced search query in godoc and test case.

### ISSUE THREAD

**Issue by shurcooL** [google/go-github#707]
From #701, there are 2 improvements I think we can make for our search endpoints:

- [ ] The godoc can be improved to give an example query. Right now, https://godoc.org/github.com/google/go-github/github#SearchService.Issues doesn't say much. I think it'd be helpful to give an example query that can be done. For example, maybe a query like this:

    `"gopher is:issue label:bug language:go"`
    with
    `opt := &github.SearchOptions{Sort: "created", Order: "asc"}`

    ```Go
    result, _, err := cl.Search.Issues(ctx, "gopher is:issue label:bug language:go", opt)
    ```

- [ ] We should add another test case for `search` that covers a query with spaces and colons. That way, the query parameter escaping functionality won't accidentally regress in the future.

See https://github.com/google/go-github/pull/701#issuecomment-324362880 for more context.

**Comment by e-beach** [comment]
Can this be assigned to me?
