### ISSUE TITLE
Remove custom media type for Repository Invitations API

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#708]
GitHub Announcement:
https://developer.github.com/changes/2017-08-23-repository-invitation-api/

The custom media type `mediaTypeRepositoryInvitationsPreview` that was added in #373 can now be removed as it is no longer necessary.

Edit: ~~~GitHub Enterprise API customers may wish to comment on this issue if they feel that this removal should be delayed for any reason.~~~

**Comment by RaviTezu** [comment]
Hi @gmlewis Can I take this?

**Comment by gmlewis** [comment]
I just talked to @willnorris who reminded me that we will not be removing any features until we get confirmation that the removal won't break Enterprise API clients... so please hold off on addressing this issue.

Also, semantic versioning, once we nail that down for this repo, should assist with this situation.

See #376, #617, and #638 for further discussion.

**Comment by RaviTezu** [comment]
Sure @gmlewis

**Comment by kshitij10496** [comment]
I can take this up next if @RaviTezu is not currently working on it.

**Comment by gmlewis** [comment]
Please see my [comment above](https://github.com/google/go-github/issues/708#issuecomment-324725282). We need confirmation from GitHub Enterprise API customers that the removal will not break them, which has happened in the past. Alternatively, semantic versioning needs to be adhered to in this repo before proceeding with this issue.

**Comment by knrt10** [comment]
@gmlewis is this issue still blocked? If not I would like to work on this.

**Comment by gmlewis** [comment]
This issue is no longer blocked thanks to versioning. Feel free to take it, @knrt10.

**Comment by knrt10** [comment]
Would you please assign me.

**Comment by gmlewis** [comment]
You first need to be sent an invite, @knrt10, and @willnorris can send you one when he has a chance.

In the meantime, however, please consider this issue to be assigned to you.
Others will see that in this comment section.
