### ISSUE TITLE
[Need help] What's the syntax of search query

### ISSUE THREAD

**Issue by yutongz** [google/go-github#710]
I am trying to use [SearchService](https://github.com/google/go-github/blob/master/github/search.go#L100) to query specific PRs. 

I tried github api with something like: `https://api.github.com/search/issues?q=type:pr+label:release-note+repo:istio/istio+is:merged+merged:>2017-08-01&sort=created&order=asc` and the response was as expected.

Then I tried to use golang api to do the same thing, https://github.com/yutongz/test-infra/pull/8.
The issue I don't understand is when I print out my query string [here](https://github.com/yutongz/test-infra/pull/8/files#diff-643f4beccfdc71f42786f85288864424R346), I got 
`type:pr+repo:istio/istio+label:release-note+is:merged` 
while I hit the error: 
`Failed to fetch PR with release note for istio: GET https://api.github.com/search/issues?order=desc&q=repo%3Aistio%2Fistio%2Btype%3Apr%2Blabel%3Arelease-note%2Bis%3Amerged&sort=create: 422 Validation Failed`

So my questions are:
1. What syntax I should use in query string?
2. What's the meaning of `params.Encode()` before [sending out the request](https://github.com/google/go-github/blob/master/github/search.go#L179)

Thanks!

**Comment by shurcooL** [comment]
The string should be the same as what you'd type on github.com in a search UI box. Something like:

```Go
cl.Search.Issues(context.Background(), "repo:istio/istio type:pr label:release-note is:merged", nil)
```

This issue further validates issue #707; we should add an example to godoc.

**Comment by yutongz** [comment]
Thanks for a quick response. That works and yes, it would be better to have a little bit more instruction.
