### ISSUE TITLE
Support Marketplace (preview) API.

### ISSUE THREAD

**Issue by shurcooL** [google/go-github#720]
GitHub API Docs: https://developer.github.com/v3/apps/marketplace/.

Not seeing an announcement blog post mentioning this, but there are new API endpoints available, as documented at the URL above.

This issue is to track their implementation.

A sub-task here is supporting the `MarketplacePurchaseEvent` event, which is tracked in a separate issue #704.

**Comment by lackerman** [comment]
Hi @shurcooL, I would love to get involved but I would be remiss if I didn't say that I'm very new to Golang. My understanding from the Contribution guide and the issue you raised is that this requires the implementation of the `marketplace_listing` endpoints in perhaps a `marketplace.go` file. Any suggestions or resources to get me underway would be greatly appreciated.

**Comment by shurcooL** [comment]
Sounds great, thanks @lackerman!

The contribution guide should have most of the things covered. For a general idea of what it looks like, I suggest looking at a similar issue and the PR that it took to resolve it in the past. Those serve as great examples/references. For example, see issue #569 and PR #620.

You can start your PR by implementing just one endpoint and sending a PR for review first. We can give feedback, and once everything looks good, you can implement the remaining endpoints. That way you're less likely to spend time on something that needs to be changed.

> this requires the implementation of the `marketplace_listing` endpoints in perhaps a `apps_marketplace.go` file

A new file named `apps_marketplace.go` sounds like a great fit to me. 👍

**Comment by lackerman** [comment]
@shurcooL thanks for the information. I've created a PR and would appreciate any feedback.
