### ISSUE TITLE
Preview of additional endpoints for GitHub Apps.

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#722]
GitHub Developer Announcement:
https://developer.github.com/changes/2017-09-21-additional-endpoints-for-github-apps/

Woohoo!  Lots of new endpoints to support.

I'm thinking that this is way too big for a single PR, and yet it would probably be silly to open up a separate issue for each endpoint... so how about if I add a checkbox task list to the endpoints in this issue and we can check them off as PRs address them? Obviously, the first PR will also need to add the new custom media type `application/vnd.github.machine-man-preview+json` in the `Accept` header and following PRs can just use it.

Here are the recently-added endpoints:
- [ ] [GET /](https://developer.github.com/v3/#root-endpoint)
- [ ] [GET /emojis](https://developer.github.com/v3/emojis/)
- [ ] [GET /events](https://developer.github.com/v3/activity/events/#list-public-events)
- [ ] [GET /networks/:owner/:repo/events](https://developer.github.com/v3/activity/events/#list-public-events-for-a-network-of-repositories)
- [ ] [GET /orgs/:org/events](https://developer.github.com/v3/activity/events/#list-public-events-for-an-organization)
- [ ] [GET /users/:username/events](https://developer.github.com/v3/activity/events/#list-events-performed-by-a-user)
- [ ] [GET /users/:username/events/public](https://developer.github.com/v3/activity/events/#list-public-events-performed-by-a-user)
- [ ] [GET /users/:username/received_events](https://developer.github.com/v3/activity/events/#list-events-that-a-user-has-received)
- [ ] [GET /users/:username/received_events/public](https://developer.github.com/v3/activity/events/#list-public-events-that-a-user-has-received)
- [ ] [GET /repos/:owner/:name/community/profile](https://developer.github.com/v3/repos/community/#retrieve-community-profile-metrics)
- [ ] [GET /repos/:owner/:repo/community/code_of_conduct](https://developer.github.com/v3/codes_of_conduct/#get-the-contents-of-a-repositorys-code-of-conduct)
- [ ] [GET /repos/:owner/:repo/branches/:branch/protection](https://developer.github.com/v3/repos/branches/#get-branch-protection)
- [ ] [GET /repos/:owner/:repo/branches/:branch/protection/restrictions](https://developer.github.com/v3/repos/branches/#get-restrictions-of-protected-branch)
- [ ] [GET /repos/:owner/:repo/branches/:branch/protection/restrictions/users](https://developer.github.com/v3/repos/branches/#list-user-restrictions-of-protected-branch)
- [ ] [GET /repos/:owner/:repo/branches/:branch/protection/restrictions/teams](https://developer.github.com/v3/repos/branches/#list-team-restrictions-of-protected-branch)
- [ ] [GET /repos/:owner/:repo/branches/:branch/protection/required_pull_request_reviews](https://developer.github.com/v3/repos/branches/#get-pull-request-review-enforcement-of-protected-branch)
- [ ] [GET /repos/:owner/:repo/branches/:branch/protection/enforce_admins](https://developer.github.com/v3/repos/branches/#get-admin-enforcement-of-protected-branch)
- [ ] [PUT /repos/:owner/:repo/branches/:branch/protection](https://developer.github.com/v3/repos/branches/#update-branch-protection)
- [ ] [DELETE /repos/:owner/:repo/branches/:branch/protection](https://developer.github.com/v3/repos/branches/#remove-branch-protection)
- [ ] [PATCH /repos/:owner/:repo/branches/:branch/protection/required_status_checks](https://developer.github.com/v3/repos/branches/#update-required-status-checks-of-protected-branch)
- [ ] [DELETE /repos/:owner/:repo/branches/:branch/protection/required_status_checks](https://developer.github.com/v3/repos/branches/#remove-required-status-checks-of-protected-branch)
- [ ] [POST /repos/:owner/:repo/branches/:branch/protection/required_status_checks/contexts](https://developer.github.com/v3/repos/branches/#add-required-status-checks-contexts-of-protected-branch)
- [ ] [PUT /repos/:owner/:repo/branches/:branch/protection/required_status_checks/contexts](https://developer.github.com/v3/repos/branches/#replace-required-status-checks-contexts-of-protected-branch)
- [ ] [DELETE /repos/:owner/:repo/branches/:branch/protection/required_status_checks/contexts](https://developer.github.com/v3/repos/branches/#remove-required-status-checks-contexts-of-protected-branch)
- [ ] [DELETE /repos/:owner/:repo/branches/:branch/protection/restrictions](https://developer.github.com/v3/repos/branches/#remove-restrictions-of-protected-branch)
- [ ] [PUT /repos/:owner/:repo/branches/:branch/protection/restrictions/users](https://developer.github.com/v3/repos/branches/#replace-user-restrictions-of-protected-branch)
- [ ] [POST /repos/:owner/:repo/branches/:branch/protection/restrictions/users](https://developer.github.com/v3/repos/branches/#add-user-restrictions-of-protected-branch)
- [ ] [DELETE /repos/:owner/:repo/branches/:branch/protection/restrictions/users](https://developer.github.com/v3/repos/branches/#remove-user-restrictions-of-protected-branch)
- [ ] [PUT /repos/:owner/:repo/branches/:branch/protection/restrictions/teams](https://developer.github.com/v3/repos/branches/#replace-team-restrictions-of-protected-branch)
- [ ] [POST /repos/:owner/:repo/branches/:branch/protection/restrictions/teams](https://developer.github.com/v3/repos/branches/#add-team-restrictions-of-protected-branch)
- [ ] [DELETE /repos/:owner/:repo/branches/:branch/protection/restrictions/teams](https://developer.github.com/v3/repos/branches/#remove-team-restrictions-of-protected-branch)
- [ ] [PATCH /repos/:owner/:repo/branches/:branch/protection/required_pull_request_reviews](https://developer.github.com/v3/repos/branches/#update-pull-request-review-enforcement-of-protected-branch)
- [ ] [DELETE /repos/:owner/:repo/branches/:branch/protection/required_pull_request_reviews](https://developer.github.com/v3/repos/branches/#remove-pull-request-review-enforcement-of-protected-branch)
- [ ] [POST /repos/:owner/:repo/branches/:branch/protection/enforce_admins](https://developer.github.com/v3/repos/branches/#add-admin-enforcement-of-protected-branch)
- [ ] [DELETE /repos/:owner/:repo/branches/:branch/protection/enforce_admins](https://developer.github.com/v3/repos/branches/#remove-admin-enforcement-of-protected-branch)

Here are the endpoints for [user-to-server requests](https://developer.github.com/apps/building-integrations/setting-up-and-registering-github-apps/identifying-users-for-github-apps/#user-to-server-requests):

- [ ] [POST /repos/:owner/:repo/git/trees](https://developer.github.com/v3/git/trees/#create-a-tree)
- [ ] [POST /repos/:owner/:repo/git/refs](https://developer.github.com/v3/git/refs/#create-a-reference)
- [ ] [POST /repos/:owner/:repo/git/blobs](https://developer.github.com/v3/git/blobs/#create-a-blob)
- [ ] [POST /repos/:owner/:repo/git/commits](https://developer.github.com/v3/git/commits/#create-a-commit)
- [ ] [POST /repos/:owner/:repo/git/tags](https://developer.github.com/v3/git/tags/#create-a-tag-object)
- [ ] [PATCH /repos/:owner/:repo/git/refs/:ref](https://developer.github.com/v3/git/refs/#update-a-reference)
- [ ] [DELETE /repos/:owner/:repo/git/refs/:ref](https://developer.github.com/v3/git/refs/#delete-a-reference)
- [ ] [PUT /repos/:owner/:repo/topics](https://developer.github.com/v3/repos/#replace-all-topics-for-a-repository)
- [ ] [PUT /repos/:owner/:repo/contents/:path](https://developer.github.com/v3/repos/contents/#create-a-file) (create)
- [ ] [PUT /repos/:owner/:repo/contents/:path](https://developer.github.com/v3/repos/contents/#update-a-file) (update)
- [ ] [DELETE /repos/:owner/:repo/contents/:path](https://developer.github.com/v3/repos/contents/#delete-a-file)
- [ ] [POST /repos/:owner/:repo/statuses/:sha](https://developer.github.com/v3/repos/statuses/#create-a-status)
- [ ] [PUT /repos/:owner/:repo/branches/:branch/protection](https://developer.github.com/v3/repos/branches/#update-branch-protection)
- [ ] [DELETE /repos/:owner/:repo/branches/:branch/protection](https://developer.github.com/v3/repos/branches/#remove-branch-protection)
- [ ] [PATCH /repos/:owner/:repo/branches/:branch/protection/required_status_checks](https://developer.github.com/v3/repos/branches/#update-required-status-checks-of-protected-branch)
- [ ] [DELETE /repos/:owner/:repo/branches/:branch/protection/required_status_checks](https://developer.github.com/v3/repos/branches/#remove-required-status-checks-of-protected-branch)
- [ ] [POST /repos/:owner/:repo/branches/:branch/protection/required_status_checks/contexts](https://developer.github.com/v3/repos/branches/#add-required-status-checks-contexts-of-protected-branch)
- [ ] [PUT /repos/:owner/:repo/branches/:branch/protection/required_status_checks/contexts](https://developer.github.com/v3/repos/branches/#replace-required-status-checks-contexts-of-protected-branch)
- [ ] [DELETE /repos/:owner/:repo/branches/:branch/protection/required_status_checks/contexts](https://developer.github.com/v3/repos/branches/#remove-required-status-checks-contexts-of-protected-branch)
- [ ] [DELETE /repos/:owner/:repo/branches/:branch/protection/restrictions](https://developer.github.com/v3/repos/branches/#remove-restrictions-of-protected-branch)
- [ ] [PUT /repos/:owner/:repo/branches/:branch/protection/restrictions/users](https://developer.github.com/v3/repos/branches/#replace-user-restrictions-of-protected-branch)
- [ ] [POST /repos/:owner/:repo/branches/:branch/protection/restrictions/users](https://developer.github.com/v3/repos/branches/#add-user-restrictions-of-protected-branch)
- [ ] [DELETE /repos/:owner/:repo/branches/:branch/protection/restrictions/users](https://developer.github.com/v3/repos/branches/#remove-user-restrictions-of-protected-branch)
- [ ] [PUT /repos/:owner/:repo/branches/:branch/protection/restrictions/teams](https://developer.github.com/v3/repos/branches/#replace-team-restrictions-of-protected-branch)
- [ ] [POST /repos/:owner/:repo/branches/:branch/protection/restrictions/teams](https://developer.github.com/v3/repos/branches/#add-team-restrictions-of-protected-branch)
- [ ] [DELETE /repos/:owner/:repo/branches/:branch/protection/restrictions/teams](https://developer.github.com/v3/repos/branches/#remove-team-restrictions-of-protected-branch)
- [ ] [PATCH /repos/:owner/:repo/branches/:branch/protection/required_pull_request_reviews](https://developer.github.com/v3/repos/branches/#update-pull-request-review-enforcement-of-protected-branch)
- [ ] [DELETE /repos/:owner/:repo/branches/:branch/protection/required_pull_request_reviews](https://developer.github.com/v3/repos/branches/#remove-pull-request-review-enforcement-of-protected-branch)
- [ ] [POST /repos/:owner/:repo/branches/:branch/protection/enforce_admins](https://developer.github.com/v3/repos/branches/#add-admin-enforcement-of-protected-branch)
- [ ] [DELETE /repos/:owner/:repo/branches/:branch/protection/enforce_admins](https://developer.github.com/v3/repos/branches/#remove-admin-enforcement-of-protected-branch)
- [ ] [PATCH /repos/:owner/:repo/issues/:number](https://developer.github.com/v3/issues/#edit-an-issue)

It seems reasonable to assign multiple owners to this issue, and here in the comments we will attempt to clearly document who is working on which endpoints so that we don't waste anyone's time or effort.

Thank you in advance for contributing to this open source project!
Your assistance is greatly appreciated.

**Comment by e-beach** [comment]
I don't think those are new endpoints. I believe the above endpoints are now permissible for GitHub Apps to use, but we already support them for normal API clients. That includes user-to-server requests.

What is new is the machine-man preview header. We might as well add this header to every endpoint listed. I think I can do that in one pull request.

**Comment by gmlewis** [comment]
GitHub follow-on announcement:
https://developer.github.com/changes/2017-10-20-additional-endpoints-for-github-apps/

@elliott-beach - you investigated this previously... thank you!  Do you want to take a look and see if this issue can be closed?

**Comment by shurcooL** [comment]
A status update here. We had a PR that implemented this issue (at least partially), but deferred merging it because of rationale posted in https://github.com/google/go-github/pull/736#pullrequestreview-78581351.

Basically, if we wait long enough, this issue will get resolved on its own without us having to make any risky changes (back and forth) in `go-github`.

If someone really needs this functionality sooner, let us know here so we can make a better informed decision. So, the issue is in waiting/hold status until then.

**Comment by gmlewis** [comment]
Another GitHub Developer API follow-on announcement:
https://developer.github.com/changes/2018-10-11-new-endpoints-available-for-github-apps/

**Comment by gmlewis** [comment]
Closing issue as obsolete.
