### ISSUE TITLE
Set maximum size of webhook request to 10MB

### ISSUE THREAD

**Issue by lkysow** [google/go-github#735]
As discussed here: https://github.com/google/go-github/pull/693#discussion_r141508166 this ticket is to track/discuss whether we should be adding a 10MB limit to the size of the body for webhook requests.

**Comment by wesleimp** [comment]
@gmlewis this issue can be closed

**Comment by wesleimp** [comment]
@gmlewis this issue can be closed

**Comment by gmlewis** [comment]
Thank you, @wesleimp.

Closing.
