### ISSUE TITLE
Add support for "require review from code owners" for branch protection

### ISSUE THREAD

**Issue by denniswebb** [google/go-github#742]
Current library doesn't support this option.
https://developer.github.com/v3/repos/branches/#update-branch-protection

Working on PR to add it.

**Comment by sayboras** [comment]
I think we can close this issue, as it's already supported. https://github.com/google/go-github/blob/master/github/repos.go#L760

**Comment by gmlewis** [comment]
Thank you, @sayboras! Closing.
