### ISSUE TITLE
Login field support for commit author

### ISSUE THREAD

**Issue by ardakuyumcu** [google/go-github#759]
When fetching a commit, the commit author struct does not populate the login field as expected. It looks like the `Login` field is populated under the `username` json key only for webhooks: https://github.com/google/go-github/blob/master/github/git_commits.go#L53

The inconsistent naming is referred to in: https://github.com/google/go-github/issues/605#issuecomment-323763728

What do you guys think of adding a new field in the `CommitAuthor` struct called `Username` which populates from `username`, and change the `Login` field to use the `login` field?

**Comment by gmlewis** [comment]
I'm confused.  I'm trying to find examples in the GitHub documentation to support the addition of the `login` field to the `CommitAuthor` struct.

I'm looking here:
https://developer.github.com/v3/activity/events/types/
and searching for "author" and get 11 hits.

Hits 7 and 8 show:

```json
      "author": {
        "name": "baxterthehacker",
        "email": "baxterthehacker@users.noreply.github.com",
        "username": "baxterthehacker"
      },
```

Hits 9 and 11 are not a `CommitAuthor` ... but are part of `ReleaseEvent` and `StatusEvent`, respectively.

Hit 10 is:

```json
      "author": {
        "name": "baxterthehacker",
        "email": "baxterthehacker@users.noreply.github.com",
        "date": "2015-05-05T23:40:12Z"
      },
```

So I'm having troubles understanding this issue.

Can you please point me to examples in the GitHub API docs that justify these changes?

**Comment by ardakuyumcu** [comment]
The login field I am trying to populate is under the `author` entry inside the commits API: https://developer.github.com/v3/repos/commits/

The original `Login` field was added as part of a larger change to support the `username` field in webhooks. I'm not sure why Github uses `username` in webhooks but `login` in their commit APIs, but that's the inconsistency I'm trying to resolve.

**Comment by shurcooL** [comment]
> The login field I am trying to populate is under the `author` entry inside the commits API: https://developer.github.com/v3/repos/commits/

That would map to [`RepositoryCommit`](https://godoc.org/github.com/google/go-github/github#RepositoryCommit), which has [`Author *User`](https://godoc.org/github.com/google/go-github/github#RepositoryCommit.Author) field, and [`User`](https://godoc.org/github.com/google/go-github/github#User) has [`Login string`](https://godoc.org/github.com/google/go-github/github#User.Login) field.

**Comment by ardakuyumcu** [comment]
When I do a `GetCommit`, the return type is a `*Commit`: https://github.com/google/go-github/blob/master/github/git_commits.go#L63

Does that mean I need to cast to a `RepositoryCommit`?

**Comment by ardakuyumcu** [comment]
I need to use `Repositories.GetCommit` instead of `Git.GetCommit`.

**Comment by shurcooL** [comment]
It sounds like you're confusing Git Service (https://godoc.org/github.com/google/go-github/github#GitService) with Repository Service (https://godoc.org/github.com/google/go-github/github#RepositoryService).

Earlier, you said:

> The login field I am trying to populate is under the `author` entry inside the commits API: https://developer.github.com/v3/repos/commits/

That maps to https://godoc.org/github.com/google/go-github/github#RepositoriesService.GetCommit method, not https://godoc.org/github.com/google/go-github/github#GitService.GetCommit method.

**Comment by ardakuyumcu** [comment]
Thanks for the help!

**Comment by shurcooL** [comment]
No problem.
