### ISSUE TITLE
Repo.Username() + Repo.Name() helper methods

### ISSUE THREAD

**Issue by tleyden** [google/go-github#768]
When using go-github, I'm finding myself doing this a lot:

```
repoNameComponents := strings.Split(*userEvent.Repo.Name, "/")
username := repoNameComponents[0]
repoName := repoNameComponents[1]
```

it would be nice if there were helper methods like `Repo.Username()` and `Repo.Name()` to make this easier.  

Or maybe return both in a single call:

```
username, reponame := Repo.Details()
```

I'd be willing to put together a PR if this is something that would be likely to get merged.

**Comment by shurcooL** [comment]
> `*userEvent.Repo.Name`

Could you please elaborate on that? What user event has a Repo field that has a `Name` field? Did you mean `FullName`?

I want to understand the problem better, so we can converge on a solution which is closer to optimal.

I know there are some places where `FullName` field has the value "owner/repo" (e.g., https://godoc.org/github.com/google/go-github/github#Repository.FullName), but they usually also have `Owner` and `Name` fields, such that splitting `FullName` isn't neccessary.

**Comment by tleyden** [comment]
It's a `PushEvent`.  

Code snippet in context:

https://github.com/tleyden/keynuker/blob/110c0a672b75a4ccf5331bc08f2fc3fe354ac1c1/gh_user_event_fetcher.go#L141-L160

**Comment by shurcooL** [comment]
Are you sure that code is working as expected? I'd expect `*userEvent.Repo.Name` to be just the repo name, not "org/repo".

[`PushEvent`](https://godoc.org/github.com/google/go-github/github#PushEvent) contains a `Repo *PushEventRepository` field, and [`PushEventRepository`](https://godoc.org/github.com/google/go-github/github#PushEventRepository) has `Owner`, `Name`, and `FullName` fields. I think you should be able to use `Owner` and `Name` directly, instead of splitting `FullName`.

Look at the example given at https://developer.github.com/v3/activity/events/types/#pushevent:

```JSON
 "repository": {
    "id": 35129377,
    "name": "public-repo",
    "full_name": "baxterthehacker/public-repo",
```

**Comment by tleyden** [comment]
I'll double check this and get back to you.

**Comment by tleyden** [comment]
> Are you sure that code is working as you expect? I'd expect *userEvent.Repo.Name to be just the repo name, not "org/repo".

I double-checked by retesting [this similar code](https://github.com/tleyden/keynuker/blob/master/gh_user_event_fetcher.go#L286-L290) and adding some logging, and I'm seeing `*userEvent.Repo.Name` as "org/repo", and splitting on `/` is working (otherwise that code would panic if it was just the repo name)

> PushEvent contains a Repo *PushEventRepository field, and PushEventRepository has Owner, Name, and FullName fields. I think you should be able to use Owner and Name directly, instead of splitting FullName.

In my case, the `github.UserEvent` has a non-empty `Repo` field, however when I call `ParsePayload()` on that event and get back the `github.PushEvent`, the resulting PushEvent has a nil `.Repo` field.  

It corresponds to a recent `PushEvent` I grabbed off my own public event feed:

https://gist.github.com/tleyden/826a0bea5591a6082e85d3c905db20bf

- At the UserEvent level, the [repo field is present](https://gist.github.com/tleyden/826a0bea5591a6082e85d3c905db20bf#file-gistfile1-txt-L12-L15) and has the  "org/repo" format.  
- There is no `repo` field within the [payload](https://gist.github.com/tleyden/826a0bea5591a6082e85d3c905db20bf#file-gistfile1-txt-L17-L46)

**Comment by shurcooL** [comment]
Thanks, that's very helpful.

So you're looking to access the `Repo` field of [`Event`](https://godoc.org/github.com/google/go-github/github#Event) type, not of the [`PushEvent`](https://godoc.org/github.com/google/go-github/github#PushEvent) payload.

The JSON content of the entire event you shared makes it very clear that there's very limited information available in that repo field:

```JSON
"repo": {
  "id": 98492410,
  "name": "tleyden/keynuker",
  "url": "https://api.github.com/repos/tleyden/keynuker"
},
```

Thanks for providing the information. I'll take some time to think about this.

**Comment by wesleimp** [comment]
@gmlewis What do you think about this issue?

IMHO we can close this issue and if it happens again we reopen it.

**Comment by gmlewis** [comment]
Closing.
