### ISSUE TITLE
Support new API features for Archived Repositories

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#776]
GitHub Developer API Announcement:
https://developer.github.com/changes/2017-11-08-archiving-repositories/

This issue consists of one main change (along with updates to the comments):

    *   Add the new `archived bool` to `Repository` responses.

Since the `Repository` struct is used both in the responses and in the [`RepositoriesService.Edit` method](https://github.com/google/go-github/blob/master/github/repos.go#L359), 
this will also enable API users to archive a repo through this client library by setting `archived: true`.

Note that the `libraryVersion` will not need changing as these minor changes are backward-compatible.

This is a great issue for a new contributor to work on since the scope is small. Check out the [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) doc to get started. Let me know if you would like to be assigned to this issue (by commenting below) and I will send you an invite to contribute to this repo that you will then need to accept.

Thank you for your contributions!  All assistance is greatly appreciated!

**Comment by sahildua2305** [comment]
@gmlewis I can work on this
