### ISSUE TITLE
gen-accessors should skip Client, service structs and unexported fields.

### ISSUE THREAD

**Issue by shurcooL** [google/go-github#778]
There are two issues with `gen-accessors.go` generating accessors it should not be (/cc @gmlewis FYI). It's relatively harmless, but should be fixed.

First, gen-accessors.go does not skip unexported fields, which causes it to generate accessors that it shouldn't. For example:

```Go
// Getclient returns the client field.
func (s *service) Getclient() *Client {
	if s == nil {
		return nil
	}
	return s.client
}
```

Second, it does not skip certain structs that it should skip, including `Client`, `service`, and perhaps others. It should only generate accessors for structs that are mapped to GitHub objects. For example:

![image](https://user-images.githubusercontent.com/1924134/32703567-dc25b4a0-c7c5-11e7-8fcf-8cc6453f5b93.png)

![image](https://user-images.githubusercontent.com/1924134/32703592-39854818-c7c6-11e7-8e4e-7bf742a7b91b.png)

**Comment by sahildua2305** [comment]
@shurcooL I'd like to tackle this. What do you think about having an extended list of blacklisted structs to avoid while generating accessor methods?

**Comment by shurcooL** [comment]
Thanks!

I think adding a list of blacklisted structs is the way to go.
