### ISSUE TITLE
gmlewis offline until late December

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#781]
I'm not sure if filing an issue for this is really appropriate, but I couldn't think of a better way at the moment.

I'm going to be offline for the next ~4-5 weeks and will not be responsive to requests for administration of this repo.

If you have urgent issues that must be addressed in the next day or two, please inform me now... feel free to use this issue... and I will attempt to address them before I disappear.

If not, thanks again for everyone's contributions, and I wish you all a safe, healthy, and happy holiday season!

**Comment by shurcooL** [comment]
I think this can be closed now, right? Welcome back @gmlewis! :)

**Comment by gmlewis** [comment]
Thanks, @shurcooL!  Definitely time to close this issue.  :smile:
