### ISSUE TITLE
Add 'review_requested' and 'review_request_removed' to PullRequestEvent action

### ISSUE THREAD

**Issue by sungwoncho** [google/go-github#790]
[PullRequestEvent](https://godoc.org/github.com/google/go-github/github#PullRequestEvent) action is missing 'review_requested' and 'review_request_removed'.

It would be an enhancement to add them.

https://developer.github.com/v3/activity/events/types/#pullrequestevent

**Comment by scriptonist** [comment]
@shurcooL Let me take this Issue

**Comment by shurcooL** [comment]
It's all yours. Thank you.

**Comment by scriptonist** [comment]
According to the  [API Docs](https://developer.github.com/v3/activity/events/types/#pullrequestevent)

> Deliveries for `review_requested` and `review_request_removed` events will have an additional field called `requested_reviewers`.

Should I add this field to `PullRequestEvent`? If so what will it's type be ?, an `[] *User` ?

**Comment by shurcooL** [comment]
That sounds right to me. Make sure it goes under the Webbook section of fields.

**Comment by scriptonist** [comment]
@shurcooL I believe It's an `[] *User` 
On testing I got a response like this
```
"requested_reviewers":[
         {*User  }
      ],

``
