### ISSUE TITLE
Apps.ListUserRepos may return message "specify a custom media type in the 'Accept' header".

### ISSUE THREAD

**Issue by lingsamuel** [google/go-github#797]
When I am trying to use `Apps.ListUserRepos`, I got message like this:
![image](https://user-images.githubusercontent.com/14567045/33372247-3e8de840-d538-11e7-944a-75e1d68be1ea.png)

I know this can be fix by adding following accept header:
```go
// in github/github.go line 85~86
// https://developer.github.com/changes/2016-09-14-Integrations-Early-Access/
mediaTypeIntegrationPreview = "application/vnd.github.machine-man-preview+json"
```

And it can be fix by add following to `ListUserRepos` function in `github/apps_installation.go`
```go
req.Header.Set("Accept", mediaTypeIntegrationPreview)
```

I can provide a PR to fix this.

I noticed that there is a TODO comment in other function says that `TODO: remove custom Accept header when this API fully launches.`, so I will keep this in my fix.

**Comment by shurcooL** [comment]
Hi, thanks for reporting this.

I've taken a look at the documentation for that endpoint at  https://developer.github.com/v3/apps/installations/#list-repositories-accessible-to-the-user-for-an-installation and was surprised to find that it doesn't mention anything about a custom Accept header there.

I'd really like to be able to confirm that adding that header is the right fix via documentation.

After digging further, I found PR #436 which mentioned https://developer.github.com/changes/2016-09-14-Integrations-Early-Access/, which includes:

![image](https://user-images.githubusercontent.com/1924134/33465519-48e0e9b2-d616-11e7-8167-19427bb8c366.png)

So I think that confirms this is the right thing to do.
