### ISSUE TITLE
Repository hooks are not accessible by Integration

### ISSUE THREAD

**Issue by karpovicham** [google/go-github#800]
I could not get the list of repository hooks with Integration authorization using this functions https://github.com/google/go-github/blob/master/github/repos_hooks.go#L109 

I receive the error:
```
GET https://api.github.com/repos/MyOrgName/MyRepoName/hooks: 403 Resource not accessible by integration [] ( 1 repositories) in MyRepoName
```

It works well if we authorize by OAuth2 token, but not by Integration.

Could you please suggest any other way how could I get the list of the repository hooks with the Integration? 
If I there are no any yet do you have plans to implement this in the near future?

Thanks

**Comment by shurcooL** [comment]
This sounds like a GitHub API question, not a `go-github`-specific issue.

I'm not sure what the answer is. I don't see anything on this topic at https://developer.github.com/v3/repos/hooks/#list-hooks.

I'd suggest searching through the rest of GitHub documentation, and if you don't find anything, try contacting GitHub support. At the top of https://developer.github.com/v3/, it says:

> If you have any problems or requests please contact [support](https://github.com/contact?form%5Bsubject%5D=APIv3).

If you find that there is something that can be applied to `go-github` code to improve it, we welcome such enhancements, so please let us know.

**Comment by karpovicham** [comment]
Thanks @shurcooL 

Yes, you're right, this is a question for the GitHub API.

It's not possible to get hooks list this way as it's not even in their list of available endpoints for app:
https://developer.github.com/v3/apps/available-endpoints/
