### ISSUE TITLE
Remove custom media type for License API

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#813]
GitHub API Announcement:
https://developer.github.com/changes/2017-11-28-ending-the-license-api-preview/

This issue is a place-holder for work that needs to be done after we have confirmation that Enterprise API customers no longer need the custom media type header, or when the semantic versioning issue (#376) is resolved.

**Comment by MorrisLaw** [comment]
Hey @gmlewis I'd like to take this issue. Can you assign it to me, so I can be notified once the confirmation goes through? Thank you

**Comment by MorrisLaw** [comment]
@gmlewis does this now have the info required to get started, since issue [#376](https://github.com/google/go-github/issues/376) has been closed via PR [#772](https://github.com/google/go-github/pull/772) or are there more things that need to get fleshed out before starting on this?

**Comment by gmlewis** [comment]
Yes, @MorrisLaw, this is cleared for take-off. Thank you!

**Comment by MorrisLaw** [comment]
Sorry for the late PR, but it's in now! (: @gmlewis
