### ISSUE TITLE
Support preview GraphQL API v4 Node IDs in REST API v3 resources

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#814]
GitHub Developer API announcement:
https://developer.github.com/changes/2017-12-19-graphql-node-id/

To complete this issue:

* a new media type (`application/vnd.github.jean-grey-preview+json`) must be added to `github.go`,
* this media type must be added to the header of calls to all affected endpoints (see announcement),
* a new `node_id` field must be added to the appropriate responses structs that are returned.

This issue presents a great learning opportunity for a new contributor to participate and interact with this community of passionate and enthusiastic Go developers. Any and all contributions are greatly appreciated!

If you would like to work on this issue, please comment below and our team will send you an invite so we can assign the issue to you. Make sure to check out the [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) documentation for help on getting started. Thank you!

**Comment by anubhakushwaha** [comment]
@gmlewis Can I take this up?

**Comment by gmlewis** [comment]
Definitely!  Thank you, @anubhakushwaha!  I sent you an invite.

**Comment by joho** [comment]
I'm currently blocked on a project as I need `node_id` on PullRequest. 

I'd be happy to submit a PR adding it, but don't want to duplicate any of @anubhakushwaha's work in case there's a second PR in progress (btw thanks a lot for the first one). Let me know if it's wanted/needed.

**Comment by parkr** [comment]
`node_id`'s are also present in webhook payloads, e.g. the `push` event has a `repository.node_id`, `sender.node_id`, etc.

**Comment by palash25** [comment]
Hey @gmlewis I see that the following resources were not covered by the PR #817 
Projects
Pull Requests
Reactions
Releases
Repositories
Statuses
Teams
Users

I would like to take this up to complete the rest of the work :smile:

**Comment by vaibhavsingh97** [comment]
@gmlewis Since @palash25 haven't sent PR, I would love to add resources mentioned by him.

**Comment by gmlewis** [comment]
Let's give @palash25 a day or two to respond and afterward you can take this, @vaibhavsingh97.

**Comment by palash25** [comment]
@gmlewis I am busy preparing for gsoc currently so @vaibhavsingh97 can take this up

**Comment by gmlewis** [comment]
Good luck with Google Summer of Code, @palash25!

OK, this is yours, @vaibhavsingh97.

**Comment by vaibhavsingh97** [comment]
@gmlewis I checked all the mentioned resources mentioned in [https://developer.github.com/changes/2017-12-19-graphql-node-id/](https://developer.github.com/changes/2017-12-19-graphql-node-id/) and maximum resources contains node ID in the response. 
I had sent PR #1149 to add missing Node IDs in response of some resources
