### ISSUE TITLE
Check hook 500

### ISSUE THREAD

**Issue by lou-lan** [google/go-github#818]

**Comment by lou-lan** [comment]
{"message":"Server Error","documentation_url":"https://developer.github.com/enterprise/2.11/v3"}

resp.body message

**Comment by kshitij10496** [comment]
Hey @lou-lan 

Can you share the API endpoint you are trying to hit and the `go-github` package function you are using to do so?

**Comment by lou-lan** [comment]
It's my Github Enterprise problem, I reinstalled GitHub，thank you.
