### ISSUE TITLE
Why GetCombinedStatus need ListOptions?

### ISSUE THREAD

**Issue by lou-lan** [google/go-github#819]
Function: GetCombinedStatus(ctx context.Context, owner, repo, ref string, opt *ListOptions)
GitHub API docs: https://developer.github.com/v3/repos/statuses/#get-the-combined-status-for-a-specific-ref

Why GetCombinedStatus need ListOptions?

**Comment by theodesp** [comment]
As per the documentation, `The most recent status for each context is returned, up to 100. This field paginates if there are over 100 contexts.` , so it can get a pagination parameter
