### ISSUE TITLE
How to get last updated time of a repo's source code?

### ISSUE THREAD

**Issue by rafw** [google/go-github#821]
I use this code to get last update time.
`r, _, err := c.Repositories.Get(context.Background(), user, repo)
srcLastUpdated := r.GetUpdatedAt().Time`

But in fact the result `srcLastUpdated` is not the last update time of the source code. How can I get it? Thanks!

**Comment by gmlewis** [comment]
I wrote a quick test program to check out this `google/go-github` repo:

```go
	srcLastUpdated := r.GetUpdatedAt().Time
	fmt.Printf("srcLastUpdated = %v\n", srcLastUpdated)
	createdAt := r.GetCreatedAt().Time
	fmt.Printf("createdAt = %v\n", createdAt)
	pushedAt := r.GetPushedAt().Time
	fmt.Printf("pushedAt = %v\n", pushedAt)
```

and it prints:

```
srcLastUpdated = 2018-01-03 16:58:04 +0000 UTC
createdAt = 2013-05-24 16:42:58 +0000 UTC
pushedAt = 2017-12-29 15:47:42 +0000 UTC
```

So it looks like you want `GetPushedAt`.
