### ISSUE TITLE
CLI tool in examples

### ISSUE THREAD

**Issue by FenwickElliott** [google/go-github#822]
### Use Case
My main usage of this project is with a small CLI tool I use to (primarily) create a Github repo which I can push to without leaving my IDE.

For example (within working directory):

```
git init
go-git-cli new example
git remote add origin https://github.com/FenwickElliott/example.git
```
### Questions
- Would the community liked this use case added to the examples directory?
- For authorization I use a package that gets an OAuth2 token and saves it locally (in Application Storage). Is that acceptable or is there another method of authorization is should use?

**Comment by gmlewis** [comment]
I like having more examples, and this sounds like a useful one!
The OAuth2 solution sounds good to me from the description.
Thank you for the offer, @FenwickElliott!

**Comment by FenwickElliott** [comment]
@gmlewis I finally got around to writing this up. Would you mind glancing over it before I submit it as  a pull request?

https://github.com/FenwickElliott/go-github/blob/cli/example/newrepo/main.go

(getting the OAuth2 token involved too much tangental material so I am just importing it as a environment variable)

Thanks regardless

**Comment by gmlewis** [comment]
Thanks, @FenwickElliott!

I've looked it over and have a bunch of code-review comments, but can't make them with that link... overall, I think that this will be a good addition to have... so if you are willing to go through the process of a code review via a PR, then I'm happy to review it and get it into this repo after we've made some changes.

Thanks again!

**Comment by FenwickElliott** [comment]
@gmlewis, 

Great, thank you. I would be very grateful for your review.

I'll submit the PR when I get back to my desk.


Thanks again,
