### ISSUE TITLE
Support dismissed_review IssueEvent

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#827]
GitHub Developer API announcement:
https://developer.github.com/changes/2018-01-05-dismiss-event-breaking-change/

This announcement actually confuses me a bit...
From the announcement, the `dismissed_review` IssueEvent is changing, but I don't see any history of it, so I don't know when it was introduced. Nevertheless, we would like to support it, so it needs to be added to the `IssueEvent` struct in `github/issues_events.go`.

I think it would suffice to leave its type as a `string` field, similar to other states returned by this package (as opposed to strictly enumerating the values), unless there are objections.

This would be a great first issue for a new contributor to this repo or new Go developer to work on.
All help is greatly appreciated. Thank you!

**Comment by vaibhavsingh97** [comment]
@gmlewis I want to solve this issue, just learnt go 😍

**Comment by gmlewis** [comment]
Excellent! Welcome to the project and to Go in general, @vaibhavsingh97! :smile:

I've sent you an invite to collaborate on this repo so once you accept, I can assign this (or any) issue to you.

Check out our [CONTRIBUTING.md][https://github.com/google/go-github/blob/master/CONTRIBUTING.md] docs to help you get up and running quickly.

**Comment by vaibhavsingh97** [comment]
hi @gmlewis can you please assign the issue to me. I will send PR soon 😅

**Comment by gmlewis** [comment]
Update from GitHub Developer API announcement:
https://developer.github.com/changes/2018-01-17-issue-event-breaking-change/

**Comment by mrsimonfletcher** [comment]
FYI - I did not unassign this issue (I don't have access) 🤔. I also don't have access to assign an assignee so can't add you back, sorry @vaibhavsingh97. 

cc @gmlewis

**Comment by gmlewis** [comment]
Hehe... that's odd.  I'm not sure how that unassign happened.  Ah, actually I have a theory...

I think around late January we flipped a switch that required all contributors to have two-factor enabled in their account, and it booted out all contributors who didn't. Since GitHub just visited this issue due to your comment, it automatically unassigned.

At least, that's my theory and I'm sticking with it until I hear a better explanation.  😄 

Meanwhile, I no longer have permission to send invites from this repo and @vaibhavsingh97 and @mrsimonfletcher don't show up in the list of contributors, so we'll just have to agree on an assignee in the discussion section.

So I'm thinking it is totally safe for you to take this over, @mrsimonfletcher.  Thank you!

**Comment by vaibhavsingh97** [comment]
@gmlewis I would love to take this issue and fix since I claimed the issue long back and never able to close it, so would love to close it now.

**Comment by gmlewis** [comment]
OK, then, back to you, @vaibhavsingh97.
