### ISSUE TITLE
Support preview Lock Reason via the Lock Issue API

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#828]
GitHub Developer API announcement:
https://developer.github.com/changes/2018-01-10-lock-reason-api-preview/

Supporting this change will require the following:

- [ ]  add a new preview media type (`application/vnd.github.sailor-v-preview+json`)  to `github.go`,
- [ ]  add new `active_lock_reason` and `lock_reason` fields (`ActiveLockReason` and `LockReason` in Go, respectively) to `Issue` and `PullRequest` responses,
- [ ]  add a new (optional) `lock_reason` field (`LockReason` in Go) to the `IssuesService.Lock` request (which will involve a breaking API change, so that the `libraryVersion` will need to be bumped),
- [ ]  add a new `lock_reason` (`LockReason` in Go) field to `IssueEvent` and `PullRequestEvent`,
- [ ]  write supporting tests, and
- [ ]  bump the `libraryVersion`.

This is slightly more involved than some of the other recent enhancements, but would still be a good challenge for any new contributor to this repo or to a new Go developer.

All contributions are greatly appreciated. Check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) document for more information on how to get started.

Feel free to volunteer for any issue, and we can send you an invite to contribute to the repo (which you then accept) and the issue can be assigned to you so that others don't attempt to duplicate the work.

Thank you!

**Comment by anirudhmurali** [comment]
Hey @gmlewis, I'm willing to work on this. Can you invite me? TIA :)

**Comment by gmlewis** [comment]
Thank you, @anirudhmurali! Invite sent.

**Comment by sandlis** [comment]
Hey @anirudhmurali, are you working on this?
If not, would you mind if I pick this up?

**Comment by anirudhmurali** [comment]
No, you can go ahead.

**Comment by gmlewis** [comment]
Thank you, @sandlis! Now that we tag this repo with semantic versioning, we no longer have a `libraryVersion` so there is no further action needed on your part.
