### ISSUE TITLE
Make use of testHeader and testMethod consistent

### ISSUE THREAD

**Issue by sahildua2305** [google/go-github#829]
As found out while reviewing https://github.com/google/go-github/pull/817, we have some inconsistencies in our tests where some of the tests don't use the `testHeader` and `testMethod` functions to test request header and method.

One of the defaulter is https://github.com/google/go-github/blob/master/github/git_trees_test.go#L22.

This is completely harmless. Though it's important to make sure it doesn't cause further confusion for the new contributors as it did in that PR initially.

Via this issue, I'd like to point it out and mention that I'd like to fix this inconsistency.

**Comment by willnorris** [comment]
sounds good to me.  assigned to you.
