### ISSUE TITLE
Support NULL Megerable field for pull request query

### ISSUE THREAD

**Issue by leslie-qiwa** [google/go-github#830]
Based on statement of [mergeability](https://developer.github.com/v3/pulls/#get-a-single-pull-request),  

> The value of the mergeable attribute can be true, false, or null. If the value is null, this means that the mergeability hasn't been computed yet, and a background job was started to compute it. Give the job a few moments to complete, and then submit the request again. When the job is complete, the response will include a non-null value for the mergeable attribute.

However, current mergeable in go-github is boolean type. So when it is null, seems like it is assigned as false, which cause calling application making wrong decision. During my concurrent testing, I did find sometimes, GitHub returns null field. So seems like it need to be supported.

**Comment by gmlewis** [comment]
In `pulls.go`, we have:

```go
// PullRequest represents a GitHub pull request on a repository.
type PullRequest struct {
...
	Merged              *bool      `json:"merged,omitempty"`
	Mergeable           *bool      `json:"mergeable,omitempty"`
...
```

Note that `Mergeable` is a pointer to a `bool`.

If you use the `GetMergeable` accessor function in `github-accessors.go`, then it will always return `false` if the field is `nil`. If, however, you access the field directly, for example:

```go
if pr.Mergeable == nil {
	fmt.Println("Mergeable is null... please try again later.")
}
```

then you should be able to determine if the field was returned or not.

Does this resolve your issue, or am I missing something?

**Comment by leslie-qiwa** [comment]
You are right. It spends me some times to find out GetMergeable method is wrong before you replied that. That is why I raise it up. As developer, I most likely use GetMergeable() directly as other GetXXX methods. Otherwise, GetMergeable method probably should just not be exposed to avoid confusion for other people.

**Comment by wesleimp** [comment]
@gmlewis I think we can close this issue. Agreed?

**Comment by gmlewis** [comment]
> Otherwise, GetMergeable method probably should just not be exposed to avoid confusion for other people.

For consistency, we will keep all accessors available, but just realize that their use it optional.

Thank you, @wesleimp!

Closing.
