### ISSUE TITLE
Required to be an owner of an org to fetch concealed members

### ISSUE THREAD

**Issue by jusunglee** [google/go-github#831]
..but the v3 docs clearly state that the authenticated user only needs to be a member. Was this different elaborate?

// ListMembers lists the members for an organization. If the authenticated
// user is an **owner** of the organization, this will return both concealed and
// public members, otherwise it will only return public members.
//
// GitHub API docs: https://developer.github.com/v3/orgs/members/#members-list
func (s *OrganizationsService) ListMembers(ctx context.Context, org string, opt *ListMembersOptions) ([]*User, *Response, error) {

versus

https://developer.github.com/v3/orgs/members/
List all users who are members of an organization. If the authenticated user is also a **member** of this organization then both concealed and public members will be returned.

**Comment by gmlewis** [comment]
Thanks for the issue report, @jusunglee.

It looks like the documentation needs updating, as it appears that the GitHub Developer API docs have changed since this was first written.
I don't think any code needs changing.

Agreed?

**Comment by wesleimp** [comment]
@gmlewis I think we can close this issue

**Comment by gmlewis** [comment]
Definitely.  Thank you, @wesleimp !
Closing.
