### ISSUE TITLE
No requirement of Accept headers in methods involving DELETE

### ISSUE THREAD

**Issue by anubhakushwaha** [google/go-github#834]
While working on #814 I realized that in **projects.go** , the methods involving DELETE set accept headers though the functions don't return a response which might require the client to specify the accept format.Instances at :

[DeleteProject](https://github.com/google/go-github/blob/master/github/projects.go#L101) 
[DeleteProjectColumn](https://github.com/google/go-github/blob/master/github/projects.go#L229) 
[MoveProjectColumn](https://github.com/google/go-github/blob/master/github/projects.go#L253) 
[DeleteProjectCard](https://github.com/google/go-github/blob/master/github/projects.go#L392) 
[MoveProjectCard](https://github.com/google/go-github/blob/master/github/projects.go#L420)

Let me know if the issue raised is valid and if yes, I was willing to fix it.

**Comment by gmlewis** [comment]
I'm afraid I don't understand the issue. The custom accept header used here (`mediaTypeProjectsPreview` which equals `"application/vnd.github.inertia-preview+json"`) is used to enable preview features in the GitHub API as described [here](https://developer.github.com/v3/projects).

To help me understand, let's take one example: [DeleteProject](https://github.com/google/go-github/blob/master/github/projects.go#L111)...

The parts of interest are:

```go
func (s *ProjectsService) DeleteProject(ctx context.Context, id int) (*Response, error) {
...
	return s.client.Do(ctx, req, nil)
}
```

Note that a `Response` is indeed returned where the status code can be checked.

Are you perhaps referring to the returned [media type as described here](https://github.com/google/go-github/issues/727#issuecomment-358202582)?

**Comment by anubhakushwaha** [comment]
@gmlewis I should have researched better,closing.

**Comment by gmlewis** [comment]
No problem.  Glad you found a solution.
