### ISSUE TITLE
Support preview Organization Invitation API

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#838]
GitHub Developer API announcement:
https://developer.github.com/changes/2018-01-25-organization-invitation-api-preview/

Supporting this change will require the following:

- [ ] create two new endpoints
- [ ] add two new fields to an existing endpoint
- [ ] add the new custom media type
- [ ] create tests for the new endpoints and update the test(s) for the existing endpoint
- [ ] run the generator as described in [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md)

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue, and we can send you an invite to contribute to the repo (which you then accept) and the issue can be assigned to you so that others don't attempt to duplicate the work.

Thank you!

**Comment by scriptonist** [comment]
It's not my first time contributing to this project but I'm happy to to take this up.
