### ISSUE TITLE
Please consider tagging versions

### ISSUE THREAD

**Issue by packrat386** [google/go-github#839]
API breaking changes like #816 get merged into this package alarmingly often, which leaves the users scrambling to get their code compiling again. Because there are no published version tags, our options are to either be ready to update our code at a moments notice or pin/vendor a single snapshot in time and manually verify and update when we can. Essentially all dependency management tools in the ecosystem support the ability to tag certain changes as major versions so that we can get any non-breaking updates for "free". It'd make it a lot easier on the users of the package if you could maintain and publish version tags on GitHub, because otherwise we have no idea when the next `go get` is going to break everything.

**Comment by gmlewis** [comment]
See #376.

**Comment by shurcooL** [comment]
Also see PR #772, which is a PR in progress for issue #376.

**Comment by packrat386** [comment]
Whoops. I looked back through the old issues to try to make sure it wasn't a repeat, but I guess I didn't look far enough. Closing favor #376
