### ISSUE TITLE
Enable two-factor auth on your account

### ISSUE THREAD

**Issue by willnorris** [google/go-github#842]
We're in the process of requiring two-factor auth for the github.com/google organization, which will apply both to members of the organization as well as any outside collaborators on any of the repos there.  We've added a number of folks as outside collaborators on go-github so that we can assign issues to you that you're working on.  

When we do flip the switch, anyone who does not have 2fa enabled will automatically be removed from the repo.  So, if you want to still be able to have issues assigned to you, please enable 2fa as soon as possible.  I'm cc'ing all of the collaborators below, even those that may already have 2fa enabled (so that I'm not outing anyone that doesn't have it enabled currently).

Learn more about 2fa at https://help.github.com/articles/securing-your-account-with-two-factor-authentication-2fa/

/cc @sqs @ktoso @juliaferraioli @aleksclark @huytd @chriskingnet @wlynch @shurcooL @jkosecki @ttacon @anirudhmurali @chandresh-pancholi @glapul @RaviTezu @sahildua2305 @rubenvereecken @callmegarrus @gmlewis @MorrisLaw @yozamacs @scriptonist @Succo @vaibhavsingh97 @varadarajana @kshitij10496 @anubhakushwaha @lucasalcantara @elliott-beach @S2606 @korovaisdead @ahmedhagii

**Comment by gmlewis** [comment]
For any collaborator who got an email today about losing access, please read Will's message above, enable two-factor auth on your GitHub account, and then ping this thread and we can send a new invite.

**Comment by gmlewis** [comment]
Closing issue as obsolete.

**Comment by willnorris** [comment]
hah!  That's kind of hilarious that this was still open 😄

**Comment by gmlewis** [comment]
Yeah, my bad. 😁

In case it wasn't obvious, I got the urge to scrub through the repo issues today.  😁

Feel free to reopen any I've made mistakes on, @willnorris .

**Comment by juliaferraioli** [comment]
Uh, I'm pretty sure this was my responsibility to close, so I'll take the blame/credit 😄

**Comment by gmlewis** [comment]
> Uh, I'm pretty sure this was my responsibility to close, so I'll take the blame/credit 😄

Hah!  Hey, it's great to hear from you, @juliaferraioli ! 
I hope all is going well with you!
