### ISSUE TITLE
[question] Drain up to 512 bytes and close the body to let the Transport reuse the connection

### ISSUE THREAD

**Issue by diorahman** [google/go-github#843]
Hi, do you think we still need following lines today (with current and newer golang version)?

https://github.com/google/go-github/blob/master/github/github.go#L481-L485

Thanks!

**Comment by sahildua2305** [comment]
@diorahman I see that we support 1.7.x version as well? Since which version are these lines of code redundant?

**Comment by willnorris** [comment]
Look like it was introduced in 1.7, so should be safe to remove: https://github.com/golang/go/commit/18072adbca7ee2cb2019704577a8f3f142010ba7

**Comment by sahildua2305** [comment]
Cool, thanks for checking @willnorris.

Thanks for reporting, @diorahman. Would you like to send a PR to remove these lines? If not, I'll go ahead and remove.

**Comment by diorahman** [comment]
I have submitted a PR. Sorry for a bit funky event above hehe. Need to change account due to CLA.
