### ISSUE TITLE
PullRequest missing "labels" property.

### ISSUE THREAD

**Issue by kyoh86** [google/go-github#854]
In `pulls` API, each pull-requests have a "labels" property
https://developer.github.com/v3/pulls/#response

 but in the following struct, it's missed.
https://github.com/google/go-github/blob/master/github/pulls.go#L22

**Comment by willnorris** [comment]
definitely looks like an oversight, but should be a pretty simple fix.  Do you want to send a pull request, or one of us can fix it pretty quickly?

**Comment by kyoh86** [comment]
I sent a pull request. plz review it.
