### ISSUE TITLE
Question: get all Pr that are waiting for review from one specific user

### ISSUE THREAD

**Issue by cpanato** [google/go-github#858]
Hello, I was checking the code and did not find a filter or an API call that returns all pending review from one specific user.

in the UI we can use the filter: `is:open is:pr review-requested:USERNAME`

I tried to set the `PullRequestListOptions` but did not work :/

is that possible? or do I need to get all the PRs and then iterate using the `ListReviewers`?

thanks so much

**Comment by shurcooL** [comment]
This is possible via the search issues endpoint:

https://developer.github.com/v3/search/#search-issues. https://godoc.org/github.com/google/go-github/github#SearchService.Issues

You’d need to set the search query to `is:open is:pr review-requested:USERNAME`.

**Comment by cpanato** [comment]
thanks!
