### ISSUE TITLE
AppEngine now supports Go 1.8

### ISSUE THREAD

**Issue by JensRantil** [google/go-github#859]
AppEngine now [supports Go 1.8](https://cloud.google.com/appengine/docs/standard/go/release-notes#october_25_2018). This means that you no longer need to run the `gofmt` command [here](https://github.com/google/go-github#google-app-engine).

**Comment by willnorris** [comment]
ooh nice, I hadn't realized that!  Would mind putting together a pull request to remove that?

**Comment by JensRantil** [comment]
https://godoc.org/github.com/google/go-github/github#hdr-Google_App_Engine also needs to be updated.
