### ISSUE TITLE
Just a simple "Thank you"

### ISSUE THREAD

**Issue by andygrunwald** [google/go-github#860]
I just want to leave a big Thank You to all contributors.

This library is so useful to automate a lot of tasks around Github. And I am sure that the work of more than 180 contributors has saved many hours per developer who can just focus on getting their stuff done. Thank you 👍 

But even more important (for me): **I learned so much by reading the code of this library**.

* Service Structure: The way how the single services are split is just great, easy to understand and to extend.
* HTTP Unit Testing: Before this library, i was not aware how to test external HTTP interfaces. This library showed me how to do it (with bootstrapping an own HTTP server and mocking the response properly)
* Proper Auth: The way how this lib integrates the way to auth against the external service (via RoundTripper) is so elegant in my opinion. With this, it is not 100% build into the lib, but more into the HTTP client. Smart way!

For me personally I design all my client libs according to the design of this library. It has everything in there and is well written.

So once I meet one of the authors and contributors, remind me that you participated in this project and will say Thank You in person.

Keep up the good work and don't let open source work switch to stress. You are doing amazing work. Don't forget this.

**Comment by shurcooL** [comment]
As one of the (many) [contributors](https://github.com/google/go-github/graphs/contributors), thank you for the thank you. :)

I agree with the 3 points you've raised. It's nice to see them written up and appreciated. I also am a big fan of those properties of the design of this library. I'll add one of my favorites to it:

- Conditional Requests via HTTP caching [`http.Transport`](https://godoc.org/net/http#Transport): As https://github.com/google/go-github#conditional-requests says: 

    > `go-github` does not handle conditional requests directly, but is instead designed to work with a caching `http.Transport`. We recommend using https://github.com/gregjones/httpcache for that.

    Instead of trying to implement HTTP caching directly, a general purpose `http.Transport` can be used. That means it can be developed independently, and reused in other places that need it, rather than being tightly coupled with `go-github` itself.

**Comment by andygrunwald** [comment]
I will close this now because here is no action needed instead of drinking a ☕️ or a 🍺 and celebrate.
