### ISSUE TITLE
Incorrect Accept header in DownloadReleaseAsset.

### ISSUE THREAD

**Issue by SteelPhase** [google/go-github#870]
https://github.com/google/go-github/blob/d2b80df1e3eeccae96eb1cb489e65372cc9550c8/github/repos_releases.go#L256

I was able to confirm with curl, that removing `mediaTypeGraphQLNodeIDPreview` from the Accept header will result in the server returning the correct response.

With the `mediaTypeGraphQLNodeIDPreview` Accept header the v3 json response is returned.

**Comment by shurcooL** [comment]
Thanks for reporting. I suspect this is a bug that affects all GitHub versions. `mediaTypeGraphQLNodeIDPreview` should not have been added to that endpoint, because it operates on binary data, not JSON.

We should remove `mediaTypeGraphQLNodeIDPreview` from it.

**Comment by rhysd** [comment]
I'm also facing this problem even if I use GitHub API (not enterprise). After the `mediaTypeGraphQLNodeIDPreview` is added, a downloaded binary file with the method is broken. I confirmed that removing `mediaTypeGraphQLNodeIDPreview` from the custom accept headers fixed the problem.
