### ISSUE TITLE
Support preview Hovercard API

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#875]
GitHub Developer API announcement:
https://developer.github.com/changes/2018-03-21-hovercard-api-preview/

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue, and we can send you an invite to contribute to the repo (which you then accept after you enable two-factor authentication) and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by MonicB14** [comment]
@gmlewis I will be happy to take this issue. Please feel free to assign it to me.

**Comment by gmlewis** [comment]
Thank you, @MonicB14!  I assigned it to you.
