### ISSUE TITLE
Support preview Protected Branches API

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#876]
GitHub Developer API announcement:
https://developer.github.com/changes/2018-03-16-protected-branches-required-approving-reviews/

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue, and we can send you an invite to contribute to the repo (which you then accept after you enable two-factor authentication) and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by scriptonist** [comment]
@gmlewis Is it okay take up this issue? I've already made a couple of contributions in the past.

**Comment by gmlewis** [comment]
Sounds great, @scriptonist! Thank you.

**Comment by scriptonist** [comment]
I guess the preview period for  [protected branches](https://developer.github.com/changes/2015-11-11-protected-branches-api/)  has ended which is detailed [here](https://developer.github.com/changes/2017-09-06-protected-branches-preview-end/).

**Comment by gmlewis** [comment]
Fixed by #880.
