### ISSUE TITLE
Support preview Reactions API

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#877]
GitHub Developer API announcement:
https://developer.github.com/changes/2018-03-16-team-discussion-reactions-api-and-apps-endpoints/

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue, and we can send you an invite to contribute to the repo (which you then accept after you enable two-factor authentication) and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by urohit011** [comment]
I would like to take it on.

**Comment by gmlewis** [comment]
Thank you, @urohit011! Invite sent.
Once you have two-factor authentication enabled, you can accept the invite and I can assign this issue to you.

**Comment by urohit011** [comment]
Thanks @gmlewis, I have enabled two factor authentication and accepted the invitation.
