### ISSUE TITLE
Extending branch protection to include number of reviewers

### ISSUE THREAD

**Issue by victoryNap** [google/go-github#879]
Currently the PullRequestReviewsEnforcement struct doesn't contain the `required_approving_review_count` object that is available through the API. Working on a PR to add it.

https://github.com/google/go-github/blob/master/github/repos.go#L562-L568

https://developer.github.com/v3/repos/branches/#get-branch-protection

**Comment by victoryNap** [comment]
@gmlewis would you mind taking a look at this?

**Comment by gmlewis** [comment]
Thanks, @victoryNap. I commented on the PR.

**Comment by victoryNap** [comment]
Reviewing and making changes now. Thanks for the feedback.

**Comment by victoryNap** [comment]
@gmlewis @shurcooL When you get a minute, I've updated the PR for this.

**Comment by wesleimp** [comment]
@gmlewis I think we can close this issue, right?

**Comment by gmlewis** [comment]
Thank you, @wesleimp, I believe you are correct.

If anyone disagrees, feel free to reopen and explain why.  Thanks.

Closing.
