### ISSUE TITLE
preview period for protected branches has ended

### ISSUE THREAD

**Issue by scriptonist** [google/go-github#887]
I guess the preview period for  [protected branches](https://developer.github.com/changes/2015-11-11-protected-branches-api/)  has ended which is detailed [here](https://developer.github.com/changes/2017-09-06-protected-branches-preview-end/).I think this will be a good time to remove the preview headers.

**Comment by willnorris** [comment]
we only drop the preview headers when they are no longer needed in GitHub Enterprise, which typically lags behind by a month or two.
