### ISSUE TITLE
Support additional endpoints for GitHub Apps API

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#895]
GitHub Developer API announcement:
https://developer.github.com/changes/2018-04-17-additional-endpoints-for-github-apps/

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue, and we can send you an invite to contribute to the repo (which you then accept after you enable two-factor authentication) and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our CONTRIBUTING.md guide to get started.

Thank you!

**Comment by xabxx** [comment]
@gmlewis could you send me an invite? would like to be assigned to this issue. thanks!

**Comment by gmlewis** [comment]
It looks like I'm currently unable to send invites. @willnorris - could you please send @xabxx an invite and also assign this issue to @xabxx ? Thanks!

**Comment by xabxx** [comment]
@gmlewis @willnorris hey guys, any updates?:)

**Comment by gmlewis** [comment]
Hi @xabxx, I recommend just going ahead to start working on it... don't let the assignment hold you up. It is pretty clear from this thread that you are planning on working on it, so others shouldn't start work until they check here on this thread.  :grin:

**Comment by gmlewis** [comment]
Updated GitHub Developer API announcement for this issue:
https://developer.github.com/changes/2018-04-25-new-user-to-server-endpoints-for-github-apps/

**Comment by gmlewis** [comment]
Another updated GitHub Developer API announcement for this issue:
https://developer.github.com/changes/2018-05-21-additional-endpoints-for-github-apps/

**Comment by waseem18** [comment]
As there's no PR for this yet, I'm interested in taking up this issue.

**Comment by gmlewis** [comment]
Thank you, @waseem18. It looks to me like you are correct.
I'm going to close this issue.

If anyone finds anything missing, please re-open and identify which one(s) are missing.
