### ISSUE TITLE
OrganizationsListOptions and UserListOptions shouldn't have ListOptions field.

### ISSUE THREAD

**Issue by shurcooL** [google/go-github#900]
While reviewing #899, I spotted what I believe to be an issue with the `OrganizationsService.ListAll` method. It takes an `opt *OrganizationsListOptions` parameter, which is:

https://github.com/google/go-github/blob/69ab5d997213689855e5db797eb5016ad0cc957a/github/orgs.go#L74-L81

According to the GitHub API docs for that endpoint, available at https://developer.github.com/v3/orgs/#list-all-organizations:

> Note: Pagination is powered exclusively by the `since` parameter. Use the Link header to get the URL for the next page of organizations.

As a result, I believe it's incorrect for `OrganizationsListOptions` to embed the `ListOptions` struct, which contains the normal pagination parameters page/per_page.

If this analysis is confirmed to be correct, then `ListOptions` should be removed from `OrganizationsListOptions`, since it doesn't belong there.

**Comment by shurcooL** [comment]
The same issue affects `UserListOptions` struct:

https://github.com/google/go-github/blob/69ab5d997213689855e5db797eb5016ad0cc957a/github/users.go#L137-L144

Its documentation (https://developer.github.com/v3/users/#get-all-users) also says:

> Note: Pagination is powered exclusively by the `since` parameter. Use the Link header to get the URL for the next page of users.

**Comment by shurcooL** [comment]
But `RepositoryListAllOptions` does **not** have this issue:

https://github.com/google/go-github/blob/master/github/repos.go#L231-L236

**Comment by sandlis** [comment]
@shurcooL Can you please send me an invite? I would like to work on this.

**Comment by shurcooL** [comment]
I don't have permissions to send out invites, but maybe @willnorris or @gmlewis can.

In the meantime, feel free to start working on this. It should be clear to readers of this issue.

Please note, the first step of making progress here should be to confirm the issue is valid. It's currently labeled as `NeedsInvestigation`. Once we've confirmed the original analysis is correct, we can move this to `NeedsFix` state and that's when a PR implementing the fix can be sent. Thanks!

**Comment by sandlis** [comment]
Thanks @willnorris for the invite!
Looking at the docs it does look like an issue to me.
I tried hitting both /users and /organizations API directly, without using go client, 'page' param does not seem to have any impact but 'per_page' param does.

https://api.github.com/users?since=135&per_page=1
https://api.github.com/organizations?since=135&per_page=1

Should I wait till any of the mentors confirm this issue or should I start working on this right away?
Also, do we want to support this undocumented 'per_page' optional param?

**Comment by shurcooL** [comment]
Thanks a lot for investigating this @sandlis!

Actually, your findings confirm to me that this issue isn't as black and white as I originally thought (where my suspected fix was to remove `ListOptions` from `OrganizationsListOptions`).

I think I misinterpreted the GitHub documentation. When it said:

> Note: Pagination is powered exclusively by the since parameter. Use the Link header to get the URL for the next page of organizations.

I took that to mean "since" is the only parameter supported, "page" and "per_page" are not.

However, I suspect what it really means is that "since" is supported in place of "page". But "per_page" still works as usual.

If that's the intended API behavior, then to resolve this issue, we should either document the current embedded `ListOptions` struct saying that only its `PerPage` field is supported (non-breaking API change), or remove it and add `PerPage` directly in its place.

However, there is a bit of a strange inconsistency with the [list-all-public-repositories endpoint](https://developer.github.com/v3/repos/#list-all-public-repositories). It behaves differently, notably, in that it does *not* respect the `per_page` parameter:

https://api.github.com/repositories?since=135&per_page=1

So `RepositoryListAllOptions` is correct (it does not have `ListOptions` embedded).

I think the best thing to do next would be to contact GitHub support and ask them if the `per_page` parameter is indeed officially supported (but missing from docs by accident) for listing users and orgs, and if it's indeed unsupported for listing public repos (and is correctly omitted from docs there).

**Comment by sandlis** [comment]
@shurcooL I sent them a request from support page to check it.
Will update here when I get any response from them.

**Comment by shurcooL** [comment]
Thanks for contacting them, this is very helpful.

go-github already supports a small number of undocumented (but often used and seemingly endorsed by GitHub) API endpoints; specifically, for fetching user/org/repo by ID. You can find them by searching for "undocumented" at https://godoc.org/github.com/google/go-github/github.

If we didn't already have those `ListOptions` embedded, then I agree, adding them would not make much sense.

However, given they were already in the code all this time, I don't think we should suddenly remove them. It's still possible GitHub will decide to document and officially support them. So instead, I think it's better for us to simply document them as being undocumented/unsupported parts of the GitHub API at this time. That way, people who continue to still rely on them can better understand the risk of doing so (as GitHub could change behavior suddenly). But we avoid creating unnecessary churn.

So I think the best resolution to this issue is a non-breaking API documentation change, something like:

```diff
 // OrganizationsListOptions specifies the optional parameters to the 
 // OrganizationsService.ListAll method. 
 type OrganizationsListOptions struct { 
 	// Since filters Organizations by ID. 
 	Since int `url:"since,omitempty"` 

+	// Note: Pagination is powered exclusively by the since parameter.
+	// ListOptions.PerPage controls an undocumented GitHub API parameter.
 	ListOptions 
 }
```

And a similar change for `UserListOptions`.

**Comment by sandlis** [comment]
That sounds good.
What about ListOptions.Page? Do we want to do anything about it?

**Comment by sandlis** [comment]
@shurcooL 

https://github.com/google/go-github/pull/903

Please review this pull request for mentioned documentation updates.
