### ISSUE TITLE
[Feature Request] Support Branch protection for setting `required_approving_review_count`

### ISSUE THREAD

**Issue by majormoses** [google/go-github#905]
Per the [rest api docs](https://developer.github.com/v3/repos/branches/#update-branch-protection) you can send `required_approving_review_count` as part of the `required_pull_request_reviews` object with an integer between 1-6 which represents the number of people required to approve the request in larger teams it is not uncommon to want more than a single approval before merging.

![image](https://user-images.githubusercontent.com/3145127/39460174-282769c8-4cb6-11e8-8d83-e01f5ef4c75c.png)

**Comment by victoryNap** [comment]
I started the work on this but got side tracked. Will finish it up. 

https://github.com/google/go-github/pull/880

**Comment by gmlewis** [comment]
Fixed by #880.
Closing.
