### ISSUE TITLE
GetIgnoreTemplat doesn't work

### ISSUE THREAD

**Issue by joan-saum** [google/go-github#909]
Hi

It seems there is a problem with the function GetGitIgnoreTemplate()

I tried it on many repository but it return nothing all the time
I also create a repository with a C gitignore template here : https://github.com/joan-saum/testGitIgnore
but still the function return me nothing.

Is it the good way to know if a repository contain a .gitignore file or should i use something else ?

**Comment by gmlewis** [comment]
Hi @joan-saum,

When in doubt, it is a good idea to check the source code:
https://github.com/google/go-github/blob/master/github/github-accessors.go#L7895-L7901

```go
// GetGitignoreTemplate returns the GitignoreTemplate field if it's non-nil, zero value otherwise.
func (r *Repository) GetGitignoreTemplate() string {
	if r == nil || r.GitignoreTemplate == nil {
		return ""
	}
	return *r.GitignoreTemplate
}
```

What you are seeing here is an accessor that makes it easy to access a field of a returned `Repository` struct, and this (at least by itself) is probably not what you want.

If you actually want the contents of the `.gitignore` files in many different repos, then you will want to actually access the contents of the repos themselves.

I don't have time at the moment to put together an example program for you, but it can be done with the GitHub API.

If you are still stuck and would like an example program, please let me know and I will try to whip one up later for you.

Good luck.

**Comment by joan-saum** [comment]
Hi @gmlewis and thank you for your answer

Actually, i don't really care about the contents of the `.gitignore` files. I just want to know if there is a `.gitignore` file in a specific repository.

I thought `GetGitignoreTemplate` could help me to do it simply but i think this is not for what i want.
I will use the GitHub API, list the content of the repo and check if there is a `.gitignore`

Thanks for your time!
