### ISSUE TITLE
Error codes for failed repo webhook requests are "Unknown" 

### ISSUE THREAD

**Issue by jusunglee** [google/go-github#912]
`Repositories.ListHooks(ctx, owner, repository, opts)` returns hooks, response, and error. If response failed with codes such as `404` or `403`, this is not reflected in the error code. Using `errors.Code(err)` when `response` returns an error HTTP status code will simply return `codes.Unknown`, when it should really be `codes.PermissionDenied` or `codes.NotFound`. 

Propose a change where we map HTTP Response status codes (if error) into the error object's error code.

**Comment by gmlewis** [comment]
Thank you, @jusunglee  !  I apologize for missing this issue 3 (!) years ago!!!

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

**Comment by AGMETEOR** [comment]
@gmlewis can I take a look?

**Comment by gmlewis** [comment]
Sure, @AGMETEOR ... It's yours.

**Comment by AGMETEOR** [comment]
Thanks @gmlewis . Been out on leave so this got delayed a bit. But will start working on it before this week ends.

**Comment by AGMETEOR** [comment]
Hi @gmlewis , from looking at the code looks like the they're being returned properly. I wrote a quick test like so, thoughts?
```go
func testErrorStatusCode(t *testing.T, code int) {
	client, mux, _, teardown := setup()
	defer teardown()

	mux.HandleFunc("/repos/o/r/hooks", func(w http.ResponseWriter, r *http.Request) {
		testMethod(t, r, "GET")
		w.WriteHeader(code)
	})

	ctx := context.Background()
	_, _, err := client.Repositories.ListHooks(ctx, "o", "r", nil)

	v, ok := err.(*ErrorResponse)

	if !ok {
		t.Error("Returned error not of Error Response type")
	}

	res := &http.Response{
		Request:    &http.Request{},
		StatusCode: code,
	}

	want := &ErrorResponse{
		Response: res,
	}

	if want.Response.StatusCode != v.Response.StatusCode {
		t.Error("Error response does not contain status code")
	}

	if !errors.Is(err, want) {
		t.Errorf("Error = %#v, want %#v", err, want)
	}
}

func TestRepositoriesService_ListHooks_403_code_no_rate_limit(t *testing.T) {
	testErrorStatusCode(t, http.StatusForbidden)
}

func TestRepositoriesService_ListHooks_404_code(t *testing.T) {
	testErrorStatusCode(t, http.StatusNotFound)
}

```

**Comment by gmlewis** [comment]
Excellent, @AGMETEOR !
Thank you for verifying that the codes are coming through properly.

If you would like to add a PR demonstrating this, that's great... otherwise if you just want to have this documented in this issue that is totally fine with me too and we can close it.  Your call.

**Comment by AGMETEOR** [comment]
@gmlewis i prefer to push a PR with the test. I’ll do that later today
