### ISSUE TITLE
Support the new Checks API (beta)

### ISSUE THREAD

**Issue by sridharavinash** [google/go-github#913]
The new Checks API was recently announced in https://developer.github.com/changes/2018-05-07-new-checks-api-public-beta/

While it's currently in beta and supports only GithHubApps, it might be worthwhile adding support.

I'm happy to get an initial PR going for this.

**Comment by gmlewis** [comment]
Here are some recent updates to the Checks API:

GitHub Developer API announcement:
https://developer.github.com/changes/2018-05-23-request-actions-on-checks/

**Comment by gmlewis** [comment]
...and some more recent updates to the Checks API:
https://developer.github.com/changes/2018-07-11-graphql-checks-preview/#changes-to-the-checks-rest-api
