### ISSUE TITLE
Remove custom media type for Marketplace API

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#917]
GitHub Developer API announcement:
https://developer.github.com/changes/2018-05-22-marketplace-api/

The custom media type `application/vnd.github.valkyrie-preview+json` can be removed from `github.go` as the "Marketplace API" is no longer in preview but has become official.

**Comment by MattAlp** [comment]
Can I take this issue?

**Comment by gmlewis** [comment]
That would be great, @MattAlp! Thank you.

**Comment by MattAlp** [comment]
Thank you, @gmlewis! I have opened pull request #928 after following the CONTRIBUTING.MD instructions.
