### ISSUE TITLE
Support additional endpoints for the Migrations API

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#918]
GitHub Developer API announcement:
https://developer.github.com/changes/2018-05-24-user-migration-api/

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue, and we can send you an invite to contribute to the repo (which you then accept after you enable two-factor authentication) and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our CONTRIBUTING.md guide to get started.

Thank you!

**Comment by sanketpayghan** [comment]
Can you send me an invite. I am new to golang but Would like to work on it.

**Comment by willnorris** [comment]
@sanketpayghan: invite sent.

**Comment by sanketpayghan** [comment]
Thanks @willnorris

**Comment by sanketpayghan** [comment]
Working on this

**Comment by mohanprasaths** [comment]
@sanketpayghan  If you are not working on this  I would like to work on this
