### ISSUE TITLE
Remove custom media type for global node IDs

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#919]
GitHub Developer API announcement:
https://developer.github.com/changes/2018-05-30-end-jean-grey-preview/

The custom media type `application/vnd.github.jean-grey-preview+json` can be removed from `github.go` as it is no longer needed. Also please verify that `application/vnd.github.v3+json` is being sent in the header.

**Comment by S2606** [comment]
@gmlewis I would like to work on this. Also should this media type `application/vnd.github.jean-grey-preview+json` be replaced by `application/vnd.github.v3+json`

**Comment by S2606** [comment]
@gmlewis I would like to work on this
