### ISSUE TITLE
addition of preview Accept headers in RepositoriesService.ListByOrg causes errors with GHE

### ISSUE THREAD

**Issue by dmitris** [google/go-github#930]
Preview headers cause server 500 Errors with GHE (observed with GHE version 2.11 - in particular, it is the `application/vnd.github.scarlet-witch-preview+json` header that is causing it).  It happens rarely - only on some requests with some specific `page` parameter value - but when it does, it happens consistently (always for the same request / URL) thus preventing the listing of public repositories.

Currently the several preview Accept types are added to ALL `RepositoriesService.ListByOrg` calls - even when no preview features are needed or wanted, with no possibility to turn the header addition off.  Maybe this can be made configurable so that clients could at least turn off the Accept header addition - for example, through an additional field in `RepositoryListByOrgOptions` or some other way.  Alternatively, we could make the users who do need to use the preview features to specify corresponding options.

**Comment by gmlewis** [comment]
Thank you, @dmitris, for this PR, and sorry for the delay in reply.

We currently don't have a good way to support GitHub Enterprise customers with regards to removal of custom preview headers. It has always been the policy of this repo to attempt to support as many preview headers as possible and remove them when they are deprecated by the public GitHub API.

I'll leave this issue open to alerts GHE users about the problem (and so they can patch in the change), but until we have a good filtering mechanism of custom preview headers (which I don't foresee happening), we will have to let this issue (and corresponding PR) remain open until the preview header is officially removed by the GitHub Developer API team.
