### ISSUE TITLE
Support new API parameters for project card archiving

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#941]
GitHub Developer API announcement:
https://developer.github.com/changes/2018-06-27-project-card-archiving/

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue, and we can send you an invite to contribute to the repo (which you then accept after you enable two-factor authentication) and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by sanketpayghan** [comment]
I would like to work on this.

**Comment by sanketpayghan** [comment]
As per mentioned in API documentation, I am sending `archived = false` in updateProjectCard API but it is not restoring it back. I am calling ListProjectCards API and there `archived=true` even after update API with `archived=false`.

I am doing something wrong or Is this bug?

**Comment by sanketpayghan** [comment]
@gmlewis

**Comment by gmlewis** [comment]
I'm afraid I don't know.

I have found over the years that the GitHub tech support team is super friendly and helpful.

It might be a good idea to fire off an email to support@github.com and tell them you are asking a question about this specific GitHub v3 API (and send them links to the docs you are reading) and state the problem and what you are observing. Could you please do that, @sanketpayghan?
Let's see what they say about this issue.

Thanks, @sanketpayghan!

**Comment by sanketpayghan** [comment]
@gmlewis sure will do
