### ISSUE TITLE
how to clone directory from github?

### ISSUE THREAD

**Issue by liwandaniel** [google/go-github#942]
`client.Repositories.GetContents` is able to get downLoadUrl for one file
is there any API to clone a directory from specific repo?

**Comment by gmlewis** [comment]
I think what you want is called a "git sparse checkout".
Please see https://stackoverflow.com/questions/600079/how-do-i-clone-a-subdirectory-only-of-a-git-repository for more details.

**Comment by liwandaniel** [comment]
thx a lot, I got it, this is how git works
How does "git sparse checkout" work in "go-github"? I want it works in Golang

**Comment by gmlewis** [comment]
This repo is all about making calls to the [GitHub v3 API](https://developer.github.com/v3/?) which is quite different from making calls to the command-line tool [`git`](https://git-scm.com/doc).

That said, however, it should be very easy to do what you want from Go by using the [exec](https://godoc.org/os/exec) package. Simply make a call to command-line `git` and pass it all the arguments you need.

**Comment by liwandaniel** [comment]
ok, I will try using Go command-line tool, thx a lot
