### ISSUE TITLE
How to use this library on GHE?

### ISSUE THREAD

**Issue by rluisr** [google/go-github#943]
I want to use this library GItHub Enterprise.

**Comment by gmlewis** [comment]
Just create a client and change your [`BaseURL`](https://github.com/google/go-github/blob/master/github/github.go#L129-L132) to point to your locally-hosted (enterprise) instance of GitHub and you should be up and running.

Please let us know if you have any problems.

**Comment by rluisr** [comment]
@gmlewis Thanks a lot. working.
