### ISSUE TITLE
Add support for pre-receive hooks API

### ISSUE THREAD

**Issue by nmiyake** [google/go-github#944]
https://developer.github.com/v3/repos/pre_receive_hooks/

This API is only available to GitHub Enterprise instances, but it's still a published part of the API so I think that adding support for this in this library would make sense.

**Comment by nmiyake** [comment]
Not sure what the stance of this project is on GHE-only APIs, but opened a PR that implements this.

If this project does not plan to accept GHE-only APIs, would appreciate any feedback/thoughts on how to deal with this (short of maintaining a fork)

**Comment by gmlewis** [comment]
Yes, we definitely like this repo to support both the public GitHub server and also enterprise instances of the GitHub v3 API whenever possible.

Thank you for doing this, @nmiyake!
