### ISSUE TITLE
Transfer request has incorrect json name for specifying team ids

### ISSUE THREAD

**Issue by juliaferraioli** [google/go-github#946]
As pointed out in the [recent comment on the PR](https://github.com/google/go-github/pull/788#discussion_r201838235) for adding support, the json name should be `team_ids`, not `team_id`.

**Comment by juliaferraioli** [comment]
I can fix this up really quickly if you want to assign it to me :-)

**Comment by dmitshur** [comment]
Thanks for following up on this @juliaferraioli!

As an aside, I got a chance to use the Repository Transfer API recently (I changed my GitHub username and wanted to move all my repos under old name to preserve import paths), and it worked great. Thanks for implementing it! :)
