### ISSUE TITLE
Add PullRequest to Issue struct

### ISSUE THREAD

**Issue by kyleconroy** [google/go-github#95]
If an issue has a pull request, a pull request JSON payload is returned. That JSON payload should be parsed into a PullRequest struct and attached to the Issue.

**Comment by rubenvereecken** [comment]
Is this still considered open? It sounds pretty straightforward.

**Comment by wlynch** [comment]
Looks like this was added in 32d2b56.

**Comment by gmlewis** [comment]
Agreed.  Closing issue. Thanks, @wlynch.
