### ISSUE TITLE
A note regarding baseURL's for enterprise Github instances. 

### ISSUE THREAD

**Issue by vanugrah** [google/go-github#958]
To whomsoever it may concern, 

There is an important caveat regarding the baseURL when creating clients for enterprise Github instances ( for example with the [**NewEnterpriseClient**](https://godoc.org/github.com/google/go-github/github#NewEnterpriseClient) method). 

The baseURL of the public facing API is simply: `https://api.github.com/"`
However for enterprise Github instances the baseURL for the API is slightly different: `https://<mycompany>.github.com/api/v3/"`

Using a baseURL without the `/api/v3/` suffix will result in HTTP 406 Not Acceptable errors and lead you down a path of debugging Oauth clients and request headers. I learnt this after many hours and tears. 

Documenting this as an issue to help others in the future. Perhaps we could add note on the godoc regarding the difference in baseURL structures between public and enterprise Github.

**Comment by gmlewis** [comment]
Thank you, @vanugrah! We definitely want to make life easier for Enterprise GitHub users of this package.

We would greatly appreciate PRs that would help others to reduce or eliminate their pain points. If you or others could create these PRs (who are actually using this package with Enterprise GitHub), that would be excellent.

Also, wouldn't the `baseURL` be `https://github.<mycompany>.com/api/v3/` for Enterprise users?

**Comment by vanugrah** [comment]
Thanks for the reply @gmlewis - I'll submit a PR shortly. To answer your question regarding the baseURL, if the Github enterprise instance is hosted by Github then the `baseURL` would in fact be `https://github.<mycompany>.com/api/v3/` as you've mentioned. However in the case that enterprise instance is licensed and self hosted then it will likely have a subdomain under the companies domain i.e. `https://<mycompany>.github.com/api/v3/`.
