### ISSUE TITLE
Support new Webhook Event for GitHub Apps using User-to-Server tokens

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#959]
GitHub Developer API announcement:
https://developer.github.com/changes/2018-07-25-github-app-authorization-event/

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue, and we can send you an invite to contribute to the repo (which you then accept after you enable two-factor authentication) and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by sanketpayghan** [comment]
Will work on this

**Comment by MorrisLaw** [comment]
Is this still being worked on? @sanketpayghan @gmlewis I can pick it up if needed

**Comment by gmlewis** [comment]
Thank you, @MorrisLaw... I think it is safe to say that you can take it over.
