### ISSUE TITLE
Support changes to the Checks REST API

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#980]
GitHub Developer API announcement:
https://developer.github.com/changes/2018-08-16-changes-to-the-checks-rest-api/

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue, and we can send you an invite to contribute to the repo (which you then accept after you enable two-factor authentication) and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by techmexdev** [comment]
can take this on!

**Comment by tmc** [comment]
This passed the change deadline so someone should jump on it.

**Comment by techmexdev** [comment]
feel free to take it on @jnewland

**Comment by jnewland** [comment]
🎉 https://github.com/google/go-github/pull/990
