### ISSUE TITLE
Update AppsService.CreateInstallationToken with API changes

### ISSUE THREAD

**Issue by gmlewis** [google/go-github#981]
GitHub Developer API announcement:
https://developer.github.com/changes/2018-08-16-renaming-and-deprecation-of-github-app-installation-access-token-route/

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue, and we can send you an invite to contribute to the repo (which you then accept after you enable two-factor authentication) and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started.

Thank you!

**Comment by UjjwalAyyangar** [comment]
I'd like to work on this.

**Comment by UjjwalAyyangar** [comment]
@gmlewis I'd like to work on this.

**Comment by UjjwalAyyangar** [comment]
@gmlewis I'd like to work on this.

**Comment by tadityar** [comment]
Since the issue was left open for more than a month, I decided to submit a PR.
