### ISSUE TITLE
Add Topics API Preview 

### ISSUE THREAD

**Issue by gkze** [google/go-github#984]
This would be a very small change, adding `application/vnd.github.mercy-preview+json` (`mediaTypeTopicsPreview`) to `activity_star.go` and would allow the client to get topics for a starred repository.

**Comment by gmlewis** [comment]
Thank you, @gkze, but could you please be more specific?

I'm looking through the GitHub Developer API docs here:
https://developer.github.com/v3/activity/starring/
and don't see any mention of this custom header.

**Comment by gkze** [comment]
Sure, this feature was introduced a year ago: https://developer.github.com/changes/2017-07-17-update-topics-on-repositories/ and also works on `user/starred`, but this seems to be unclear / undocumented.

It seems to only be documented in the "Repositories" section: https://developer.github.com/v3/repos/#list-all-topics-for-a-repository

**Comment by gmlewis** [comment]
OK, so if I understand you correctly, adding the `mediaTypeTopicsPreview` custom header to the following endpoints will return the topics for the starred repo:

* `ActivityService.ListStarred`
* `ActivityService.IsStarred`
* `ActivityService.Star`
* `ActivityService.Unstar`

correct?

**Comment by gkze** [comment]
No - this header should only be passed in `ActivityService.ListStarred` as the rest of the calls do not return that data.

**Comment by gkze** [comment]
I would like to volunteer for this issue.
