### ISSUE TITLE
PullRequestEvent doesn't unmarshall Assignee field.

### ISSUE THREAD

**Issue by jgsqware** [google/go-github#993]
When receiving `PullRequestEvent`, there is `Assignee` field in the `JSON` but it's not unmarshalled in the `PullRequestEvent` struct.

**Comment by gmlewis** [comment]
Thank you, @jgsqware, but looking at https://developer.github.com/v3/activity/events/types/#pullrequestevent
I see that there is an `assignee` field under the `pull_request` object, but not at the top-level where you have placed it in #994.

If you have actually seen an `assignee` field at this location in GitHub API events, can you please contact `support@github.com` and ask them to confirm its existence and correspondingly update their GitHub Developer API docs?

**Comment by jgsqware** [comment]
Sure I'll contact them, it's tested as I needed it.

The assignee in the top level is the one from the general event item,
present when action `assigned` or `unassigned` is used.

In case of `assigned` action, the Assignee` in `pull_request` object is
populated, but the other way around, when it's `unassigned`, the field is
emptied as it reflects the last state of the object.



Le ven. 7 sept. 2018 à 21:32, Glenn Lewis <notifications@github.com> a
écrit :

**Comment by gmlewis** [comment]
Thank you for contacting GitHub Developer API tech support.  Please report back to this issue when you hear from them.

Meanwhile, we can go ahead with #994 since it solves the issues you were seeing.
